### ISSUE TITLE
"Submit Update" button is disabled when user only wants to update below fields : Disable additional sub camps and Single level sub camps only

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1]
Steps to reproduce : 
1. Go to https://canonizer3.canonizer.com/ 
2. Login with valid email and password
3. Open any topic 
4. Open any camp
5. Click on Manage/Edit This Camp
6. Click on Submit Camp Update Based On This 
7. Select/deselect options : Disable additional sub camps and Single level sub camps only and try to update camp

Expected Result : User should able to update camp

Actual Result : "Submit Update" button is disabled
Please refer attached screenshot : 
![image](https://user-images.githubusercontent.com/40416610/203052291-31a04ac9-ca70-4a69-8e25-5122e5a35087.png)

**Comment by shahab-ramzan** [comment]
PR raised https://github.com/the-canonizer/canonizer-3.0-frontend/pull/585

**Comment by subhancd** [comment]
working fine on both staging and beta

**Comment by rupalichavan9860** [comment]
Verified
