### ISSUE TITLE
Camp Leader issues

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1005]
Steps to reproduce : 
1. Create Topic - User A(Rupali C)
2. User A is camp leader
3. Update "Agreement" camp - select No camp leader
4. Login with User B(Rupali cano) and directly support Agreement camp
5. Login with User C(Rupali-CanoUser) and click on "Sign"
6. Observe nickname in pop up 
Issue 1 : Incorrect oldest direct supporter nickname showing in sign pop up
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/a3a63aaa-c4b1-4c3b-b41e-f5847a994758)

7. Click on Submit
8. Observe camp leader 
Actual Result : User C(Rupali-CanoUser) is camp leader
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/af47d665-6918-47de-aacc-c73c3e2b7231)

Expected Result : User A is must be a camp leader and User C(Rupali-CanoUser) must be delegated user

**Comment by sajid315** [comment]
These issue's are already fixed and was not working due to the code not taking effect on server, After Apache restart its working fine.

**Comment by rupalichavan9860** [comment]
Working fine on development server

**Comment by saniatg** [comment]
working fine on production
