### ISSUE TITLE
Enable push notification -> Getting notification "Nickname has just added delegate support to in this topic" 3 times

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1011]
Steps to reproduce : 
1. Login with User A and Create topic
2. Login with User B and delegate support to User A
3.Observe Enable push notification 

Getting "Nickname has just added delegate support to in this topic" 3 times instead of 1 

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/b9c2b743-b142-4532-93ce-ef5fc105fdee)

**Comment by array-junkie** [comment]
As discussed with @rupalichavan9860, Web notifications should work the same as emails.
