### ISSUE TITLE
Enable push notification : Proposed a change to statement, topic, camps notifications are missing

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1012]

**Comment by array-junkie** [comment]
@rupalichavan9860 Now notifications are working. New FCM HTTP v1 is configured now. There might be a change that you have to reenable push notifications.

**Comment by rupalichavan9860** [comment]
@M-Darab Yes working fine now

**Comment by rupalichavan9860** [comment]
Verified on live
