### ISSUE TITLE
 Two camp leaders are being assigned in a specific case

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1013]
Steps:

1. Create a topic by user A , by default User A is a camp leader
2. Now create camp1
3. Login with User B and click on 'camp1' from tree
4. Click on sign button

Actual result: User B is also assigned as the camp leader , now there are 2 camp leaders A and B
Expected result: Only user A must be camp leader, for other sign button must remain inactive
![Screenshot 2024-05-31 at 9 28 00 AM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/a0205e7a-b15f-4286-892c-1a9422996977)
![Screenshot 2024-05-31 at 9 28 07 AM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/ca9c97da-a0cc-4a25-b61b-0b6743d6f99d)

**Comment by rupalichavan9860** [comment]
Not an issue
