### ISSUE TITLE
Sign button is disabled in a specific scenario , it should be enabled

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1015]
Steps:

1. user A is supporter and camp leader of camp agreement
2. User B is not able to click on sign button as it is disabled

Actual result: Sign button is disabled with info "Couldn't sign! This camp is not your first choice

Expected result: Sign button should be enabled with warning message like that there is already a camp leader and your support will be delegated 
![Screenshot 2024-06-03 at 7 23 14 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/3ef739dd-1df1-4a6f-a5f9-d567cd320f40)
something like this

**Comment by wahaj-hafeez** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1800

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1800

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
