### ISSUE TITLE
'Sign' button is disabled but on hover click on the message, pop up opens which is incorrect

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1017]
Pre condition- camp already has a camp leader

Sign button is disabled, hover on it and the text appears click on it
pop up opens which is incorrect
![Screenshot 2024-06-04 at 7 05 30 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/710b39a6-5f24-48df-b0f9-557e661f3872)

**Comment by wahaj-hafeez** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1811

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1811

**Comment by rupalichavan9860** [comment]
Verified on development server

**Comment by saniatg** [comment]
working fine on production
