### ISSUE TITLE
Direct supporters are unable to Object and agree the change 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1018]
Object and agree options are disabled 
Please refer attached screenshot : 

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/f2bcfec0-e1b2-4565-8365-4b2e8bc24bd9)

**Comment by rupalichavan9860** [comment]
Facing this issue for topic and camp statement history pages

**Comment by DevAlchemyCD** [comment]
PR : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1806

**Comment by rupalichavan9860** [comment]
Verified on development server

**Comment by saniatg** [comment]
working fine on production
