### ISSUE TITLE
Search :Camp Statement - Remove "Canonizer Algorithm" and "Score" from Advance Filter

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1022]
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/e2d8f848-af01-44da-bc52-cb3296e6f0c6)

**Comment by saniatg** [comment]
working fine on development

**Comment by rupalichavan9860** [comment]
Verified on live
