### ISSUE TITLE
Email address is not showing in account settings profile page

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1023]
![Screenshot 2024-06-10 at 1 49 36 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/92661165-be47-4804-946b-cdc2b1e2aeec)

**Comment by rupalichavan9860** [comment]
Verified on dev server

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
