### ISSUE TITLE
Getting error on click "view this version" on update pages

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1026]
![Screenshot 2024-06-11 at 10 29 22 AM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/0cab4b2e-ff1b-4bc5-b2b3-3b84220fb014)

**Comment by rupalichavan9860** [comment]
Verified on development server

**Comment by saniatg** [comment]
working fine on production
