### ISSUE TITLE
Sign button is giving error, not working

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1027]
![Screenshot 2024-06-11 at 10 31 30 AM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/577e902e-db6e-48ae-b26f-9195b07b131d)

**Comment by array-junkie** [comment]
This is fixed. PR https://github.com/the-canonizer/canonizer-3.0-api/pull/1041

**Comment by rupalichavan9860** [comment]
Working fine on development server

**Comment by saniatg** [comment]
working fine on production
