### ISSUE TITLE
Nick name ID is displaying in drop down in below case 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1029]
Steps to reproduce : 
1. Create topic with User A
2. User A is the camp leader of "Agreement" camp
3. Remove support and add support directly (Do not sign)--Now no camp leader
4. Update camp "Agreement" - Select "User A" as camp leader
5. Do not commit changes
6. Remove support from Agreement camp 
7. Now click on commit - record will be objected 
8. click on "Submit update based on this"

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/a7b948c5-ae04-46ff-bec8-bcd47b555e7a)

**Comment by rupalichavan9860** [comment]
Working fine now on dev server

**Comment by rupalichavan9860** [comment]
Verified on live

**Comment by saniatg** [comment]
@M-Darab on  Step 8 there is an issue , submit update button is missing
![Screenshot 2024-07-15 at 9 40 56 AM](https://github.com/user-attachments/assets/5f74038d-5df1-44fe-ad39-077e0ea91489)
