### ISSUE TITLE
Under the "Agreement" camp, the user can create a camp with the name "agreement."

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#103]
Please refer attached screenshot : 
![image](https://user-images.githubusercontent.com/40416610/208382362-ed0c5880-2e21-4193-a517-bfd4788f42f7.png)

![image](https://user-images.githubusercontent.com/40416610/208382820-8f8e1996-d2f0-4d16-af73-10c20f579fc5.png)

**Comment by subhancd** [comment]
camp with the name "agreement" can still be created and the canonizer sorted tree is empty after redirection


![Image](https://user-images.githubusercontent.com/104552751/208904306-daeefa70-172a-48aa-9708-795c5446a379.png)

**Comment by rupalichavan9860** [comment]
Yes. this is working fine on beta

**Comment by ks-rahul** [comment]
@rupalichavan9860 @subhancd now the code is deployed on the staging server please check now.

**Comment by subhancd** [comment]
working fine on both beta and staging. @rupalichavan9860 kindly, verify and close the ticket

**Comment by rupalichavan9860** [comment]
Verified
