### ISSUE TITLE
Remove subscription pop up is showing twice

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1031]
1. Go to account setting
2. Subscriptions
3. Click on remove subscription
4. POp up will appear click remove

Now again pop up will appear

![Screenshot 2024-06-13 at 8 12 46 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/a1a2dffb-8b2f-4e7f-8c94-4e27a8ed38e3)

**Comment by ks-rahul** [comment]
@saniatg I'm not able to replicate this issue. If you are facing any specific scenario, please provide that scenario.

**Comment by ks-rahul** [comment]
@saniatg i have checked this multiple times with multiple camps and topics. it is working fine.

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
