### ISSUE TITLE
Camp leader Nick's name appears twice on the camp update page. 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1036]
Steps to reproduce : 
1. Create topic
2. User is direct supporter and camp leader
3. Go to "Camp Update" page and observe "Camp Leader" drop down 

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/07f774a8-207a-4420-8844-c76f3edba534)

**Comment by rupalichavan9860** [comment]
Working fine on development server

**Comment by saniatg** [comment]
working fine on production
