### ISSUE TITLE
Direct support not working as nickname data is empty

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1037]
![Screenshot 2024-06-17 at 11 18 03 AM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/f6ba27c5-10ad-4f94-ae05-8c97bc4f5dcc)
![Screenshot 2024-06-17 at 11 24 37 AM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/16bb9db3-1912-4e93-9c48-220a2c88df06)
Not able to  give direct support 
Giving error: Nick name is required"

As Nickname has no Data

**Comment by ks-rahul** [comment]
this is duplicate issue of this ticket https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/issues/1035

**Comment by rupalichavan9860** [comment]
Verified on development server

**Comment by rupalichavan9860** [comment]
Verified on live
