### ISSUE TITLE
When Camp leader is not selected, it should say Camp leader- "No" on the topic detail page, just as the history page does.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1045]
History page : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/8a322dac-d7c9-4de1-a4f1-5f112a56b94d)

Topic detail page : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/98e73c9d-3ab1-4cac-b6dd-5ed3d9135de3)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1841

**Comment by rupalichavan9860** [comment]
Working fine now on development server
