### ISSUE TITLE
Canonizer: UI/UX Overhaul - Register Page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1050]
Remove "All fields are mandatory." from the registration page because "Contact Number" is not mandatory.

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/970c94d5-1bda-42bb-a027-bbf56ea2b8fb)

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live

**Comment by ashish76** [comment]
@rupalichavan9860 we have changed the label to "All fields marked with * are mandatory." I think this makes more sense. Please verify and let me know.
