### ISSUE TITLE
Incorrect Score for the following case

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#107]
**Steps to reproduce**

1. create a topic
2. create camp1 -> add support in camp1
3. create camp2 -> add support in camp2
4. create camp3 -> change support preference of camp3 to 1st preference -> add support
**Actual Result**
![image](https://user-images.githubusercontent.com/104552751/208603053-938ca460-f3c6-4608-81fb-e102aece3604.png)
**Expected result**
score should be following
Topic : 1.0
camp3: 0.63
camp2: 0.25
camp1: 0.13

**Comment by subhancd** [comment]
working fine on staging

**Comment by subhancd** [comment]
@rupalichavan9860 working fine and staging but not working on beta.

![Image](https://user-images.githubusercontent.com/104552751/208904968-cd5dc2fa-b195-40ae-acd2-9b476f9d45a1.png)

**Comment by rupalichavan9860** [comment]
Working fine on beta
