### ISSUE TITLE
"Browse Page" is not working.

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/Canonizer-Beta--Issue-Tracking#1072]
Steps:

1. Go to the url "https://ux-dev.canonizer.com".
2. Then click on "Browse" from "Header" and "Footer" both navigation bar.

![Image](https://github.com/user-attachments/assets/ee1cb953-bf93-4df5-acac-ecc3186d699d)

**Comment by rupalichavan9860** [comment]
Working fine now

**Comment by rupalichavan9860** [comment]
Verified on live
