### ISSUE TITLE
New UI/UX - Getting "server error" on create topic

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1075]
Please refer attached screenshot : 
![image](https://github.com/user-attachments/assets/23beeec7-8ad1-4514-9a1a-c93faf1e6e31)

**Comment by ks-rahul** [comment]
@saniatg  this is fixed now. please check

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
