### ISSUE TITLE
Browse : Only My Topics functionality is missing 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1077]

**Comment by sajid315** [comment]
@wahaj-hafeez in case of "Only my topics" functionality. Following is the figma node id.

https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=1301-9172&t=G5z3wUKVE1KYJttg-0

And as a payload we need to send the following payload at backend.

```
{
    "algorithm": "blind_popularity",
    "asofdate": 1724755773.864,
    "namespace_id": "1",
    "page_number": 1,
    "page_size": 15,
    "search": "",
    "filter": "0",
    "asof": "default",
    "user_email": "xnvrcxygnowsuuhulx@bbitj.com",
    "is_archive": 0,
    "sort": false
}
```

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2096

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
