### ISSUE TITLE
Topic History : Canon is blank on history page 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1081]
Please refer attached screenshot : 
![image](https://github.com/user-attachments/assets/7c0acc63-0890-4a1c-992e-6bd7d74c182b)

**Comment by sajid315** [comment]
@wahaj-hafeez I just checked the backend response , there's a key named as namespace is coming in response. 
And you have to populate it in each history card of topic hisotry.

**Comment by wahaj-hafeez** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2039

**Comment by DevAlchemyCD** [comment]
PR: [the-canonizer/canonizer-3.0-frontend#2039](https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2039)

**Comment by rupalichavan9860** [comment]
@wahaj-hafeez @sajid315 I can see canon now but names are not proper(">" are missing) . Please refer attached  screenshot 

![image](https://github.com/user-attachments/assets/c690c9b6-b18b-48a7-b886-cd22bd94bd0f)

![image](https://github.com/user-attachments/assets/f2f5359f-f786-49c9-8ae9-7c66e6ab8955)

**Comment by sajid315** [comment]
Ok @rupalichavan9860 , I am looking into this matter.

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2152

**Comment by rupalichavan9860** [comment]
Working fine now

**Comment by rupalichavan9860** [comment]
Verified on live
