### ISSUE TITLE
Extend the character limit for the camp name field from 30 to 60 characters.

### ISSUE THREAD

**Issue by akuks** [the-canonizer/Canonizer-Beta--Issue-Tracking#1082]
We are enhancing the camp name field in our application to better accommodate user needs. Currently, the character limit for this field is set to 30 characters. However, we have observed that this limitation is restrictive for users who need to input longer camp names. Therefore, we propose increasing the character limit to 60 characters.

**User Feedback:** Several users have reported difficulties in entering their complete camp names due to the current 30-character limit. This change is based on direct feedback from our user base, emphasizing the need for more flexibility.

**Comment by sajid315** [comment]
I have updated the characters limit from 30 to 60 characters from backend side, even in validations as well . Following is the PR raised. 

@akuks we need to run migrations on ux-dev server to make it up-to-date.

**Comment by sajid315** [comment]
@BrentAllsop do we need same for topic name as well ? Should we extend the topic name field to 60 characters ?

**Comment by sajid315** [comment]
As per discussion in last morning scrum, we need to extend the character limit to 80 characters for both topic and camps.

**Comment by DevAlchemyCD** [comment]
PR : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2146

**Comment by rupalichavan9860** [comment]
Verified. There are few issues and we will log them separately

**Comment by rupalichavan9860** [comment]
Verified on live
