### ISSUE TITLE
Create topic page : When the user types a word into the Canon drop down text box, it should display the corresponding list item.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1083]
Currently it is not displaying matching items , Please refer attached screenshot 

![image](https://github.com/user-attachments/assets/fbfaf1b8-703f-4c9a-a624-d60a8819a648)

**Comment by saniatg** [comment]
verified

**Comment by rupalichavan9860** [comment]
Verified on live
