### ISSUE TITLE
Wrong spelling of "consensus"

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1084]
refer screenshot
![Screenshot 2024-08-05 at 10 13 26 PM](https://github.com/user-attachments/assets/12fadeeb-0d84-443c-a72c-8d9bca2fcf6f)

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
