### ISSUE TITLE
Username link is clickable but not working

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1087]
![Screenshot 2024-08-05 at 10 30 01 PM](https://github.com/user-attachments/assets/9354bff0-71ce-4958-bbac-8bb13ff83263)

**Comment by DevAlchemyCD** [comment]
PR : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2094

**Comment by saniatg** [comment]
verified

**Comment by rupalichavan9860** [comment]
Verified on live
