### ISSUE TITLE
Browse Page- the div is not redirecting  when click on it, it shows hand pointer all over but is not clickable on the grey area

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1090]
![Screenshot 2024-08-05 at 11 10 34 PM](https://github.com/user-attachments/assets/74f00bb3-4263-4672-b69f-7455176ac2fb)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2111

**Comment by hassaanCD** [comment]
Verified

**Comment by hassaanCD** [comment]
Verified on live
