### ISSUE TITLE
Camp statement - giving error on click cross icon 

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1091]
Click on cross icon on nickname field the 
click button 'publish statement' shows error , same for button "Save as draft"
![Screenshot 2024-08-05 at 11 24 10 PM](https://github.com/user-attachments/assets/b889cd7b-846a-4684-bc62-e4225f13a517)

![Screenshot 2024-08-05 at 11 16 36 PM](https://github.com/user-attachments/assets/95f4a179-52e5-4d93-88ec-6dc9e272e84e)

**Comment by saniatg** [comment]
verified and is working

**Comment by hassaanCD** [comment]
Verified on live
