### ISSUE TITLE
Add/Update Camp Statement issues

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1092]
Issue 1 : "*" must be in red color for field "Nickname*"
![image](https://github.com/user-attachments/assets/f8fd6d9d-910c-48e1-b144-6fae0961e2af)

Issue 2 : The cursor should be pointing to the end of the Update Camp Statement paragraph, rather than the beginning.

**Comment by ks-rahul** [comment]
@rupalichavan9860 point no. 2 is the default editor functionality. and for point no. 1 please explain more.

**Comment by rupalichavan9860** [comment]
Issue 1 : "*" must be in red color for field "Nickname"

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
