### ISSUE TITLE
Create Topic : Summary is missing on create topic form

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1097]

**Comment by ks-rahul** [comment]
@rupalichavan9860 According to the new design, the summary field is only available on the edit page, not on the create page.

**Comment by rupalichavan9860** [comment]
Okay @ks-rahul We need to remove Summary from email as well then

**Comment by rupalichavan9860** [comment]
Verified on live
