### ISSUE TITLE
Sitemap is not working

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1098]
Please refer attached screenshot : 
![image](https://github.com/user-attachments/assets/63b3a3ec-e954-4371-8f7f-05fbbbec1b90)

**Comment by ks-rahul** [comment]
@akuks Could you please update the environment key to NEXT_PUBLIC_ENVIRONMENT = 'production' and rebuild the application?

**Comment by rupalichavan9860** [comment]
Working fine now

**Comment by rupalichavan9860** [comment]
Verified on live
