### ISSUE TITLE
Camp Statement History: When opening an old proposed changed to a statement from recent activities, "0" appears instead of "Update Current Statement."

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1099]
Please refer attached screenshot : 

![image](https://github.com/user-attachments/assets/7bad7374-6918-406b-a840-6e70df81ea52)

**Comment by sajid315** [comment]
@rupalichavan9860 this issue has been resolved now, the issue was coming due to id of statement was coming as NULL. 
Now it's working fine, please have a look.

**Comment by rupalichavan9860** [comment]
Yes @sajid315 Working fine now

**Comment by hassaanCD** [comment]
Verified on live
