### ISSUE TITLE
Tacking count/views- Just created a topic and in 1 minute the views are 6

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1101]
The same user views are being counted each time the page is being visited, which is incorrect as per the description in the ticket

[Session Handling: To avoid counting multiple views from the same user within a short period, the server can track user sessions and ensure that repeated views within a single session are only counted once.
Cookies: By setting cookies, the camp page can track if a user has visited the page before and decide whether to increment the view count based on that information.]

**Comment by sajid315** [comment]
@saniatg I just checked the issue as mentioned by you, 

One issue we have is about cookie expiration and setting of cookie, first time cookie is not setting. We are looking into this issue. 

Further explanation about it,

1- Right now views are working on base of cookies, on Ux-dev server we have 4 minute time configured to count the next view of a user on a specific topic/camp.
2- In Agreement camp we are showing total views of all the camps.

**Comment by sajid315** [comment]
@saniatg now the cookie is creating as per the time set on the front-end. 
Right now the time is 4 minute. I will request @akuks to make it one hour or some hours on ux-dev server.

**Comment by saniatg** [comment]
@sajid315 @rupalichavan9860 , now whenever the user is visiting the page the count increases by 1 .

**Comment by saniatg** [comment]
Working on live as per the comment mentioned above
