### ISSUE TITLE
'Save as draft' button  is not working in add camp statement

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1102]
![Screenshot 2024-08-07 at 1 44 29 PM](https://github.com/user-attachments/assets/1e7fe2f7-bc48-4ced-ac9e-35ed75206274)

**Comment by sajid315** [comment]
@saniatg 
Now the "Save as Draft" is working and you can check it on Ux-Dev server. Following is the screenshot.

![Image](https://github.com/user-attachments/assets/86ce7210-95fe-4cde-916f-1011212c374d)

**Comment by saniatg** [comment]
Verified

**Comment by hassaanCD** [comment]
Verified on live
