### ISSUE TITLE
Register- Success message is missing

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1103]
- When sign up
- EnterOTP
- Choose tags
- Message is missing instead should show " You have successfully signed up!"
- 
![Screenshot 2024-08-07 at 4 22 27 PM](https://github.com/user-attachments/assets/5ef0e330-5927-40f5-a802-2b9830ab2063)

**Comment by saniatg** [comment]
verified. 
Success tag message is seen

**Comment by hassaanCD** [comment]
Verified on live
