### ISSUE TITLE
Add Support : UI issue 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1104]
Need space between "Thank" and "you". Please refer attached screenshot 
![image](https://github.com/user-attachments/assets/aa22817f-00e1-4b59-b8b8-06dec1d02fc3)

**Comment by sajid315** [comment]
@wahaj-hafeez messages are updated under following PR :
https://github.com/the-canonizer/canonizer-3.0-api/pull/1125

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
