### ISSUE TITLE
Thread page- showing invalid dates when hover agreement camp

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1105]
![Screenshot 2024-08-08 at 1 19 16 PM](https://github.com/user-attachments/assets/07b01887-718e-419d-b4ba-a0f8152ae115)

**Comment by ks-rahul** [comment]
@saniatg this is not developed yet.

**Comment by ks-rahul** [comment]
@saniatg this is deployed now check.

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
