### ISSUE TITLE
Create post is not working on click submit

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1106]
![Screenshot 2024-08-08 at 1 21 50 PM](https://github.com/user-attachments/assets/08b721ef-e98e-44fd-b896-e53feed79b42)

**Comment by ks-rahul** [comment]
@saniatg this is not deployed yet

**Comment by ks-rahul** [comment]
@saniatg this is done. check

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
