### ISSUE TITLE
When overriding support, the support order/preference number changes, and the supported camps are not listed in the following scenario.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1107]
Steps to reproduce : 
1. Create topic 
2. Create 4 camps "C1" ,"C2", C3","C4" 
3. Create sub camp of "C2" 
4. Support all camps  "C1" ,"C2", C3","C4" 
Below are supported camps 
![image](https://github.com/user-attachments/assets/e0880a8f-8466-4a47-b95a-7230425c86cd)

6. Now try to support sub camp of "C2" 

![image](https://github.com/user-attachments/assets/8fae57be-e405-4f64-b4dc-b283302188d3)

Expected Result : When user trying to support child of "C2" , it should list all supported camps and support order of child camp must be same as parent camp

**Comment by rupalichavan9860** [comment]
As discussed at the meeting, I am adding one more change to this .
Every new camp that a user is going to support should be highlighted in a different color, and there should be a note to let the user know why.

The user has already supported four camps (C1,C2,C3,C4) and is now supporting the following new camp "C5"; please see the attached screenshot. 
![image](https://github.com/user-attachments/assets/f7fa8da1-a06f-4a45-99b7-4baa2a9010b7)

Expected Result : "C5" should be in a different color, and there should be a note to explain why.

**Comment by rupalichavan9860** [comment]
This is not fixed

**Comment by sajid315** [comment]
@rupalichavan9860 as per the expected results mentioned in this ticket , its already working fine on ux-dev server. 

Every new camp in which we are going to add support showing in different color. 
Also when we are adding support to any sub-camp , all of the camps are showing in which user already is with the subcamp in same order as parent camp.

![Image](https://github.com/user-attachments/assets/6e1d0088-7934-481b-8bd5-b6346f42b8de)

**Comment by DevAlchemyCD** [comment]
@rupalichavan9860 ! This ticket is working fine on the UX server. As mentioned in the ticket, the expected result, we need is that if we are going to add support in the current camp, then the name of the current camp should be highlighted, and there should be a tooltip displaying the info regarding the current camp. It's working on the UX-dev server.

**Comment by rupalichavan9860** [comment]
Yes this is working fine now

**Comment by rupalichavan9860** [comment]
Verified on live
