### ISSUE TITLE
Empty categories are selected when clicking on the cross after selecting categories. Getting error "SQLSTATE[23000]: Integrity constraint violation:"

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1109]
Please refer attached screenshot : 
![image](https://github.com/user-attachments/assets/5beaa49c-6b79-48f6-86c0-c8b329eb2856)

and getting below error on Save topic 
![image](https://github.com/user-attachments/assets/00aca164-e973-4d93-a83a-eb6e921311a8)

**Comment by ks-rahul** [comment]
@rupalichavan9860 I'm unable to reproduce this issue. It works fine on both the local and UX-dev servers. Please provide the steps to reproduce if any.

**Comment by rupalichavan9860** [comment]
@ks-rahul Please refer below steps 
1. Fill all information 
2. Select tag and click on cross icon in tags drop down , it will select empty tag 
3. Click on Save topic

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
