### ISSUE TITLE
Meta Tags API is failing for the following case

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#111]
**Steps to reproduce**

1. navigate to threads from recent activities from homepage
**Actual Result**
![image](https://user-images.githubusercontent.com/104552751/208851198-a218233a-ff1f-4fba-a72a-8933bb9d918f.png)

**Comment by sajid315** [comment]
Payload is invalid, string is passing in **forum_num** instead of integer.

**Comment by rupalichavan9860** [comment]
Verified
