### ISSUE TITLE
Profile Info (ADDITIONAL INFORMATION) is displayed in white, which is not visible.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1111]
Please refer attached screenshot : 
![image](https://github.com/user-attachments/assets/e1b5a727-0d84-42ea-8436-2b5c0d86bbf7)

**Comment by saniatg** [comment]
verified

**Comment by rupalichavan9860** [comment]
Verified on live
