### ISSUE TITLE
Count is showing 0 for few sec before correctly updating on statement history page

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1112]
When edit any statement, the count in left menu shows 0 for all which is not correct, it takes a sec where it shows 0 and then updates
![Screenshot 2024-08-14 at 4 31 59 PM](https://github.com/user-attachments/assets/9ab0de28-5f4e-45d9-8d37-6a8465fc4c27)

**Comment by wahaj-hafeez** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2039

**Comment by DevAlchemyCD** [comment]
PR: [the-canonizer/canonizer-3.0-frontend#2039](https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2039)

**Comment by saniatg** [comment]
verified

**Comment by saniatg** [comment]
Working fine on live
