### ISSUE TITLE
Create post - the field is seen blank on click submit button for a sec

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1113]
Steps:

1. Create a thread
2. Click on button " comment on this thread"
3.  On clicking button submit the field is seen blank, instead show a loader or should be smooth when submit
![Screenshot 2024-08-16 at 1 12 09 PM](https://github.com/user-attachments/assets/eaebcd33-b773-4ac3-8f00-5bd9af6ca962)

**Comment by saniatg** [comment]
verified

**Comment by hassaanCD** [comment]
Verified on live
