### ISSUE TITLE
"Remove all support "check box is not functional

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1114]
When Click on this checkbox, the button should show "remove" and onclick it should remove support

![Screenshot 2024-08-16 at 1 06 45 PM](https://github.com/user-attachments/assets/088f46ca-fa18-44d7-b459-100676c9d458)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2045

**Comment by hassaanCD** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
