### ISSUE TITLE
Thread- It should be 'Reply'  as it is singular if the count is 1 not replies

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1115]
![Screenshot 2024-08-16 at 3 42 01 PM](https://github.com/user-attachments/assets/fa7e33da-3756-4d2e-b2bf-f01e4a9b8b35)
Refer screenshot

**Comment by saniatg** [comment]
verified and is working fine

**Comment by hassaanCD** [comment]
Verified on live
