### ISSUE TITLE
Create camp is not working 

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1118]
'Create camp button is not enabling" when adding all mandatory fields

![Screenshot 2024-08-19 at 2 59 27 PM](https://github.com/user-attachments/assets/cdc78d8b-6b81-4482-a306-094971dc581d)

**Comment by hassaanCD** [comment]
Camp only created if user select nickname again, then button enabled.

**Comment by saniatg** [comment]
verified and is working  fine

**Comment by rupalichavan9860** [comment]
Verified on live
