### ISSUE TITLE
Parent camp as 'Agreement ' is not being saved when creating camp from any other camp detail page

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1119]
Steps:

1.  Go to any topic and create camp 'camp1' under agreement
2. Now from 'camp1' detail page click on 'create camp' button
3. Choose parent camp as 'Agreement' and click save

Actual result: 'camp1' is seen as parent camp
Expected result:Parent camp must be 'Agreement'

**Comment by saniatg** [comment]
verified

**Comment by rupalichavan9860** [comment]
Verified on live
