### ISSUE TITLE
Browse page- Drop down field should show hand pointer

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1121]
![Screenshot 2024-08-21 at 2 52 56 PM](https://github.com/user-attachments/assets/6df309ed-c904-4cc9-a29b-230c73f46da7)

**Comment by saniatg** [comment]
Not an issue

**Comment by DevAlchemyCD** [comment]
> Not an issue

All right, we already have a hand pointer. And seems fine.
