### ISSUE TITLE
Support- drag and drop is not working when trying to drag 2nd position and dropping to 1st

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1124]
![Screenshot 2024-08-22 at 10 54 25 AM](https://github.com/user-attachments/assets/bb7168ed-9bf6-40e4-8580-a7402b8bb9fc)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2175

**Comment by saniatg** [comment]
Working fine on manage support modal pop up.

**Comment by hassaanCD** [comment]
Verified on live
