### ISSUE TITLE
Page crash on manage camp 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1126]
![image](https://github.com/user-attachments/assets/67897336-d66d-43a0-b6e8-ee7a2c01e340)

**Comment by sajid315** [comment]
@wahaj-hafeez as discussed with Rahul , following code is breaking the page. Please check it asap.



![Image](https://github.com/user-attachments/assets/ebcd78d5-79c9-4934-b5bc-52446d5464fd)

**Comment by DevAlchemyCD** [comment]
PR : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2065

**Comment by rupalichavan9860** [comment]
Working fine now

**Comment by rupalichavan9860** [comment]
Working fine on live
