### ISSUE TITLE
Unable to submit camp statement - button is disabled

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1127]
![image](https://github.com/user-attachments/assets/80f4ad1d-d59d-4fbd-801b-5f11d60c549d)

**Comment by saniatg** [comment]
Getting page crash now , on click 'Add statement' button
![Screenshot 2024-08-26 at 10 53 00 AM](https://github.com/user-attachments/assets/1bdf2a2d-2279-4552-a17d-dc16a5f70bd5)

**Comment by rupalichavan9860** [comment]
working fine now

**Comment by rupalichavan9860** [comment]
Verified on live
