### ISSUE TITLE
PROFILE SETTINGS (PREFERENCES) : When the user chooses information(saved) and checks again, it does not display the saved information.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1128]
Please refer attached screenshot : 
![image](https://github.com/user-attachments/assets/5f75da54-5497-41e9-9e50-4e17cf19e5c4)

**Comment by rupalichavan9860** [comment]
Also, if the user picks language and/or algorithms but does not select any tags and tries to save the data, they will get the following error.

![image](https://github.com/user-attachments/assets/b4175070-fc46-410b-8e17-97b5aba0249f)

**Comment by saniatg** [comment]
@vikasranatalentelgia Not fixed
![Screenshot 2024-10-07 at 1 07 09 PM](https://github.com/user-attachments/assets/e1fd617f-496a-4942-b8a2-ba74b2e7c1c5)

**Comment by rupalichavan9860** [comment]
@vikasranatalentelgia Topic tags are now saved; however, Language and Default Algorithm Preferences are not.

**Comment by rupalichavan9860** [comment]
Getting error for topic tags as well 
![image](https://github.com/user-attachments/assets/b68e39ab-db5d-43b7-a8d9-ac0bbd8cde7d)

**Comment by hassaanCD** [comment]
I am also getting an issue while testing preferences.
Steps:
Create a new topic and navigate directly to preference page without adding any tags in the topic (from topic detail page) .
You will see a lot of tag options and two of them are already selected which is an issue. 
No tags must be already selected for new topics. Tags must be selected by user from options and remain save after click on save button.

**Comment by saniatg** [comment]
@vikasranatalentelgia on click save button , show message " Information save successfully" a toaster message

**Comment by saniatg** [comment]
working fine now

**Comment by akashgit77** [comment]
@vikasranatalentelgia we are getting again
Steps:

1. Select tag and  save then click on discard and save.
2. Refresh the page and save again

![Image](https://github.com/user-attachments/assets/6134a465-a009-4aaf-9ddb-6d1eb2de4112)

**Comment by rupalichavan9860** [comment]
Topic tags are now saved; however, Language and Default Algorithm Preferences are not.

**Comment by rupalichavan9860** [comment]
@vikasranatalentelgia Still Language and Default Algorithm Preferences are not getting saved

**Comment by saniatg** [comment]
@vikasranatalentelgia Save  Language and Default Algorithm Preferences  and tags now open the same URL in incognito window, the changes will not be saved

**Comment by rupalichavan9860** [comment]
Working fine on UX server

**Comment by rupalichavan9860** [comment]
Verified on live
