### ISSUE TITLE
Home Page and privacy-policy : Need to highlight the links. Currently, links are highlighted on mouse hover.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1130]
![image](https://github.com/user-attachments/assets/2a4608bb-6bf8-4f5a-b975-8b38e8917245)

![image](https://github.com/user-attachments/assets/ee73644e-790f-4d16-80f4-6e9c13cb3a42)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2203

**Comment by rupalichavan9860** [comment]
Verified

**Comment by akashgit77** [comment]
![Image](https://github.com/user-attachments/assets/8e7b1968-53e0-4864-8641-b6b31a04e475)

@rupalichavan9860 Should we highlight this link too?

**Comment by rupalichavan9860** [comment]
@akashgit77 I think this is fine, since we already have one link to the home page on the same page.

**Comment by sajid315** [comment]
> [@akashgit77](https://github.com/akashgit77) I think this is fine, since we already have one link to the home page on the same page.

Ok @rupalichavan9860 so we can move this ticket ahead.

**Comment by rupalichavan9860** [comment]
Yes @sajid315 Working fine on live as well so closing this
