### ISSUE TITLE
Browse- Sometimes , browse page takes more than a minute to load 

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1133]
![Screenshot 2024-08-26 at 10 23 06 PM](https://github.com/user-attachments/assets/5cb17a66-d7f8-4128-b38d-eb6ccb44d2bc)

**Comment by saniatg** [comment]
Also , sometimes on click browse shows 'internal error"

![Screenshot 2024-08-26 at 10 45 20 PM](https://github.com/user-attachments/assets/159aaa6a-5fad-40c6-8257-18ca0ec316da)

**Comment by sunnyjindal** [comment]
Closing this ticket as this was resolved sometime ago.
