### ISSUE TITLE
Notifications- The count is not showing on bell icon, when I click on 'View all' then shows count

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1134]
1. Login the app
2. Now when you click on notification icon, there is no count

![Screenshot 2024-08-26 at 10 40 09 PM](https://github.com/user-attachments/assets/551673d0-a932-4809-b47a-db4b82170782)
 
3. Now click on 'View all notification" and suddenly count appears
![Screenshot 2024-08-26 at 10 40 28 PM](https://github.com/user-attachments/assets/7474e33d-30ed-443b-9cfc-8ae2b3589542)

**Comment by rupalichavan9860** [comment]
Verified

**Comment by hassaanCD** [comment]
Verified on live
