### ISSUE TITLE
Print is not working 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1137]
Please refer attached screenshot : 
![image](https://github.com/user-attachments/assets/ed30f9c0-e403-47bf-82ac-b8cee06be230)

**Comment by vikasranatalentelgia** [comment]
@rupalichavan9860 Kindly close the ticket,
 It is working fine

**Comment by rupalichavan9860** [comment]
Verified on live
