### ISSUE TITLE
Join canonizer to support menu option is not working

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1138]
When the user clicks on "Join Canonizer to Support," nothing happens, and the 3 dots menu does not open. The user must reload the website to continue the process.
Please refer attached screenshot : 

![image](https://github.com/user-attachments/assets/59b8daa7-e5ce-441b-8b29-0231570b2e37)

**Comment by rupalichavan9860** [comment]
Verified

**Comment by hassaanCD** [comment]
Verified on live
