### ISSUE TITLE
Page crash when copy / paste my threads URL in other browser 

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1148]
Steps:  

1. User A creates thread
2. Go to my threads and copy URL
3. Paste in other browser

Getting crash

![Screenshot 2024-08-27 at 12 42 01 PM](https://github.com/user-attachments/assets/3e62eba9-e3e0-4931-89bb-6245bc4bf768)

**Comment by ks-rahul** [comment]
@saniatg i have tested this and working fine for me. is there any specific scenario please provide?

**Comment by saniatg** [comment]
Not coming now. Closing for now

**Comment by hassaanCD** [comment]
Verified on live
