### ISSUE TITLE
Nickname- Icon is missing for a specific nickname

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1149]
Refer screenshot
![Screenshot 2024-08-27 at 1 26 53 PM](https://github.com/user-attachments/assets/ea50b4a5-330e-419e-af9c-48e821779a82)

**Comment by ks-rahul** [comment]
@saniatg we have removed the icon now.

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
