### ISSUE TITLE
"Remove Support" message is not showing properly on "Supported Camp" page

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/Canonizer-Beta--Issue-Tracking#1151]
When user try to remove support from "Supported Camp" page. Then "Remove Support" message is not showing properly.
As shown in attached screenshot:

![Image](https://github.com/user-attachments/assets/6744f1de-593c-46d6-8491-c5bca9e8299c)

**Comment by nalwa** [comment]
@hassaanCD  can you please add exact case in which message is not appearing.  that would be helpful. thanks

**Comment by hassaanCD** [comment]
"Remove Support" success message is not showing now. For better user experience we must show "Remove Support" success message.

**Comment by hassaanCD** [comment]
Still not able to see "success message" after support removal. So I am reverting this ticket.

**Comment by hassaanCD** [comment]
Verified on UX-DEV

**Comment by hassaanCD** [comment]
Verified on live
