### ISSUE TITLE
Update Camp Statement : Getting error "The given data was invalid." 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1155]
Steps to reproduce : 
1. Create topic
2. Add camp statement 
3. Do not commit changes
4. Edit Change - add some more text 
5. Click on "Publish Statement" 

Getting below error : 

![image](https://github.com/user-attachments/assets/a347cf5f-8cdd-4be2-9b9a-cf8f5a36d223)

**Comment by rupalichavan9860** [comment]
@wahaj-hafeez @sajid315 I am not getting error now but when I edit the change , changed text is not visible on record

**Comment by rupalichavan9860** [comment]
Verified on UX server

**Comment by saniatg** [comment]
Not fixed on live "I am not getting error now but when I edit the change , changed text is not visible on record"

**Comment by rupalichavan9860** [comment]
Verified on live
