### ISSUE TITLE
Update Camp issues

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1156]
Issue 1 : Camp Name field should disabled for camp "Agreement"
Currently user is able to modify "Agreement" camp name

Issue 2 : Remove "Parent Camp" field for Agreement camp 

Issue 3 : "Update Camp" button is disabled 
Currently user is unable to submit new changes to the camp

Please refer below screenshot : 

![image](https://github.com/user-attachments/assets/b0bb0061-e774-46da-94a2-03f50de816fe)

**Comment by sajid315** [comment]
Same sort of issue reported in following ticket.

https://github.com/the-canonizer/canonizer-3.0-frontend/issues/2075

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
