### ISSUE TITLE
Recent Initiatives: For camp statements, HTML tags are displayed.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#116]
Please refer attached screenshot : 

![image](https://user-images.githubusercontent.com/40416610/209045589-f9a9f1c6-f96b-4bb3-829a-616f318686f7.png)

**Comment by rupalichavan9860** [comment]
Still getting undefined for image 
![image](https://user-images.githubusercontent.com/40416610/210595991-1cb44c00-b448-4ded-812c-171d014c6fad.png)

**Comment by hassaanCD** [comment]
fixed

**Comment by rupalichavan9860** [comment]
Verified on live
