### ISSUE TITLE
Objection on history pages are not working

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1160]
Steps:

1. Submit any change from non supporter
2.  Now when supporter tries to object on click Object button, the object page is not seen instead the update page is seen

**Comment by sajid315** [comment]
I just checked the figma design, its missing the objection forms. So we are working on it & informed to Twinkle regarding updates.

We need to add objection form for topic/camp & statement.

**Comment by DevAlchemyCD** [comment]
PR:  https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2145

**Comment by hassaanCD** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
