### ISSUE TITLE
Profile- Incorrect DOB is being saved

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1162]
As a user I deleted the saved DOB and left it empty and saved the changes. After few hours of exploring the app , I saw some random date got saved
![Screenshot 2024-08-28 at 1 20 32 PM](https://github.com/user-attachments/assets/1638bacb-390a-47f5-a433-32e35024d941)

**Comment by vikasranatalentelgia** [comment]
![image](https://github.com/user-attachments/assets/32362549-ef0b-46d3-b65f-2dbc31e40d32)
@saniatg I have removed the DOB and it is working fine

**Comment by saniatg** [comment]
It working fine now

**Comment by hassaanCD** [comment]
Verified on live
