### ISSUE TITLE
Some videos are not playing

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/Canonizer-Beta--Issue-Tracking#1163]
Some videos like "The World In Your Head" are not playing.

**Comment by sajid315** [comment]
@akuks the video URL is added in config but we are missing slash in the base URL. After adding this it will work fine.



![Image](https://github.com/user-attachments/assets/d5d4f91c-6053-4167-be8b-83d4753eb4d7)

**Comment by sajid315** [comment]
@hassaanCD all of the videos are playing now on ux-dev server. Have a look please.

**Comment by rupalichavan9860** [comment]
Working fine now

**Comment by rupalichavan9860** [comment]
Verified on live
