### ISSUE TITLE
Not able to create topic with spaces

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1164]
Steps:

1. Click on create topic button
2. Add many spaces and then add duplicate title
3. Click save button

Nothing is happening, there is no error message of duplicate title
![Screenshot 2024-08-28 at 2 57 26 PM](https://github.com/user-attachments/assets/93a2b8e2-02c0-408d-bbb5-374b16fb3cba)

**Comment by ks-rahul** [comment]
@saniatg We are trimming only the leading and trailing spaces.

**Comment by saniatg** [comment]
Right but  there is not error message incase of duplicate topic

**Comment by saniatg** [comment]
@ks-rahul Not fixed

**Comment by ks-rahul** [comment]
@saniatg ![Image](https://github.com/user-attachments/assets/58f1893a-1d80-4672-a7ec-870e37d57fa7)
can you please specify the steps

**Comment by saniatg** [comment]
working now

**Comment by saniatg** [comment]
Verified on live
