### ISSUE TITLE
Remove subscription is not working in specific case

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1165]
Precondition- There should  be camps in a topic

1. Subscribe an entire topic and camp
2. On profile , subscriptions click on remove icon

The topic is not unsubscribed , only icon is removed

**Comment by vikasranatalentelgia** [comment]
@saniatg Close this ticket  because in the updated design user icon is remove from the topic 

Now user cant remove the topic directly
