### ISSUE TITLE
Manage Statement : Getting error "Error during AI improvement!" on "Improve with AI"

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1167]
Please refer attached screenshot : 

![image](https://github.com/user-attachments/assets/56de1c6a-ae90-448e-887b-a4dae41f388a)

**Comment by ks-rahul** [comment]
@rupalichavan9860 The OpenAI key is currently missing on the server. I will ask @akuks  to update the OpenAI key for this.

**Comment by rupalichavan9860** [comment]
Working fine now

**Comment by rupalichavan9860** [comment]
Again facing same issue on UX and beta server

**Comment by ks-rahul** [comment]
@rupalichavan9860 openapi key is missing

**Comment by saniatg** [comment]
This is removed now
