### ISSUE TITLE
Emojis aren't working for the new editor.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#117]
Please refer below screenshot : 
![image](https://user-images.githubusercontent.com/40416610/209045850-e3e694ae-4d9f-4186-8635-ebaf093d2248.png)

**Comment by SidhantUppalSyantaq** [comment]
@rupalichavan9860 Do we need to save the emojis or should we remove the option to add the emoji's ?

**Comment by vikasranatalentelgia** [comment]
@rupalichavan9860 Do we need to save the emojis or should we remove the option to add the emoji's ?

**Comment by saniatg** [comment]
@rupalichavan9860 Tested and is working fine for both live and staging.

**Comment by rupalichavan9860** [comment]
Verified
