### ISSUE TITLE
Create/Edit camp issues

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1175]
1. Keywords field is missing on Create/Edit camp 
2. Update Camp form : It should be "Input information required to update a camp." instead of "Input information required to create a camp."
![image](https://github.com/user-attachments/assets/58aa7482-b5a6-4c06-9e11-452ec275d904)

**Comment by ks-rahul** [comment]
@rupalichavan9860 The keyword field has been removed in the new design and replaced with a topic tag.

**Comment by rupalichavan9860** [comment]
@ks-rahul Keywords field is available on history page 
![image](https://github.com/user-attachments/assets/dbb8e57a-a3c1-41e5-9d39-933d7f7a7485)

Do we need to rename this?

**Comment by rupalichavan9860** [comment]
And we don't have tags for camp.

**Comment by ks-rahul** [comment]
@rupalichavan9860 I have removed the keywords field from the camp history page.

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
