### ISSUE TITLE
Forgot Password (Enter password verification code): Cursor should point to next input field 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1179]
Please refer attached screenshot : 

![image](https://github.com/user-attachments/assets/906500c4-4a8a-41d2-b6ad-82cfd6497ab0)

As of now, the user must manually click in each box to enter the OTP

**Comment by rupalichavan9860** [comment]
Working fine now

**Comment by hassaanCD** [comment]
Verified on live
