### ISSUE TITLE
Issue in creating a topic in specific cases.

### ISSUE THREAD

**Issue by gautamv16** [the-canonizer/Canonizer-Beta--Issue-Tracking#1181]
Please find attached screenshot.

![image](https://github.com/user-attachments/assets/8abe0e86-37bb-442e-9247-7e6d2bffbc0d)

**Comment by rupalichavan9860** [comment]
@gautamv16 @ks-rahul This is already reported https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/issues/1109

**Comment by rupalichavan9860** [comment]
Working fine now

**Comment by rupalichavan9860** [comment]
Verified on live
