### ISSUE TITLE
Nickname must not accept only special characters etc.

### ISSUE THREAD

**Issue by gautamv16** [the-canonizer/Canonizer-Beta--Issue-Tracking#1182]
Please refer attached screenshot. There must be a special character validation for nickname.

![image](https://github.com/user-attachments/assets/d87ef43f-d7ca-4a9d-8a2c-0fdaa805fd86)

**Comment by saniatg** [comment]
verified

**Comment by saniatg** [comment]
@vikasranatalentelgia I think here Gautam is saying that Special char are allowed but not all.

**Comment by rupalichavan9860** [comment]
Verified on UX server

**Comment by rupalichavan9860** [comment]
Verified on live
