### ISSUE TITLE
Browse search- when searched for keyword' 23e' page keeps loading

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1185]
![Screenshot 2024-08-30 at 11 30 07 AM](https://github.com/user-attachments/assets/d4f20436-7af1-4c44-88ff-e8c603056c1b)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2111

**Comment by saniatg** [comment]
verified

**Comment by hassaanCD** [comment]
Verified on live
