### ISSUE TITLE
Browse search - Search  drop down is not collapsing after enter

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1186]
![Screenshot 2024-08-30 at 11 36 52 AM](https://github.com/user-attachments/assets/7630ccfc-1203-4d84-b56f-206a6e9560fb)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2111

**Comment by saniatg** [comment]
verified

**Comment by hassaanCD** [comment]
Verified on live
