### ISSUE TITLE
After clear search, it is not going back to "Browse" page and stay on searched topic page

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/Canonizer-Beta--Issue-Tracking#1187]
Steps:
User logged in and navigate to "Browse" page
Then User type any topic in "search bar" and enter
User navigates to the "searched topic"
Then staying on same searched topic page if user clear the already searched topic then it is not navigating back to "Browse" main page

Expected Result: It must go back to "Browse" main page

**Comment by wahaj-hafeez** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2111

**Comment by DevAlchemyCD** [comment]
PR:  https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2111

**Comment by hassaanCD** [comment]
Verified

**Comment by hassaanCD** [comment]
Verified on live
