### ISSUE TITLE
Browse page: When user go to "number of topic per page" dropdown dropdown and click on it, then page scroll back to top

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/Canonizer-Beta--Issue-Tracking#1188]
Steps:
User logged in and navigate to "Browse" page
User scroll down to "number of topic per page" dropdown and click on it
When user clicks it, it navigates back to the top which is a bug

**Comment by ks-rahul** [comment]
@hassaanCD this is working fine

**Comment by hassaanCD** [comment]
Verified

**Comment by hassaanCD** [comment]
Verified on live
