### ISSUE TITLE
Show "no data found" text when no matching results are found on browse page

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1189]
When choose any tag and no matching results are found , currently is shows blank instead show no data found.
![Screenshot 2024-08-30 at 4 21 28 PM](https://github.com/user-attachments/assets/6a512eaa-903d-4546-8976-0a697351b5d1)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2111

**Comment by saniatg** [comment]
verified

**Comment by hassaanCD** [comment]
Verified on live
