### ISSUE TITLE
Include topic tags on the topic history page.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1190]
once picked, there is no way to view the topic tags the user has chosen for the topic. we need to show them on the topic history page

**Comment by sajid315** [comment]
@rupalichavan9860 I am working on this ticket , right now according to flow we have single record of attached tags with a topic. 

So with each topic history card , do we need to retain the history of selected tags at that specific time ? That's needed to be discussed.

**Comment by sajid315** [comment]
At the front-end following is the node-id to show the tags,

https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=77-4580&node-type=FRAME&t=i5dc9oA48Mb3noDi-0#938124730

**Comment by sajid315** [comment]
Raised PR: 

https://github.com/the-canonizer/canonizer-3.0-api/pull/1136

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2152

**Comment by rupalichavan9860** [comment]
Topic tags are added in breadcrumb detail, but there are other issues that I have logged individually, so I'm closing this.

**Comment by rupalichavan9860** [comment]
Verified on live
