### ISSUE TITLE
Camp Leader nickname should have link 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1191]
![image](https://github.com/user-attachments/assets/ea654edb-ebe1-4b4f-ab62-b13f2ddbd9b3)

**Comment by rupalichavan9860** [comment]
Not fixed
![image](https://github.com/user-attachments/assets/80ba3031-8ae2-4811-839a-65b0faa1b96b)

**Comment by wahaj-hafeez** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2152

**Comment by DevAlchemyCD** [comment]
PR:  https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2152

**Comment by rupalichavan9860** [comment]
Can see the link, however it must be in blue like the other links. 
![image](https://github.com/user-attachments/assets/6ac87574-65f9-48dd-b8e8-516f240ea73f)

**Comment by ks-rahul** [comment]
as discussed with Rupali I have fixed this ticket

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
