### ISSUE TITLE
Specific Topic is crashing

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1193]
https://ux-dev.canonizer.com/topic/4737-test5363/1-Agreement
![Screenshot 2024-08-30 at 7 35 21 PM](https://github.com/user-attachments/assets/16049455-963b-442f-9918-28a7c00ebddb)

**Comment by rupalichavan9860** [comment]
Working fine now

**Comment by saniatg** [comment]
This topic is not on live
