### ISSUE TITLE
Camp leader is not updating in update pages

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1199]
Steps:

1. Assign agreement camp a camp leader
2. On agreement camp update page , update camp leader to no camp leader
3. Submit the update
4. Edit the update

In the Camp leader field will still show the name of camp leader instead it should how 'No camp leader'

**Comment by DevAlchemyCD** [comment]
PR : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2203

**Comment by rupalichavan9860** [comment]
Verified

**Comment by hassaanCD** [comment]
Verified on live
