### ISSUE TITLE
Remove support is not working

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#12]
**Steps to reproduce**

1. login with valid credentials
2. create a topic
3. click on remove support
**Actual Result**
update api is failing
![image](https://user-images.githubusercontent.com/104552751/203481886-e8942d1f-505e-4de1-aa86-42670050b406.png)

**Comment by nalwa** [comment]
@rupalichavan9860  i have fixed this issue and raised PR against this.

**Comment by rupalichavan9860** [comment]
Working fine now
