### ISSUE TITLE
In the following case, the subscribed camp is not listed in email

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#120]
Steps to reproduce : 
1. Login with User A and create topic and create camp("camp 1")
2. Subscribe to entire topic, Agreement camp and sub camp ("camp 1")
3. Add support to "camp 1" 

![image](https://user-images.githubusercontent.com/40416610/209280324-c9d65400-e3fd-4387-9934-d5d7359ce469.png)

Expected Result : 
It should list all subscribed camps in email

Actual Result : 
"You are subscribed to Agreement(link to Agreement)" is missing

![image](https://user-images.githubusercontent.com/40416610/209280259-69518367-eddd-4301-b776-13b329bc650f.png)

Steps to reproduce : 
1. Login with User A and create topic and create camp("camp 1")
2. Subscribe to entire topic, Agreement camp and sub camp ("camp 1")
3. Add support to "camp 1" 
4. Login with User B and delegate support to User A 

Expected Result : 
It should list all subscribed camps in email

Actual Result : 
"You are subscribed to Agreement(link to Agreement)" is missing

![image](https://user-images.githubusercontent.com/40416610/209280853-af4c215e-8e0c-463c-a1c7-095ae55d49dd.png)

**Comment by saniatg** [comment]
@rupalichavan9860 tested and is working fine on staging and on live.

**Comment by rupalichavan9860** [comment]
Verified
