### ISSUE TITLE
The subscribed camp icon should be highlighted in blue color.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1205]
Please refer attached screenshot :
![image](https://github.com/user-attachments/assets/286610e0-c44e-4814-b580-5ad6210e23fe)

**Comment by rupalichavan9860** [comment]
@ks-rahul It works fine in menu options but not in breadcrumbs. Could you also do the same in breadcrumbs?

**Comment by rupalichavan9860** [comment]
Working fine now

**Comment by hassaanCD** [comment]
Verified on live
