### ISSUE TITLE
Include review filter :"In review" camp name should appear on the Include review filter. 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1208]
![image](https://github.com/user-attachments/assets/feb2b003-7732-4740-958a-41150de4efdd)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2305

**Comment by rupalichavan9860** [comment]
Verified on UX server

**Comment by saniatg** [comment]
Verified on live
