### ISSUE TITLE
Add/Manage Support : Validations are missing for Citation link

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1209]
Currently accepting normal text as well 

![image](https://github.com/user-attachments/assets/ca5e3448-4f74-4a98-8553-5b23932c920f)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2152

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
