### ISSUE TITLE
incorrect score for the following case

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#121]
**Steps To Reproduce**

1. create a topic
2. create 4 camps
3. support all 4 camps
4. change parent of camp1 to camp4
5. change parent of camp3 to camp2
6. navigate to camp2
7. click on directly add and support 
8. make camp2 1st preference --> click on submit
**Actual Result**
![image](https://user-images.githubusercontent.com/104552751/209282161-e57508ea-cb14-4f4b-a54c-e83f3af62bae.png)

**Comment by saniatg** [comment]
@rupalichavan9860 tested and is working fine on staging and live.

**Comment by rupalichavan9860** [comment]
Verified
