### ISSUE TITLE
Add/Manage Support issues 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1210]
Issue 1 : It should be "Reason for adding/removing support" instead of "Reason for adding support" when user is adding/removing support

Issue 2 : It should be "Reason for adding/removing/changing order support" instead of "Reason for adding support" when user changing support order

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2152

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
@wahaj-hafeez Issue 2 is not working on both UX and live

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2356

**Comment by rupalichavan9860** [comment]
Working fine

**Comment by saniatg** [comment]
Working fine on live
