### ISSUE TITLE
Notifications are not working

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1211]
![Screenshot 2024-09-03 at 11 09 15 AM](https://github.com/user-attachments/assets/83a27b2f-1ac1-40ea-8a61-10c9d86180ff)

**Comment by array-junkie** [comment]
@saniatg Notifications are working now. Kindly recheck the ticket.

**Comment by saniatg** [comment]
working now

**Comment by saniatg** [comment]
working on live
