### ISSUE TITLE
Remove Keywords from Camp History Comparison page 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1218]
![image](https://github.com/user-attachments/assets/d97e8d09-699b-49a7-b721-aa92bb71764e)

**Comment by rupalichavan9860** [comment]
#1175 
 According to the ticket, keywords have been deleted, hence they must also be removed from the comparison page.

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2197

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
@wahaj-hafeez They are still available on live - Camp History and Camp History Comparison page 
![image](https://github.com/user-attachments/assets/bf9dbeef-39a4-4d1c-a29a-465dcb5314f7)


![image](https://github.com/user-attachments/assets/eff8dac7-b4d3-4a2d-8c9e-7493d6890c91)

**Comment by DevAlchemyCD** [comment]
As per our discussion with all teams, we have removed the keywords field from UI for both current and new camps.

**Comment by rupalichavan9860** [comment]
Verified on UX server

**Comment by saniatg** [comment]
Working fine on live
