### ISSUE TITLE
Email (topic/camp create) :  Remove Topic /camp Summary 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1219]
Since the topic /camp summary is not available on the create topic /camp page, we also need to delete it from the email.
Please refer attached screenshot : 
![image](https://github.com/user-attachments/assets/9f818a40-a5af-4ab2-bed0-d9fe58e88879)

![image](https://github.com/user-attachments/assets/9f4d8e4d-78cd-4ff7-b7fa-5c331b90b000)

**Comment by rupalichavan9860** [comment]
Not fixed yet 
![image](https://github.com/user-attachments/assets/ed327b9b-e6cb-4f72-996f-54f3dd71cb2b)

![image](https://github.com/user-attachments/assets/1ef63244-d2fc-4d2a-b42d-9da80be218ab)

**Comment by array-junkie** [comment]
@rupalichavan9860 It occurs again due to cache. It is resolved now. Kindly check again.

**Comment by rupalichavan9860** [comment]
Yes @M-Darab Working fine now

**Comment by rupalichavan9860** [comment]
Verified on live
