### ISSUE TITLE
Wiki editor (Statement) : The topic detail page's wiki text formatting is incorrect.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#122]
Please refer attached screenshot : 
Statement history page : 
![image](https://user-images.githubusercontent.com/40416610/209307416-75ff8780-021b-4d1b-9a4f-9326723bce97.png)

Topic detail page : 
![image](https://user-images.githubusercontent.com/40416610/209307395-01c661f3-e113-40c6-9b6e-cdaf8ffb6b63.png)

**Comment by saniatg** [comment]
@sunilspr7  bullets shows solid round ones when adding statement, but on detail shows round ones. Refer screenshots
![Screenshot 2023-01-04 at 6 54 02 PM](https://user-images.githubusercontent.com/91254708/210565838-f57aa96d-36b4-461f-bee2-2cee1497679d.png)
![Screenshot 2023-01-04 at 6 54 15 PM](https://user-images.githubusercontent.com/91254708/210565858-9ff6584e-d158-4cb4-a930-8363741c8ab2.png)

**Comment by rupalichavan9860** [comment]
Closing this because we are no longer using the wiki editor
