### ISSUE TITLE
Archive- When archive a camp which has support , it should not show in supported camp

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1228]
Also, in support tree, it should not show the name and the support

![Screenshot 2024-09-04 at 6 10 08 PM](https://github.com/user-attachments/assets/a5fc4eec-b95a-477c-bd4e-63533e2fb564)

**Comment by array-junkie** [comment]
@saniatg This issue is not reproducible. Kindly take a look and mention the steps to reproducible (if any).

**Comment by saniatg** [comment]
verified

**Comment by hassaanCD** [comment]
Verified on live
