### ISSUE TITLE
Will move the wysiwyg editor only after canonizer 3 is live

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#123]
As discussed , code will be reverted from beta and will use Wiki editor only.

Will move the wysiwyg editor only after canonizer 3 is live

**Comment by sunilspr7** [comment]
https://github.com/the-canonizer/canonizer-3.0-api/pull/487

**Comment by rupalichavan9860** [comment]
wysiwyg editor is implemented
