### ISSUE TITLE
Camp Archive issues 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1230]
Camp Archive is not working properly on new UI/UX 

Issue 1 : Unarchive This Camp button is missing 

Issue 2: When trying to update camp (to unarchive the camp), the change is automatically objected.  
![image](https://github.com/user-attachments/assets/8a3549da-8b05-473e-9738-c384e1cbd1d3)

**Comment by array-junkie** [comment]
@wahaj-hafeez In the case of Camp Archive, the "Edit based on this" button should be disabled for all the changes other than the live change.

**Comment by DevAlchemyCD** [comment]
PR:  https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2152

**Comment by rupalichavan9860** [comment]
Verified

**Comment by sajid315** [comment]
For production site the hotfix is following:
https://github.com/the-canonizer/canonizer-3.0-api/pull/1146

**Comment by rupalichavan9860** [comment]
Verified on live
