### ISSUE TITLE
Remove Create Camp button for archived camp

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1232]
Please refer attached screenshot : 
![image](https://github.com/user-attachments/assets/c0ba4d15-b5ba-47b1-a11b-0778919db01a)

Currently getting below error , 
![image](https://github.com/user-attachments/assets/8a92b023-bf66-4d59-9840-c7c63612ce34)

**Comment by saniatg** [comment]
Not fixed @ks-rahul

**Comment by saniatg** [comment]
Not fixed
If you archive a camp from update camp page on right side click on button 'update camp' then on that page you will see 'create camp' page it should not work
![Screenshot 2024-09-18 at 11 50 59 AM](https://github.com/user-attachments/assets/a1e7f028-0a91-48eb-a128-fd08cb4dd58d)

**Comment by ks-rahul** [comment]
@saniatg I am not able to replicate this issue could you please provide more details or connect on call to show?

**Comment by saniatg** [comment]
@ks-rahul attached video for the steps

https://github.com/user-attachments/assets/b4358431-8832-4be8-b2c7-7509db81b35c

**Comment by sajid315** [comment]
@rupalichavan9860 , @saniatg in case of archive this button should be disabled as well OR should be removed. 
We are looking into this. 

![Image](https://github.com/user-attachments/assets/4d55a91c-f949-4aca-af64-bee6094f17a4)

**Comment by ks-rahul** [comment]
@sajid315 If we disable this button, how will the user be able to unarchive the camp?

**Comment by ks-rahul** [comment]
@saniatg I have followed the steps shown in the video, but I am still unable to replicate the issue. It is working fine on both the server and locally.

**Comment by saniatg** [comment]
@ks-rahul still not working, showing update camp but if a camp is archived it can only be unarchive not edit. Need to remove the button "update current camp"
![Screenshot 2024-10-03 at 11 55 11 AM](https://github.com/user-attachments/assets/969b837a-f62a-43e0-8edf-576977a14159)

**Comment by saniatg** [comment]
verified

**Comment by rupalichavan9860** [comment]
Verified on live
