### ISSUE TITLE
In the case described below, the URL displays filter=undefined. 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1233]
Click on any camp from "Consensus tree" and observe URL 
Please refer attached screenshot : 
![image](https://github.com/user-attachments/assets/f530e924-5fd9-483c-bfd7-29e86d254710)

**Comment by rupalichavan9860** [comment]
Working fine now

**Comment by hassaanCD** [comment]
Verified on live
