### ISSUE TITLE
Adding Camp Statement : Getting error "The given data was invalid." on Save As Draft button in below case

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1234]
Without entering in mandatory fields click on "Save As Draft" button 
Actual Result : Getting error "The given data was invalid."
Please refer attached screenshot 

![image](https://github.com/user-attachments/assets/21dd029e-b0d9-4ba1-90a9-7e9ca7940d2e)

**Comment by sajid315** [comment]
@rupalichavan9860 we have checked this issue that is actually coming due to validation issue. 
This part of validation is linked with ticket #1253 on which Rahul is working on. 

Once that ticket will be done we will consider this issue and work on it.

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2152

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
