### ISSUE TITLE
Add Statement from menu is not redirecting to the Add Camp Statement page in case of as of date filter

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1235]
when the user clicks on Add Statement (as of date filter applied) in the menu, it does not redirect to the Add Camp Statement page. 

Currently it is reloading same page

**Comment by hassaanCD** [comment]
Verified

**Comment by hassaanCD** [comment]
Verified on live
