### ISSUE TITLE
Google Address is not working

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1237]
Please refer attached screenshot : 
![image](https://github.com/user-attachments/assets/0667c367-d947-46f1-88a1-fce91c6a2583)

**Comment by vikasranatalentelgia** [comment]
@rupalichavan9860 

![image](https://github.com/user-attachments/assets/9f66842b-e11e-492e-96a2-a280439694f4)

URL needs to be authorized

**Comment by rohit-talentelgia** [comment]
@akuks kindly check this
