### ISSUE TITLE
Mobile - Thread page is not responisve

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1246]
![ImportedPhoto 747294154 622343](https://github.com/user-attachments/assets/6f41dfd9-cf25-477c-8314-7e02390d95af)

**Comment by ks-rahul** [comment]
@saniatg this is fixed already
![Image](https://github.com/user-attachments/assets/821d28be-62cd-46ba-8556-1ccae82ff0af)

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
