### ISSUE TITLE
Add Statement - buttons are overlapping and not aligned

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1248]
![ImportedPhoto 747294154 623614](https://github.com/user-attachments/assets/1b7df533-b28c-4b0a-8df6-f85be50a7198)

**Comment by saniatg** [comment]
@ks-rahul Not fixed

**Comment by hassaanCD** [comment]
Verified

**Comment by saniatg** [comment]
Verified on live
