### ISSUE TITLE
Frontend : Message required for ticket https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/issues/91 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#125]
Frontend : Message required for ticket https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/issues/91 
Message : "You are not authorized to object to this topic/camp/statement because you do not support this camp."

**Comment by saniatg** [comment]
@shahab-ramzan Message is not showing in case of statement. When non supporter submit the Objection .

**Comment by sunilspr7** [comment]
When a direct supporter copies the URL and logs in, the Object button is disabled; however, when the page is reloaded, the Object button is enabled.

**Comment by rupalichavan9860** [comment]
@vikasranatalentelgia Working properly for topic and camp history pages, but the statement history page still has a problem.

**Comment by vikasranatalentelgia** [comment]
@rupalichavan9860 PR raised for the same
