### ISSUE TITLE
Incorrect sibling camp listing 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1251]
Please refer attached screenshot : 
Tree : 
![image](https://github.com/user-attachments/assets/ebf6a17c-0eb2-4b9a-8ccb-f3661356ccf0)

click on camp "C3" , "C4" and "C5" and observe SIBLING CAMPS section

![image](https://github.com/user-attachments/assets/0855e7f6-2931-456b-8235-c5219f0e777f)

Actual Result : Camp "C2" is listing instead of "C1"

**Comment by sajid315** [comment]
@rupalichavan9860 the issue has been resolved as discussed in call with you. 
PR has been merged on Ux-dev you can check it now for the above same topic. 

![Image](https://github.com/user-attachments/assets/2a6a9ece-052e-49ab-8d00-3c18aeb76a10)

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
