### ISSUE TITLE
Search : "General" canon name showing for all topics 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1252]
Please refer attached screenshot : 
![image](https://github.com/user-attachments/assets/3dd85aa5-9a42-485b-bf10-a8db3847d3be)

![image](https://github.com/user-attachments/assets/e142e92f-f144-4235-b57f-2adf1500432d)

**Comment by saniatg** [comment]
@vikasranatalentelgia not fixed
![Screenshot 2024-10-07 at 10 53 57 AM](https://github.com/user-attachments/assets/3f311a21-243b-4f2e-af03-8d2b6242afca)

**Comment by saniatg** [comment]
Working fine

**Comment by rupalichavan9860** [comment]
Verified on live
