### ISSUE TITLE
Wrong spelling of additional

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1255]
Please refer attached screenshot : 
![image](https://github.com/user-attachments/assets/06ede9ab-ff27-400a-a797-112e0b88b63a)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2175/files

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
