### ISSUE TITLE
Mobile device (Supported camps ) : Search box and reset button overlapping remove support icon

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1259]
Please refer attached screenshot :

![image](https://github.com/user-attachments/assets/1b5d36e6-ff0a-4b53-8b1b-060a056621e1)

**Comment by saniatg** [comment]
@ks-rahul Not fixed
![ImportedPhoto 750747134 869486](https://github.com/user-attachments/assets/516fd030-10d0-4eb5-8a51-8a9b02cbd76b)

**Comment by ks-rahul** [comment]
@saniatg can we connect

**Comment by saniatg** [comment]
@ks-rahul cache issue. Working fine now

**Comment by rupalichavan9860** [comment]
Verified on live
