### ISSUE TITLE
Unable to support the camp due to error "Nick name is required" even when nick name is provided.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1260]
Please refer attached screenshot : 
![image](https://github.com/user-attachments/assets/25550b2d-8aee-434f-af2b-63e937eb3e3a)

**Comment by DevAlchemyCD** [comment]
PR : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2143

**Comment by rupalichavan9860** [comment]
Working fine now

**Comment by hassaanCD** [comment]
Verified on live
