### ISSUE TITLE
Mobile-Change password- save text is out of the button 

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1262]
![ImportedPhoto 747552043 908315](https://github.com/user-attachments/assets/7d6d6617-ee6b-44bd-a8a5-a2619666d893)

**Comment by rupalichavan9860** [comment]
Not fixed 
![image](https://github.com/user-attachments/assets/0100c8d6-f49a-4e03-bd77-ab3e328cfc24)

**Comment by saniatg** [comment]
verified

**Comment by hassaanCD** [comment]
Verified on live
