### ISSUE TITLE
Supported camps- Show pagination only when there are more records

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1271]
![Screenshot 2024-09-09 at 3 20 30 PM](https://github.com/user-attachments/assets/b6d805d4-fad3-4598-aac4-dd49cad84074)

**Comment by rupalichavan9860** [comment]
This is already reported in https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/issues/1236

**Comment by saniatg** [comment]
verified

**Comment by rupalichavan9860** [comment]
Verified on live
