### ISSUE TITLE
PREFERENCES issues

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1273]
Issue 1 : Topic tags are not listing 
![image](https://github.com/user-attachments/assets/06e67260-8b52-40a9-a8e4-bf1d4adf8d64)

Issue 2 : Getting below error : 
![image](https://github.com/user-attachments/assets/b939ee8f-b75e-4498-8e74-d29a6d0ba96d)

**Comment by rupalichavan9860** [comment]
Again facing same issue 
![image](https://github.com/user-attachments/assets/217767d3-7634-4f30-93d2-1daa5afc2881)

**Comment by rupalichavan9860** [comment]
Not fixed

**Comment by saniatg** [comment]
working fine @rupalichavan9860 please confirm

**Comment by rupalichavan9860** [comment]
Working fine now

**Comment by rupalichavan9860** [comment]
This is still not working but we have different ticket for the same so closing this one
