### ISSUE TITLE
Add News 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1274]
Button color is missing 
![image](https://github.com/user-attachments/assets/9b5cc05e-6695-43c6-9437-d4bcc131a663)

**Comment by ks-rahul** [comment]
@rupalichavan9860 this is not done. we will working on it

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
