### ISSUE TITLE
Canon and Parent Camp symbols are same 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1276]
Please refer attached screenshot : 

![image](https://github.com/user-attachments/assets/9656b3e6-7926-43a2-905f-f8e659b1b34b)

![image](https://github.com/user-attachments/assets/cd72df44-144d-4c5f-a5fd-046507acc168)

**Comment by rupalichavan9860** [comment]
@ks-rahul I am still confused about canon symbol . Please check canon symbol on user supports page 

![image](https://github.com/user-attachments/assets/cb5ffa6f-eb49-43fe-ba24-81be89281602)


Create new topic : 
![image](https://github.com/user-attachments/assets/7a560b75-2c07-4a72-9bfa-e7e6ea4b061a)

**Comment by rupalichavan9860** [comment]
Working fine now

**Comment by rupalichavan9860** [comment]
Last commented issue is not working on beta server

**Comment by ks-rahul** [comment]
@akuks could you please sync the ui-ux-branch on beta.canonizer.com server

**Comment by rupalichavan9860** [comment]
Working fine now on live as well
