### ISSUE TITLE
Empty spaces in pop-over is click able and page is reloaded

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/Canonizer-Beta--Issue-Tracking#1278]
Steps:
Logged in and go to topic detail page of any topic
Click on "info" icon of topic or agreement
Pop over will open
Click on empty spaces in pop-over as shown in screenshot
Empty spaces are clickable and page is reloaded

![Image](https://github.com/user-attachments/assets/b464ff5d-57c5-4589-a373-4a6e2e13bcfc)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2203

**Comment by hassaanCD** [comment]
Verified

**Comment by hassaanCD** [comment]
Verified on live
