### ISSUE TITLE
Beta Email :  Footer links are redirecting to canonizer.com pages

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#128]
Below Footer links from emails 
1. Help
2. White Paper 
3. Jobs 
4. Privacy Policy 
5. Terms & services

**Comment by ashish76** [comment]
Hi @rupalichavan9860  As per Brent requirements, all beta emails links should be canonizer.com instead of beta.canonizer.com

**Comment by rupalichavan9860** [comment]
Yes. Closing this
