### ISSUE TITLE
Supported camps : Incorrect note when changing support order 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1285]
Please refer attached screenshot : 
![image](https://github.com/user-attachments/assets/f559432d-eb4f-4e6d-9ae7-b2dcb5aa2c67)

**Comment by saniatg** [comment]
@vikasranatalentelgia not fixed
![Screenshot 2024-10-07 at 10 57 31 AM](https://github.com/user-attachments/assets/86c040d5-30aa-4fcc-a524-f0be7f505a8f)

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
