### ISSUE TITLE
Support Camps : Support is getting removed from all camps 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1286]
Steps to reproduce : 
1. Go to account settings -supported camps
2. Move camps
3. Click on save changes 
4. Click on submit multiple times 

Getting below screen and Support is getting removed from all camps 
![image](https://github.com/user-attachments/assets/8ac8f556-47d5-4671-8c99-a16e33f30f30)

**Comment by rupalichavan9860** [comment]
Not fixed

**Comment by rupalichavan9860** [comment]
Working fine now

**Comment by saniatg** [comment]
verified on live
