### ISSUE TITLE
After clearing cache, try to add support, first it show "Remove support" button for a second and then show "Add Support"

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/Canonizer-Beta--Issue-Tracking#1290]
As shown in attached screenshots:

![Image](https://github.com/user-attachments/assets/ec247830-34ea-4aa9-8147-c5244d8a11a0)
![Image](https://github.com/user-attachments/assets/a30326ff-e363-41bd-b5cd-99cf73ce45a4)

**Comment by wahaj-hafeez** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2152

**Comment by DevAlchemyCD** [comment]
PR:  https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2152

**Comment by hassaanCD** [comment]
Verified

**Comment by hassaanCD** [comment]
Verified on live
