### ISSUE TITLE
Mange Topic/Manage Camp Button UI issue: No spacing and not centrally aligned

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/Canonizer-Beta--Issue-Tracking#1291]
As shown in attached screenshot:
![Image](https://github.com/user-attachments/assets/bfd9be58-8f92-47cc-9c0b-b8dc06e5d454)

**Comment by hassaanCD** [comment]
Verified

**Comment by saniatg** [comment]
verified on live
