### ISSUE TITLE
manage camp page is not showing in a specific case

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1292]
Steps:

1. Click on 'i'  icon and then try clicking the button

The page doesn't load

![Screenshot 2024-09-11 at 7 26 38 PM](https://github.com/user-attachments/assets/49092b23-b55d-44ef-ba0a-e25fe46bc325)

**Comment by ashish76** [comment]
@saniatg could you specify the steps to reproduce this?

**Comment by sajid315** [comment]
As discussed this issue with @saniatg , it is working fine now and no more reproducible. Closing the ticket.

**Comment by rupalichavan9860** [comment]
Verified on live
