### ISSUE TITLE
Issues with the topic detail page when the as of date filter is applied.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1293]
Issue 1 :  Bread crumbs are blank 
![image](https://github.com/user-attachments/assets/e70bceb7-0083-4cf8-8563-0866b91c4345)

Issue 2 : Add Statement button is missing 
![image](https://github.com/user-attachments/assets/fba70594-a1ca-4b3d-b9c9-98630ae66f17)

**Comment by rupalichavan9860** [comment]
Apply as of the earlier date than the topic's creation date.

**Comment by rupalichavan9860** [comment]
Verified

**Comment by akashgit77** [comment]
![Image](https://github.com/user-attachments/assets/824628da-778b-48f4-9af7-688ba117cc36)

@vikasranatalentelgia getting error when we select date before topic was created.

**Comment by rupalichavan9860** [comment]
Still not working in below case : 
1. Open any existing old topic
2. Go to topic history 
3. Click on "View Version"
4. Go to Supported camps 
5. Click on latest topic 
6. Observe 


![image](https://github.com/user-attachments/assets/043729ea-c5da-4b85-8eee-d1be5cf22cc4)

**Comment by rupalichavan9860** [comment]
Verified on UX server

**Comment by saniatg** [comment]
Working fine on live
