### ISSUE TITLE
The camp name limit is 80 characters, although only camp names of 30 characters are stored.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1296]

**Comment by sajid315** [comment]
@rupalichavan9860 this issue is coming due to column not updated in database. 
Once Ashutosh will be done with replication of database from prod to ux-dev , it will be fixed automatically.

**Comment by sajid315** [comment]
@akuks you need to run migrations on ux-dev database and must need to check the status of migration,

```
php artisan migrate:status
php artisan migrate
```

**Comment by sajid315** [comment]
@rupalichavan9860 this ticket is now working fine please have a look now. I am able to store 80 characters in DB.

**Comment by rupalichavan9860** [comment]
Working fine now

**Comment by rupalichavan9860** [comment]
Verified on live
