### ISSUE TITLE
Camp name links from below email should highlight specific camp 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#13]
Please refer attached screenshot : 

![image](https://user-images.githubusercontent.com/40416610/203486991-d180bf5e-d37f-46fd-9e61-d4f6b8a3e93a.png)

Expected Result : Camp name links should highlight specific camp 

Actual Result :  Links are highlighting Agreement camp

**Comment by subhancd** [comment]
working fine on both staging and beta. @rupalichavan9860
