### ISSUE TITLE
On the thread detail page, the incorrect thread creation date is displayed.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#130]
Please refer attached screenshot : 
![image](https://user-images.githubusercontent.com/40416610/209765341-aac753a4-62ed-4aed-b612-518d0c48361c.png)

**Comment by ks-rahul** [comment]
@rupalichavan9860 the old thread has the wrong date in DB. that's why the old thread showing the wrong date.

**Comment by rupalichavan9860** [comment]
We need more discussion on this, so we're putting it on hold.

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by rupalichavan9860** [comment]
@ashish76 Not working on live

**Comment by ashish76** [comment]
@rupalichavan9860 @akuks Please run the following command on production and also keep a backup of the thread table.
php artisan ThreadCreatedDate:update

I already mentioned the command  on the PR
https://github.com/the-canonizer/canonizer-3.0-api/pull/536

**Comment by rupalichavan9860** [comment]
Verified on live
