### ISSUE TITLE
There are serial numbers in "Delegated Supported Camps" page but not in "Direct Supported Camps" page

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/Canonizer-Beta--Issue-Tracking#1300]
As shown in attached screenshots:
"Direct supported Camps" without serial number
![Image](https://github.com/user-attachments/assets/92ce64b8-3e30-45d8-aa5c-e19e04ef6912)
"Delegated supported Camps" with serial number
![Image](https://github.com/user-attachments/assets/0c58e93c-04e1-48da-9dc8-66e7930e761e)

**Comment by rupalichavan9860** [comment]
Verified

**Comment by hassaanCD** [comment]
Verified on live
