### ISSUE TITLE
Delegated Support Camps page: When page is changing then serial number start again every time for a new page

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/Canonizer-Beta--Issue-Tracking#1301]
As shown in attached screenshot below, serial starts again for every new page.
![Image](https://github.com/user-attachments/assets/cfc16922-91b4-4e3f-9ba7-3dce2c7c7482)

**Comment by hassaanCD** [comment]
Not fixed

**Comment by saniatg** [comment]
verified

**Comment by hassaanCD** [comment]
Verified on live
