### ISSUE TITLE
Profile Setting side bar menu: "Delegated supported camps" option from "Supported Camp" drop down must be open and checked

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/Canonizer-Beta--Issue-Tracking#1302]
"Delegated supported camps" option from "Supported Camp" drop down must be open and checked if "Delegated supported Camp" page is showing.
![Image](https://github.com/user-attachments/assets/826ae29a-2a8b-4c98-87c1-45a3d4a0eea3)
![Image](https://github.com/user-attachments/assets/d12393f6-07b3-49d5-b80e-93d2ef24a73f)

**Comment by saniatg** [comment]
verified

**Comment by hassaanCD** [comment]
Verified on live
