### ISSUE TITLE
Issues when objecting any change

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1303]
1-The change is objected, shows going live time tomorrow. It shouldn't go live
2- When object , need to refresh the page to check the changes

![Screenshot 2024-09-12 at 4 07 49 PM](https://github.com/user-attachments/assets/673d81c7-9669-4b98-a773-834b6267b7da)

**Comment by sajid315** [comment]
As discussed with @saniatg  , only issue we identified in this ticket is text issue, and for that part we already have a ticket as mentioned below. 
Converting it to P0 , #1280 .

**Comment by saniatg** [comment]
verified

**Comment by saniatg** [comment]
Not working, I think code is not deployed

**Comment by saniatg** [comment]
Working fine on live
