### ISSUE TITLE
Statement: After objection from direct supporter, the objection card and button remain there

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/Canonizer-Beta--Issue-Tracking#1304]
Steps:
User A create topic so he is a direct supporter
User B (non supporter) submit and commit change in topic of user A
Change is now in pending waiting for object or accept by User A
User A rejects it by click on "Objection" button
After Objection the "Objection Card" remain there as it is which is an issue
![Image](https://github.com/user-attachments/assets/3de47453-f497-47d1-b120-45e78764597d)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2165

**Comment by hassaanCD** [comment]
Verified

**Comment by hassaanCD** [comment]
Verified on live
