### ISSUE TITLE
Popup missing randomly on ux-dev for similar camp names, also need to recheck the panel and popup for existing camps

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/Canonizer-Beta--Issue-Tracking#1307]
Steps:

1. User logged in and create a topic.
2. Under this topic "Try to create a camp with name that is already existed".
3. According to Figma if user type a camp name which is already existed then the right panel shows the similar camps as listing and then a pop up appears with 2 buttons as shown in attached screenshot below:

![Image](https://github.com/user-attachments/assets/3341ea9a-9979-405b-ac3c-3812be4f8f3a)

![Image](https://github.com/user-attachments/assets/738c24c2-b861-4c06-95b7-3601b01029a6)

Actual Result: When try to type an already existed camp then no panel and pop up is showing like below.

![Image](https://github.com/user-attachments/assets/9009cf1e-edfc-4dc6-9138-4716eaef79b4)

**Comment by ks-rahul** [comment]
@hassaanCD first two points are working on the server

![Image](https://github.com/user-attachments/assets/beb053f4-cab0-4e6b-8584-47fbc7ed01b0)
![Image](https://github.com/user-attachments/assets/9c5c1963-aa65-4fda-84de-8fd6803277a8)

**Comment by ks-rahul** [comment]
For the third point, we initially implemented a minimum of 3 characters required in the search field, but this has now been changed. Additionally, if no results are available from the search API, the right section will remain unchanged.

**Comment by hassaanCD** [comment]
Not Fixed. "Contribute popup" is not showing.

**Comment by ks-rahul** [comment]
@hassaanCD we need to connect.

**Comment by ks-rahul** [comment]
![Image](https://github.com/user-attachments/assets/1a6be635-6308-4556-95ed-e9170537794d)
@hassaanCD

**Comment by hassaanCD** [comment]
https://www.loom.com/share/7d608eed549b4a41a932b38cfec2dc3b?sid=af5a9952-4b56-4aad-823b-060523c2a619

@ks-rahul As you can see in the video that pop is not appearing for first camp "c1" but it is showing for second camp "c2" when I changed the parent from "c1" to "Agreement".

**Comment by hassaanCD** [comment]
Verified

**Comment by hassaanCD** [comment]
Verified on live
