### ISSUE TITLE
As of date (Custom Date) and View This version : Color must be blue on topic detail page 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1309]
Please refer attached screenshot : 
![image](https://github.com/user-attachments/assets/17051350-41ef-499a-bd72-ac43aa8503a1)

**Comment by hassaanCD** [comment]
Verified on UX-DEV

**Comment by hassaanCD** [comment]
Verified on live
