### ISSUE TITLE
Make a separate queue for all the email and push notification, where we are sending notifications to Supporters and Subscribers. This has to be exactly the same way we implemented for Thread and Posts.

### ISSUE THREAD

**Issue by ashish76** [the-canonizer/Canonizer-Beta--Issue-Tracking#131]
Optimize the code for sending email and push notifications to Supporters and Subscribers. 
This has been already done for the Thread and Post. We have to do in the same way for other places.

**Comment by gautamv16** [comment]
@ashish76 please revert this PR from development and create a seperate branch for it and push to repository. Please get merged with latest development base on your local first with this branch.

**Comment by rupalichavan9860** [comment]
Verified by Ashutosh

**Comment by rupalichavan9860** [comment]
Verified on live by @akuks
