### ISSUE TITLE
Supported Camps column name 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1312]
Column name must be only "Topics" instead of "Supported Topics" 
![image](https://github.com/user-attachments/assets/c7e40c0f-1f86-48a1-a70f-973f6d96c8cc)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2203

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
