### ISSUE TITLE
Delegate support is not removing on first click

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1313]
When click on delegate support button, the loader keeps loading. Need to reload the page

**Comment by sajid315** [comment]
@saniatg we rechecked this issue from both aspects backend and front-end, but its working at my side. And even on all browsers. 

Can you please recheck this thing? OR we can schedule a call with @rupalichavan9860 on this, if this issue is coming on her screen.

**Comment by saniatg** [comment]
working fine  now

**Comment by hassaanCD** [comment]
Verified on live
