### ISSUE TITLE
Nickname is editable on objection pages and getting error 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1315]
![image](https://github.com/user-attachments/assets/9b0e0704-5da1-4d2f-955d-f7381414ffa9)

![image](https://github.com/user-attachments/assets/1a7e44a3-9ea4-493b-acfc-b4f347a9fa2d)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2175

**Comment by rupalichavan9860** [comment]
Still getting error 
![image](https://github.com/user-attachments/assets/a6ac35f8-257a-4390-9489-de73c4286efa)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2197

**Comment by saniatg** [comment]
verified

**Comment by hassaanCD** [comment]
Verified on live
