### ISSUE TITLE
Eventline- When select different algo other than 'One person one vote' the event line does not work correctly

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1316]
![Screenshot 2024-09-13 at 10 09 33 AM](https://github.com/user-attachments/assets/8ace1b27-d14f-4c21-8d40-a03c02b5dae8)

**Comment by DevAlchemyCD** [comment]
@saniatg I have checked this issue from the front-end side and identified that it is coming from the API's response data. 

Following is the difference of "mind_experts" algorithm results on ux-dev and production respectively. 

@sunilspr7 can you please look into this ? 

![image](https://github.com/user-attachments/assets/45ed0961-16e7-4c79-a470-f20a17aeea59)

![image](https://github.com/user-attachments/assets/9d1b4e83-563a-48c2-9b9e-dfea6406910b)

**Comment by sunilspr7** [comment]
@saniatg Could you please share the steps for this? Also, is this working properly on the live server as well?

**Comment by saniatg** [comment]
Working fine now on UX and on live

**Comment by rupalichavan9860** [comment]
Verified on live
