### ISSUE TITLE
Refine- value is being saved without applying /saving 

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1318]
Steps:

1. selected Algorithm in topic detail page  as'Mind expert' 
2. Click on Apply button
3. Now open the refine drawer and choose' One person one vote'
4. Do not click apply and close the drawer

You will see in the value is retained

**Comment by hassaanCD** [comment]
Verified

**Comment by hassaanCD** [comment]
Verified on live
