### ISSUE TITLE
A list of topics that match the user's search term should be displayed, along with the necessary pagination.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1319]
Currently have to scroll a long page. 
![image](https://github.com/user-attachments/assets/cc5ad542-3bce-46f9-b5d6-f4b4f0c9eab1)

**Comment by rupalichavan9860** [comment]
Verified on UX server

**Comment by hassaanCD** [comment]
Verified on live
