### ISSUE TITLE
Previous topic tags are shown for the current topic. 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1321]
Steps to reproduce : 
1. Create topic with topic tags 
2. Open any other topic with different topic tags 
3. Observe topic tags in bred crumb 
![image](https://github.com/user-attachments/assets/fd69ebd5-4890-4b23-8a7f-c15102bb0277)

After reload : It is working fine . listing correct tags
![image](https://github.com/user-attachments/assets/3c897d41-2ad4-45af-b9e3-c5d6f05c0b6f)

**Comment by sajid315** [comment]
Following issues were identified in this ticket. 
1- Tags for each topic was showing same as opened in previous topics by users. 
2- Tags were not coming after topic creation in breadcrumb. 

So all of the issues are resolved and deployed on ux-dev server.

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
