### ISSUE TITLE
Join Canonizer To Support must be enabled in below case 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1322]
Pre-condition : User is logged out
Steps : 
1. Open any topic
2. Go to 3 dot menu options 
3. Observe 

Expected Result : Join Canonizer To Support must be enabled
![image](https://github.com/user-attachments/assets/4ad59e99-b360-4f1e-85f5-374666a15d21)

**Comment by DevAlchemyCD** [comment]
PR : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2184

**Comment by rupalichavan9860** [comment]
Verified

**Comment by hassaanCD** [comment]
Verified on live
