### ISSUE TITLE
Button name should be "Add Camp Support" instead of "Join Canonizer to Support"

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1323]
Once user logged in , it should show button name as "Add Camp Support" instead of "Join Canonizer to Support"

![image](https://github.com/user-attachments/assets/cb640735-2a5e-43c2-9dca-27e29f0cdee8)

**Comment by rupalichavan9860** [comment]
When user is not logged in Button name must be "Join Canonizer to Support"

![image](https://github.com/user-attachments/assets/93a49533-af10-4d77-9e82-e369470af43f)

**Comment by rupalichavan9860** [comment]
Verified

**Comment by hassaanCD** [comment]
Verified on live
