### ISSUE TITLE
Topic Detail page: It shows both "Manage Statement" and "Add Statement"

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/Canonizer-Beta--Issue-Tracking#1325]
Steps:
User A create topic so he is a direct supporter
User B (non supporter) submit and commit change in topic of user A
Change is now in pending waiting for object or accept by User A
When User A refresh the page it shows both "Manage Statement" and "Add Statement" as shown in attached screenshot:
![Image](https://github.com/user-attachments/assets/094352e6-cf9c-4613-acb0-3db09d1c8fdf)

**Comment by wahaj-hafeez** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2165

**Comment by DevAlchemyCD** [comment]
PR : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2184

**Comment by hassaanCD** [comment]
Verified

**Comment by hassaanCD** [comment]
Verified on live
