### ISSUE TITLE
Topic/Camp: After objection from direct supporter, the objection card and button remain there

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/Canonizer-Beta--Issue-Tracking#1326]
Steps:
User A create topic so he is a direct supporter
User B (non supporter) submit and commit change in topic of user A
Change is now in pending waiting for object or accept by User A
User A rejects it by click on "Objection" button
After Objection the "Objection Card" remain there as it is which is an issue
![Image](https://github.com/user-attachments/assets/a398425b-c0a7-4ec5-a74a-9a952407b678)

**Comment by DevAlchemyCD** [comment]
@hassaanCD ! this issue is fixed in ticket# 1304. PR is also attached in that ticket as well.

**Comment by hassaanCD** [comment]
Verified

**Comment by hassaanCD** [comment]
Verified on live
