### ISSUE TITLE
Advance filter- when apply include review , the count is showing but there are not records

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1327]
![Screenshot 2024-09-16 at 4 34 46 PM](https://github.com/user-attachments/assets/6ddb8265-9066-407e-9bb9-f33f10ad2166)

**Comment by rupalichavan9860** [comment]
Not fixed

**Comment by nalwa** [comment]
@saniatg  its not reproducible, please verify .

**Comment by saniatg** [comment]
I have logged separate issue where include review filter is not working correclty

**Comment by saniatg** [comment]
I have logged separate issue where include review filter is not working correclty
