### ISSUE TITLE
Create topic : Unable to create topic with name which is not live 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1330]
Steps to reproduce : 
1. Create topic with name "topic1"
2. Change topic name to "topic2" 
3. Make it live 
4. Now try to create topic with "topic1"

Expected result : It should create new topic 
Actual Result : It is showing error message "The topic name has already been taken." 

![image](https://github.com/user-attachments/assets/9ed6eb9c-a829-4dde-8ae0-4d9d763e7ae2)

![image](https://github.com/user-attachments/assets/848b717d-bc85-49ed-9761-a78879b5b302)

**Comment by hassaanCD** [comment]
Verified

**Comment by hassaanCD** [comment]
Verified on live
