### ISSUE TITLE
Update Topic : Should show error message when trying to update topic name with existing topic name 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1333]
Currently nothing is happening on Update topic button click and showing undefined result . Please refer attached screenshot :

![image](https://github.com/user-attachments/assets/eaa68b22-69c4-4fdd-882e-d4ab50698d0a)

**Comment by hassaanCD** [comment]
Verified

**Comment by hassaanCD** [comment]
Verified on live
