### ISSUE TITLE
Disable Objection button for non supporters

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1335]
Please refer attached screenshot : 
![image](https://github.com/user-attachments/assets/f1d9879a-90c9-485c-8db2-da89e6b79f06)

As of now showing error on submitting objection 
![image](https://github.com/user-attachments/assets/79499588-d5ce-4806-b29a-9020212f54db)

**Comment by rupalichavan9860** [comment]
Need to do this for topic, camp and camp statement

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2175

**Comment by rupalichavan9860** [comment]
Not fixed 
![image](https://github.com/user-attachments/assets/f27a5ce9-74ef-4d64-9b1d-fdc0a3d4052f)

![image](https://github.com/user-attachments/assets/019c2bee-bbac-413d-818f-4aba958f1ad3)

**Comment by DevAlchemyCD** [comment]
This ticket is working fine for me on UX-dev

![Image](https://github.com/user-attachments/assets/ff1c06e3-229d-442c-991b-36585f88f4b0)

![Image](https://github.com/user-attachments/assets/a827b631-eb99-4a3c-aa8a-287d7eab0c17)

**Comment by rupalichavan9860** [comment]
Yes working fine now

**Comment by hassaanCD** [comment]
Verified on live
