### ISSUE TITLE
Incorrect URL whenever creating camps

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1336]
Steps:

1. Create a topic
2. Create a camp under agreement
3. create another camp under agreement
4. Create third camp under agreement

Notice the url shows undefined and incorrect algo on topic detail page
![Screenshot 2024-09-16 at 10 45 54 PM](https://github.com/user-attachments/assets/e03f0e7a-156d-4c2a-9696-0b6bf5df9cab)

**Comment by saniatg** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
