### ISSUE TITLE
Incorrect warning shows for a sec and then disappears on click delegate button

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1337]
Steps:

1. Click on delegate your support to any user in any topic
2. Modal pop up will shows
3. Click on Delegate button

On top there is a warning which is incorrect and then disappears and then success message

![Screenshot 2024-09-16 at 11 04 24 PM](https://github.com/user-attachments/assets/47bdf2b5-8d63-4575-b878-978e9b246b8c)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2203

**Comment by saniatg** [comment]
@wahaj-hafeez not fixed

**Comment by DevAlchemyCD** [comment]
deployed on ux-dev server

**Comment by saniatg** [comment]
Verified on ux-dev server

**Comment by hassaanCD** [comment]
Verified on live
