### ISSUE TITLE
In the following scenarios, the user is unable to subscribe to the camp.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#134]
Steps : 
1. User A subscribed to two camps
2. Remove subscription from one camp from Accounts settings-subscriptions 
3. Return to the same camp and try to subscribe again 

Actual Result : 
 The user is unable to subscribe to the camp.

![image](https://user-images.githubusercontent.com/40416610/209802231-74636df0-addd-43ad-8116-50e472f2d7d4.png)

**Comment by sajid315** [comment]
@rupalichavan9860  I just verified this ticket steps, there was another same issue #215 from back-end side. So with that fixing of 215 this issue is also resolved.
And the PR for that fixing is below one. 
https://github.com/the-canonizer/canonizer-3.0-api/pull/599

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
