### ISSUE TITLE
Topic count is showing incorrect on topic search page

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1341]
scenario
Add 'top' on create topic page and then click on see more results

Notice the count on left and topic results

![Screenshot 2024-09-17 at 3 54 44 PM](https://github.com/user-attachments/assets/29f732b5-f957-453b-b07a-58742928febc)

**Comment by saniatg** [comment]
@vikasranatalentelgia not working
![Screenshot 2024-09-17 at 10 14 19 PM](https://github.com/user-attachments/assets/6d3024c3-004a-45a7-9563-bf61e014a4b8)

**Comment by saniatg** [comment]
verified

**Comment by rupalichavan9860** [comment]
Verified on live
