### ISSUE TITLE
The breadcrumb is displaying the camp name twice rather than "Agreement".

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1342]
Please refer attached screenshot : 
![image](https://github.com/user-attachments/assets/ba3ca0a5-1721-4b46-963e-263e6711d5ba)

**Comment by rupalichavan9860** [comment]
![image](https://github.com/user-attachments/assets/8d13d3dd-5835-4965-9c3b-03e2096052c3)

**Comment by rupalichavan9860** [comment]
Working fine now

**Comment by hassaanCD** [comment]
Verified on live
