### ISSUE TITLE
User profile -supported camps  are not showing and canon is showing empty

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1343]
Scenarios- Compare any two topics and on compare page , click on nickname link

supported camps  are not listing and canon is showing empty
![Screenshot 2024-09-17 at 9 56 22 PM](https://github.com/user-attachments/assets/9b7cb6ae-ceb6-4389-8add-0abe18056327)

**Comment by rupalichavan9860** [comment]
Working fine now

**Comment by saniatg** [comment]
Verified on live
