### ISSUE TITLE
Topic with the tag name is not correctly showing when click from preferred topic on home page

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1345]
Case:
On home page under preferred topics , click on a tag
e.g. I clicked on terminology , it redirected to the topic which shows history tag which is incorrect

**Comment by array-junkie** [comment]
@saniatg It is a data-related issue. It is working fine for new topics, only old topics are effected. It looks like this issue occurs when we change tags on the admin side.

@akuks Kindly refresh the UX Dev MongoDB.

**Comment by saniatg** [comment]
@M-Darab not fixed, now when I click on any specific category , it redirects to the page which 'All' data with all the categories

**Comment by sajid315** [comment]
@saniatg looking into this issue.

**Comment by saniatg** [comment]
working fine for now

**Comment by saniatg** [comment]
verified on live
