### ISSUE TITLE
Search data is not showing in  a specific case

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1346]
copy URL
https://ux-dev.canonizer.com/search?q=canonizer

In different browser paste this URL , the search should count but the data is not displayed
![Screenshot 2024-09-17 at 10 56 12 PM](https://github.com/user-attachments/assets/cad427a1-7b95-436f-ae5a-3ca277fbae2e)

**Comment by saniatg** [comment]
The searched results are showing but the results are of previously searched keyword
I searched for keyword' topic' but as you can see in the screenshot it shows 'canonizer' keyword results which I searched previously
![Screenshot 2024-09-24 at 4 56 35 PM](https://github.com/user-attachments/assets/96e5fb97-eacc-42c1-9313-6b09eaae7800)

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
Verified on live
