### ISSUE TITLE
Home page- your preferred topic view more link is not working

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1350]
![Screenshot 2024-09-18 at 12 21 15 PM](https://github.com/user-attachments/assets/3f379c37-84ef-4e7a-850b-1250d75f744e)

**Comment by saniatg** [comment]
@ks-rahul When click on See more link , I cannot see more topics as there are many
![Screenshot 2024-09-30 at 9 00 39 PM](https://github.com/user-attachments/assets/aa9bf4fe-1c49-43d4-ad99-4607d0ec919b)

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
Preferred topics are removed now
