### ISSUE TITLE
Incorrect tags are showing on topic manage pop up and the topic on home page under 'preferred topics'

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1351]
Refer screenshots
![Screenshot 2024-09-18 at 1 30 56 PM](https://github.com/user-attachments/assets/f54a45ef-647f-4ba1-983a-c813f4154fed)
![Screenshot 2024-09-18 at 1 30 17 PM](https://github.com/user-attachments/assets/e9d7248d-c1f4-484b-9330-825d0cceaa97)

**Comment by sajid315** [comment]
@saniatg I just verified the issue, this fixing was already done while we updated the breadcrumb part. Now it's showing correct data.

![Image](https://github.com/user-attachments/assets/287fd8d9-568c-4689-a0de-82dea25785d1)

**Comment by rupalichavan9860** [comment]
Verified on UX server

**Comment by saniatg** [comment]
working fine on live
