### ISSUE TITLE
Topic/Camp/Statement History Pages : When you scroll up and down, only one of the many records is visible. 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1354]
Please refer attached screenshot : 
![image](https://github.com/user-attachments/assets/f6a7ab15-745a-4c68-bbff-ac12348a8d2a)

on reload , it is working fine 
![image](https://github.com/user-attachments/assets/c2d7be41-c132-464d-8f81-2392f36b696a)

**Comment by DevAlchemyCD** [comment]
PR : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2184

**Comment by rupalichavan9860** [comment]
This is working fine now but as user scroll down sometimes it is taking time to load and getting below screen 
![image](https://github.com/user-attachments/assets/da407c62-8463-48fc-91da-ed879c3229b3)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2197

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
