### ISSUE TITLE
Create New Topic : Note "(General is recommended, unless you know otherwise)" is missing 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1355]
![image](https://github.com/user-attachments/assets/b2ccd372-1e15-4c42-83b7-a97f7b6ec3d4)

![image](https://github.com/user-attachments/assets/8e47ac05-e29c-4ede-bff8-a2c0a9b65f5f)

**Comment by DevAlchemyCD** [comment]
PR : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2184

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
