### ISSUE TITLE
History page camp about nickname and URL  is not updating on manage camp modal pop up

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1359]
1. Go to agreement camp history page
2. Add camp about nickname and  camp about URL
3. Commit the changes 

On manage camp modal pop up on hover ' i' icon the values  of camp about nickname and  camp about URL are not seen
![Screenshot 2024-09-19 at 11 56 51 AM](https://github.com/user-attachments/assets/91a62390-d927-48a7-afd4-5793e17b04c3)

**Comment by sajid315** [comment]
@saniatg this issue has been fixed now with the latest fixing of "camp record" issue in the breadcrumb. Have a look please.

**Comment by rupalichavan9860** [comment]
Working fine on UX server

**Comment by rupalichavan9860** [comment]
Verified on live
