### ISSUE TITLE
Search page -camp statement, when  click on the arrow it does  not work

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1360]
![Screenshot 2024-09-19 at 7 57 51 PM](https://github.com/user-attachments/assets/ea797c08-cc63-4912-aede-12e67ad6bf8c)

**Comment by saniatg** [comment]
Now I can see semi colon @vikasranatalentelgia 
![Screenshot 2024-09-24 at 4 41 17 PM](https://github.com/user-attachments/assets/adc8b400-2b6a-4334-b4ce-b46acbfb7c5c)

**Comment by saniatg** [comment]
verified

**Comment by hassaanCD** [comment]
Verified on live
