### ISSUE TITLE
DELEGATED SUPPORTED CAMPS : Issues on Remove Support pop up 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1361]
Please refer attached screenshot : 
![image](https://github.com/user-attachments/assets/66358f94-6248-4346-82c8-3db13570d35b)

Issue 1 : Nickname must be in blue color
Issue 2 : Font does not look well. 

Please refer current system screenshot : 
![image](https://github.com/user-attachments/assets/b596694b-361c-4c3d-8241-34c99da245e1)

**Comment by rupalichavan9860** [comment]
Verified

**Comment by hassaanCD** [comment]
Verified on live
