### ISSUE TITLE
Missing functionality : If there is an update to the topic, camp, or statement, a flag should appear on the detail page. 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1363]
Please refer below screenshot for more details : 

![image](https://github.com/user-attachments/assets/0ca4f2f3-55d4-4fb8-a428-c8f30e84aef4)

We also need : 
1. Mouse over message explaining what they are.
2. When clicked, it should  redirect to the corresponding history page.

**Comment by sajid315** [comment]
@wahaj-hafeez make sure the redirection also working on click of icon.

**Comment by DevAlchemyCD** [comment]
PR : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2274

**Comment by rupalichavan9860** [comment]
@wahaj-hafeez Working fine for topic and camp, but it is still missing for camp statement 

![image](https://github.com/user-attachments/assets/4c487a02-897a-4f2c-9f70-5f88f1ef0024)

**Comment by rupalichavan9860** [comment]
Verified on UX server

**Comment by rupalichavan9860** [comment]
Verified on live
