### ISSUE TITLE
Support related information is missing on new server

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1364]
Please refer below screenshot : 
![image](https://github.com/user-attachments/assets/bd42112b-cfe8-4e9e-a056-ef04a500cdb4)

**Comment by sajid315** [comment]
@wahaj-hafeez 
I had a discussion with Twinkle about this message placement in new UI/UX support tree. 

So we can place the info related to support tree with the Title of this section, same as we have for "Camp Statement".

![Image](https://github.com/user-attachments/assets/316bfa64-1643-4886-b3f3-e272b7b1dfdf)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2298

**Comment by rupalichavan9860** [comment]
Verified on UX and live
