### ISSUE TITLE
Camp History Comparison : Parent Camp filed is missing 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1365]
Parent Camp filed is missing on Camp History Comparison

**Comment by wahaj-hafeez** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2212

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2212

**Comment by saniatg** [comment]
verified

**Comment by rupalichavan9860** [comment]
Verified on live
