### ISSUE TITLE
Topic History Comparison : Live topic name is displaying in old record 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1366]
Please refer attached screenshot : 
![image](https://github.com/user-attachments/assets/5c0e0fd7-83a2-4e6e-bbdc-0f56ffcb12f2)

![image](https://github.com/user-attachments/assets/3f6afd7e-e006-4d37-9504-64c11ec8c2dd)

**Comment by DevAlchemyCD** [comment]
deployed on ux-dev server

**Comment by rupalichavan9860** [comment]
Verified on UX server

**Comment by rupalichavan9860** [comment]
Verified on live
