### ISSUE TITLE
Remove icon is not showing on supported page

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1370]
Steps:

1. I had a topic which had 3 camps and all supported by the user
2. I  created a subcamp 3 under camp 3
3. Then changed the parent to agreement
4. checked on supported page

Remove icon was not showing
![Screenshot 2024-09-20 at 4 33 21 PM](https://github.com/user-attachments/assets/ce30108d-4e69-4274-9686-a028d612df5c)

**Comment by DevAlchemyCD** [comment]
@saniatg ! We have updated the library for drag and drop on the above-mentioned page. Now! it's working fine.

**Comment by rupalichavan9860** [comment]
Working fine on UX server

**Comment by saniatg** [comment]
working fine on Live
