### ISSUE TITLE
DELEGATED SUPPORTED CAMPS : Layout issue when the topic and camp name are 80 characters long.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1372]
Please refer attached screenshot : 
![image](https://github.com/user-attachments/assets/9ef5a8bf-1ac3-4ef6-8dca-2be6edd2f08c)

**Comment by rupalichavan9860** [comment]
It is showing only "...." 
![image](https://github.com/user-attachments/assets/bef9cac0-8bfd-4f30-a4ab-d29492b06e22)

**Comment by ks-rahul** [comment]
![Image](https://github.com/user-attachments/assets/00622739-1e05-42c3-a5e8-c6b187ea9d4d)
@rupalichavan9860 could you explain more about this

**Comment by saniatg** [comment]
verified

**Comment by hassaanCD** [comment]
Verified on live
