### ISSUE TITLE
Why can't I object? pop up : Link to help page should be in blue color

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1373]
![image](https://github.com/user-attachments/assets/479f83a5-183e-48a3-8956-35e4bb1d6144)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2203

**Comment by rupalichavan9860** [comment]
Verified

**Comment by hassaanCD** [comment]
Verified on live
