### ISSUE TITLE
Home Page :  WHAT’S NEW AT CANONIZER? and Recent activities are not displaying in below case 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1378]
Steps to reproduce : 
1. Clear cache
2. Go to https://ux-dev.canonizer.com/ or log in to https://ux-dev.canonizer.com/ 

  WHAT’S NEW AT CANONIZER? and Recent activities are not displaying 

![image](https://github.com/user-attachments/assets/beba4819-28c9-4949-bcfe-29e287b69e08)

**Comment by saniatg** [comment]
verified

**Comment by rupalichavan9860** [comment]
Verified on live
