### ISSUE TITLE
Topic name is not getting updated on  the breadcrumbs 

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1379]
Steps:

1. Update a topic with any name
2. commit changes

Notice the topic name on the breadcrumb, it is not updated even on refresh
.
![Screenshot 2024-09-23 at 7 14 45 PM](https://github.com/user-attachments/assets/7c866035-06eb-42fe-a49e-b133e7f3642f)

**Comment by DevAlchemyCD** [comment]
deployed on ux-dev server.

**Comment by saniatg** [comment]
Verified on UX

**Comment by hassaanCD** [comment]
Verified on live

**Comment by hassaanCD** [comment]
Verified on live
