### ISSUE TITLE
Compare statement is not working, page keeps loading for a specific case

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#138]
Case:

If you compare 2 statements, one which is in review and other in object state. 
For in review and object state, on click Compare statement button, the page just keeps loading.

![Screenshot 2022-12-30 at 10 16 35 AM](https://user-images.githubusercontent.com/91254708/210036316-68c9ecee-b74d-4b48-995f-c2638a201934.png)
![Screenshot 2022-12-30 at 10 26 46 AM](https://user-images.githubusercontent.com/91254708/210036325-5b3015b0-8b7e-47c5-a0c4-69135e11e729.png)

**Comment by saniatg** [comment]
Working fine now .

**Comment by ks-rahul** [comment]
now working fine on production

**Comment by saniatg** [comment]
@rupalichavan9860 Tested and  fine on production.
