### ISSUE TITLE
Page crash on News Feed 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1382]
Steps to reproduce : 
1. Select topic
2. Go to Refine 
3. Select "Mind Experts" and Apply
4. Click on News Feed 

Getting below page crash 

![image](https://github.com/user-attachments/assets/55a9244a-c869-489c-ae72-ee38dd5aed5d)

**Comment by saniatg** [comment]
verified

**Comment by saniatg** [comment]
verified on live
