### ISSUE TITLE
Camp names are listing twice for below user 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1383]
https://ux-dev.canonizer.com/user/supports/55?canon=1
Please refer attached screenshot : 

![image](https://github.com/user-attachments/assets/a05b789a-31f8-4612-b1f3-455f2b3d28a4)

**Comment by ks-rahul** [comment]
@rupalichavan9860 , as discussed with @nalwa , this issue has already been fixed in production. Once the code is deployed on the production, the problem will be resolved, and we will verify it again.

**Comment by rupalichavan9860** [comment]
Working fine on live
