### ISSUE TITLE
Topic Change going in history instead of live, in below mentioned case

### ISSUE THREAD

**Issue by nalwa** [the-canonizer/Canonizer-Beta--Issue-Tracking#1384]
Steps:

1. create a topic
2. submit change on topic and commit the change
3. after change go live automatically.

Result:   Change go in history and previous live remain live.

Expected:  New submitted change should go live and previous should go in history

**Comment by array-junkie** [comment]
It is not reproducible on UX dev. @hassaanCD @saniatg @rupalichavan9860 kindly verify this ticket.

**Comment by hassaanCD** [comment]
I have tested the issue with above mentioned steps and it is working fine.

**Comment by hassaanCD** [comment]
Verified

**Comment by hassaanCD** [comment]
Verified on live
