### ISSUE TITLE
Camp Activities : Nickname added their support on Camp Agreement is missing 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1386]
When the user creates a new topic, it immediately adds support to the Agreement camp and assigns a camp leader. 

It shows "Nickname assigned as camp leader Agreement" activity, but there is no support added activity. 

![image](https://github.com/user-attachments/assets/d90eb61a-9eec-4ff7-b459-e56fcc0229f8)

**Comment by array-junkie** [comment]
@rupalichavan9860 This functionality is the same as Production. Do we have to update the current functionality?

**Comment by rupalichavan9860** [comment]
Also direct/delegate support added and removed activities are showing like "Nickname removed support Support removed"  (Support removed)with link to same page  which is not required 
![image](https://github.com/user-attachments/assets/b6c9087b-2a18-4ec9-ad06-149fe4671e0a)

**Comment by sajid315** [comment]
https://github.com/the-canonizer/canonizer-3.0-api/pull/1171

**Comment by rupalichavan9860** [comment]
Verified on UX and live
