### ISSUE TITLE
When changing algorithms, the scores do not change. 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1387]
Please refer attached screenshot : 

![image](https://github.com/user-attachments/assets/e66b9df6-e006-442a-a6f8-13c1cd2058b7)

![image](https://github.com/user-attachments/assets/77ae38da-53d8-470d-b3b8-7193cc6ecaac)

**Comment by sajid315** [comment]
@rupalichavan9860 I have checked this issue on ux-dev server , so following is the conclusion on it, 

1- Some of the Service API's + Backend API's are taking time to respond on ux-dev , this is the first problem.
2- And some of the issues are at front-end level while changing of the algorithm and applying the filters, I discussed these with @vikasranatalentelgia and he's looking into these.

**Comment by saniatg** [comment]
@vikasranatalentelgia not fixed

**Comment by rupalichavan9860** [comment]
It's working fine. The scores are changing right now. Will verify for correct score calculation and log any issues that occur.

**Comment by saniatg** [comment]
verified on live
