### ISSUE TITLE
Not able to register with a new account

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1393]
Steps:

1.  Click on register link
2. Add details 
3. Enter OTP
4. Now on preferred  categories page  , choose tags click on button' Get started'

The button is disabled and is not redirected 
The user must be logged in and register, but he is not
![Screenshot 2024-09-27 at 5 08 14 PM](https://github.com/user-attachments/assets/a3f8207d-8be0-4818-93c6-3a193e6c4014)

**Comment by sajid315** [comment]
@saniatg i tried the same steps and registerd on ux-dev with new account , categories selection is working for me. And after registration I am logged in succesfully.

![Image](https://github.com/user-attachments/assets/0b217231-c41b-4b7f-9253-eededd75aed8)

**Comment by rupalichavan9860** [comment]
Verified on live

**Comment by saniatg** [comment]
Working fine on live
