### ISSUE TITLE
Notifications : Getting error "Something went wrong" on View All click 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1396]
Please refer attached screenshot : 
![image](https://github.com/user-attachments/assets/83cd7bde-8e1b-4b60-b4bd-e3671691a270)

**Comment by saniatg** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Not working 
![image](https://github.com/user-attachments/assets/7505a925-fc8d-4169-b3d8-053260685323)

**Comment by rupalichavan9860** [comment]
Working fine now

**Comment by hassaanCD** [comment]
Verified on live
