### ISSUE TITLE
Layout issue on Register page 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1397]
Please refer attached screenshot : 

![image](https://github.com/user-attachments/assets/33a38026-5741-4357-9458-06aacdd7a2c1)

**Comment by rupalichavan9860** [comment]
Please check this in Firefox browser

**Comment by rupalichavan9860** [comment]
Not fixed 

![image](https://github.com/user-attachments/assets/0ce59ceb-63ab-4897-a920-813820dd4dfc)

**Comment by rupalichavan9860** [comment]
Verified on UX server

**Comment by saniatg** [comment]
Working fine  on live
