### ISSUE TITLE
News Feed : Incorrect URL path 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1401]
Please refer attached screenshot : 
![image](https://github.com/user-attachments/assets/fb6b5003-0856-44e5-ad71-9ce1b5f68d2b)

Open in new window : 

![image](https://github.com/user-attachments/assets/8f940e23-dd02-4fe2-951a-11bdfa47a8b3)

**Comment by ks-rahul** [comment]
working fine on the server

**Comment by rupalichavan9860** [comment]
@ks-rahul Click on nick name 
![image](https://github.com/user-attachments/assets/95d321a9-d19a-4f6a-b441-6c543fc3767f)

**Comment by ks-rahul** [comment]
@rupalichavan9860 Previously, the nickname field was not clickable, so I am changing it to display it as regular text.


![Image](https://github.com/user-attachments/assets/6f1de1ba-1fa3-4531-93e0-acb7c64d1aa9)

**Comment by rupalichavan9860** [comment]
Verified on UX server

**Comment by rupalichavan9860** [comment]
Verified on live
