### ISSUE TITLE
Getting crash on a specific topic, when enter keyword as 'script' in search

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1402]
Steps:

1. Enter 'script' in search 
2.  click on the 1st topic searched result
3. Click enter

camp not found error
![Screenshot 2024-10-01 at 11 03 31 AM](https://github.com/user-attachments/assets/dbfa4b8b-3565-46cf-8bfb-cb3e21ec5456)

**Comment by nalwa** [comment]
@saniatg  this is coming for one old record only. i have tested with many new topics with same cases not producible anymore.

**Comment by saniatg** [comment]
not coming on coming on live
