### ISSUE TITLE
Preferences- The user tags are getting deleted on discard without saving the changes

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1404]
Steps

1. Go to preferences
2. Choose 3-4 tags and save
3. Now click on discard button
4. All saved tags are unchecked
5. And navigate to nickname section
6. Come back to preferences

The tags are deleted even if I did not enter save button
![Screenshot 2024-10-01 at 11 18 22 AM](https://github.com/user-attachments/assets/46b9fc09-ea95-4cfd-97af-51de34da8748)

**Comment by saniatg** [comment]
verified

**Comment by hassaanCD** [comment]
Verified on live
