### ISSUE TITLE
Camps are not clickable in the breadcrumb 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1407]
![image](https://github.com/user-attachments/assets/9c8ad7cc-2d16-4dfa-9bb4-f6f68333b41f)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2212

**Comment by saniatg** [comment]
@wahaj-hafeez Not fixed

**Comment by saniatg** [comment]
@wahaj-hafeez it is clickable , but taking time to load

**Comment by DevAlchemyCD** [comment]
deployed on ux-dev server

**Comment by rupalichavan9860** [comment]
@wahaj-hafeez It is still taking time to load, and the user is unable to determine whether they have clicked or not. Need to display the loader or something.

**Comment by ks-rahul** [comment]
@rupalichavan9860 could you please once now.

**Comment by rupalichavan9860** [comment]
Verified on UX server

**Comment by rupalichavan9860** [comment]
Verified on Live
