### ISSUE TITLE
Few "Your preferred topics" are blank on home page and 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1408]
Please refer attached screenshot : 
![image](https://github.com/user-attachments/assets/73205534-0c29-4c54-8edb-e960d3ba7a2c)

Click on See more : 

![image](https://github.com/user-attachments/assets/5499d03a-130c-4664-93e0-907d83764a43)

**Comment by sajid315** [comment]
@rupalichavan9860 this issue was account specific and has been resolved now, please check. 

![Image](https://github.com/user-attachments/assets/aa147202-6d71-476e-be77-61cd01ec6ed9)

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Working fine on live
