### ISSUE TITLE
Camp Statement History page is not showing in below case 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1409]
Steps to reproduce : 
1. Create topic with User A
2. Login with another user(User B) and add camp statement - it will be in "in review"
3. Again login with User A and check name in 3 dots menu options 

![image](https://github.com/user-attachments/assets/9546eb0e-b911-4097-9713-236189a0e73f)
4. Now click on "Manage Statement"
5. Observe

It is redirecting to "Adding Camp Statement" instead of Camp statement history page
![image](https://github.com/user-attachments/assets/7df67464-e265-4573-94a8-174b6db056a9)

**Comment by DevAlchemyCD** [comment]
PR : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2212

**Comment by rupalichavan9860** [comment]
Verified

**Comment by hassaanCD** [comment]
Verified on live
