### ISSUE TITLE
In the scenario below, the "Upload File" link redirects to the "Help" page.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#141]
Steps to reproduce : 
1. Go to https://canonizer.com/
2. Login with valid email and password 
3. Go to Account settings-Supported camps
4. Click on any Camp name
5. Click on "Upload File" link

Actual Result : 
The "Upload File" link redirects to the "help" page.
![image](https://user-images.githubusercontent.com/40416610/210304644-b145e006-1c95-407b-b3ba-efd8468f036c.png)

Expected Result : 
The "Upload File" link should take you to the "Upload File" page.

**Comment by sunnyjindal** [comment]
@rupalichavan9860 I think we are disabling the option of uploading files. You will need to check with Brent once.

**Comment by nalwa** [comment]
i have checked this scenario. @sunnyjindal  its an issue because its appearing when i am logging with valid admin credentials. 

Link needs to be fixed from front-end.

**Comment by rupalichavan9860** [comment]
Not working

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by saniatg** [comment]
@rupalichavan9860 working fine on production.

**Comment by rupalichavan9860** [comment]
Verified on live
