### ISSUE TITLE
Browse page - under sandbox canon , showing no data

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1411]
Steps:

1. Go to browse
2. Choose " sandbox "
3. Click on any topic

No data
![Screenshot 2024-10-03 at 4 22 31 PM](https://github.com/user-attachments/assets/08108fa5-e8e8-417b-8d9f-c30f6cb7c4df)

**Comment by sajid315** [comment]
@saniatg this issue is related to data only at ux server. And regarding this I informed to @akuks. 

We are just refreshing the data on it.

**Comment by sajid315** [comment]
@saniatg now this issue has been resolved , please recheck and let me know if any other case not works.

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
