### ISSUE TITLE
Remove support-  incorrect  error message 

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1412]
Steps:

1. Create topic
2. Click on remove support button
3. Click on remove

You will error message " reason is required" but reason is not mandatory

![Screenshot 2024-10-03 at 4 32 45 PM](https://github.com/user-attachments/assets/601c23c2-4555-411a-a900-4bccdb2afe63)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2246

**Comment by saniatg** [comment]
verified

**Comment by hassaanCD** [comment]
Not fixed on live

**Comment by hassaanCD** [comment]
Not fixed on live

**Comment by hassaanCD** [comment]
Verified on live
