### ISSUE TITLE
Browse page issue 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1415]
Steps to reproduce : 
1. Go to https://ux-dev.canonizer.com/
2. Go to Browse
3. Select canon "All" 
4. Click on last page 
5. Check "Show Only My Topics" 
6. Observe 

Please refer attached screenshot : 
![image](https://github.com/user-attachments/assets/cb1959bc-094d-499e-969a-9bab5d4269da)

**Comment by DevAlchemyCD** [comment]
deployed on ux-dev server

**Comment by rupalichavan9860** [comment]
Working fine on UX server

**Comment by rupalichavan9860** [comment]
Verified on live
