### ISSUE TITLE
Home page - Divs are not clickable 

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1417]
Scenarios- The divs under hot topics/ preferred topics when try clicking on them sometimes the click works mostly it does not.
It should be smooth and the whole div must be clickable
![Screenshot 2024-10-07 at 3 47 37 PM](https://github.com/user-attachments/assets/5860d412-a75a-4aad-b9ee-a792d4de7039)

**Comment by rupalichavan9860** [comment]
Verified on UX server

**Comment by saniatg** [comment]
Working on production
