### ISSUE TITLE
When unarchived camp, the button to commit change is not showing

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1418]
Steps:

1. Archive a camp
2. and then click on Unarchive camp button from history page

Commit button is not showing
![Screenshot 2024-10-07 at 3 52 27 PM](https://github.com/user-attachments/assets/851ba992-9780-451d-b603-0f8acf946840)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2305

**Comment by saniatg** [comment]
working fine on dev-ux

**Comment by saniatg** [comment]
working fine on live
