### ISSUE TITLE
Previous threads are shown for the current topic and getting page crash on threads 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1419]
Please refer below steps and screenshot : 
1. Open any topic who is having threads . I am using topic "Theories of Mind and Conscious"
![image](https://github.com/user-attachments/assets/bcb42071-7e60-4d5d-a049-6ff8a106b009)

2. Open another topic 
I have opened topic "Help "

![image](https://github.com/user-attachments/assets/0e2dc3a9-32d9-49c3-8c92-baa445627e08)

3. Now click on any thread and observe 

Getting below page crash 
![image](https://github.com/user-attachments/assets/30c17ea2-5b4a-4e4c-ad34-19bff44adffd)

**Comment by ks-rahul** [comment]
@rupalichavan9860 i have checked this on the server and it is working fine. is there any specific scenario

**Comment by rupalichavan9860** [comment]
@ks-rahul Let's connect for this

**Comment by rupalichavan9860** [comment]
Not fixed

**Comment by rupalichavan9860** [comment]
Working fine now

**Comment by rupalichavan9860** [comment]
Verified on live
