### ISSUE TITLE
"Under Review" Tag is missing on detail page in UX-Dev

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/Canonizer-Beta--Issue-Tracking#1420]
As shown in attached screenshot of Figma design:
![Image](https://github.com/user-attachments/assets/d0de9936-308d-434c-84e8-29631d28f41f)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2314

**Comment by hassaanCD** [comment]
Verified on UX-DEV

**Comment by hassaanCD** [comment]
Verified on live
