### ISSUE TITLE
Getting page crash on as of date filter

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1421]
Steps to reproduce : 
1. Go to any old topic 
2. Go to any history page and click on view this version (Old record)
3. Go to Supported camps 
4. Click on any recent topic /camp 
5. Observe topic detail page 

![image](https://github.com/user-attachments/assets/fa94b7a1-4eb8-40af-b96c-9771e5936a84)

Click on "Create Camp"-- Getting below page crash 

![image](https://github.com/user-attachments/assets/3124999d-4792-4411-af28-caa785db79f0)

**Comment by rupalichavan9860** [comment]
Not fixed

**Comment by saniatg** [comment]
working fine @rupalichavan9860 please check

**Comment by rupalichavan9860** [comment]
Verified on live
