### ISSUE TITLE
Topic with canon "no-namespace"

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1423]
Please refer attached screenshot : 

![image](https://github.com/user-attachments/assets/de479eb4-49f3-4aaf-bf02-f5b0b284322a)

**Comment by vikasranatalentelgia** [comment]
@rupalichavan9860 can you please explain what should be there instead of "no-namespace" for this topic?

**Comment by rupalichavan9860** [comment]
@vikasranatalentelgia I am also not sure about this . You can discuss this in meeting if required

**Comment by saniatg** [comment]
https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/issues/1545
created ticket
