### ISSUE TITLE
Creating a New Camp /Edit camp : Parent Camp field is editable and getting error 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1424]
Please refer attached screenshot : 

![image](https://github.com/user-attachments/assets/d44f1436-28a6-473f-9647-a22880d9cac3)

**Comment by rupalichavan9860** [comment]
Working fine now

**Comment by hassaanCD** [comment]
Verified on live
