### ISSUE TITLE
Admin (Shares) : 404 Not Found error on Nickname link click 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1426]
Please refer attached screenshot : 
![image](https://github.com/user-attachments/assets/daa7d9ef-31dd-4d18-829d-30196174b69f)

**Comment by sajid315** [comment]
@akuks I just checked the issue about nickname URL not found. Seems like the ENV variable in the admin panel is wrong named as 

**"APP_URL_FRONT_END"**

It should point our production site = https://canonizer.com

@akuks can you please check it for the production site please ?

**Comment by sajid315** [comment]
After discussion with @akuks , I have raised the fixing of URL issue for ux-dev server.

https://github.com/the-canonizer/canonizer3-admin/pull/88

**Comment by rupalichavan9860** [comment]
@sajid315  Not Fixed 
![image](https://github.com/user-attachments/assets/7aaf1b77-5a21-40e9-88d2-102d03940768)

**Comment by sajid315** [comment]
@rupalichavan9860 you can see in the following screenshot, the link is redirecting to ux-dev canonizer profile. 

![Image](https://github.com/user-attachments/assets/d04cfa01-1367-46f4-ae77-f9ff9c60ba4c)

**Comment by rupalichavan9860** [comment]
@sajid315 Yes working now

**Comment by rupalichavan9860** [comment]
Verified on live
