### ISSUE TITLE
In the scenario below, the admin user does not have access to the file upload page.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#143]
Steps for replication:
1. Navigate to https://canonizer.com/.
2. Click on Login.
3. Enter a valid email address for someone with administrative access.
4. Click on "Request One-Time Verification Code."
5. Enter a valid One-Time Verification Code and log in.

Actual Result : There is no file upload link.

**Comment by sunnyjindal** [comment]
@rupalichavan9860 again the same thing. No upload file option should be given to the user.

**Comment by rupalichavan9860** [comment]
Verified on both staging and live
