### ISSUE TITLE
Mobile device (Supported camps) issues

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1432]
Issue 1 :  Search box and reset button are missing 

Issue 2 : Incorrect support order numbers 
![image](https://github.com/user-attachments/assets/c860f0dd-936a-4349-af6b-e5cbe47d96f8)

Issue 3 : Pagination is missing 

Issue 4 : Layout issue when the topic name is 80 characters long. 

![image](https://github.com/user-attachments/assets/88ab73c5-d73b-407c-b1ce-ad4a4c12eea2)

**Comment by rupalichavan9860** [comment]
Issue 4 - Not fixed 
![image](https://github.com/user-attachments/assets/9c066ee1-9cdc-4abc-814b-259ecdcdceea)

**Comment by rupalichavan9860** [comment]
![image](https://github.com/user-attachments/assets/1d03dddf-a35a-48a5-8237-e1e51e201ad7)

**Comment by saniatg** [comment]
verified

**Comment by rupalichavan9860** [comment]
Verified on live
