### ISSUE TITLE
Started by and Post in this thread is blank on Thread page when opening thread related web notification 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1435]
Please refer attached screenshot : 
![image](https://github.com/user-attachments/assets/4d538ae9-977b-4752-aefd-9e8d844cde85)

**Comment by ks-rahul** [comment]
@rupalichavan9860 Is there a specific scenario for this? I tested it on the server, and it is working as expected.

![Image](https://github.com/user-attachments/assets/2113a9b3-7ae8-4502-a59f-2cd39abe18fc)

**Comment by ks-rahul** [comment]
@rupalichavan9860 I have replicated this fixing now.

**Comment by saniatg** [comment]
Not able to test this getting crash on thread @ks-rahul

**Comment by rupalichavan9860** [comment]
Verified on UX server

**Comment by saniatg** [comment]
WORKING FINE ON LIVE
