### ISSUE TITLE
No data is showing for camp result

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/Canonizer-Beta--Issue-Tracking#1436]
Steps:
Create a new topic
Create a camp under it with name "C1"
A "contribute" panel will appear with "Show more results" option in the end
Click on "Show more results" and navigate to "More Results" page
Observe that no data is showing on the page despite of showing "number of camps" in the side bar 
As shown in attached screenshot:
![Image](https://github.com/user-attachments/assets/f16179f1-2291-453d-81ae-6c1e051fd343)

**Comment by saniatg** [comment]
Live- "See more result "link on click on topic page , shows "no records found " instead of many records in search
![Screenshot 2024-10-17 at 10 05 06 AM](https://github.com/user-attachments/assets/e3b61afa-e0ec-4686-8a9f-c920d4b74261)

**Comment by hassaanCD** [comment]
Verified on UX-Dev

**Comment by hassaanCD** [comment]
Not fixed on live

**Comment by hassaanCD** [comment]
Verified on live
