### ISSUE TITLE
Web Notifications : Getting error on multiple clicks on "Delete All"  and "Mark All Read"

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1437]
Please refer attached screenshot : 

![image](https://github.com/user-attachments/assets/ae90dd9c-fffb-4699-aa28-80aa703ac928)

**Comment by saniatg** [comment]
working fine on dev

**Comment by saniatg** [comment]
working fine on production
