### ISSUE TITLE
Blog link when click from the header is not working

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#144]
Refer screenshot
![Screenshot 2023-01-03 at 12 10 02 PM](https://user-images.githubusercontent.com/91254708/210310337-ac1788c8-9efa-4c2d-96a5-e8ebb016405d.png)

**Comment by ks-rahul** [comment]
@saniatg please check now

**Comment by saniatg** [comment]
@rupalichavan9860 tested and is working fine on live and staging.

**Comment by rupalichavan9860** [comment]
Verified
