### ISSUE TITLE
Profile Setting: Discard functionality is not working properly

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/Canonizer-Beta--Issue-Tracking#1441]
Steps:
Go to Profile Settings
Type addresses line 1 and address line 2 and then 
Now click on discard button
Observe address line1 and address line 2 fields
Result: Address line 2 discard but address line 1 remain there with "loading" under it
As shown in attached screenshot
![Image](https://github.com/user-attachments/assets/2e876b6a-629c-4194-8aac-fd2d1682ed05)

**Comment by hassaanCD** [comment]
Not fixed

**Comment by hassaanCD** [comment]
"Address 1" is now clearing after click on "discard button" but "loading" is still showing under the the field.
![Image](https://github.com/user-attachments/assets/17051427-1fe6-4b28-b74e-d6ad3c113538)

**Comment by saniatg** [comment]
@akuks , google address should working on dev, currently it shows loading. Discard is working fine

**Comment by rohit-talentelgia** [comment]
@saniatg as discussed in the meeting, if discard functionality is working fine, then close this ticket
