### ISSUE TITLE
Mobile - History page is overlapping main menu drawer

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/Canonizer-Beta--Issue-Tracking#1443]
History page is overlapping main menu drawer as shown in attached screenshot:
![Image](https://github.com/user-attachments/assets/b1b3efd4-244d-4601-bad5-da529f65cabc)

**Comment by DevAlchemyCD** [comment]
Deployed on ux-dev server.

**Comment by hassaanCD** [comment]
Verified

**Comment by hassaanCD** [comment]
Not fixed on live

**Comment by hassaanCD** [comment]
Not fixed on live

**Comment by hassaanCD** [comment]
Not fixed on live

**Comment by hassaanCD** [comment]
Verified on live
