### ISSUE TITLE
Topics are not loading in mobile when click on 'Browse more' button on home page

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1447]
From home page click on browse button , the topics are not loaded
![ImportedPhoto 750746818 423499](https://github.com/user-attachments/assets/3183fee6-e03d-4799-900f-2286d1dc8c3a)

**Comment by rohit-talentelgia** [comment]
Hello @saniatg we have checked the same and it is working find on Production and UX Server

**Comment by saniatg** [comment]
Working fine. Closing the issue
