### ISSUE TITLE
Camp Statements : Editor issue 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#145]
When using an ordered and unordered list at the same time, data is not displayed or saved correctly.

Please refer attached screenshots : 
Entered Data : 
![image](https://user-images.githubusercontent.com/40416610/210323730-cb351d43-9ce8-4a6f-be05-c979d87b8634.png)
![image](https://user-images.githubusercontent.com/40416610/210323758-4e3e32c5-f180-4c11-a58f-5ba5dd465c95.png)

Preview : 
![image](https://user-images.githubusercontent.com/40416610/210323793-ee5b0f96-6a9d-4499-a0c5-cde655e2f4e7.png)

**Comment by rohit-talentelgia** [comment]
As discussed over the call, we need to try CKeditor open source. @vikasranatalentelgia look into this.

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by rupalichavan9860** [comment]
Verified on live
