### ISSUE TITLE
Topic/Camp/Statement : View This version is not working 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1450]

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2246

**Comment by sajid315** [comment]
PR : https://github.com/the-canonizer/canonizer-3.0-api/pull/1165

**Comment by rupalichavan9860** [comment]
I can see the selected record but color is not getting changed

**Comment by saniatg** [comment]
@sajid315 color is not CHANGED

**Comment by saniatg** [comment]
For Color issue -ticket has been created , moving this ticket

**Comment by saniatg** [comment]
Not working on live . Added statement from non supporter and then committed change  , the record will be in review. Click view this version . The statement is not seen

**Comment by DevAlchemyCD** [comment]
> Not working on live . Added statement from non supporter and then committed change , the record will be in review. Click view this version . The statement is not seen

@saniatg ! This is not working on live because the code is not deployed on live environment but it is deployed on UX-dev server. The code will be updated on live after current releaese.

**Comment by rupalichavan9860** [comment]
Verified on live
