### ISSUE TITLE
Incorrect support score in below case 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1453]
Steps to reproduce : 
1. Create topic 
2. Create 2 camps "C1" and "C2"
3. Support both camps 
4. Create sub camp of "C1" and support 
5. Observe scores 

![image](https://github.com/user-attachments/assets/13441965-3fb9-4432-b5b7-351085351481)

It must be "0.75" and "0.25"

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2272

**Comment by rupalichavan9860** [comment]
Working fine on UX server

**Comment by hassaanCD** [comment]
Not fixed on live

**Comment by hassaanCD** [comment]
Verified on live
