### ISSUE TITLE
Getting same notification twice when click on check box" remove all support"

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1457]
![Screenshot 2024-10-17 at 11 06 31 AM](https://github.com/user-attachments/assets/6755e2a9-c45f-40e4-8071-7f55707e801a)

**Comment by saniatg** [comment]
working fine for now

**Comment by DevAlchemyCD** [comment]
We have informed @saniatg regarding that issue. She said its fixed now
