### ISSUE TITLE
"Object button" is showing for few seconds even in the case of single user who commits

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/Canonizer-Beta--Issue-Tracking#1459]
Steps:
Login and create a topic
Now click on "Add Statement"
It will navigate to add statement page
Now add any statement in editor 
click on publish
It will navigate to statement history" page
Click on commit and observe the result 
Result: Object button is showing for few seconds which is an issue
As shown in attached screenshot:
![Image](https://github.com/user-attachments/assets/34e51e9a-bd41-4a25-83f7-6d208fddd83a)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2305

**Comment by hassaanCD** [comment]
Verified on UX-DEV

**Comment by hassaanCD** [comment]
Verified on live
