### ISSUE TITLE
In the following cases, the Object button is enabled for non-supporters(delegated supporter).

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#146]
Steps to reproduce : 
1. Login with User A and Create 3 camps 
2. Support all 3 camps 
3. Login with User B and Delegate support to User A in any camp 
4. Login with User B and Update Camp 1 - update any field - it will be in review
5. Login with User A and Update Camp 2 - change parent to "Camp 3" - it will be live
6. Login with User A and Update Camp 2 - change parent to "Camp 1" - it will be live
7. Now observe Camp 1 updated in 2nd step with User B login 

Actual Result : Object button is enabled for User B (delegated user)

**Comment by sunilspr7** [comment]
@gautamv16  PR created against this ticket - https://github.com/the-canonizer/canonizer-3.0-api/pull/528

**Comment by rupalichavan9860** [comment]
Working fine

**Comment by rupalichavan9860** [comment]
Verified on live
