### ISSUE TITLE
Whatever activity I am doing on live. It is showing same notification message

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/Canonizer-Beta--Issue-Tracking#1461]
Whatever activity I am doing on live like add support, remove support, delegate support. It is showing same "remove as camp leader" notification message every time.
As shown in attached screenshot:
![Image](https://github.com/user-attachments/assets/5ca3a160-9bf5-4f14-9f3b-2f47782eeb9d)

**Comment by sajid315** [comment]
Following is the PR for hotfix.
https://github.com/the-canonizer/canonizer-3.0-api/pull/1168

**Comment by hassaanCD** [comment]
Verified on live
