### ISSUE TITLE
Getting error on add support 'nickname required' on UX

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1467]
![Screenshot 2024-10-21 at 6 58 09 PM](https://github.com/user-attachments/assets/96320534-00e7-4488-b4a7-d7da1a401466)

**Comment by saniatg** [comment]
verified

**Comment by hassaanCD** [comment]
Verified on live

**Comment by rupalichavan9860** [comment]
Verified on live
