### ISSUE TITLE
Browse Page : Showing ";" when there are no topics under canon 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1469]
Please refer attached screenshot : 
![image](https://github.com/user-attachments/assets/c40f0c5d-3580-4f8b-a6de-94b1ce42fcbe)

**Comment by DevAlchemyCD** [comment]
Already done under ticket #1415 .

**Comment by rupalichavan9860** [comment]
Working fine on UX server

**Comment by saniatg** [comment]
verified on live

**Comment by rupalichavan9860** [comment]
Not fixed on live 

![image](https://github.com/user-attachments/assets/5f787d8f-cfd8-4c2b-8329-041173ae8a4a)

**Comment by saniatg** [comment]
Verified on live

**Comment by rupalichavan9860** [comment]
Verified on live
