### ISSUE TITLE
404 page not found when click on file upload from blog page

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#147]
Steps:

1. Do not login
2. Click on Blog from breadcrumb
3. User will be redirected to https://blog.canonizer.com/
4. Now click on 'File upload'

404 error will be seen also , button 'Go Back' is not working.
![Screenshot 2023-01-04 at 11 41 53 AM](https://user-images.githubusercontent.com/91254708/210496480-0f25b5ae-e551-4ee4-8366-28002dfb2e3c.png)

**Comment by rupalichavan9860** [comment]
Working fine
