### ISSUE TITLE
Remove link "Blog" from canonizer emails 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1470]
Please refer attached screenshot : 
![image](https://github.com/user-attachments/assets/e8d311b9-b7cc-45d4-85e3-2f4262a9bd32)

**Comment by rupalichavan9860** [comment]
Verified on UX server

**Comment by saniatg** [comment]
Verified on live

**Comment by rupalichavan9860** [comment]
Verified on live
