### ISSUE TITLE
Live (Search) : Getting page crash on specific topic 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1472]
Steps : 
1. Go to search 
2. Search keyword "https://canonizer.com"
3. Click on highlighted topic 

![image](https://github.com/user-attachments/assets/afcdfa06-bb7b-4644-9801-31cde3c09e82)

Getting below page crash : 
![image](https://github.com/user-attachments/assets/a1ecd35f-6037-4117-b8b7-57692aed565a)

**Comment by rohit-talentelgia** [comment]
The URL is not correct, it should be "https://canonizer.com/topic/1156-https-canonizer-com-create/1-Agreement"

**Comment by rohit-talentelgia** [comment]
@rupalichavan9860 The issue is not reproducible for the same scenario in newly created topics. There may be some issue at the point when this topic was created. Kindly check

**Comment by saniatg** [comment]
This topic is not there now, and working fine for similar topics
