### ISSUE TITLE
For a while, Something went wrong is displaying on video page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#149]
![image](https://user-images.githubusercontent.com/40416610/210596580-0f1f62aa-5989-421c-a26d-9a23d6de3315.png)

**Comment by shahab-ramzan** [comment]
@rupalichavan9860 Working fine. Can you please test again 
<img width="1428" alt="Screen Shot 2023-01-05 at 12 43 36 PM" src="https://user-images.githubusercontent.com/96526562/210727895-9c51e66b-e5a0-4830-87e2-b93b305c21d7.png">

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by ks-rahul** [comment]
Working fine on production

**Comment by rupalichavan9860** [comment]
Verified on production
