### ISSUE TITLE
Page crash on below link from email "You have been promoted as direct supporter."

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#15]
Please refer attached screenshot : 
![image](https://user-images.githubusercontent.com/40416610/203500304-0da9b8c5-b5fa-44a7-bfc5-67bc124bc491.png)

Getting below page crash : 
![image](https://user-images.githubusercontent.com/40416610/203500210-437682a4-76ca-461f-befc-5ba3ace65ce6.png)

**Comment by nalwa** [comment]
@ashish76 i have worked on this email , There is one more issue in same email only one camp is listed. 

So let me know will you be working on both issues?

**Comment by akuks** [comment]
@nalwa What is the PR ?

**Comment by rupalichavan9860** [comment]
Crash issue is fixed
