### ISSUE TITLE
Live- Camp statement is not updating when editing the change to already  submitted data

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1501]
Steps:

1. Create topic
2. Add camp statement
3. Do not commit changes
4. Edit Change - add some more text
5. Click on "Publish Statement"
6. and commit

the statement shows the one added before edit.

edited statement with updated text is not showing.

**Comment by rupalichavan9860** [comment]
Please refer #1155
