### ISSUE TITLE
Score count is incorrect in a specific case

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#1504]
Case:
 Go to any topic, and support the topic
 support shows count 1 
now apply mind expert filter
Create a new topic, the score shows 0 and in refine the algo is one person one vote

**Comment by sajid315** [comment]
@vikasranatalentelgia as we discussed in the call. This problem is coming due to payload passing to service API from front-end side. 
And according to above steps, it should pass 'blind_popularity' algo when ever refine filter not having any filter applied OR in the URL.

**Comment by saniatg** [comment]
@vikasranatalentelgia not fixed

**Comment by saniatg** [comment]
Not able to replicate.  Closing for now

**Comment by saniatg** [comment]
Working fine on production
