### ISSUE TITLE
For Non-Supporter pending data is not showing at topic history page, but counting is showing for both "live" and "pending data".

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/Canonizer-Beta--Issue-Tracking#1506]
Steps:

Edit change topic with User A and do not commit, then copy the  URL and and open with User B.

https://github.com/user-attachments/assets/f47aca58-4f21-4692-8ecf-f03d19566a0a

**Comment by sajid315** [comment]
PR raised:
https://github.com/the-canonizer/canonizer-3.0-api/pull/1183

**Comment by akashgit77** [comment]
@sajid315 Working fine on ux server

**Comment by akashgit77** [comment]
![Screenshot from 2024-11-18 18-29-05](https://github.com/user-attachments/assets/dddf2fce-944e-4d28-89b8-c711d16b1703)
Not working on live

**Comment by hassaanCD** [comment]
Having one of my change in pending state, when I am trying to access to topic history page, its redirecting me back and API getting error. 
@sajid315 have a look please, if its relevant to this issue.

![Image](https://github.com/user-attachments/assets/3e032a10-fb60-49bf-8612-96d2acbd7c83)

**Comment by sajid315** [comment]
PR Raised for ITR-6 branch is following:
https://github.com/the-canonizer/canonizer-3.0-api/pull/1192

**Comment by saniatg** [comment]
working fine on dev

**Comment by saniatg** [comment]
working fine on live
