### ISSUE TITLE
Live: Search is not working when user type keyword "Tree".

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/Canonizer-Beta--Issue-Tracking#1507]
When user try to search keyword "Tree" then it is not working.
![Image](https://github.com/user-attachments/assets/f87859da-fcc4-41d0-8907-fd26d336d94f)

**Comment by hassaanCD** [comment]
Verified on UX-DEV

**Comment by saniatg** [comment]
working fine on production
