### ISSUE TITLE
Canon's name is not updating on the application. 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1508]
Steps to reproduce : 
1. Go to admin panel
2. Rename any existing canon 
3. Observe canon name on the application

Expected Result :  It should show updated canon name 

Actual Result : As of now need to clear cache to see updated canon name

**Comment by sajid315** [comment]
@rupalichavan9860  This issue has been fixed for the ux-dev server. Following were the issues. 

1- Browse page canon list was coming from redux cache and it was not updating when admin updates the canons.
2- Backend canon lisitng was coming from Redis cache that was not updating on action from admin panel. 

Both of the above issue's are resolved and working on ux-dev server right now.

We need to do a hotfix to production after QA testing or need to wait until the next prod release to make it work on production.

**Comment by rupalichavan9860** [comment]
Verified on UX server
