### ISSUE TITLE
Multiple issue when 'as of date' filter is applied on topic creation

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#151]
Steps:

1. Create a new topic
2. add statement and click on view this version
3. As of date will be selected
4. Now click on create topic button from left side

Issue 1: on success-full creation the UI is distorted, refer screenshot
![Screenshot 2023-01-04 at 6 57 45 PM](https://user-images.githubusercontent.com/91254708/210704589-a88efa35-c220-4ef4-87bf-a3ecace19546.png)

5. Now click on the link 'topic creation date' on that page
6. click on create camp 
Issue 2: On creating camp, parent camp name is NAN and on click submit error is shown. Refer screenshot

![Screenshot 2023-01-04 at 7 02 15 PM](https://user-images.githubusercontent.com/91254708/210705148-72eecf53-2807-47d1-924b-25e68067cc9c.png)

**Comment by saniatg** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
Working fine on production.
