### ISSUE TITLE
Page crash on topic detail page when applying filter as of date 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1510]
Please refer attached screenshot : 
![image](https://github.com/user-attachments/assets/62381ee3-ccbd-44b4-b15b-ee5858176042)
 

![image](https://github.com/user-attachments/assets/bab1551d-4972-49a7-947c-782ec337adcd)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2298

**Comment by rupalichavan9860** [comment]
Verified on UX server

**Comment by saniatg** [comment]
Working fine on production
