### ISSUE TITLE
Subscription issue on live

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/Canonizer-Beta--Issue-Tracking#1513]
Steps:
Login Canonizer live and create a topic (Topic A)
Add camp under it and add subscription to both topic and camp
Now create another topic with camp (Topic B)
Now navigate to home page and select Topic A from "Recent Activities"
It will navigate to Topic detail page of topic A, observe the breadcrumbs, you can see subscription icon with both topic and camp
Now again navigate back to home page and click on Topic B from "Recent Activities"
It will navigate to Topic detail page of topic B, observe the breadcrumbs, you can see subscription icon with both topic and camp even Topic B and its camp is not subscribed earlier which is an issue.

**Comment by ks-rahul** [comment]
@hassaanCD I have followed the steps, and it appears to be working fine. Could you please verify it once?

**Comment by hassaanCD** [comment]
It is working fine on now on live so I am closing this ticket.
