### ISSUE TITLE
Editor issues 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#152]
1. The page crashes when a user copies any existing statement with images.

Please refer attached screenshot : 
![image](https://user-images.githubusercontent.com/40416610/210944746-e97c4cf9-f2c4-4ee2-9a62-abaf4f77d4b2.png)

2. The entire content including the content that wasn't selected changed when the user changed the typeface after selecting a short section of text (after image).

![image](https://user-images.githubusercontent.com/40416610/210945324-860ba83b-f7a6-41e1-bd0e-399a8bb48571.png)

**Comment by rohit-talentelgia** [comment]
Hello @rupalichavan9860 , regarding point 2 mentioned by you, this is actually a feature of every editor. if you apply bold/italic/underline formatting etc, it will work fine, but if you are changing it to heading tags, you have to enter before and after the tags you want to change the format and then apply the format. This is general feature of every editor.

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
