### ISSUE TITLE
Incorrect support order when changing parent 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1520]
Current support status : 

![image](https://github.com/user-attachments/assets/a11cef28-7c43-450e-a24c-03712cbef02c)

Change Parent of "Sub C1" to "C1"
Observe preference number for "Sub C1"

Expected Result :  It must be "1"

Actual Result : It is showing "3"

![image](https://github.com/user-attachments/assets/dc86e159-4171-4a1c-971e-9a9999a29780)

**Comment by nalwa** [comment]
@rupalichavan9860   For me this is not incorrect, as we do remove the common support from parent only.  as mentioned below:
Scenario 7 : Support is getting removed from both child and parent camp while changing parent


Steps to reproduce : 
1. Create topic and 2 camps by "User A" and support both camps
2. Login with "User B" and delegate support to "User A" in any camp
3. Login with User A and Create new camp "Test camp 1"
4. Update "Test camp 1" and change parent camp to "Camp 1" from "Agreement"

Expected Result : 
Common Support should get removed from parent camp 

Actual Result : 
Support is getting removed from both camps(parent and child)


QA Status :  FAIL
Ticket no : 1334

So, preference order was never discussed to be changed as per me, also i do not find any documented case for this scenario. So logically its working fine. So i need confirmation over this case if this the requirement??? If yes please doc this case as well.

**Comment by rupalichavan9860** [comment]
@BrentAllsop Could you please check and update on this?

**Comment by BrentAllsop** [comment]
Yes, @Nalwa,
The original design said nothing about order, so this is the correct operation given the original design.
After it was implemented, we discovered it would be better in most cases to preserve the super camp support order over a conflicting sub camp, so this issue was created to address that.
If there is some other spec that needs to be changed, let us know and we can change it there also.

**Comment by nalwa** [comment]
Ok @BrentAllsop , its clear now. i will preserve the super camp preference order in this scenario.

**Comment by rupalichavan9860** [comment]
Verified and Working fine on UX server

**Comment by rupalichavan9860** [comment]
Verified on live
