### ISSUE TITLE
Search : Missing (S) for Camp, Statement and Nickname pages 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1531]
Please refer attached screenshot : 
Topic : 
![image](https://github.com/user-attachments/assets/314f7a45-eaba-4662-881f-1a2e6fa88c23)

Camp : 
![image](https://github.com/user-attachments/assets/20c42ab3-fd10-4c47-ae45-de2e5fda37dc)

Camp Statement : 
![image](https://github.com/user-attachments/assets/db6a265c-cf0d-4f8d-a7a1-b954bebed385)

Nickname : 
![image](https://github.com/user-attachments/assets/f1863d3a-fdae-4a7d-914e-a3ef73d31178)

**Comment by saniatg** [comment]
Working fine on ux-dev

**Comment by saniatg** [comment]
Working fine on production
