### ISSUE TITLE
Supported Camps : Issue while changing support order

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1533]
I am able to adjust the support order, however the screen got stuck and I got the following error in the console. 
Please refer attached screenshot : 

![image](https://github.com/user-attachments/assets/562886e5-d631-4dca-b1e9-d400cdb21fa0)

**Comment by rupalichavan9860** [comment]
Verified on UX server

**Comment by saniatg** [comment]
working fine on live
