### ISSUE TITLE
Page crash on Thread name click 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1534]
Steps : 
1. Create thread
2. Click on thread name 
Please refer attached screenshot : 
![image](https://github.com/user-attachments/assets/ba48f882-df53-4de7-b1af-25af429c3dd7)

**Comment by rupalichavan9860** [comment]
Verified on UX server

**Comment by saniatg** [comment]
working fine on live
