### ISSUE TITLE
Incorrect topic detail page showing in below case 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1538]
Steps to reproduce : 
1. Go to https://ux-dev.canonizer.com/
2. Click on any topic name 
3. Click on Help 

Expected Result : It should show topic detail page for topic "Help"
Actual Result : Showing data of previously selected topic 
Please refer attached screenshot : 

![image](https://github.com/user-attachments/assets/2ecbf241-8fda-46de-9b71-c052df0eb833)

**Comment by hassaanCD** [comment]
Verified on UX-DEV

**Comment by saniatg** [comment]
working fine on live
