### ISSUE TITLE
Meta tag issues 

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#154]
Issue 1: EditNewsPage URL is not matching as shared in the sheet.
![Screenshot 2023-01-06 at 1 25 24 PM](https://user-images.githubusercontent.com/91254708/210962799-93e81c28-c81d-400f-a4c5-0b6edee14ca1.png)
 
Issue 2: CampForumPage and CampForumCreatePage- Title is not matching as shared in the sheet.
Issue 3: CompareStatementPage URL is not matching as shared in the sheet.

**Comment by saniatg** [comment]
@M-Darab also description is not matching for the following :
EditNewsPage
CampForumPage
CampForumCreatePage
Support 
UserProfile

**Comment by array-junkie** [comment]
@saniatg 

On "EditNewsPage" description state that "Add a news link/video link limited to 2000 characters on any camp/topic of your choice." Excel Sheet Line: 15

I don't understand about the camp/topic choice, can you elaborate it?

**Comment by saniatg** [comment]
@M-Darab description is still not matching for
CampForumPage
CampForumCreatePage
UserProfile

**Comment by array-junkie** [comment]
@saniatg Some pages are incorrect in the payload, those are fixed from frontend side. One new page "CampForumListPage" is added in the excel sheet. We made request for update of description, once it's updated I'll update.

**Comment by saniatg** [comment]
Descriptions are matching now

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
@rupalichavan9860 Tested and is working fine on production
