### ISSUE TITLE
Refine - Correct "As of" filter must be selected

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/Canonizer-Beta--Issue-Tracking#1540]
Steps:
Logged in and create a topic
Open "refine" filter in "topic detail" page
Select "Include Review" and click on "Apply"
You will see "Include Review" selected on "Topic detail" page
Again open "Refine" filter and observe "As of" flitters

Issue: You can see "Default" is selected even previously "Include review" is selected which is also showing on "topic detail" page![Image](https://github.com/user-attachments/assets/f11b2934-db85-40cf-8dda-88d40040c420)

**Comment by rupalichavan9860** [comment]
Verified on UX server

**Comment by hassaanCD** [comment]
Working fine on live
