### ISSUE TITLE
Drafted statement is not showing (in case of second user)

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/Canonizer-Beta--Issue-Tracking#1551]
Steps:
Login with user A and create a new topic
Add statement which is autosaved (User A)
Now login with User B and try to edit the statement of User A
Now click on "save as draft" button
It will navigate User B to "Topic detail" page where "edit draft" button is showed
Click on "edit draft" button (User B), it will navigate to "update statement" page
Observe editor of "update statement page"
Actual Result: Drafted statement is not saved so it is not showing which is an issue

**Comment by DevAlchemyCD** [comment]
PR :  https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2339

**Comment by hassaanCD** [comment]
Verified on UX-DEV

**Comment by hassaanCD** [comment]
Working fine on live
