### ISSUE TITLE
Parent change issue

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#158]
Steps to reproduce : 
1. Login with User A and create 2 camps "camp 1" and "camp 2"
2. Support both camps
3. Login with User B and change parent of "camp 1" to "camp 2" and commit changes - it will be in "in review"
4. Login with User B and change parent of "camp 2" to "camp 1" and commit changes - it will be in "in review"
5. Go to topic detail page and apply "include review" filter 

Actual Result: The "Canonizer Sorted Camp Tree"  is empty, and User A can accept both changes.
![image](https://user-images.githubusercontent.com/40416610/211328746-4b389953-1459-4f56-8f78-1065d7073dc6.png)

Obtaining the following while agreeing on the second change

![image](https://user-images.githubusercontent.com/40416610/211328051-1668dd2e-9ec2-4e11-a502-cb11a4b3a978.png)

**Comment by mark-shamy** [comment]
Thank you Rupali! To resolve this issue, either Access-Control-Allow-Origin for the subdomain api3.canonizer.com needs to be added to the server http header on Apache or the application being served on the subdomain needs to be moved to the primary domain.

**Comment by nalwa** [comment]
@rupalichavan9860  this issue has fixed. Issue was arising because **child was appearing in the drop down  of parent   IN step no 4. you have mentioned above.**  

The same has been restricted in staging 2.O. Please verify the same with staging 2.O.

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by rupalichavan9860** [comment]
Verified on live
