### ISSUE TITLE
Hide Rank functionality Doubt/Question 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1593]
As per functionality, the score is not visible to non-supporters, but it is visible to those who navigate to the event line. Does the score on the event line also need to be hidden?

**Comment by sunnyjindal** [comment]
@rupalichavan9860 I think Brent clarified this. We can close this?

**Comment by rupalichavan9860** [comment]
@sunnyjindal Yes . I am closing this
