### ISSUE TITLE
Remove static ad at the bottom of the page

### ISSUE THREAD

**Issue by sunnyjindal** [the-canonizer/Canonizer-Beta--Issue-Tracking#16]
![Image](https://user-images.githubusercontent.com/6779755/203546159-884ec6f8-1f65-4479-85b2-48f2acbc0f17.png)

This is a static ad. I think this should be removed.

**Comment by sunnyjindal** [comment]
@rupalichavan9860 please confirm.

**Comment by rupalichavan9860** [comment]
Yes @sunnyjindal This should be removed.

**Comment by rupalichavan9860** [comment]
@ks-rahul Please refer below screenshots. I guess we need to remove this too

![image](https://user-images.githubusercontent.com/40416610/205930586-97312a9a-ad4f-4a76-a9f5-5c6b7422ef5f.png)

**Comment by ks-rahul** [comment]
@rupalichavan9860 Right now we will keep these static ads. as per the discussion in the skype group with Ashutosh and Gautam.

**Comment by rupalichavan9860** [comment]
Yes @ks-rahul .For now I am closing this
