### ISSUE TITLE
The spelling of "Patent" in the blog footer is incorrect.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#161]
Please refer attached screenshot : 
![image](https://user-images.githubusercontent.com/40416610/211726206-0e3aabe8-89a5-4dfc-9fc1-91cd53a842ab.png)

**Comment by ks-rahul** [comment]
this is fixed.

**Comment by rupalichavan9860** [comment]
Working fine
