### ISSUE TITLE
Clicking on email footer links highlights improper header links

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#165]
Steps to reproduce : 
1. Go to any email 
2. Click on link "Help" and "Jobs"

Actual Result : It is highlighting  "Upload File" and "Blog" links
Please refer below screenshot : 
![image](https://user-images.githubusercontent.com/40416610/212619739-0122262c-a79a-42e9-87c4-675ff898edc0.png)

![image](https://user-images.githubusercontent.com/40416610/212619902-d06e7364-d777-4f01-81f1-2150110f8e1f.png)

Expected Result : It should highlight "Help" and "Jobs"

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by saniatg** [comment]
@rupalichavan9860 Tested and is working fine on Production

**Comment by rupalichavan9860** [comment]
Verified
