### ISSUE TITLE
Issues with Header and footer links

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#166]
When users click on Email footer links and then header links, they are redirected to the wrong pages.

**Comment by rupalichavan9860** [comment]
@ks-rahul Still facing issues 
![image](https://user-images.githubusercontent.com/40416610/213366703-0d4afda3-f4cd-4921-bfbe-37a3a6adacaa.png)

**Comment by ks-rahul** [comment]
@rupalichavan9860 check now.

**Comment by rupalichavan9860** [comment]
Working fine now

**Comment by saniatg** [comment]
@rupalichavan9860 Tested and is working fine on Production

**Comment by rupalichavan9860** [comment]
Verified
