### ISSUE TITLE
beta: No topics are showing for the below mentioned algorithms

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#17]
No topics are showing for the following algorithms:
computer science experts, phd, Christian, secular/non religious, universal unitarian, atheist, transhumanist, united utah, republican, forward party, democrat, canonizer shares and canonizer canonizer. 
![image](https://user-images.githubusercontent.com/104552751/203706535-d5a6b2a6-e4d3-4919-9782-07eae1ec92fd.png)

**Comment by sajid315** [comment]
@subhancd  cache updated for beta now its working fine.

**Comment by subhancd** [comment]
working fine
