### ISSUE TITLE
We need drop-down menu on the user supports page where users can choose their nick name and view the supported camps.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#170]

**Comment by rupalichavan9860** [comment]
@ashish76 @ks-rahul As discussed, please refer below issues : 
1. When a logged-in user clicks on their own nickname (either public or private), a drop-down menu should appear with all of the nicknames.
As of now, it does not include all nick names.

![image](https://user-images.githubusercontent.com/40416610/215463893-9baff901-2d42-44fe-b259-6ca2531f602d.png)


2.Layout issues : 

![image](https://user-images.githubusercontent.com/40416610/215464979-79441409-e648-49ab-9ff1-a4d405e81b87.png)

**Comment by hassaanCD** [comment]
not fixed

**Comment by rupalichavan9860** [comment]
Issue 2 is not working

**Comment by ks-rahul** [comment]
@rupalichavan9860 please check now.

**Comment by rupalichavan9860** [comment]
Working fine now

**Comment by hassaanCD** [comment]
Tested and is working on production
