### ISSUE TITLE
When the user is not logged in, the topic history and camp history pages are empty.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#173]
Steps to reproduce : 
1. Select any topic 
2. Go to Manage/Edit This Topic and Manage/Edit This Camp and copy URL
3. Open new browser and paste the URL(User must be logged out)
4. Observe pages

Actual Result : Topic names and camp names are occasionally blank, and it  also occasionally fail to display any records.
Please refer attached screenshot : 
![image](https://user-images.githubusercontent.com/40416610/213626544-909d5345-6860-4a54-aa94-331e9a7d5213.png)

![image](https://user-images.githubusercontent.com/40416610/213626881-05dd629d-d607-43a1-86f9-ef44c539a3ea.png)

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by saniatg** [comment]
@rupalichavan9860 Tested and is working fine on production

**Comment by rupalichavan9860** [comment]
Still facing issue in private window

**Comment by sunilspr7** [comment]
@rupalichavan9860 and @saniatg it's working fine from my side. Please check your side once again

**Comment by rupalichavan9860** [comment]
This is working fine now so closing this
