### ISSUE TITLE
Staging : The pages Terms & Services and Privacy Policy are empty 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#176]
The pages https://canonizer3.canonizer.com/privacy-policy and https://canonizer3.canonizer.com/terms-and-services are empty
Please refer attached screenshot : 
 
![image](https://user-images.githubusercontent.com/40416610/215026865-10d7599c-d13c-46a1-b8db-4d29d9d3693b.png)

![image](https://user-images.githubusercontent.com/40416610/215026801-e81569c2-d1aa-48a7-a072-122caf8a8325.png)

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by hassaanCD** [comment]
Tested and is working on production
