### ISSUE TITLE
Implementation of a horizontal dynamic bar for score values against each camp

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#177]
![image](https://user-images.githubusercontent.com/40416610/215055447-a4928b00-4d53-4e07-9559-751692814a01.png)

**Comment by hassaanCD** [comment]
not fixed

**Comment by rupalichavan9860** [comment]
@shahab-ramzan Can you please check

**Comment by rupalichavan9860** [comment]
On staging, verified. @BrentAllsop Could you kindly check and clarify?

**Comment by rupalichavan9860** [comment]
This is not working properly on live for scores less than 5.
![image](https://user-images.githubusercontent.com/40416610/220344655-c745f6c9-ccb0-4fad-86e4-8cb4702a0075.png)

**Comment by saniatg** [comment]
@rupalichavan9860 working fine on staging.  
on live issue for scores less than 5 is still pending

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by rupalichavan9860** [comment]
Verified on live
