### ISSUE TITLE
On bread crumb, the layout is messed up.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#178]
Please refer attached screenshot :  
![image](https://user-images.githubusercontent.com/40416610/215074002-d36717ca-9c7a-4a2b-913f-23aa68b00947.png)

**Comment by rupalichavan9860** [comment]
Not working

**Comment by hassaanCD** [comment]
not fixed

**Comment by rupalichavan9860** [comment]
Working fine now

**Comment by saniatg** [comment]
@rupalichavan9860 Tested and is working fine on production.

**Comment by rupalichavan9860** [comment]
Verified on live
