### ISSUE TITLE
The topic list on the home and browse pages is empty.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#179]
Select namespace "All"
Please refer attached screenshot : 
![image](https://user-images.githubusercontent.com/40416610/216568065-65e3a3c7-a002-4781-87f0-3670978724e1.png)

**Comment by saniatg** [comment]
@rupalichavan9860 tested and is working fine on staging and on live

**Comment by rupalichavan9860** [comment]
Verified
