### ISSUE TITLE
When delegating support, the page crashes.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#180]
Please refer attached screenshot : 
![image](https://user-images.githubusercontent.com/40416610/216918102-ef4e1d7b-4392-4224-8296-e08e4f33bb43.png)

**Comment by vikasranatalentelgia** [comment]
@karun0607gautam I have checked the page crash issue and the API
https://service.canonizer.com/api/v1/tree/get

is returning delegates as objects, it should be an array

![image_2023_02_06T13_08_07_083Z](https://user-images.githubusercontent.com/98095849/217160480-fae8d679-20b4-4302-a364-2074e9b692b1.png)

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by hassaanCD** [comment]
Tested and is working on production
