### ISSUE TITLE
Getting 'Page not found' when removing support in a specific case

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#181]
Steps:
Precondition-enable browser notification for canonizer

1. Add support to any camp

2.You will get browser notification like shown in the screenshot below, then click on that notification on side.
![Screenshot 2023-02-08 at 1 16 12 PM](https://user-images.githubusercontent.com/91254708/217480170-00d5813d-f516-453a-a705-faa767449755.png)

3.Then click on check box 'remove all '
4. Now click on submit button

Page not found error on click submit button
![Screenshot 2023-02-08 at 12 34 44 PM](https://user-images.githubusercontent.com/91254708/217480386-d209956e-45d6-4c91-883a-aa0965e5fd5f.png)

**Comment by saniatg** [comment]
Working fine now

**Comment by rupalichavan9860** [comment]
Verified

**Comment by ks-rahul** [comment]
Working fine on production

**Comment by saniatg** [comment]
Tested and is working fine on Production
