### ISSUE TITLE
When a user removes support, the web notification is not working.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#183]
When another user removes their support, the user does not receive a web notification.

**Comment by ashish76** [comment]
@rupalichavan9860 On direct removing support there was only an email(supporter and subscriber) notification implemented.
and push notifications implemented only promoted delegates' cases.

I will be going to implement push notifications on the direct removing support  for supporters and subscribers

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by rupalichavan9860** [comment]
Working fine on live
