### ISSUE TITLE
Implement below 2.0 ticket in 3.0 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#184]
Please refer :  https://github.com/the-canonizer/canonizer.2.0/issues/1149

**Comment by saniatg** [comment]
@rupalichavan9860 verified with ticket #1149 and is working fine on staging

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
