### ISSUE TITLE
Email layout issues : Removed support email 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#185]
The font color in the removed support email is inconsistent.
Please refer attached screenshot : 

![image](https://user-images.githubusercontent.com/40416610/220370265-5435ab36-e435-4597-a5b0-2275cce97c5a.png)

![image](https://user-images.githubusercontent.com/40416610/220370374-7f2ff5ec-14a6-476e-902f-90abd7ad221a.png)

**Comment by sajid315** [comment]
@rupalichavan9860,
Unable to find this different text color email, also as discussed in call with you. This email is not required anymore. 
Please mention if you found this issue again.

**Comment by rupalichavan9860** [comment]
Removed support emails are removed in another ticket so closing this
