### ISSUE TITLE
The name of the Agreement camp appears twice on the supported camps page.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#186]
Issue 1 : Warning messages
Steps to reproduce :

1. Login with User A and create more than 2 camps and support all camps
2. Login with User B and support Agreement camp
3. Login with User A , go to Agreement cap and click on "Delegate Your Support"
4. Observe camps

Please refer attached screenshot : 
![image](https://user-images.githubusercontent.com/40416610/220510835-09b8fa59-98c8-4449-8482-629ada91f66a.png)

**Comment by hassaanCD** [comment]
fixed



![Image](https://user-images.githubusercontent.com/120023458/221779071-1398ebb8-a30f-45b2-8460-ad3763397d4f.png)

**Comment by array-junkie** [comment]
Linked with https://github.com/the-canonizer/canonizer-3.0-frontend/issues/830

**Comment by rupalichavan9860** [comment]
Verified on live
