### ISSUE TITLE
Object button is enabled for direct user (topic history) but when user click on it , it is showing "Why can't I object?" pop up

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#187]
Steps to reproduce : 
1. Create topic and create sub camp
2. Support sub camp
3. Login with User B and Submit change to a topic 
4. Login with User A and got to Manage/edit this topic
5. Click on Object button 
Please refer attached screenshot : 

![image](https://user-images.githubusercontent.com/40416610/220648038-364c62d9-cbcf-4714-a735-c88413b3033f.png)

**Comment by DevAlchemyCD** [comment]
@rupalichavan9860 this ticket done with #857

**Comment by saniatg** [comment]
@rupalichavan9860 working fine on staging

**Comment by saniatg** [comment]
@rupalichavan9860 Working fine on production
