### ISSUE TITLE
Error when attempting to log out

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#188]
Steps to reproduce : 
1. Login with valid email and password 
2. Navigate to any of the user support pages, such as https://canonizer3.canonizer.com/user/supports/347?topicnum=1674&campnum=4&namespace=19
3. Click on Username and click on Log Out 

Getting below error on staging : 
![image](https://user-images.githubusercontent.com/40416610/220807989-35a021d9-7cc5-478f-b508-b3c827a09f4b.png)

Live : 
![image](https://user-images.githubusercontent.com/40416610/220807863-590d17de-d2f8-4b52-bc16-dd20a7be9aa3.png)

**Comment by saniatg** [comment]
@rupalichavan9860 working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by rupalichavan9860** [comment]
Not fixed on live 
![image](https://user-images.githubusercontent.com/40416610/222231960-398136ae-0e31-4f00-adfe-64f70c5459ce.png)

**Comment by ks-rahul** [comment]
@rupalichavan9860 could you please check now.

**Comment by rupalichavan9860** [comment]
@ks-rahul Still getting "server error "

**Comment by hassaanCD** [comment]
working fine on both staging and live

**Comment by rupalichavan9860** [comment]
Verified on both staging and live
