### ISSUE TITLE
Main page not works in specific scenario

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/Canonizer-Beta--Issue-Tracking#189]
Steps to Reproduce

1. Go to canonizer3.canonizer.com and click on Login button
2. Click on Google icon and login with a "New" Google account

Actual Result:  Main page is not working when login with a "new" Google account as shown in attached screenshot below

![Image](https://user-images.githubusercontent.com/120023458/220856408-2d04612f-ccd2-40d9-a71b-b0e041e0ed99.png)

**Comment by ks-rahul** [comment]
Hi @shahab-ramzan after login in with a new account namespace_id is missing in the service API. please look into this.

**Comment by hassaanCD** [comment]
Fixed



![Image](https://user-images.githubusercontent.com/120023458/230055250-e86ee29b-c43f-4ab3-9e4d-c2eb54f76711.png)

**Comment by hassaanCD** [comment]
Working fine on production



![Image](https://user-images.githubusercontent.com/120023458/231423412-27c710cb-48c2-4da2-94eb-ac9ee96b0e3d.png)
