### ISSUE TITLE
Objector Nick name links from Topic /camp/statement history pages should redirect to specific namespace list(where current topic is created)

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#19]
By default it is redirecting to “general”(1) namespace - https://canonizer3.canonizer.com/user/supports/347?topicnum=1034&campnum=2&namespace=1

**Comment by subhancd** [comment]
working fine on both staging and beta

**Comment by rupalichavan9860** [comment]
Not working for topic and camp history

**Comment by rupalichavan9860** [comment]
Still not working for topic history

**Comment by rupalichavan9860** [comment]
Working fine
