### ISSUE TITLE
Support numbers are not visible clearly.

### ISSUE THREAD

**Issue by sunnyjindal** [the-canonizer/Canonizer-Beta--Issue-Tracking#190]
![Image](https://user-images.githubusercontent.com/6779755/220879363-61d1b183-158d-485f-b997-b560505f02aa.png)

**Comment by hassaanCD** [comment]
fixed



![Image](https://user-images.githubusercontent.com/120023458/221832386-372a5cac-1deb-405b-9654-36d071a2f867.png)

**Comment by rupalichavan9860** [comment]
Verified on live
