### ISSUE TITLE
All camps are not listing under "Canonizer Sorted Camp Tree"

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#192]
Please refer attached screenshot : 

![image](https://user-images.githubusercontent.com/40416610/220968192-fd4c7e1b-b5ef-45f9-bc50-6f224c3f5a5b.png)

![image](https://user-images.githubusercontent.com/40416610/220968635-60a75d14-a660-44f8-9799-11440f8221a6.png)

When click on "Camp 2", getting below errors : 
![image](https://user-images.githubusercontent.com/40416610/220968512-9eb2f17a-f2f5-4d2c-927c-3c8333cb2308.png)

**Comment by sajid315** [comment]
@rupalichavan9860 I am unable to reproduce this issue. Can you please mention exact step here if you found ? 
I checked above screenshot topic on live, its listing all camps.

**Comment by rupalichavan9860** [comment]
@sajid315 I'm changing this to "In Progress" because we need to figure out what's causing this problem.

**Comment by sajid315** [comment]
Issue #230 made by Rupali that have steps to reproduce the issue.

**Comment by rupalichavan9860** [comment]
Reference ticket #230 is fixed so closing this

**Comment by rupalichavan9860** [comment]
Verified on live
