### ISSUE TITLE
Unable to agree on the topic/statement change 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#193]
Steps to reproduce :

1. Create topic and create sub camp
2. Support sub camp
3. Login with User B and Submit change to a topic
4. Login with User A and go to Manage/edit this topic
5. "I agree with this topic change" is missing

Please refer attached screenshot : 
![image](https://user-images.githubusercontent.com/40416610/221008841-cb7543fd-3ba9-4d56-9de7-160405d20f3d.png)

Steps to reproduce :

1. Create topic and create sub camp
2. Support sub camp
3. Login with User B and Submit change to a agreement camp statement
4. Login with User A and go to Manage/edit this statement(Agreement camp)
5. "I agree with this statement change" is missing

Please refer attached screenshot : 
![image](https://user-images.githubusercontent.com/40416610/221015272-c87f5b70-104f-4265-9454-c6d2663080cc.png)

**Comment by array-junkie** [comment]
PR has been raised. https://github.com/the-canonizer/canonizer-3.0-api/pull/571

@rupalichavan9860 As per the previous discussions, We implemented the given changes. Now only Direct and Implicit Supporters can Agree & object

**Comment by sajid315** [comment]
PR raised from frontend side.
https://github.com/the-canonizer/canonizer-3.0-frontend/pull/865

**Comment by saniatg** [comment]
@rupalichavan9860 tested and is working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by rupalichavan9860** [comment]
Verified on live
