### ISSUE TITLE
Responsive issue on nick names page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#195]
Please refer attached screenshot : 
![image](https://user-images.githubusercontent.com/40416610/221722799-a8e6dfb3-c03b-45e1-b821-69f83e9ffc58.png)

**Comment by rupalichavan9860** [comment]
Not fixed

**Comment by hassaanCD** [comment]
Fixed



![Image](https://user-images.githubusercontent.com/120023458/224979771-59865c8b-1636-4fa2-a080-0b47d18879f6.png)

**Comment by rupalichavan9860** [comment]
Verified on live
