### ISSUE TITLE
Layout problem on the User Support page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#197]
Please refer attached screenshot : 

![image](https://user-images.githubusercontent.com/40416610/222476616-6d47fb5d-dad0-4391-b2be-ba3e0e0ff088.png)

**Comment by rupalichavan9860** [comment]
@vikasranatalentelgia The font size for "Select Nick Name" is extremely small . Please refer attached screenshot :  
![image](https://user-images.githubusercontent.com/40416610/223277664-fc2d502b-7f01-4982-ab23-377df23bfb55.png)

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by hassaanCD** [comment]
Verified on production



![Image](https://user-images.githubusercontent.com/120023458/231427490-24998d4c-4e35-4a20-8f20-18a0b2c325f1.png)




![Image](https://user-images.githubusercontent.com/120023458/231427522-59f7fd8c-0be4-4ada-82df-4b62d9d98b18.png)
