### ISSUE TITLE
Field City's visibility status is not being updated.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#198]
Steps to reproduce : 
1. Go to https://canonizer.com/
2. Login with valid email and password 
3. Go to Account Settings 
4. Set the "City" field's visibility status to Private
5. Click on Update
6. Choose any other tab, then return to the Profile info tab.
7.  Check the city's visibility status.

Actual Result : visibility status is not being updated.

**Comment by array-junkie** [comment]
PR has been raised https://github.com/the-canonizer/canonizer-3.0-frontend/pull/852

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by rupalichavan9860** [comment]
Verified on live
