### ISSUE TITLE
Mobile Devices : Layout issue on Camp Update page 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#199]
Please refer attached screenshot : 

![image](https://user-images.githubusercontent.com/40416610/222871345-7d3100ce-8572-4f56-a3f9-2215add04600.png)

It should be like create camp page : 

![image](https://user-images.githubusercontent.com/40416610/222871381-0ebc8ec1-9d49-418d-81eb-e591689f08f6.png)

**Comment by hassaanCD** [comment]
Not fixed



![Image](https://user-images.githubusercontent.com/120023458/225838567-0fc939bf-3804-4992-8cac-2364f2cccb4c.png)

**Comment by ks-rahul** [comment]
@hassaanCD PR is not merged. https://github.com/the-canonizer/canonizer-3.0-frontend/pull/871

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by hassaanCD** [comment]
Working fine on production



![Image](https://user-images.githubusercontent.com/120023458/227512669-b53f7488-cacc-43d8-842c-5aea2482d8b0.png)
