### ISSUE TITLE
Camp update is not working in beta

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#2]
Please refer below screenshot : 

![image](https://user-images.githubusercontent.com/40416610/203062852-7dee34a9-5c61-476f-9c74-0631847bb4b9.png)

**Comment by sajid315** [comment]
@rupalichavan9860 I am unable to reproduce this issue on local.

**Comment by sajid315** [comment]
https://github.com/the-canonizer/canonizer-3.0-api/pull/420

**Comment by sajid315** [comment]
@rupalichavan9860 issue tracked on staging and fixing PR has been raised. 
Check it again please when deployed.

**Comment by rupalichavan9860** [comment]
@sajid315 Working fine now
