### ISSUE TITLE
Beta : Incorrect data displaying in recent activities 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#20]
Please refer attached screenshots : 

Topic : 
![image](https://user-images.githubusercontent.com/40416610/203909521-4894231e-49c4-4115-b1ba-8d72b124b32d.png)

Camp : 
![image](https://user-images.githubusercontent.com/40416610/203909471-24f50514-7cab-47b3-a755-897f47ca7888.png)

**Comment by subhancd** [comment]
Same issues exists on homepage for recent activities.
![image](https://user-images.githubusercontent.com/104552751/204448987-a2336f22-e1ef-472c-a8c8-8cf2e205305d.png)

**Comment by sajid315** [comment]
@rupalichavan9860 issue fixed on beta now, here following are the results.



![Image](https://user-images.githubusercontent.com/111273633/204732280-77d82d90-6961-4d18-b79a-56dd575c469e.png)

**Comment by sajid315** [comment]
Issue was the queue job for activities.

**Comment by rupalichavan9860** [comment]
Verified
