### ISSUE TITLE
Include the following disclaimer text in the email and blog footer as well

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#201]
Footer must be uniform .
As of now following disclaimer text in the email and blog footer is missing :  
Canonizer is an[ open source ](https://github.com/the-canonizer/canonizer-3.0-frontend)project designed to build consensus and bring people together. Your collaboration can make all the difference. Join us!

**Comment by rupalichavan9860** [comment]
Text is available in the footer of emails, but not yet in the blog footer.

**Comment by ks-rahul** [comment]
@rupalichavan9860 because the blog is not merged. @akuks please look into this.

https://github.com/the-canonizer/canonizer3-blog/pull/8

**Comment by saniatg** [comment]
@ks-rahul text is still missing for blog
![Screenshot 2023-03-14 at 11 31 44 AM](https://user-images.githubusercontent.com/91254708/224910113-5ce777d1-c734-4822-a61d-249346b4eba9.png)

**Comment by saniatg** [comment]
@rupalichavan9860 Because of auto deployment failed earlier code was not updated  , tested and is working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
