### ISSUE TITLE
Add/ remove/delegate support is not working on staging

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#203]
![Screenshot 2023-03-06 at 10 56 41 AM](https://user-images.githubusercontent.com/91254708/223026112-9db36eb0-ea97-40e7-8859-087c8b92a009.png)

**Comment by array-junkie** [comment]
@saniatg it is fixed

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
