### ISSUE TITLE
On the support page, there is a misspelling in the error message.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#204]
Please refer attached screenshot : 
![image](https://user-images.githubusercontent.com/40416610/223204330-8e10f572-25d7-4988-b23f-54f8acb9ebc4.png)

**Comment by saniatg** [comment]
@rupalichavan9860 tested and is working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
