### ISSUE TITLE
Even though it is a mandatory field on the supported camps page, the field Summary accepts blank spaces.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#205]
Please refer attached screenshot :  
![image](https://user-images.githubusercontent.com/40416610/223205488-152f2775-a665-41dc-8669-da358b00b435.png)

**Comment by saniatg** [comment]
@rupalichavan9860 tested and is working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
