### ISSUE TITLE
Camp name is missing on "Reason for adding/removing support" pop up

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#206]
Steps to reproduce : 
1. Create topic and camp
2. Support camp
3. Go to account settings 
4. Click on Remove Support icon after camp name
5. Click on Save Changes
6. Observe pop up 

Actual Result :  Camp name is missing . Please refer attached screenshot :  
![image](https://user-images.githubusercontent.com/40416610/223210860-3b1fac0a-3b67-4ce2-a465-2494da947811.png)

**Comment by hassaanCD** [comment]
Not fixed. Instead of showing "Camp" name it is showing "Topic" name.



![Image](https://user-images.githubusercontent.com/120023458/224978812-892d5b0e-f0c3-4955-b470-9a454a05fd36.png)

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
