### ISSUE TITLE
Showing  incorrect placeholder 'Nick Name' on Reason for adding/removing support

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#207]
Steps:

1. When adding /removing support , select any reason from dropdown
2. Now,  click on cross icon on right side of field when hover  to remove the selected reason
Nick name as placeholder is seen which is incorrect
![Screenshot 2023-03-07 at 1 28 43 PM](https://user-images.githubusercontent.com/91254708/223361320-25ce61bf-007c-4e65-ace4-ddddb2cdf06f.png)

**Comment by saniatg** [comment]
Working fine on staging.

**Comment by rupalichavan9860** [comment]
Verified on live
