### ISSUE TITLE
Change the position of Subscription icon on topic detail page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#209]
The icon will appear between the topic/camp name and the horizontal score bar.

**Comment by saniatg** [comment]
@rupalichavan9860 Working fine now on staging
![Screenshot 2023-03-22 at 11 37 35 AM](https://user-images.githubusercontent.com/91254708/226816850-b3717afd-3cb9-4698-9c1f-0b53cad13cd1.png)

**Comment by hassaanCD** [comment]
Working fine on production



![Image](https://user-images.githubusercontent.com/120023458/227513210-ee63e468-d3cf-4ee2-8093-c72f04b5e558.png)
