### ISSUE TITLE
Page breaks on clicking on preview for the following case in camp update

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#21]
**Steps To Reproduce**

1. create a topic
2. create a camp -> camp1
3. add support in the camp1
4. update camp1
5. navigate to agreement from breadcrumbs
6. navigate to update agreement camp
7. click on preview
**Actual Result**
Page breaks down
![image](https://user-images.githubusercontent.com/104552751/203910107-4a8abbe4-927a-4ac9-b6aa-6b287272dd14.png)

**Comment by rupalichavan9860** [comment]
Not working

**Comment by rupalichavan9860** [comment]
Working fine
