### ISSUE TITLE
Error when attempting to log out 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#210]
Steps to reproduce : 
1. Go to https://canonizer.com/
2. Go to any topic 
3. Click on "Camp Forum"
4. Click on nick name from "Last Updated On" column or from thread details page 
5. Click on Log Out 

Actual Result : Getting "Server error". Please refer attached screenshot 

![image](https://user-images.githubusercontent.com/40416610/223770414-943c1e2a-7df4-4935-b421-44389ebed835.png)

**Comment by ashish76** [comment]
@rupalichavan9860 we tried to reproduce the issue with the case you mentioned, but it is not being produced, so please check once again or if there is any other step to reproduce please mention it.

**Comment by rupalichavan9860** [comment]
@ks-rahul @ashish76This is no longer an issue, thus I'm closing this ticket.
