### ISSUE TITLE
On the supported camps page, the incorrect topic name is displayed.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#212]
Click on Manage support and observe topic name below :  
![image](https://user-images.githubusercontent.com/40416610/223840880-2c4cb5c7-5e11-4758-bd19-3bf3531d1c93.png)

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by hassaanCD** [comment]
Working fine on production



![Image](https://user-images.githubusercontent.com/120023458/227453168-0a33d7e0-a4b4-4ccf-9614-1ca90c3daeac.png)
