### ISSUE TITLE
Text is not correct in the modal pop up when remove support

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#213]
Go to supported camps where there is support to more than 1 camp
When click on 'remove support' it will remove all the support from the camps which is correct, but the message on the pop up is not correct 
"You are about to remove your support from the camp: "topic_name"

Instead correct message is "You are about to remove your support from all the camps: "topic_name"
![Screenshot 2023-03-09 at 10 12 07 AM](https://user-images.githubusercontent.com/91254708/223920075-bb6fc67e-048a-4f4f-a145-d5c95637e81f.png)

**Comment by hassaanCD** [comment]
Fixed



![Image](https://user-images.githubusercontent.com/120023458/224984237-c56546eb-ecdd-4d09-a1ac-a0856134ba20.png)

**Comment by rupalichavan9860** [comment]
Verified on live
