### ISSUE TITLE
Account Settings ->Delegated Support Camps->Remove Support is not working 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#214]
Nothing happens when the user clicks the "Remove" button.

![image](https://user-images.githubusercontent.com/40416610/224427567-6a4baaf0-95c9-4636-a8fc-d4020546913c.png)

**Comment by saniatg** [comment]
Working fine on staging @rupalichavan9860

**Comment by saniatg** [comment]
Working fine on production
