### ISSUE TITLE
Unable to subscribe to camp

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#215]
Pease refer attached screenshot :  

![image](https://user-images.githubusercontent.com/40416610/224601037-cdf3a66f-fd09-4705-b692-c2f2a1689d11.png)

**Comment by DevAlchemyCD** [comment]
@rupalichavan9860 i did testing on both live and staging regarding subscribe and unsubscribe.
i am unable to reproduce this issue can you please have a look ?

**Comment by rupalichavan9860** [comment]
@wahaj-hafeez Can you please refer below topic and try to subscribe all camps
https://canonizer3.canonizer.com/topic/1850-Reproduce-192/3-Camp-2

It is showing in review camp name

**Comment by rupalichavan9860** [comment]
@wahaj-hafeez Steps to reproduce : 
1. Login with User A and Create topic
2. Create 2 camps "camp 1" and "camp 2"
3. Support both camps (Login with User A)
4. Login with User B and update camp 1 - change parent to camp 2 and update camp name to "camp 1 up 1"and commit changes----It will be in "in review"
5. Again login with User A and Subscribe camp 1-Working fine
6. Try to subscribe camp 2 - It is showing "You are subscribed to Camp 1 up 1"

**Comment by sajid315** [comment]
@rupalichavan9860 
What will be the acceptance criteria for this ticket ?
