### ISSUE TITLE
All subscribed and supported camps are not listing in below email

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#217]
I received the following two emails on live from user "J-Brew" when he added support to camp and created a post.

**added their support to camp :** 

![image](https://user-images.githubusercontent.com/40416610/224750504-a7ccb076-3ab2-47e2-b362-c2158f401ad2.png)

It is listing only one subscribed camp 

**made the following post to the Camp :** 
![image](https://user-images.githubusercontent.com/40416610/224750755-5b49c00d-aa31-4096-b08e-f686fa13845a.png)

It is listing all subscribed and supported camps

@BrentAllsop Is this an issue ?

**Comment by nalwa** [comment]
hi @rupalichavan9860  i need some more clarification on this ticket. as you have also mentioned @BrentAllsop  to verify this .

**Comment by rupalichavan9860** [comment]
@nalwa After I discussed this with Brent, I realized that "Integrated Information Theory" is a sub camp of "Mind-Brain Identity," which is why it is listed there.

There is not a problem, so I'll close this.
