### ISSUE TITLE
Camps and topics that have recently been subscribed to are not visible under Account Settings -> Subscription.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#219]
It currently displays only 10 topics. The eleventh topic is not listed.

**Comment by sajid315** [comment]
Raised PR 
https://github.com/the-canonizer/canonizer-3.0-frontend/pull/872

**Comment by rupalichavan9860** [comment]
@sajid315 I can now see all topics, but the most recent ones are listed on the last page.
![image](https://user-images.githubusercontent.com/40416610/225401644-c9152e94-06ab-4ffc-89ff-b8cbda46f623.png)

**Comment by sajid315** [comment]
Ok @rupalichavan9860. We will update

**Comment by array-junkie** [comment]
Done [PR #584](https://github.com/the-canonizer/canonizer-3.0-api/pull/584)

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Working fine on live
