### ISSUE TITLE
Beta: Score in "Sort Camp Tree" and "Support Tree" is not same on changing algorithm

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#22]
**Steps to reproduce**

1. navigate to topic detail page of any topic
2. change algorithm to "Mind Experts"
3. scroll down and check the score in "Support Tree"
**Actual Result**
score tree in sorted camp tree and support camp tree is not the same

**Comment by nalwa** [comment]
@rupalichavan9860  this is working fine for me. is there any specific topic for which its giving wrong score ?

**Comment by subhancd** [comment]
@nalwa this issue for this particular topic https://beta.canonizer.com/topic/88-Theories-of-Consciousness/1-Agreement

**Comment by subhancd** [comment]
list of algorithms with incorrect score

- one person one vote
- computer science experts
- transhumanist
- sandy city

**Comment by nalwa** [comment]
ok @subhancd   i will check

**Comment by nalwa** [comment]
@shahab-ramzan  as per discussion we have now implemented same score on sorted tree and support tree can you pleas verify if its working fine for new changes.

**Comment by shahab-ramzan** [comment]
@nalwa Yes PR has been merged for this task. 
https://github.com/the-canonizer/canonizer-3.0-api/issues/443

**Comment by nalwa** [comment]
ok @shahab-ramzan

**Comment by subhancd** [comment]
working fine on both staging and beta
