### ISSUE TITLE
Dialog should be different while changing the support order of a camp using drag and drop in Account Settings

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#220]
Currently it displays below dialog when I click the Save Changes button.

![image](https://user-images.githubusercontent.com/40416610/225134477-6afa8335-0e76-43e7-9a80-aee4f0351644.png)

**Comment by ks-rahul** [comment]
@rupalichavan9860  could you please specify what needs to change in the dialog?

**Comment by ashish76** [comment]
@ks-rahul  please change the message to

You are about to change the order of your supported camps. You can optionally add a helpful reason, along with the citation link.

**Comment by hassaanCD** [comment]
Not fixed



![Image](https://user-images.githubusercontent.com/120023458/225833645-00e4838c-b82f-4e21-b33c-e06784498fc2.png)

**Comment by rupalichavan9860** [comment]
@ks-rahul I'm attempting to drag camps, but I'm having no luck.
![image](https://user-images.githubusercontent.com/40416610/226718173-217be285-d57f-4470-82b3-9e4068297f30.png)

Attempting to shift "camp 3" to the third option as shown below
![image](https://user-images.githubusercontent.com/40416610/226718348-3f41b6da-971f-4ea5-8bf5-a528710f9f73.png)

but if I drop, it will stay the same as in the first picture.
![image](https://user-images.githubusercontent.com/40416610/226718562-98d458ae-fc9e-42e2-9e94-68bd83d44d41.png)


Also, when I save, I see a different dialog, but the button name that appears is "Remove."

![image](https://user-images.githubusercontent.com/40416610/226718841-8419346f-664a-4b20-8850-8ad056676231.png)

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by hassaanCD** [comment]
Verified on production


![Image](https://user-images.githubusercontent.com/120023458/231439203-e8b06de6-a5ef-45e1-a716-7082bbd02f2a.png)



![Image](https://user-images.githubusercontent.com/120023458/231439286-34303d6e-63d8-4d8c-9ac9-ed04f042a0b8.png)




![Image](https://user-images.githubusercontent.com/120023458/231439314-f98151ac-9300-4ce6-aa24-da5878bf8c2e.png)
