### ISSUE TITLE
Some menus are not working form Manage support /Supported camps page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#221]
Steps to reproduce : 
1. Go to any topic
2. Go to supported camp
3. Click on Manage Support
4.  After the "Camp Forum" button, click the three dots.
5. Click on "Add News", "Subscribe to Entire Topic", "Subscribe to the Camp"

Actual result : Clicking "Subscribe to Entire Topic" and "Subscribe to the Camp" results in nothing happening and getting console error.
Clicking "Add News" results in nothing happening

![image](https://user-images.githubusercontent.com/40416610/225346814-cf344f04-0ce3-494e-bdc6-5ce84d2a6729.png)

![image](https://user-images.githubusercontent.com/40416610/225347015-8eff8d7c-3436-4bfe-aab6-944ce3369394.png)

**Comment by hassaanCD** [comment]
Not fixed



![Image](https://user-images.githubusercontent.com/120023458/225841170-983467f1-bdf9-4fa9-accc-317e1f7c2460.png)

**Comment by rupalichavan9860** [comment]
Working fine on both staging and live
