### ISSUE TITLE
Direct supporter of camp is not able to agree the changes submitted by non supporters for camps , topic and statements

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#224]
Steps:

1. Create a topic by user A 
2. Now create a camp 'camp1' and support the camp
3. Login with user B and submit changes to the camp1
4. Commit the change, changes will be in review
5. Login with User A and check the check box 'I agree with this camp change'

Actual result :getting error"User agreed is required."
Expected result: User A is direct supporter of camp 1 and should be able to agree the changes

![Screenshot 2023-03-17 at 11 06 37 AM](https://user-images.githubusercontent.com/91254708/225822567-6e110f6e-1740-473a-b9dd-2b9ef45c6a77.png)

**Comment by array-junkie** [comment]
@saniatg it is working fine on staging.

**Comment by saniatg** [comment]
Working fine on staging

**Comment by hassaanCD** [comment]
Working fine on production



![Image](https://user-images.githubusercontent.com/120023458/227488373-1eadaeea-8802-481e-87cc-ae0d4cb8d62a.png)
