### ISSUE TITLE
Create Redirect For canonizer 1.0 topic url to canonizer 3.0 topic url with a test case to test the redirect success.

### ISSUE THREAD

**Issue by gautamv16** [the-canonizer/Canonizer-Beta--Issue-Tracking#225]
Create Redirect For canonizer 1.0 topic url to canonizer 3.0 topic url with a test case to test the redirect success.

Canonizer 1.0 topic url

https://canonizer.com/topic.asp/120/8 must redirect to :

Canonizer 3.0

https://canonizer.com/topic/120/8

We have to write a test case for the same.

**Comment by rupalichavan9860** [comment]
Verified on live
