### ISSUE TITLE
Integrate GTM Tag

### ISSUE THREAD

**Issue by sunnyjindal** [the-canonizer/Canonizer-Beta--Issue-Tracking#228]
Need the GTM In all pages:

<script async src="https://www.googletagmanager.com/gtag/js?id=G-HKYLGCPPDC"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-HKYLGCPPDC');
</script>

**Comment by sunnyjindal** [comment]
@ks-rahul please see if this can be done before the deployment tomorrow (22nd). Otherwise we will need to raise the hotfix for this as this is quite urgent.

**Comment by ks-rahul** [comment]
verified on staging
