### ISSUE TITLE
Getting error "Something went wrong" in below case

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#23]
Steps to reproduce : 
1. Login with User A ,create topic, User A is supporter of Agreement camp
2. Login with User B and delegate support to User A
3. Login with User C and delegate support to User B
4. Login with User D and delegate support to User C
5. Stay on same page(topic detail) with User's D login- Browser- 1
6. Open same topic in another browser- 2 and Login with User B
7. Remove support
8. Go to Browser- 1- try to delegate support to User B without refreshing page 
9. Click on Submit

Actual Result : Getting error "Something went wrong" 

![image](https://user-images.githubusercontent.com/40416610/203929974-555e01e5-3f94-4978-8e36-db46ede1e656.png)

**Comment by rupalichavan9860** [comment]
Simple case : 
1. Login with User A and support Agreement camp(Browser 1)
2. Login with User B and support Agreement camp(Browser 2)
3. Login A- remove support
4. Login B screen - do not refresh and try to delegate

**Comment by rupalichavan9860** [comment]
@sunnyjindal User is trying to delegate support to user who already removed their support from camp. Can you please provide content for this?

**Comment by nalwa** [comment]
@rupalichavan9860  do we have content for same scenario on 2.O?

**Comment by nalwa** [comment]
@sunnyjindal  for now message i have added is **"This user Doesn't have support in this camp, so you can not delegate your support to this user."**

after you will verify i will raise The PR for same.

**Comment by sunnyjindal** [comment]
You cannot delegate your support to the user as the selected user is not an active supporter of this camp.
@nalwa

**Comment by rupalichavan9860** [comment]
Verified
