### ISSUE TITLE
Statement is a required field on the statement page, but it accepts empty spaces.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#234]
Steps to reproduce : 
1. Create topic
2. Click on Add Camp Statement 
3. Just click in Statement filed- Submit update button will get enabled 
4. Click on "Submit Update"

Expected Result : It should show error message "Statement  is required"

Actual Result : It is getting saved with blank data

![image](https://user-images.githubusercontent.com/40416610/227633444-26db582b-77bf-49a9-8f28-34e1b0acdecf.png)

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by hassaanCD** [comment]
Working fine on production



![Image](https://user-images.githubusercontent.com/120023458/231419872-64752b2e-4423-4dd6-995c-46e1739fd319.png)
