### ISSUE TITLE
Camp Forum : "Replies" and "Last Updated On" columns are not visible on mobile device

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#235]
Please refer attached screenshot : 

Mobile Browser : 
![image](https://user-images.githubusercontent.com/40416610/228429019-30ac8aad-9f38-4a61-b26b-107355af05c8.png)

Following columns are not visible

![image](https://user-images.githubusercontent.com/40416610/228428947-383c36c9-cef4-4347-ae8b-af124b1cb03c.png)

**Comment by hassaanCD** [comment]
Fixed



![Image](https://user-images.githubusercontent.com/120023458/229747319-9fb6d2a6-3f49-4269-b866-5e618513b8a4.png)

**Comment by hassaanCD** [comment]
Verified on production



![Image](https://user-images.githubusercontent.com/120023458/231389640-62e6408e-e852-4dcd-bcf1-6021fc1771eb.png)
