### ISSUE TITLE
Include Review filter : In review camp name is not showing on topic detail page 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#236]
Steps to reproduce : 

1. Login with User A and create topic and create camp "camp 1"
2. Create sub camp "sub camp 1"
3. Login with User B and change camp name to " camp 1 in review test 1" from "camp 1"
4. Click on Sub camp "sub camp 1" in a tree
5. Select "Include Review"
6. Observe camp name 

Actual Result : In review camp name is not showing at all places
Please refer attached screenshot : 
![image](https://user-images.githubusercontent.com/40416610/228558488-125b7159-6a3a-4f91-8a83-c2433656d2d7.png)

Expected Result : It should show in review camp name

**Comment by array-junkie** [comment]
@rupalichavan9860 Working fine on staging.

**Comment by sajid315** [comment]
@rupalichavan9860 
I have raised the PR for this issue and tested on my local.



![Image](https://user-images.githubusercontent.com/111273633/231094153-33912da1-2c7f-4b7f-9868-d10ec0d2a204.png)
