### ISSUE TITLE
User is not able to upload more than one file at a time

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#237]
Please refer screenshot : 

![image](https://user-images.githubusercontent.com/40416610/228645316-660a53b2-0f93-4e93-9165-0d3ec6b232e5.png)

But User is not able to upload more than one file at a time

**Comment by ks-rahul** [comment]
@rupalichavan9860 I have uploaded four and five files on the staging and it's working fine. please let me know if Is there any particular scenario? that you are facing on bulk upload.

![Image](https://user-images.githubusercontent.com/95217406/228742817-8a42ac1f-fe7e-4853-827e-d7fdf4361820.png)

**Comment by rupalichavan9860** [comment]
Working fine now
