### ISSUE TITLE
In mobile view, need to set the position of "Only my Topics" check box .

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#238]
Steps to reproduce:

1. In mobile, open the safari browser. 
2. Enter the URL of the application (https://canonizer3.canonizer.com) in browser.
3. Login with any user and click on browse.
 check box "Only my Topics" should be placed under the search field "search by topic name".

Expected Result: In mobile view, check box "Only my Topics" should be placed under the search field "search by topic name".
Actual Result: Now it is placed under the "Select Namespace" label.

![A9C4369A-CDE0-4B95-97D9-9C0669AAC50B](https://user-images.githubusercontent.com/129028750/228757550-f3c12126-b95c-4150-870c-c027a7b7a87d.jpg)

**Comment by SandeepTalentelgia** [comment]
Not fixed- Its working as previous, I have verified in the iPhone 14. Refer screenshot.

![Image](https://user-images.githubusercontent.com/129028750/230277835-a78877de-fd63-4f8e-9197-234388d933cc.jpg)

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
