### ISSUE TITLE
In mobile view, need to apply "logo or name of the application " on the top of the left Manu. 

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#239]
Steps to reproduce:

1. In mobile, open the safari browser.
2. Enter the URL of the application (https://canonizer3.canonizer.com) in browser.
3. Login with any user and click on top right toggle.

Expected Result: In mobile view, need to apply "logo or name of the application" on the top of the left Manu or we can open the Manu under the header and give some colour as in the web.

Actual Result: Now it shows the Manu simple in white colour, without logo or name of the application.

![EDAC347A-1522-4EDF-8207-5B0A23B1495C](https://user-images.githubusercontent.com/129028750/228767502-72cd3b3c-578a-487f-aba2-a01d00181d48.jpg)

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
