### ISSUE TITLE
In mobile view need to apply icons for 1. Account Setting   2. Supported Camps    3. Log Out

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#240]
Steps to reproduce:

1. In mobile, open the safari browser.
2. Enter the URL of the application (https://canonizer3.canonizer.com) in browser.
3. Login with any user and click on top right toggle.

Expected Result: In mobile view, icons for the following modules should be applied as in web.
1. Account Setting   2. Supported Camps    3. Log Out

Actual Result: Now it shows the modules without icons.

![EDAC347A-1522-4EDF-8207-5B0A23B1495C](https://user-images.githubusercontent.com/129028750/228768853-38e87a47-b141-4ecb-b7e1-52e5f0a1d53b.jpg)

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
