### ISSUE TITLE
Notification count (On bell icon) should be automatically removed if user visit the notification screen by clicking on "view all" link.

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#241]
Steps to reproduce:

1. Login with any use, having multiple notifications.
2. Click on the bell icon in the header and then click on "view all" notification link.

Expected Result: it should mark all the notification as "viewed" and reduce the notification count accordingly.
Actual Result: Now user need to click on each and every notification one by one.

**Comment by ashish76** [comment]
I had a discussion regarding this issue, at the time of developing this feature we considered that we will show the count of unread messages. I am assuming that both "Seen" & "Read" are two different features.

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
