### ISSUE TITLE
On the Camp tree screen, need to set the design.

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#243]
Steps to reproduce:

1. Login with any user.
2. Click on browse and select sandbox testing in "namespace" field.
3. select the check box of "only my topics".
Expected Result: There should be a space between the text "Camp Tree" and "Event Line" link.
Actual Result: Now it can't show any space between text "Camp Tree" and "Event Line" link.

![screenbud-fb8eea00-439a-4358-8779-ec672b3c8b91](https://user-images.githubusercontent.com/129028750/228816101-16f5166d-9d60-48dd-8b9b-98ae2508b6a6.png)

**Comment by hassaanCD** [comment]
Fixed



![Image](https://user-images.githubusercontent.com/120023458/229744392-7de2b946-5fd1-4e8d-8147-d5fd4a18fbae.png)

**Comment by SandeepTalentelgia** [comment]
Closed
