### ISSUE TITLE
Need to apply some padding to the support count of Topics and Subcamps.

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#244]
Steps to reproduce:

1. Login with any user.
2. Click on browse and select sandbox testing in "namespace" field.
3. Select the check box of "only my topics".
4. Click on any topic or camp.

Expected Result: There should be a padding on the right side of the support count.
Actual Result:  Now it can't show the padding on the right side of the support count.

![screenbud-fb8eea00-439a-4358-8779-ec672b3c8b91](https://user-images.githubusercontent.com/129028750/228819206-3be33045-1a7d-43ea-a766-64dbb1872f35.png)

**Comment by rupalichavan9860** [comment]
This is working fine so closing this
