### ISSUE TITLE
Issue on Create new camp page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#245]
Steps to reproduce : 
1. Create topic 
2. Click on "Create New Camp" or "Start new supporting camp here"
3. Observe create new camp page

Actual Result : Camp name Agreement is missing in bread crumbs and NaN showing in Parent camp drop down

Please refer attached screenshot : 
![image](https://user-images.githubusercontent.com/40416610/228862135-3773f497-4347-4db9-afd3-a838da3ce238.png)

**Comment by rupalichavan9860** [comment]
and getting error below while creating camp : 

![image](https://user-images.githubusercontent.com/40416610/228863076-92b486d6-eeb4-47b6-89b3-670b101f3c93.png)

**Comment by ks-rahul** [comment]
@rupalichavan9860 could you please check this ticket now? this ticket look like duplicate https://github.com/the-canonizer/canonizer-3.0-frontend/issues/906.

**Comment by rupalichavan9860** [comment]
Yes @ks-rahul

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
