### ISSUE TITLE
Event Line : For Algorithms other than "One Person One Vote," the score is blank.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#246]
Please refer attached screenshot : 

![image](https://user-images.githubusercontent.com/40416610/228895467-b008906d-dd32-4065-9db8-0d8351a82020.png)

Event Time : 
![image](https://user-images.githubusercontent.com/40416610/228895616-5e515c43-c6e2-4097-9a01-9dbbeaed7cc1.png)

**Comment by rupalichavan9860** [comment]
Event line is working only for first 3 algorithms.

**Comment by sunilspr7** [comment]
@karun0607gautam  In canonizer service , added this algoriths function. So I'll use this.

**Comment by rupalichavan9860** [comment]
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/bfbac9ee-6dae-4347-9054-ffa15add9e0a)

**Comment by rupalichavan9860** [comment]
Not working
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/a21d1e46-7a26-41c9-825d-a384fce54e73)

**Comment by rupalichavan9860** [comment]
Scores are blank when a user selects an algorithm for the first time, and the entire hierarchy and score is displayed after a reload. 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/12c8c59e-39c5-4408-acda-9dce9b644c68)

on reload : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/e473641d-cd97-4eb2-926b-60d5360e6345)

**Comment by sunilspr7** [comment]
@karun0607gautam let me know when are you avaialbe for this issue. Because I have fixed this issue but server need to run script. 

@rupalichavan9860 I have already explaind this. If History saved script not runned then I added script that run same time so it is take time.

**Comment by sandeeptlgt** [comment]
Closed
