### ISSUE TITLE
Event Line : Layout issues

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#247]
Please refer attached screenshot : 
![image](https://user-images.githubusercontent.com/40416610/228896240-874d6c4b-f24f-44ad-a9e4-028e5e88f0ef.png)

**Comment by shahab-ramzan** [comment]
@rupalichavan9860 this issue is fixed and deployed on staging. Please verify

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by sandeeptlgt** [comment]
Closed, verified on live.

**Comment by rupalichavan9860** [comment]
Working fine on live
