### ISSUE TITLE
Event Line: When someone adds support, the score on the event line page is not changed.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#248]
Please refer attached screenshot : 
Topic Detail Page : 

![image](https://user-images.githubusercontent.com/40416610/228974260-7f4e3ef1-5f02-4055-9dcc-a02b98fc326a.png)

Event Line Page : 
![image](https://user-images.githubusercontent.com/40416610/228974311-c8308952-2b7a-4348-8505-f61b78f4dd97.png)

**Comment by hassaanCD** [comment]
Fixed



![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/120023458/96027770-0032-4924-8438-24560e1c48f7)


After adding support

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/120023458/585ec176-487c-4559-a8f5-280f1de9a352)
