### ISSUE TITLE
Event Line : Console error

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#249]
Steps to reproduce : 
1. Create topic 
2. Click on "Event Line"
3. Observe console for errors

Getting below console error : 
![image](https://user-images.githubusercontent.com/40416610/228976500-6d3549dc-182a-4781-abb2-f313bd0def24.png)

**Comment by shahab-ramzan** [comment]
PR raised https://github.com/the-canonizer/canonizer-3.0-frontend/pull/914

**Comment by hassaanCD** [comment]
Fixed

**Comment by rupalichavan9860** [comment]
Working fine on staging
