### ISSUE TITLE
On the supported camps page, the camp name appears twice.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#250]
Steps to reproduce : 
1. Create Topic (User is supporter of Agreement camp)
2. Click on Even Line
3. Click on "Back"
4. Click on Manage Support 
5. Observe page

Actual Result : The camp name appears twice.
![image](https://user-images.githubusercontent.com/40416610/228976839-7cc3cbe4-c562-43c0-85e3-7b9f583a9fe1.png)

**Comment by hassaanCD** [comment]
Fixed



![Image](https://user-images.githubusercontent.com/120023458/229760134-06c28385-e7ac-4334-ac4d-3e5c840adda5.png)

**Comment by sajid315** [comment]
Due to disabling event line button, this ticket moved back by @hassaanCD.

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Working fine on live
