### ISSUE TITLE
Camp Thread Must Be Sorted Based on Last updated timestamp of reply.

### ISSUE THREAD

**Issue by gautamv16** [the-canonizer/Canonizer-Beta--Issue-Tracking#251]
Camp Thread Must Be Sorted Based on Last updated timestamp of reply.

https://canonizer.com/forum/88-Theories-of-Consciousness/1-Agreement/threads
![ticket1](https://user-images.githubusercontent.com/6199964/229049357-6ba1f46d-237a-4297-a5da-4e60447e573a.png)

**Comment by rupalichavan9860** [comment]
@ashish76 Not Working. Please refer screenshot attached

![image](https://user-images.githubusercontent.com/40416610/229825826-c3b072fa-03f1-44d2-ada7-108b26f83163.png)

**Comment by rupalichavan9860** [comment]
@ashish76 Still facing the same 

![image](https://user-images.githubusercontent.com/40416610/233170654-561d68c0-6fa9-4edd-a082-430bb07a92c1.png)

**Comment by subhancd** [comment]
not fixed on development server


![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/f59b816b-f03b-44bc-95fa-4e09a6cf788a)

**Comment by kshitij1326** [comment]
@subhancd  the issue has been resolved and PR is merged on development server, could you please test it again.

**Comment by rupalichavan9860** [comment]
Working fine on both staging and live
