### ISSUE TITLE
As of Date filter issues

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#252]
"Rupali C" have created below topic on "30 March 2023, 05:59:36 PM" and "Rupali C" was direct supporter

https://canonizer3.canonizer.com/topic/2030-Event-Line/1-Agreement

Current Tree : "Rupali C" removed support on "31 March 2023"

![image](https://user-images.githubusercontent.com/40416610/229136135-3e23d506-e8bf-46f8-ab87-29f2133dbf7e.png)

Then applied As of Date filter "2023-03-30"

It should show "Rupali C"'s support 

Currently it is showing "Rupali C" as a supporter when As of date selected as "2023-03-29"

![image](https://user-images.githubusercontent.com/40416610/229136596-d65b6195-01e2-4245-8af5-d766d7fba308.png)

**Comment by rupalichavan9860** [comment]
And camp name is blank 

![image](https://user-images.githubusercontent.com/40416610/229137216-acc5b581-bef8-4f3c-98fe-558c93c7c5cf.png)

**Comment by sajid315** [comment]
@rupalichavan9860 i did the same steps here below,

https://canonizer3.canonizer.com/topic/2059-TopicTest3April/1-Agreement
1- I created a new topic on 3 april.
2- By default my support was there as count 01.

And on 4th april i removed my support from this topic as you can see also in activties panel. Now when i applied filter of 03 April its showing me the Tree with support.

![Image](https://user-images.githubusercontent.com/111273633/229712894-df30811e-9798-4433-91c4-1aa2bc3df0da.png)


And on 02 April its showing me that topic is created on 3rd april that is correct. 

![Image](https://user-images.githubusercontent.com/111273633/229713145-d86a6427-9be3-4494-87cf-197596b2e6d3.png)

**Comment by rupalichavan9860** [comment]
@sajid315 I still have the same problems. In a call, I'll explain a problem to you.

**Comment by sajid315** [comment]
@rupalichavan9860 
I checked this issue on my end but unfortunately its not giving me point that mentioned in this below screen-cast. 
https://www.loom.com/share/465c53f7759f4c4c9f954e268fb92d94



![Image](https://user-images.githubusercontent.com/111273633/232744511-e2ce914a-8be4-48df-93fb-87639b9b2266.png)

**Comment by rupalichavan9860** [comment]
@sajid315 The root of this issue was found. 
Refer to the steps below: 
1. Go to the Date and Time settings.
2. Choose the region "United States"
3. Choose one of the three USA time zones: Mountain Time (USA & Canada), Central Time (USA & Canada), or Eastern Time (USA & Canada).
4. Go to https://canonizer3.canonizer.com/
5. Select any topic.
6. Make As of Date the earlier date than the topic's creation date. 
7. Observe camp name on topic detail page 

Actual Result : Camp name is blank

**Comment by sajid315** [comment]
@rupalichavan9860  I am verifying this issue from backend side, meanwhile i am checking it from backend that why its returning tree when not created. 
Made a frontend ticket for this issue as well. 
https://github.com/the-canonizer/canonizer-3.0-frontend/issues/967

**Comment by sajid315** [comment]
PR raised and tested on my local.

**Comment by rupalichavan9860** [comment]
Verified and working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
