### ISSUE TITLE
 Need to set the design of "Direct Supported Camps" and "Delegated Support Camps" screens in iPad.

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#253]
Steps to reproduce:

1. Login the application in iPad with any user.
2. Open Supported Camps from top right dropdown.
3. Click on "Direct Supported Camps" and "Delegated Support Camps".
Expected Result: It should show the design as shown in web.
Actual Result: It shows the distracted design for both modules.

![ipad design1](https://user-images.githubusercontent.com/129028750/229479372-e8a6f685-cb3d-46e7-a3d8-5418ae5a84dc.jpeg)
![ipad design](https://user-images.githubusercontent.com/129028750/229479427-ae53ea45-ba19-421d-98f6-9dca350e9de2.jpeg)

**Comment by vikasranatalentelgia** [comment]
@rupalichavan9860 its working

**Comment by rupalichavan9860** [comment]
@vikasranatalentelgia Working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
