### ISSUE TITLE
Suggestion - In iPad, need to show the "Account setting", "Supported Camps" and "Logout" fields in left menu.

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#254]
Steps to reproduce:

1. Login the application in iPad with any user.
2. Click on the top right toggle.
3. Check the fields in left menu.
Expected Result: It should show the "Account setting", "Supported Camps" and "Logout" fields in left menu or we can show as in web.
Actual Result: It can't show the "Account setting", "Supported Camps" and "Logout" in left menu.
![ipad image](https://user-images.githubusercontent.com/129028750/229483923-9104304a-e49a-4e9e-b17c-d2fb8abd5555.JPEG)

**Comment by vikasranatalentelgia** [comment]
@SandeepTalentelgia  "Account setting", "Supported Camps" and "Logout" fields are under profile icon in iPad
![image_2023_04_04T06_11_29_870Z](https://user-images.githubusercontent.com/98095849/229704124-6f46babf-2005-4cd1-932e-78d4eed02b7b.png)

**Comment by rupalichavan9860** [comment]
Not an issue
