### ISSUE TITLE
In mobile view (ios), it can't close the left menu if user click on "Account setting" and "Supported Camps".

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#255]
Steps to reproduce:

1. Login the application in mobile view with any user.
2. Click on the top right toggle to open the left menu.
3. Check on the "Account setting" or "Supported Camps" link.
Expected Result: It should redirect the user to the "Account setting", or "Supported Camps" and close the left menu.
Actual Result: It can't close the left menu if user try to open "Account setting", or "Supported Camps".

![EDAC347A-1522-4EDF-8207-5B0A23B1495C](https://user-images.githubusercontent.com/129028750/229488427-c695e37c-b9c5-44f2-980e-cc95518a5f6f.jpg)

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
