### ISSUE TITLE
In mobile view, need to give some space between "Direct supported camp" and "Delegated support camp" button.

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#256]
1. Login the application in mobile view with any user.
2. Click on the top right toggle to open the left menu.
3. Check on the "Account setting" and open supported camps.
Expected Result: It should show some space between "Direct supported camp" and "Delegated support camp" button.
Actual Result: It can't show some space between "Direct supported camp" and "Delegated support camp" button. but it shows when user click on "Delegated support camp" button. 
![mobile imge](https://user-images.githubusercontent.com/129028750/229490298-8803feda-5857-4d44-a80a-a2d6b41ddfed.jpg)

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
