### ISSUE TITLE
On the Camp History Comparison, "Camp Archived" should be added. 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#257]

**Comment by rupalichavan9860** [comment]
@vikasranatalentelgia I can see this on a comparison page, but the spelling on the history page is "Camp Archived," while it is "Camp archive" on the comparison page. It should be the same everywhere.

![image](https://user-images.githubusercontent.com/40416610/236309162-13d3c876-015a-4da1-badf-f7d296453b91.png)

History page : 
![image](https://user-images.githubusercontent.com/40416610/236309279-2eb83815-3bb3-42b5-a948-26422f3c19db.png)

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by SandeepTalentelgia** [comment]
Closed , verified on live.
