### ISSUE TITLE
Live and Staging : 404 Page Not Found error on Sitemap

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#258]
Please refer attached screenshot : 

![image](https://user-images.githubusercontent.com/40416610/230164238-81cca120-c5c6-4fcc-8af1-01850f2673d2.png)

**Comment by ks-rahul** [comment]
@rupalichavan9860 sitemap code is directly deployed on the production. that's why it's not working on the staging.

**Comment by rupalichavan9860** [comment]
Getting the same error on live also

**Comment by ks-rahul** [comment]
@rupalichavan9860 Due to a dependency on the archive functionality, there is a 404 error displayed on the live version.

**Comment by ashish76** [comment]
@rupalichavan9860 Page not found issue on the production environment is gone. In staging the code is not deployed. Because this is a hotfix so we directly raise the PR for production.

**Comment by ashish76** [comment]
@akuks How can we put the site map-related code into staging? We raised the PR for production and it got merged and deployed on the production server. I think we need to rebase the staging branch. Please suggest.

**Comment by rupalichavan9860** [comment]
Working fine on live so closing this
