### ISSUE TITLE
Connecting line from topic to camp is missing

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#26]
refer screenshot : 
![image](https://user-images.githubusercontent.com/40416610/203957369-ea863044-c4bc-402c-8a7a-9bdf4077130d.png)

FROM JIRA : 
https://canonizer.atlassian.net/jira/software/projects/CAN/boards/3/backlog?issueType=10011%2C10015&selectedIssue=CAN-1380

**Comment by hassaanCD** [comment]
Fixed



![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/120023458/6fc1ac22-baa6-4f9a-98e1-64d5bc9f67a3)

**Comment by rupalichavan9860** [comment]
Verified on live
