### ISSUE TITLE
Need to set the design of "Delegated support camp" screen, in iPad.

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#261]
Steps to reproduce.

1. Login the application in iPad by using safari browser.
2. Open the "supported camps" screen and click on Delegated support camp.
Expected Result: It should show the "reset" and "search by topic name" field on correct position as shown in web.
Actual Result: It shows the disturbed view. refer screenshot
![ipad2](https://user-images.githubusercontent.com/129028750/230545490-5c232469-3c7a-41ef-9188-ff71b31209ba.jpg)

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
