### ISSUE TITLE
Need to fix the position of "search by topic name" and reset button in iPad.

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#262]
Steps to reproduce.

1. Login the application in iPad by using safari browser.
2. Open the "supported camps" screen and click on Direct supported camp.
3. Now c
![ipad1](https://user-images.githubusercontent.com/129028750/230546004-45789ea6-995b-4143-aedd-ef53dbef1b78.jpg)
lick on the top right toggle to open the left menu.
Expected Result: It should show the "reset" and "search by topic name" field on correct position as shown in web.
Actual Result: It shows the disturbed view. refer screenshot

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
