### ISSUE TITLE
On the update page, the text below the image is missing.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#263]
Please refer below topic : 
https://canonizer.com/statement/history/27-sandbox-practice-topic/1-Agreement

Update page : 

![image](https://user-images.githubusercontent.com/40416610/230818701-351a07ce-ae33-45ad-a306-8f49c5fe1a4c.png)

Below highlighted text is missing : 

![image](https://user-images.githubusercontent.com/40416610/230818776-32fa46b4-9ea1-44ca-be4c-b9fec4ba1a7b.png)
 

Note: Text is visible after deleting the image.

**Comment by rupalichavan9860** [comment]
Not working

**Comment by vikasranatalentelgia** [comment]
@rupalichavan9860 Please check now

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Working fine on live
