### ISSUE TITLE
Issues on videos page 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#267]
When I refresh the page, I get the following console errors. 
Please refer screenshot : 

![image](https://user-images.githubusercontent.com/40416610/231285451-97aa921d-6458-46fd-abcc-ef10e805a2b2.png)

![image](https://user-images.githubusercontent.com/40416610/231285635-cd178f17-7068-4bdd-bc4e-d32f5a2846be.png)

**Comment by rupalichavan9860** [comment]
On staging below video is not playing : 
https://canonizer3.canonizer.com/videos/consciousness?chapter=the+world+in+your+head&format=360

![image](https://user-images.githubusercontent.com/40416610/231286189-84c2d09a-7fe4-4f25-a953-ff8be12841f6.png)

**Comment by ks-rahul** [comment]
@rupalichavan9860 This video https://canonizer3.canonizer.com/videos/consciousness?chapter=the+world+in+your+head&format=360 is not available on the staging that's why it's not playing. @akuks could you please check and upload the missing video and .vtt file?

**Comment by ks-rahul** [comment]
@rupalichavan9860 The console error is visible due to Chrome's discontinuation of autoplay video on page load. To enable video playback, either the video must be muted prior to playback, or the user must manually initiate playback by clicking the play button after the page has fully loaded. 

please suggest which option is required.

**Comment by ashish76** [comment]
Based on the discussion we had on the weekly call, it is decided that we will not allow Autoplay for any browser. The user will click on the play button to play the video.

**Comment by rupalichavan9860** [comment]
Working fine now 
But below video is still not working as it is not available on staging 
@akuks Can you please check and update 

![image](https://user-images.githubusercontent.com/40416610/233168123-985cccce-f82f-4dab-bd20-7b7781fa6f5e.png)

**Comment by rupalichavan9860** [comment]
@ashish76 @ks-rahul Videos are working fine now but still getting below console errors. Can you please check ?

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/5fd0a09b-68ad-433c-9fc5-03caacac8c44)

**Comment by ks-rahul** [comment]
Hi, @akuks could you please check this video subtitle file?  **canonizer3.canonizer.com/subs/The_world_in_you_head.vtt**

**Comment by ashish76** [comment]
@akuks Could you please upload the .vtt file of the video (https://canonizer.com/videos/consciousness?chapter=the+world+in+your+head&format=360)?

**Comment by ashish76** [comment]
@shahab-ramzan I think you had a discussion with @ks-rahul in this issue. Is there any update on this?

**Comment by shahab-ramzan** [comment]
@ashish76  We don't have vtt file for this video. @akuks can you please confirm?

**Comment by ashish76** [comment]
@ks-rahul Please coordinate with @akuks and get it done.
