### ISSUE TITLE
Mails: Topic owner doesn't get any email on  removing support from camps

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#27]
Steps to reproduce:

Case 2:

1. user A creates a topic
2. 
3. user A creates a camp
4. 
5. user A adds support in the camp
6. 
7. user A removes support from the camp

Actual Result:

user A doesn’t get any email on removing support

Email in 2.0:
![image](https://user-images.githubusercontent.com/104552751/203958949-66e45930-8e8e-4462-8a3a-32d0e5970e57.png)

**Comment by rupalichavan9860** [comment]
Working fine
