### ISSUE TITLE
Each update should have a one-hour grace time before being submitted and being recorded in history.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#270]
Currently, there is no grace period if there are no supporters.

Expected  : 
1. It should have a one-hour grace time before being submitted and being recorded in history.
2. No object buttons or anything, till it is committed to history.

**Comment by array-junkie** [comment]
@rupalichavan9860  
"Currently, there is no grace period if there are no supporters"

Do we have to show grace period hour to every user(supporter or non supporter) or if there is no supporter at all on a topic?

**Comment by rupalichavan9860** [comment]
Yes @M-Darab Each submission should have a one-hour grace period, whether there are supporters or not.

**Comment by array-junkie** [comment]
PR Raised: https://github.com/the-canonizer/canonizer-3.0-api/pull/649

**Comment by sajid315** [comment]
Above PR closed before merge because there is one PHP unit test case is failing at back-end. @M-Darab  We need to resolve it.

**Comment by array-junkie** [comment]
Now test cases are working

https://github.com/the-canonizer/canonizer-3.0-api/pull/653

**Comment by array-junkie** [comment]
Parent change scenarios are not working - this could be due to a new change (https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/issues/270) ~ @rupalichavan9860

**Comment by array-junkie** [comment]
It is fixed in PR [#673](https://github.com/the-canonizer/canonizer-3.0-api/pull/673)

**Comment by rupalichavan9860** [comment]
Functionality is implemented and will log issues separately if any

**Comment by rupalichavan9860** [comment]
Working fine on live
