### ISSUE TITLE
When we search anything in "only my topics", a suggestion list should appear under the search field.

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#271]
Steps to reproduce:

1.Login with any user.
2. Click on browse and select sandbox testing in "namespace" field.
3. Try to search any topic/camp in the search field of "only my topics".

Expected Result: There should be a suggestion list under the search field.
Actual Result: Now it can't show the suggestions.

https://prnt.sc/0dR2qC_2peqr

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by SandeepTalentelgia** [comment]
Closed

**Comment by SandeepTalentelgia** [comment]
Closed, verified on live

**Comment by rupalichavan9860** [comment]
Verified on live
