### ISSUE TITLE
If we type anything in "only my topics", and refresh the page, then there is a cross functionality which is going to hide after that.

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#272]
Steps to reproduce:

1.Login with any user.
2. Click on browse and select sandbox testing in "Select Canon" field.
3. Try to search any topic/camp in the search field of "only my topics" and press enter.
4. Refresh the screen.

Expected Result: After refresh the screen, cross icon in the search field should be present as before.
Actual Result:  After refresh it hide the cross icon from the search field.

https://drive.google.com/file/d/1x_8Ibj_b6DkESTCqBeXq4VN9jLTXtxnM/view

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by SandeepTalentelgia** [comment]
Not Fixed, Verified over the live server.

**Comment by subhancd** [comment]
fixed. verified on development server.
