### ISSUE TITLE
If we pass space after the topic full name in the search field, then it is not working properly. So need to trim the traling space

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#273]
Steps to reproduce:

1.Login with any user.
2. Click on browse and select sandbox testing in "Select Canon" field.
3. Try to search any topic/camp in the search field of "only my topics" and press space after the topic full name in the search field.

Expected Result: It should trim the trailing space and show the search result.
Actual Result: Now it can't trim the trailing space and show "No data"

https://drive.google.com/file/d/1x_8Ibj_b6DkESTCqBeXq4VN9jLTXtxnM/view

**Comment by rupalichavan9860** [comment]
@vikasranatalentelgia This works for a single keyword, however it fails when I try to search for a topic containing more than one word.

Please refer attached screenshot : 

![image](https://user-images.githubusercontent.com/40416610/233165532-76ebe897-de6a-4b50-871f-3cfd97520539.png)

I am trying to search "Hard Problem"

![image](https://user-images.githubusercontent.com/40416610/233165703-156cd621-e16b-4d52-9ac1-6d31b2df0b73.png)

**Comment by rupalichavan9860** [comment]
Working fine now

**Comment by SandeepTalentelgia** [comment]
Closed

**Comment by SandeepTalentelgia** [comment]
Closed, Verified over the live server.

**Comment by rupalichavan9860** [comment]
Verified on live
