### ISSUE TITLE
Topic name should be shown in one line.

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#274]
Steps to reproduce:

1.Login with any user.
2. Click on browse and select sandbox testing in "Select Canon" field.
3. Try to search any topic/camp in the search field of "only my topics" and click on the topic/ camp name to open the details.
4. Open topic history / camp history, check for all types like - live, objected, not live and old.

Expected Result: Topic name/ Camp name should be shown in single line.
Actual Result: Now it show the Topic name/ Camp name below the title.

https://prnt.sc/WpAGDPRdJ9Nt

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
