### ISSUE TITLE
In iPhone device, There should be some space in between the Quick actions, "remove all" and "clear all changes" button.

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#275]
Steps to reproduce:

1.Login with any user in the iPhone 14pro by using safari browser.
2. Click on browse and select sandbox testing in "namespace" field.
3. Open any topic/camp and click on Directly join and support button.

Expected Result: there should be a space between the quick actions, remove all check box and clear all changes button.
Actual Result: Now it can't show any space between the quick actions, remove all check box and clear all changes button.

https://drive.google.com/file/d/1huxsJpWTpts3GeTwylKGOlIiCMueMOaj/view

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
