### ISSUE TITLE
In mobile view  "Topic History" Submitter nickname, and live time should be in the same line.

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#276]
Steps to reproduce:

1.Login with any user in the iPhone 14pro by using safari browser.
2. Click on browse and select sandbox testing in "namespace" field.
3. Open any topic/camp and open topic history screen

Expected Result: "Topic History" Submitter nickname, and live time should be in the same line.
Actual Result: Now it show "Topic History" Submitter nickname, and live time data in 2 lines.

https://drive.google.com/file/d/1OP2QgOWnOkGyzoDF5bSVd5WbLZQqdrfQ/view

**Comment by SandeepTalentelgia** [comment]
Not Fixed

![Image](https://user-images.githubusercontent.com/129028750/233264751-4f72ff69-4b29-4c3c-9144-628985b18c32.png)

**Comment by ks-rahul** [comment]
@SandeepTalentelgia could you please explain more about it what is not fixed In this ticket. as per this ticket I fixed this.



![Image](https://user-images.githubusercontent.com/95217406/233266192-accade40-0b55-4717-9ff8-72a0ba48be88.png)

**Comment by SandeepTalentelgia** [comment]
@ks-rahul Can we set all the 4 labels with different colours, in a single line as shown in web, for consistency.  refer screenshot.

![Image](https://user-images.githubusercontent.com/129028750/233269857-142e3636-d6b6-41ae-8bc9-bf25ccb4aee3.png)

**Comment by ks-rahul** [comment]
@SandeepTalentelgia  in mobile view does not have enough space to show this in one line

**Comment by rupalichavan9860** [comment]
Closing this

**Comment by SandeepTalentelgia** [comment]
Closed, As per the @ks-rahul comment, "in mobile view does not have enough space to show this in one line"
