### ISSUE TITLE
On iphone device, when we try to add a camp statement, design overlaps with each other.

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#277]
Steps to reproduce:

1.Login with any user in the iPhone 14pro by using safari browser.
2. Click on browse and select sandbox testing in "namespace" field.
3. Open any topic/camp and try to add Camp statement.

Expected Result: On camp statement, history screen, need to set the design.
Actual Result: Now it show design overlaps with each other.

https://drive.google.com/file/d/17XuaD70VLBKyrDIne2pQdXfrTSxBaSca/view

**Comment by rupalichavan9860** [comment]
@ks-rahul Can you please check below screenshot 

![image](https://user-images.githubusercontent.com/40416610/233200026-c86280c8-8c76-4571-871d-ac85b3464803.png)

**Comment by SandeepTalentelgia** [comment]
working fine

**Comment by rupalichavan9860** [comment]
Verified on live
