### ISSUE TITLE
When using As of date filter as a date earlier than the topic created date, the topic creation date link is absent. 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#279]
Please refer attached screenshot : 
![image](https://user-images.githubusercontent.com/40416610/233143370-7200e1f9-9e11-44ba-a0a9-582c7951905b.png)

**Comment by rupalichavan9860** [comment]
@ashish76 @ks-rahul Although a date and a link are available right now, when a user clicks on them, nothing is displayed on the topic detail page.

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/27095ee4-862d-4bfd-bf56-1d3fbfc4b199)

**Comment by ks-rahul** [comment]
@rupalichavan9860 I tried to replicate this issue but was unable to reproduce it. Could we connect once? Let me know what time will be suitable for you.

**Comment by rupalichavan9860** [comment]
Working fine now so closing this
