### ISSUE TITLE
Event line : Remove default text "latest timeline created" from Events section

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#282]
Please refer attached screenshot : 
![image](https://user-images.githubusercontent.com/40416610/233253633-6f280b31-11c0-4d11-9416-a93c6706e264.png)

**Comment by hassaanCD** [comment]
Fixed



![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/120023458/825d438e-7a15-4a46-b766-1db632c1b3e8)
