### ISSUE TITLE
Event Line : The last event is displayed when you click "step forward."

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#284]
It should display the current event at the time.
Please refer attached screenshot : 

![image](https://user-images.githubusercontent.com/40416610/233255046-d5cae803-b1df-4b65-ad57-bd9cf7f8918a.png)

**Comment by hassaanCD** [comment]
Fixed



![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/120023458/8f8f4876-3d22-48c2-b85a-e026ab4d03aa)

**Comment by rupalichavan9860** [comment]
Working fine on live
