### ISSUE TITLE
Event Line : End date is blank for new topics

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#285]
Please refer attached screenshot : 
![image](https://user-images.githubusercontent.com/40416610/233255663-53091de6-93f1-44e0-8424-3275cba7a324.png)

**Comment by rupalichavan9860** [comment]
Working fine for new topics

**Comment by sandeeptlgt** [comment]
Closed, verified on live.

**Comment by rupalichavan9860** [comment]
Working fine on live
