### ISSUE TITLE
In mobile devise, need to show the complete time format of "latest revision as of date" on Topic/camp History Comparison screen.

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#288]
Steps to reproduce:

1.Login with any user in the iPhone 14pro by using safari browser.
2. Click on browse and select sandbox testing in "namespace" field.
3. Open any topic/camp and try to compare 2 topics/ camps
Expected Result: it should show the complete time format as shown in the web, on Topic/camp History Comparison screen.
Actual Result: Now it can't show the complete time format as shown in the web, on Topic/camp History Comparison screen.
![Screenshot (2)](https://user-images.githubusercontent.com/129028750/233267256-d661d3fe-54cf-4dd7-8c37-a994c5e3c12a.png)

**Comment by SandeepTalentelgia** [comment]
Fixed

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by rupalichavan9860** [comment]
Verified on live
