### ISSUE TITLE
Date should be picked from the server rather than the system

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#29]
A user can change the date and time from his/her system and it changes the date in the site. it should pick date from the server.

for example, today is 16th of September. I changed the date from system to 19th September.

![image](https://user-images.githubusercontent.com/40416610/203960673-518d930c-676e-4936-8eb1-fe7c8a03f126.png)
 
From JIRA : 
https://canonizer.atlassian.net/jira/software/projects/CAN/boards/3/backlog?issueType=10011%2C10015&selectedIssue=CAN-1511

**Comment by subhancd** [comment]
the date is disabled but it still shows the date from the system
![Image](https://user-images.githubusercontent.com/104552751/206172104-ebdf0f10-37eb-4c37-84cc-d10564a862f5.png)

**Comment by subhancd** [comment]
as a result if we change the date from system and create a topic. on changing the date back to actual date, it shows score 0

**Comment by subhancd** [comment]
working fine on staging

**Comment by subhancd** [comment]
working fine on beta. @rupalichavan9860 kindly, close the ticket
