### ISSUE TITLE
In mobile devise, need to show the "Recent Activities" at the bottom of the "Support Tree for "-------   " Camp/ topic."

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#290]
Steps to reproduce:

1.Login with any user in the iPhone 14pro by using safari browser.
2. Click on browse and select sandbox testing in "namespace" field.
3. Open any topic/camp and check the position of "Recent Activities"
Expected Result: it should show the "Recent Activities" at the bottom of the "Support Tree for "-------   " Camp/ topic.".
Actual Result: Now it shows the "Recent Activities" at the middle.

![Screen Shot 2023-04-20 at 11 46 30](https://user-images.githubusercontent.com/129028750/233319288-61e315a7-abc5-4ef5-b153-2ea986d74327.png)

**Comment by SandeepTalentelgia** [comment]
Fixed

**Comment by rupalichavan9860** [comment]
Verified on stgaing

**Comment by SandeepTalentelgia** [comment]
Closed, Verified over the live server.
