### ISSUE TITLE
 We need to show a flag with Camp statement, Current topic records and Current Camp records, So that user should aware of any new updation in the respective modules. Now user have to click on manage/ edit button to check the same or by notification.

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#295]
Steps to reproduce:

1.Login with any user into the application.
2. Click on browse and select sandbox testing in "Select Canon" .
3. Open any topic/camp and check the Camp statement, Current topic records and Current Camp records.

Expected Result: It should show the flag with Camp statement, Current topic records and Current Camp records, if their is any update.
Actual Result: Now, to check the update in any module, user should click on the manage/edit button.

https://screenbud.com/s/Jm9Gh65MH3f

**Comment by array-junkie** [comment]
@rupalichavan9860 Will that flag be shown to every user whether that user is a supporter or not, or it will be shown to only supporters of that camp?

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by SandeepTalentelgia** [comment]
Closed, verified on live.

**Comment by rupalichavan9860** [comment]
Implemented on live so closing this
