### ISSUE TITLE
When user refresh the application on the staging server after login then it shows blank "Cross".

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#296]
Steps to reproduce:

1.Login with any user on the staging server.
2. Click on browse and select sandbox testing in "select Canon" field.
3. Open any topic/camp and refresh the application.
4. 
Expected Result: it should not show any blank cross after refresh the screen.
Actual Result: Now it shows the blank cross after refresh the screen.

https://screenbud.com/s/jFziPOyFr16

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by SandeepTalentelgia** [comment]
Fixed

**Comment by rupalichavan9860** [comment]
Working fine on live
