### ISSUE TITLE
On staging server, it can't show topic, camp and nickname. User is unable to submit.

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#297]
Steps to reproduce:

1. Login with any user into the application.
2. Click on browse and select sandbox testing in "Select Canon" field.
3. On supported Camps screen, it can't show topic, camp and nickname. User is unable to submit.
Expected Result: it should show the name of topic, camp and nickname. And allows the user to submit the support.
Actual Result: Now it 
![Screenshot (5)](https://user-images.githubusercontent.com/129028750/233932355-de269336-556f-428f-92d7-43b676873d4e.png)
can't show topic, camp and nickname. User is unable to submit.

**Comment by rupalichavan9860** [comment]
Working fine now

**Comment by rupalichavan9860** [comment]
Working on live
