### ISSUE TITLE
Except for the first three algorithms, the topic list is empty. 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#298]
Please refer attached screenshot :

![image](https://user-images.githubusercontent.com/40416610/234004043-6606698f-f95b-4f4e-b4d1-4033c1bd070f.png)

**Comment by sajid315** [comment]
Migrations was missing, now its working fine. 



![Image](https://user-images.githubusercontent.com/111273633/234561149-27f45b60-5023-461e-9de3-b52430902788.png)

**Comment by rupalichavan9860** [comment]
Yes working fine now

**Comment by rupalichavan9860** [comment]
Working fine on live
