### ISSUE TITLE
Unrelated information on the topic details page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#299]
Please refer attached screenshot : 

![image](https://user-images.githubusercontent.com/40416610/234008254-54f19275-8c7e-4107-a1b4-0fc3f3917e33.png)

**Comment by rupalichavan9860** [comment]
As agreed upon during the meeting As it is informational, it has to have a label demonstrating its functionality.

**Comment by shahab-ramzan** [comment]
@rupalichavan9860  This one issue is fixed in another ticket and deployed on staging. Please verify

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by rupalichavan9860** [comment]
Verified on live
