### ISSUE TITLE
Current Topic Record and Current Camp Record :On the topic detail page, display all of the fields from the history page.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#300]
Current Topic Record and Current Camp Record : 
Display every field from the history page on the topic detail page, as discussed in the meeting.

**Comment by rupalichavan9860** [comment]
Not fixed

**Comment by ks-rahul** [comment]
@rupalichavan9860 please check now.

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
