### ISSUE TITLE
The staging is not working.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#301]
Please refer attached screenshots : 
![image](https://user-images.githubusercontent.com/40416610/234108719-1c15cf32-2741-4cfc-9bf8-b38723b0f051.png)

![image](https://user-images.githubusercontent.com/40416610/234109214-ae32444c-dc04-4185-ae9b-0d22d9907bb8.png)

**Comment by ks-rahul** [comment]
fixed the "client-side exception error" issue that was caused in the "topicsFilter" component where camp archived component I made a change there @vikasranatalentelgia please validate the changes once.

**Comment by rupalichavan9860** [comment]
Working fine now
