### ISSUE TITLE
Canonizer Sorted Camp Tree is empty when selecting first 3 algorithms

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#302]
Steps : 
1. Go to https://canonizer3.canonizer.com/
2. Select any topic and observe Canonizer Sorted Camp Tree 

Actual Result :  Tree is blank
Please refer attached screenshot : 
![image](https://user-images.githubusercontent.com/40416610/234291727-e81cef75-735e-4565-9138-ff3267361470.png)

**Comment by nalwa** [comment]
@rupalichavan9860  issue is fixed. it required some commands to be executed on staging. Now its working fine. 

please verify once at your end.

**Comment by rupalichavan9860** [comment]
@nalwa Yes. Working fine now

**Comment by sajid315** [comment]
@rupalichavan9860 , @nalwa I had a case of Tree missing in specific scenario on staging:
1- Create new topic.
2- Go to Manage/Edit Camp.
3- Add any text in summary and check the archive checkbox, submit that change that will be live. 
4- Now click on Agreement and go back to topic detail page.

Tree is missing on front end. Might b archived but camp tree card is showing.

![image](https://user-images.githubusercontent.com/111273633/235081925-d0f05d77-c52d-420a-9b96-2af0f74202b8.png)

**Comment by rupalichavan9860** [comment]
Working fine on live
