### ISSUE TITLE
Live and Staging : Getting "Something went wrong" message when clicking the Twitter icon

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#303]
Please refer attached screenshot : 
![image](https://user-images.githubusercontent.com/40416610/234419156-5e261a9f-30a3-4cbf-b7ed-1c6ece8ee267.png)

**Comment by ashish76** [comment]
Hi @gautamv16 
Do we have a Twitter account for development purposes? We need the credentials to check this issue. Kindly provide.

**Comment by rupalichavan9860** [comment]
Twitter has been deleted.

**Comment by rupalichavan9860** [comment]
Verified on live
