### ISSUE TITLE
Although the Edit Summary field is optional, the topic update page will not allow you to submit a modification until you enter it.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#304]
Please refer attached screenshot : 
![image](https://user-images.githubusercontent.com/40416610/234424449-2a7595d0-70b4-41b6-ac4a-b577ed2b8426.png)

**Comment by ks-rahul** [comment]
I checked this ticket and its working fine please check.

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
