### ISSUE TITLE
Getting "Something went wrong" error message on camp update 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#305]
Steps to reproduce : 
1. Select any topic and camp
2. Update camp -Click on Camp archive /Single level sub camps only/Disable additional sub camps or enter edit summary 
3. Click on "Submit Update" 

Getting error message "Something went wrong" . Please refer below screenshot :
![image](https://user-images.githubusercontent.com/40416610/234427123-2033f19a-85b5-4dcd-bd9c-fe52f822605f.png)

**Comment by sajid315** [comment]
Issue fixed on local and added default bit as 0 as discussed on call with @nalwa. 
PR needs to be merged.
