### ISSUE TITLE
There should be an as-of link to view the topic at the point in time when this change went live (the date should be this link, after the event description).

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#307]

**Comment by sunilspr7** [comment]
Already added  camp_num value in id parameter  in event Timeline payload. Frontend side @shahab-ramzan added link on event message.

**Comment by sunilspr7** [comment]
Already added  camp_num value in id parameter  in event Timeline payload. Frontend side @shahab-ramzan added link on event message.

**Comment by sunilspr7** [comment]
@rupalichavan9860 I need some discussion on this ticket.

**Comment by sunilspr7** [comment]
@rupalichavan9860 I have added below link.
Here example of topic 88 
Topic and camp create  = https://canonizer3.canonizer.com/topic/88-Theories-of-Consciousness/1-Agreement
Topic and Camp update = https://canonizer3.canonizer.com/topic/history/88-Theories-of-Consciousness ( for topic update)
https://canonizer3.canonizer.com/camp/history/88-Theories-of-Consciousness/53-Biological-naturalism ( for camp update)

Support  =  https://canonizer3.canonizer.com/user/supports/357?topicnum=88&campnum=1&canon=1

**Comment by rupalichavan9860** [comment]
@sunilspr7 All links are redirecting to topic detail page

**Comment by sunilspr7** [comment]
@rupalichavan9860 rest are working. 
@shahab-ramzan 
This is comming empty when I am clicking on event time line message - When create a new topic 
![Screenshot 2023-08-01 124840](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/6298462/b9cdff29-7360-41da-99ac-534f3fe92130)

**Comment by shahab-ramzan** [comment]
@sunilspr7 The above mentioned issue related to invalid data was fixes previous week.

**Comment by shahab-ramzan** [comment]
@sunilspr7 Evenline Api is not returning correct URLs for events.

**Comment by rupalichavan9860** [comment]
@sunilspr7 Support link : https://canonizer3.canonizer.com/support/2960-2023--Testing-11-AUG/2-Camp-1

**Comment by sunilspr7** [comment]
@rupalichavan9860 Support link update accordign to feedback.

**Comment by rupalichavan9860** [comment]
Working fine on live
