### ISSUE TITLE
Add more dates across the top.  (as many as will fit the size of the window.)

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#308]
Add more hash marks.  One for each event, until they don’t fit.

**Comment by sunilspr7** [comment]
yes, show all dates in this format Jan 12,23 and also added tooltip (across the top)

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by rupalichavan9860** [comment]
Verified on live
