### ISSUE TITLE
Event Line : Abbreviate the dates

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#309]
For example : September 4, 2011 -> 4 Sep 11(Need to confirm the date format)

**Comment by sunilspr7** [comment]
@rupalichavan9860 we used this format Sep 4, 11

**Comment by rupalichavan9860** [comment]
Not fixed

**Comment by rupalichavan9860** [comment]
Working fine on staging
