### ISSUE TITLE
Users support listing extra functionaity

### ISSUE THREAD

**Issue by shahab-ramzan** [the-canonizer/Canonizer-Beta--Issue-Tracking#31]
Users activity History in 3.0 design.

Show user’s support:

https://canonizer.com/support

Sort according to namespace

Sort according to most recent user’s activity

Sort according to the most recent of any activities?

From Jira:
https://canonizer.atlassian.net/browse/CAN-862

**Comment by rohit-talentelgia** [comment]
As discussed over the scrum call,  this is not required.
