### ISSUE TITLE
Camp update: When "Camp archive" is unchecked, the update form should redirect to the history page.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#315]
Currently, it displays a page for updating the camp, and the user can do so twice, resulting in the creation of two entries.

**Comment by vikasranatalentelgia** [comment]
@rupalichavan9860 it is working fine in staging, Please check

**Comment by rupalichavan9860** [comment]
Working fine now
