### ISSUE TITLE
Camp Archive: The child's camp's score is added to the parent camp's. 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#317]
Steps to reproduce : 
1. Create topic and create camp "camp 1"
2. Support "camp 1"
3. Update camp "Agreement" - check "camp archive" checkbox
4. Click on Submit update
Note : Tree is blank and score is "0" which is correct 
6. Again Update camp "Agreement" - uncheck "camp archive" checkbox
7. Observe score for topic

Expected Result : Score for "camp 1" must be "1"

Actual Result :  The score for "camp 1" is "0" and the score for "Agreement" camp is "1" (the user's nick name is displayed under Agreement camp rather than "camp 1").

**Comment by rupalichavan9860** [comment]
On step 3, before committing changes observe tree 
Change : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/43e0383b-64a1-4ead-bfc6-d09a46a33f22)

Topic Detail Page : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/d3ce26a3-a492-4867-901c-80b8b167a9ff)


Actual Result :  Support is getting removed and "Camp 1" is archived - Which is incorrect

**Comment by rupalichavan9860** [comment]
@nalwa When the "Agreement" camp is archived, "Camp 1" should be archived as well, however it is not and the score is 1.

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/aa948d69-a921-465c-bc4d-af9674d52aba)

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by sandeeptlgt** [comment]
Closed, verified on live.
