### ISSUE TITLE
Camp Archive : Score is incorrect in below case

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#318]
Steps to reproduce : 
1. Create topic
2. Create 2 camps "Camp 1" and "Camp 2"
3. Support both camps
Score is "Camp 1" - 0.75 and "Camp 2" -0.25
5. Update "Camp 1"  - Select "Camp Archive" and submit
6. Observe score 

Actual Result : Score of "Camp 2" is 0.50 and Total score is 1. Please refer attached screenshot : 
![image](https://user-images.githubusercontent.com/40416610/235780708-e8c797f9-e704-4222-89d2-7406d58da262.png)

Expected Result : Score of "Camp 2" must be 1

**Comment by nalwa** [comment]
@rupalichavan9860  i have tested it on staging and its working as expected.

https://canonizer3.canonizer.com/topic/2495-archive-318/1-Agreement

above is the reference test topic i created, please re-test this once, and lets connect if  required

**Comment by rupalichavan9860** [comment]
@nalwa It is working fine now . It could be due to the one-hour grace period for each change - this change is reverted by Darab.

**Comment by rupalichavan9860** [comment]
This is working fine after reverting #270 so closing this

**Comment by rupalichavan9860** [comment]
Working fine on live
