### ISSUE TITLE
Camp Archive : Archived camp is listing in parent camp drop down

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#319]
Steps to reproduce : 
1. Create topic
2. Create 2 camps "Camp 1" and "Camp 2"
3. Support both camps
4. Update "Camp 1"  - Select "Camp Archive" and submit
5. Update "Camp 2" -  Observe parent camp drop down

Actual Result : "Camp 1" is listed in the parent camp drop down .

"Camp 1" is archived
![image](https://user-images.githubusercontent.com/40416610/235790020-13de8ee6-7b1c-4497-b5b3-6e891daff242.png)

![image](https://user-images.githubusercontent.com/40416610/235790185-7ad41ea9-20d7-4652-9e74-3d882be2c4fa.png)

"Camp 1" is listed in the parent camp drop down .
![image](https://user-images.githubusercontent.com/40416610/235790352-a081a324-ec96-4611-b975-2303af9a06db.png)

Expected Result :  Archived camps should not be listed in the parent camp drop down .

**Comment by hassaanCD** [comment]
Not fixed
Archived "camp01" is still listed in the parent camp drop down.



![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/120023458/37be1fc6-6ad2-4bb7-829a-d3051761b632)

**Comment by nalwa** [comment]
@hassaanCD  this is also working fine. 

Let's have call regrading the same.

**Comment by hassaanCD** [comment]
Fixed



![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/120023458/9b7df2ff-9d0f-4019-9ee8-33a66a5f070c)

**Comment by rupalichavan9860** [comment]
Working fine on live
