### ISSUE TITLE
Camp Archive :When a camp is created, the user has the option to archive it, but the camp is not actually archived.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#320]
Steps to reproduce : 
1. Create topic 
2. Create camp - select "Camp Archive"
3. Observe camp

Actual Result : camp is not actually archived.

**Comment by rohit-talentelgia** [comment]
@rupalichavan9860 While creating a camp, we do not need the Archive option. @vikasranatalentelgia kindly hide the Archive option on Camp creation.

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by rupalichavan9860** [comment]
Verified on live
