### ISSUE TITLE
Camp Archive : The camp with the score is displayed when the user clicks "Show archived camps."

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#321]
Score should only be displayed after unarchiving a camp.
Curranty score is displayed when the user clicks "Show archived camps."
![image](https://user-images.githubusercontent.com/40416610/236036038-89b5082c-9d48-4af4-afb4-5b9c58c94b7b.png)

Actual : 
![image](https://user-images.githubusercontent.com/40416610/236036343-192489a3-a316-4559-802a-8eb46b0ef884.png)

**Comment by nalwa** [comment]
@rupalichavan9860  i am not able to reproduce this. its working fine for me. If its appearing in any particular case. please sepcify the case.

**Comment by rupalichavan9860** [comment]
@nalwa 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/a9c7a20c-6338-48bc-898d-7d054dd48c2b)

**Comment by rupalichavan9860** [comment]
Working fine
