### ISSUE TITLE
 It can't allows the user to minimize the first topic, on staging server.

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#322]
Steps to reproduce:

1.Login with any user on the staging server.
2. Click on browse and select sandbox testing in "select Canon" field.
3. Open any topic having multiple sub topic/camps.
4. Try to minimize the first topic.

Expected Result: it should allows the user to minimize the first topic.
Actual Result: Now it can't allows the user to minimize the first topic.

Refer screenshot. https://screenbud.com/s/u2uSSd5YRfW

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
