### ISSUE TITLE
It allows any user to search the Archived Camps/Topics without selecting the checkbox "Show archived camps".

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#323]
Steps to reproduce:

1.Login with any user on the staging server.
2. Click on browse and select sandbox testing in "select Canon" field.
3. Search Archived topics in the search field, without selecting the checkbox "Show archived camps".

Expected Result: it should not allows the user to search the Archived Camps/Topics without selecting the checkbox "Show archived camps".
Actual Result: Now it allows the user to search the Archived Camps/Topics without selecting the checkbox "Show archived camps".
![Screenshot (9)](https://user-images.githubusercontent.com/129028750/237059376-805ca5ca-f28d-474d-80e9-675cad730762.png)

**Comment by SandeepTalentelgia** [comment]
Not fixed, verified on staging.

**Comment by rupalichavan9860** [comment]
Duplicate ticket of https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/issues/355

**Comment by nalwa** [comment]
@rupalichavan9860  and @SandeepTalentelgia  scenario mention is fixed. but the other scenario :
- if we select "show archived camps" , then it doesn't display archived camps.

i am working on this scenario. you can test the above mentioned scenario.

**Comment by rupalichavan9860** [comment]
> @rupalichavan9860 and @SandeepTalentelgia scenario mention is fixed. but the other scenario :
> 
> * if we select "show archived camps" , then it doesn't display archived camps.
> 
> i am working on this scenario. you can test the above mentioned scenario.

This is not working @nalwa

**Comment by nalwa** [comment]
@rupalichavan9860  There is PR - https://github.com/the-canonizer/canonizer-service/pull/233 which is not merged yet.

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by SandeepTalentelgia** [comment]
Closed, verified on live.
