### ISSUE TITLE
Need to disabled the "Manage/Edit Camp statement" and "Support Tree for "Agreement" Camp" for Archived Camps.

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#324]
Steps to reproduce:

1.Login with any user on the staging server.
2. Click on browse and select sandbox testing in "select Canon" field.
3. Search Archived topics in the search field, without selecting the checkbox "Show archived camps".
4. Open the search result.

Expected Result: it should not allow the user to search the Archived Camps/Topics without selecting the checkbox "Show archived camps".
Actual Result: Now it allows the user to use "Manage/Edit Camp statement" and "Support Tree for "Agreement" Camp" for Archived Camps.
Screenshot - screenbud.com/shot/4de1335d-493c-43bc-8f08-206b90be4bb0

**Comment by SandeepTalentelgia** [comment]
Fixed, Verified on Staging

**Comment by rupalichavan9860** [comment]
@vikasranatalentelgia The same modification is required for the following menu selections.
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/9b31bbf0-048d-4e7b-ae1b-c7383a5632c0)

**Comment by rupalichavan9860** [comment]
Working fine on staging
