### ISSUE TITLE
While creating the new Camp, if user select the "Camp archive" checkbox, then on submit, it automatically unselects the "Camp archive" checkbox,

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#326]
Steps to reproduce:

1.Login with any user on the staging server.
2. Click on browse and select sandbox testing in "select Canon" field.
3. Try to create a new Camp and select the "Camp archive" checkbox.
4. Check the "Camp archive" checkbox after submitting the update and on "Current Camp Record" screen.

Expected Result: While creating the new Camps, "Camp archive" checkbox functionality should be working.
Actual Result: Now while creating the new Camps, "Camp archive" checkbox functionality is not working.

Screenshot link- https://screenbud.com/s/5n6YG5zb5U5

**Comment by vikasranatalentelgia** [comment]
@SandeepTalentelgia the check box is hidden on the creation of Camp

**Comment by SandeepTalentelgia** [comment]
Closed

**Comment by rupalichavan9860** [comment]
On the Create camp page, the checkbox for Camp Archive is removed.

**Comment by rupalichavan9860** [comment]
Verified on live
