### ISSUE TITLE
Event line: buttons for new topics are disabled

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#327]
Please refer attached screenshot :  
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/73bd790a-e444-4137-a4a2-5abb9a779d24)

**Comment by shahab-ramzan** [comment]
@sunilspr7 Api's is returning only one event even though multiple events have been added.

**Comment by rupalichavan9860** [comment]
Even though there is only one event (that is, the topic was created and agreement camp support was added), it displays two identical events at different times.

refer attached screenshot : 

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/9a09c8f5-d6d5-404f-8827-5aa57d1e5dd8)

**Comment by sunilspr7** [comment]
@shahab-ramzan check this

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Working fine on live
