### ISSUE TITLE
Canonizer Admin : Getting below error while sending email

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#330]
Steps to reproduce : 
1. Create test template 
2. Go to Send Email
3. Select test template and select user
4. Click on Send
Getting error below 
Please refer attached screenshot : 

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/64384dd3-ba4b-4cf7-bb73-7233d5a24dbd)

**Comment by ashish76** [comment]
@rupalichavan9860 The SMTP configuration was not defined on the staging server. However, I have now configured it, and it is functioning properly. Please check and verify.

**Comment by rupalichavan9860** [comment]
@ashish76 Working fine now

**Comment by rupalichavan9860** [comment]
@ashish76 Not working on live 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/4e474413-94d6-4f70-ba83-85f6f3627eb1)

**Comment by rupalichavan9860** [comment]
@ashish76 Not working 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/82995252-01a2-4d3f-8bdb-4cf0cefc725a)

**Comment by rupalichavan9860** [comment]
This is working fine now but users are getting emails on Mailtrap instead of actual email addresses.

**Comment by rupalichavan9860** [comment]
Users are getting emails on actual email address.

**Comment by rupalichavan9860** [comment]
Working fine on live so closing this
