### ISSUE TITLE
Incorrect message(incorrect supporter count) showing on topic/camp/statement history page for Agreement camp

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#331]
Steps to reproduce : 
1. Create topic
2. Create "Camp 1"
3. Support "Camp 1" --User A
4. Login with User B and support "Camp 1"
5. Login with User C and Change submit to topic,Agreement camp and agreement camp statement and observe record 

Expected Result : It should show "1 out of 3 required supporters have agreed"

Actual Result :  Record is in "in review" but showing "1 out of 1 required supporters have agreed"
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/40416610/abf8a615-72af-4bc2-9436-34699a471db8)

**Comment by rupalichavan9860** [comment]
Message showing is correct but change is not going live
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/1b0b53ef-9190-4044-8ae7-1ec84636d5cb)

**Comment by sajid315** [comment]
@rupalichavan9860 its working now, have a look again please. And code has been pushed.

**Comment by rupalichavan9860** [comment]
@sajid315 It is showing correct supporter count but still facing below issue  
1. Create topic
2. Create "Camp 1"
3. Support "Camp 1" --User A
4. Login with User B and support "Camp 1"
5. Login with User C and Change submit to topic, Agreement camp and agreement camp statement 
6. Login with User A and Agree the only change for "agreement camp statement " submitted by User C 
7. Observe other changes(Topic and camp history)

Actual Result :  The "I Agree" checkbox is automatically selected (User A has not yet selected it).And on reload it is working fine
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/1ee91746-17e4-40d2-9eba-c8283abfe934)

**Comment by sajid315** [comment]
@rupalichavan9860 i did'nt found this issue, seems like some misunderstanding. In case you not found the issue, we can close this ticket.

**Comment by rupalichavan9860** [comment]
Yes @sajid315 This is working fine now. It may have been breaking because of cache.
