### ISSUE TITLE
Recent Activities for topic : "View All" is not displaying all activities

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#332]
Steps to reproduce :
1. Create Topic
2. Perform 2-3 activities on topic -Agreement camp
3. Click on "View All"

Observe left side activities and view all activities

Please refer attached screenshot : 

Recent Activities left : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/8ab15077-4fdc-4207-a097-67ad1d02ee59)

Recent Activities view all : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/ebfc6864-198d-4aa5-9347-313e0912f7b6)

**Comment by rupalichavan9860** [comment]
Recent Activities are not working

**Comment by ashish76** [comment]
@rupalichavan9860 I have checked this issue on the staging environment and it is working over there. Is there any specific case? Please provide details.

**Comment by rupalichavan9860** [comment]
@ashish76 Please check for new topics; recent activities are empty.

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/34fb45bf-cff7-4267-bf8a-b5376323d70d)

**Comment by rupalichavan9860** [comment]
Working fine now

**Comment by rupalichavan9860** [comment]
Verified on live
