### ISSUE TITLE
Event line is not working

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#333]
Please refer attached screenshot :

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/06b85139-ee49-46c0-833a-fa9cc35fd76c)

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by sandeeptlgt** [comment]
Closed , verified on live

**Comment by rupalichavan9860** [comment]
Working fine on live
