### ISSUE TITLE
Camp Archive : On the topic detail page for Archived camp, the status is incorrect.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#334]
Please refer attached screenshot : 

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/3c9072c6-f4e1-47c1-8aac-3a2269570baf)

**Comment by hassaanCD** [comment]
Fixed



![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/120023458/f884fd29-ae76-4cde-9834-ec4056e51089)
