### ISSUE TITLE
Change submission : Confirmation pop up issues 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#335]
Please refer attached screenshot : 

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/e5ef91a2-ac9b-43c1-a1b2-0bc02c437131)

1. Confirmation pop up  should have title
2. Message must be proper (Uppercase and lowercase)

**Comment by ks-rahul** [comment]
@rupalichavan9860 I have corrected the upper/lowercase issue and for the first point "Do you want to cancel this commit?" is the title. 



![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/95217406/763c9624-b6ad-4f6f-af64-fd88b0becd25)

**Comment by hassaanCD** [comment]
Fixed 



![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/120023458/3c8756bc-287f-445e-bd2d-99d5d5747ddf)

**Comment by rupalichavan9860** [comment]
Verified on live
