### ISSUE TITLE
When the user is not logged in, the topic list on the home and browse page is very long.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#336]

**Comment by hassaanCD** [comment]
@sajid315 This issue occurred again. Please check it.

**Comment by sajid315** [comment]
@hassaanCD issue resolved now. 
Issue fixed on restart of apache services of staging , while having call with @akuks.



![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/111273633/788bc63a-6644-4e90-acdd-4bdabe062abc)

**Comment by hassaanCD** [comment]
Fixed



![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/120023458/488b07b0-1eac-4ca9-9946-e9730844419e)

**Comment by rupalichavan9860** [comment]
Working fine on live
