### ISSUE TITLE
Issue on search

### ISSUE THREAD

**Issue by vikasranatalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#337]
1. Login with any user on the staging server.
2. Click on browse
3. Search any topic and press enter
4. Searched topic is listed
5. Refresh the page and wait for 5 to 6 seconds

Expected result: Only the searched topic should be displayed
Actual result: When the user waits for 5 to 6 seconds the whole topic list is displayed

**Comment by hassaanCD** [comment]
Fixed



![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/120023458/d2a75a0b-d07e-4046-866a-7e01addd7956)

**Comment by hassaanCD** [comment]
Working fine on production



![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/120023458/43f24d84-3363-423e-8614-8c6cd31a9de4)
