### ISSUE TITLE
"100% of canonized score on all supported camps" is missing when the user is not logged in. 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#339]

**Comment by hassaanCD** [comment]
Not fixed 
As shown in attached screenshots below:

When user is logged in



![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/120023458/a8b7acbb-f401-45d3-86ee-8b6e24993980)


When user is not logged in



![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/120023458/727ce1c5-6022-4463-8f1f-17ffd9805c5d)

**Comment by rupalichavan9860** [comment]
Not fixed

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
