### ISSUE TITLE
Support is not getting removed from parent camp in below case

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#34]
Steps to reproduce : 
1. Create topic
2. Create two camps "camp 1" and "camp 2"
3. Support both camps by User A
4. Login with User B and change parent of "camp 2" to "camp 1" from agreement and commit changes
5. Wait for 24 hours and observe Canonizer Sorted Camp Tree

Expected Result :
Support should get removed from “camp 1”

Actual Result :
Support is not getting removed from “camp 1”. Refer attached screenshot : 

![image](https://user-images.githubusercontent.com/40416610/203962730-54a1245e-ce89-41b2-9e1a-712748a5aac7.png)

JIRA ticket : https://canonizer.atlassian.net/jira/software/projects/CAN/boards/3/backlog?issueType=10011&selectedIssue=CAN-1472

**Comment by sunilspr7** [comment]
I dig the issue deeply and also had call with Sajid to figure out the cause, and we were able to find out the cause which  require minor chnages from Sajid's side.

**Comment by sunilspr7** [comment]
https://github.com/the-canonizer/canonizer-3.0-api/pull/448
I have fixed this issue in above PR

**Comment by subhancd** [comment]
created a topic, will check in 24 hours

**Comment by rupalichavan9860** [comment]
@sunilspr7 @sajid315 Support is being removed from the parent camp, and the score is correct under the support tree, but the incorrect score is still displayed under the canonizer sorted camp tree. Please see the attached image:
![image](https://user-images.githubusercontent.com/40416610/207261857-b1810d32-54c4-4117-bf7d-17ae99a6fc5d.png)

**Comment by nalwa** [comment]
@rupalichavan9860  this issue is same as - https://github.com/the-canonizer/canonizer-3.0-api/issues/451

we are on it working and testing the scenario

**Comment by rupalichavan9860** [comment]
Verified in another ticket
