### ISSUE TITLE
Need to set the design on " Camp statement history " screen.

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#340]
Steps to reproduce:

1.Login with any user on the staging server.
2. Click on browse and select sandbox testing in "select Canon" field.
3. Try to update the Camp history and minimize the statement from the right toggle.
4. Need to set the design, refer screenshot.
Expected Result: it should show the right-side toggle to bottom of the div
Actual Result: Now need to set the design
![Screenshot (12)](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/129028750/2f974405-e2b5-4b56-8449-7f731023a846)

**Comment by SandeepTalentelgia** [comment]
I have verified the ticket no 340, the design has been fixed but when user click on the right upward / downward arrow on the Camp history screen, then it hides the Camp name.
 
 refer screenshot - https://screenbud.com/s/76UoPQDCdZj

**Comment by SandeepTalentelgia** [comment]
Closed

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by rupalichavan9860** [comment]
Verified on live
