### ISSUE TITLE
Browse: Unable to search for today's created topics

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#341]
Please refer attached screenshot : 
Supported camps screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/f7f28141-3fcc-4c01-a0ba-2a98fb671f1f)

Browse search screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/51239fbb-2c50-451e-997c-c95247922d21)

**Comment by sajid315** [comment]
Above scenario working fine on staging and confirmed by @rupalichavan9860 also.

**Comment by hassaanCD** [comment]
Working fine on staging



![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/120023458/bf067caa-9999-4109-8c28-4657d5d56250)

**Comment by hassaanCD** [comment]
Working fine on production



![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/120023458/00a7dc76-cf86-4523-9b66-d53b4d8d663e)



![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/120023458/854f0d91-3aa7-47d3-b1e6-2466c7b494aa)
