### ISSUE TITLE
Event Line : Incorrect score is displaying on first event step

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#342]
First event is topic created and score is displaying as "10"
Please refer attached screenshot : 

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/a46b3098-904c-4bca-9ae8-f82be8284cc9)

**Comment by rupalichavan9860** [comment]
Working fine for new topics and topic number - 88, but still not working for other old topics
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/c5e51af7-8232-4894-9952-ccfe70931731)

**Comment by sunilspr7** [comment]
@rupalichavan9860 I have already fixed this issue. Need to run specific topic based command. 

For testing - First run this script on sever.
php artisan timeline:all 88

if tesing working fine then run
php artisan timeline:all

but we will update all topic after everything is working fine topic 88 and new topic.

**Comment by rupalichavan9860** [comment]
Score is working fine for topic 88 and new topics .

**Comment by rupalichavan9860** [comment]
Not working for other topics

**Comment by sunilspr7** [comment]
@rupalichavan9860 
For other need to run script. 
Example :- 
php artisan timeline:all 88 

Syntax: 
php artisan timeline:all [topic_num]

**Comment by rupalichavan9860** [comment]
Working fine on live
