### ISSUE TITLE
As of Date is not working properly

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#345]
Refer topic : https://canonizer3.canonizer.com/topic/88-Mind-and-Consciousness/1-Agreement
Steps to reproduce : 
1. Go to Camp https://canonizer3.canonizer.com/topic/88-Theories-of-Consciousness/12-Subjective--Though-Real (Camp created date is  : 2009-01-07)
2. Apply As of Date as "2009-01-06"

Expected Result : It should display a topic detail page with the camp's creation date and a link to it.

Actual Result : It displays the topic's creation date with a link, but nothing happens when the link is clicked.
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/65a95067-bd81-4bda-b088-d750ed13bb58)

**Comment by hassaanCD** [comment]
@rupalichavan9860 This ticket is not fixed as link is still not clickable.

**Comment by sajid315** [comment]
@hassaanCD let me check once again.

**Comment by sajid315** [comment]
@hassaanCD  This issue simply a browser cache issue, I checked again on staging site and here are the results. So it will work fine after hard reload in browser. 
After checking we can close this ticket then.

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/111273633/bc8ffcc7-6df9-4fef-afd8-d83b1ec254d2)

**Comment by rupalichavan9860** [comment]
@sajid315 Can see the camp created date and it is now clickable, however when the user clicks on the link, it does not show the camp statement, whereas if the date is selected individually, it does show the camp statement.
From link (as of date ): 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/be53983d-aeb9-42cb-85bb-14db8d04ae08)


As of date : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/3424e844-e246-4e68-91f8-23e7309df5f7)

**Comment by sajid315** [comment]
Ok @rupalichavan9860 , I will check for above scenario.

**Comment by sajid315** [comment]
We need to verify the results of the above case after completion of below ticket. 
https://github.com/the-canonizer/canonizer-3.0-frontend/issues/1102

**Comment by sajid315** [comment]
@rupalichavan9860 now its showing on my local as per the PST timezone, Please check the issue again after deployment of above mentioned ticket. 


![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/111273633/b26e878a-9490-42bc-9f5a-242b62b21b25)

**Comment by sajid315** [comment]
@rupalichavan9860 above mentioned PR is merged , have a look on issue please.
https://github.com/the-canonizer/canonizer-3.0-frontend/issues/1102

**Comment by rupalichavan9860** [comment]
Not working .

**Comment by sajid315** [comment]
Yes @rupalichavan9860 I have a look into this issue and issue was caused due to UTC timezone. So now the issue has been fixed. Also as discussed we are considering full day now in case of previous date version of tree. 
Following are the results.

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/111273633/f4806273-1dac-4a8f-9fac-81c011936735)

And on click of camp creation date. Results are following that showing the valid response now. 

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/111273633/3cd723b6-611a-4f43-b396-334caae1546f)

**Comment by rupalichavan9860** [comment]
@sajid315 Working fine now

**Comment by rupalichavan9860** [comment]
Working fine on live
