### ISSUE TITLE
Event Line : Few events are missing 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#346]
Please refer attached screenshot : 

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/c5105155-505c-45b4-824a-bf3b5fdd5a0b)

Event Line event : 

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/f6975998-3c5c-4903-8ad3-4074060b70ad)

Camp "SCVR" created event is missing and parent changed event is displaying on camp created date

**Comment by rupalichavan9860** [comment]
The order of the events is incorrect.

**Comment by sunilspr7** [comment]
@rupalichavan9860  I need to discussion on this .

**Comment by sandeeptlgt** [comment]
Working on local but not working on staging due to script.
