### ISSUE TITLE
Support is remains added to both parent and child camp 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#347]
Steps to reproduce : 
1. Create Topic and create 2 camps "Camp 1" and "Camp 2"
2. Support both camps 
3. Change parent of "Camp 2" to "Camp 1" from "Agreement"
4. Commit Change (It will go live immediately)
5. Observe score for "Camp 1" and "Camp 2"

Actual Result : 
Camp 1 score : 0.75
Camp 2 score : 0.25
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/450759e4-6f18-4ea0-91ca-1c108f87162d)

Expected Result : 
Support should get removed from "Camp 1" and "Camp 2" score should be 1

**Comment by array-junkie** [comment]
It is fixed in PR [#673](https://github.com/the-canonizer/canonizer-3.0-api/pull/673)

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Verified and working fine on live
