### ISSUE TITLE
Camp Archive : Incorrect tooltip is showing 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#348]
When the camp is archived and user wants to unarchive the camp , it should show "Unarchive the camp" instead of "Archive the camp"
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/badcd303-a3cc-4809-9483-223c4d7d29d5)

**Comment by hassaanCD** [comment]
Fixed



![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/120023458/855f572c-6f56-4885-b805-83a6710c6170)

**Comment by SandeepTalentelgia** [comment]
Closed

**Comment by rupalichavan9860** [comment]
Verified on live
