### ISSUE TITLE
Camp Archive : Child camp is not being archived. 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#349]
When Agreement camp is archived, child camp is archived as well; however, when Agreement camp is unarchived, child camp is not archived.

**Comment by hassaanCD** [comment]
Not fixed
When Agreement camp is unarchived, child camps are still archived.



![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/120023458/fbd6fbb2-189c-4d2a-82ad-5d9bffeb603d)

**Comment by nalwa** [comment]
@hassaanCD  its working fine for me on staging. let's connect for this ASAP

**Comment by hassaanCD** [comment]
Fixed



![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/120023458/4d305909-6bab-472a-848d-4f207806d39e)

**Comment by rupalichavan9860** [comment]
Working fine on staging
