### ISSUE TITLE
All supporters nicknames in popup are not listing 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#353]
Steps to reproduce : 
1. Login with User A and create topic (User A is supporter of "Agreement" camp)
2. Create sub camp 
3. Login with User B and support sub camp
4. Login with User C and add camp statement for Agreement camp
5. Observe total number of supporters pop up

Actual Result : 
It is showing "1 out of 3 required supporters have agreed" but only 2 names listing in pop up. Implicit supporter's nick name is not listing
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/eb2d0770-dd16-4634-a665-6a4d90a33bbf)

**Comment by array-junkie** [comment]
PR Raised: **[#676](https://github.com/the-canonizer/canonizer-3.0-api/pull/676)**

**Comment by rupalichavan9860** [comment]
@M-Darab Still not working. Please refer attached screenshot : 

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/839b41d6-188b-4ef6-a48f-76fa99cb3e17)

**Comment by array-junkie** [comment]
PR raised: [#686](https://github.com/the-canonizer/canonizer-3.0-api/pull/686)

**Comment by rupalichavan9860** [comment]
This is working fine now

**Comment by rupalichavan9860** [comment]
Verified on live
