### ISSUE TITLE
Change is going live without implicit supporter approver 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#354]
Steps to reproduce : 
1. Login with User A and create topic (User A is supporter of "Agreement" camp)
2. Create sub camp 
3. Login with User B and support sub camp
4. Login with User C and add camp statement for Agreement camp

Actual Result : 
It is showing "1 out of 3 required supporters have agreed" but change is going live when User A approves the change

**Comment by array-junkie** [comment]
PR Raised [#679](https://github.com/the-canonizer/canonizer-3.0-api/pull/679)

**Comment by sajid315** [comment]
Updated PR raised:
https://github.com/the-canonizer/canonizer-3.0-api/pull/681

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Working fine on live
