### ISSUE TITLE
When delegating support, the name of the supported camp shouldn't be listed below. 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#358]
Steps to reproduce : 
1. User A supporting camp "Camp 1" , "Camp 2" and "Camp 3"
2. User B is supporting "Camp 4"
3. User B login - Try to delegate support to User A in "Camp 1"

Actual result : It displays the name of both the now supported camp and the camp that will be supported 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/222f64ae-96d1-4523-a01a-ae86eb13a8aa)

Expected Result : It should not display currently supported camp, as it is already doing, and support for currently supported camp will be deleted.

**Comment by hassaanCD** [comment]
Fixed



![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/120023458/ad8a51d9-402b-44e3-81d4-54c10ec8d727)

**Comment by hassaanCD** [comment]
Working fine on production



![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/120023458/5ca78e18-af05-4c52-93ac-a1547d1fa1e7)
