### ISSUE TITLE
Change File Upload File Path To same as 2.0 as now proxy implemented.

### ISSUE THREAD

**Issue by shahab-ramzan** [the-canonizer/Canonizer-Beta--Issue-Tracking#36]
Change File Upload File Path To same as 2.0 as now proxy implemented.

Like following S3 actual path must be set to [https://domain_name/files/TWFsaWExTWFsaWE%3D_1668694648_209452.jpg](https://canonizer-public-file.s3.us-east-2.amazonaws.com/TWFsaWExTWFsaWE%3D_1668694648_209452.jpg) in short code only. So that if user copy short code then he get local domain file path to be used in statement text.

https://canonizer-public-file.s3.us-east-2.amazonaws.com/TWFsaWExTWFsaWE%3D_1668694648_209452.jpg

Please implement same in 2.0 also.

From Jira:
https://canonizer.atlassian.net/browse/CAN-1537

**Comment by rupalichavan9860** [comment]
Verified by Ashutosh
