### ISSUE TITLE
If user added a link in summary and statement of "Camp Statement History" screen, then after submit it remove the added link from statement and for summary it shows the added link as a normal text, instead of hyper link.

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#361]
Steps to reproduce:

1.Login with any user on the staging server.
2. Click on browse and select sandbox testing in "select Canon" field.
3. Select any topic and try to add link in summary and statement on "Camp Statement History" screen
4. Click on submit and check the result.

Expected Result: it should shows the added link as hyper link.
Actual Result: it remove the added link from statement and for summary it shows the added link as a normal text, instead of hyper link. 
![Screenshot 2023-05-24 at 10-50-56 Statement History Canonizer](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/129028750/07047149-1d45-44a5-88dc-7393314be7ce)
![Screenshot 2023-05-24 at 10-49-57 Manage Statement Canonizer](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/129028750/74f188ec-f4ff-4cdb-9cca-6fa9739af870)
refer screenshort.

**Comment by rupalichavan9860** [comment]
@SandeepTalentelgia You need to use link tool and then it will work

**Comment by SandeepTalentelgia** [comment]
Closed
