### ISSUE TITLE
Suggestion -  Can we change the text of both buttons, it create confusion, if user read the text in the popup "Please note that any unsaved changes will be lost if you cancel" but cancel button only close the popup, user need to click on ok button to cancel the added data. 

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#363]
Steps to reproduce:

1.Login with any user on the staging server.
2. Click on browse and select sandbox testing in "select Canon" field.
3. Select any Topic and try to update the same.
4. After submit, click on cancel on the Topic history screen.
4. Check the popup text and cancel button

Expected Result: Popup test and button text should be clear and easily understand by the user.
Actual Result: Now it popup text and cancel button creates confusion
![Screenshot 2023-05-25 at 11-54-42 24- May- Testing History Canonizer](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/129028750/0013cd89-dcf4-4201-ba01-ceac7691e667)
.

**Comment by saniatg** [comment]
fine for now
