### ISSUE TITLE
Mobile device: When the user clicks the push notification button, it keeps loading.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#365]
Please refer attached screenshot : 

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/a4e052de-25c0-4ad6-a173-4c947913ec71)

**Comment by hassaanCD** [comment]
Fixed



![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/120023458/101cbb75-8017-40c5-90e7-8c19bc994e43)

**Comment by rupalichavan9860** [comment]
@hassaanCD @ks-rahul It is not working on real mobile devices. Please check and let me know if you need any help on this

**Comment by ks-rahul** [comment]
@rupalichavan9860 I checked the production URL on my mobile, and it's working fine.

**Comment by hassaanCD** [comment]
@rupalichavan9860 It is working fine on real mobile device on production. Just took few seconds to load.

**Comment by ashish76** [comment]
@rupalichavan9860 & @hassaanCD The delay was from the Firebase side and we don't have any control over it. We already added a loader over there.

**Comment by ks-rahul** [comment]
@rupalichavan9860 , after the r&d on this issue I found that It doesn't work to send push notifications (using Firebase Cloud Messaging) to browsers on iPhone devices as they don't support the Push API, so I added a popup message "Something went wrong or Push notification is not supported in this device." for this.

**Comment by rupalichavan9860** [comment]
This problem exists for the most recent iPhone model (14 Pro), however it works perfectly for older models.

**Comment by rupalichavan9860** [comment]
Verified on live
