### ISSUE TITLE
Incorrect number of supporter count displaying on history page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#371]
Steps to reproduce : 
1. Login with User A - Create topic and create 2 camps "Camp 1" and "Camp 2"
2. Support both camps 
3. Login with User B and delegate support to User A
4. Submit a change to Agreement camp/statement/topic and observe note " 1 out of N required supporters have agreed" 

Expected Result : 
As User A is the only implicit direct supporter (direct supporter of sub camp) of Agreement camp , it should show " 1 out of 2 required supporters have agreed"

Actual Result : 
The message "1 out of 3 required supporters have agreed" is displayed, and even if User A has agreed to the change, it is not yet live.

**Comment by M-Darab** [comment]
PR Raised: **[#676](https://github.com/the-canonizer/canonizer-3.0-api/pull/676)**

**Comment by array-junkie** [comment]
@rupalichavan9860 I'm unable to find this issue. Can you please recheck and if you don't find it, we can close this ticket.

**Comment by rupalichavan9860** [comment]
Yes @M-Darab This is working fine now so closing this
