### ISSUE TITLE
While the camp is being unarchived, a delegated supporter is becoming a direct supporter.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#372]
Steps to reproduce : 
1. Login with User A - Create topic and create camp "Camp 1"
2. Support "Camp 1"
3. Login with User B and delegate support to User A
4. Login with User A and archive camp "Camp 1"
5. Again unarchive "Camp 1" and observe support tree for "Camp 1"

Actual Result : Score is restored but a delegated supporter(User B) is becoming a direct supporter.

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by sandeeptlgt** [comment]
closed, verified on live.
