### ISSUE TITLE
Multiple Camp support : A delegated supporter is becoming a direct supporter while the Agreement camp is being unarchived, and support isn't returning to every supported camp.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#373]
Steps to reproduce : 
1. Login with User A - Create topic and create camps "Camp 1", "Camp 2" and "Camp 3"
2. Support all camps 
3. Login with User B and delegate support to User A
4. Login with User A and archive camp "Agreement"
5. Again unarchive "Agreement" camp and observe support tree for "Camp 1","Camp 2" and "Camp 3"

Actual Result : 
1. Camp 1 : Score is restored but a delegated supporter(User B) is becoming a direct supporter.
2. Camp 2 and Camp 3 : Support is getting removed from camps

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by sandeeptlgt** [comment]
Closed, verified on live.

**Comment by rupalichavan9860** [comment]
Working fine on live
