### ISSUE TITLE
Camp Archive : Support is still being added to the archived camp.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#374]
Steps to reproduce : 
1, Create topic
2. Update Agreement - select "Camp Archive"
3. Update Agreement - deselect "Camp Archive"
4. Update Agreement - select "Camp Archive"
5. Update Agreement - deselect "Camp Archive"
6. Observe score 

Refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/517fff6c-65d3-40c3-9d15-ce0e80bea511)

**Comment by nalwa** [comment]
@rupalichavan9860  i am not able to reproduce it. I think this needs to be tested by clearing cache or on private window

**Comment by rupalichavan9860** [comment]
Working fine now

**Comment by sandeeptlgt** [comment]
Closed, verified on live.
