### ISSUE TITLE
We have to disable "Create new camp" for archived camps; now, a user can create a child camp of an archived camp and receive the error "Something went wrong".

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#375]
Steps to reproduce:

1.Login with any user on the staging server.
2. Click on browse and select sandbox testing in "select Canon" field.
3. Archived any Camp and try to create the child camp for the same.
4. check the error "Something went wrong".

Expected Result: "Create new camp" for archived camps should be disabled.
Actual Result: Any user can create a child camp of an archived camp 
![image_2023_06_01T18_24_09_674Z](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/129028750/673b2596-e304-4f02-997f-70bbdc1c5ab2)

**Comment by rupalichavan9860** [comment]
Camps are getting created under archived camp

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/80a37b01-489f-40e1-9aba-dede9ba8965c)

**Comment by rohit-talentelgia** [comment]
@vikasranatalentelgia kindly look into this issue

**Comment by rupalichavan9860** [comment]
@nalwa @vikasranatalentelgia Please refer below steps : 
1. Create topic
2. Update "Agreement" camp - archive 
3. Click on "Start new supporting camp here"
4. Observe page

Actual Result  : 
Getting "Something went wrong" error . Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/0a557db0-730c-4bc5-86d5-3d9348b2d10d)

**Comment by rupalichavan9860** [comment]
@vikasranatalentelgia Archive the camp and click on "Create New Camp" button on history page - getting "Something went wrong"

But if we reload the history page ,user can't see "Create New Camp"

**Comment by rupalichavan9860** [comment]
> @vikasranatalentelgia Archive the camp and click on "Create New Camp" button on history page - getting "Something went wrong"
> 
> But if we reload the history page ,user can't see "Create New Camp"

This issue is still exists

**Comment by vikasranatalentelgia** [comment]
@rupalichavan9860 the status of the ticket was In review. it is still not merged and deployed on staging.

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by SandeepTalentelgia** [comment]
Closed, verified on live.
