### ISSUE TITLE
If "show archived vamps" checkbox is selected then it should not allows the user to search unarchived camps.

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#376]
Steps to reproduce:

1.Login with any user on the staging server.
2. Click on browse and select sandbox testing in "select Canon" field.
3. Select "show archived vamps" checkbox.
4. Search the newly created Topic/camp which is not archived.
5. Check the results.

Expected Result: If "show archived vamps" checkbox is selected, then it shows only archived camps.
Actual Result: Now it shows unarchived camps if user try to search the same.

![Screenshot (20)](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/129028750/b9e5babf-495e-4e68-a171-6d1de2b041db)

**Comment by vikasranatalentelgia** [comment]
@SandeepTalentelgia I have discussed with @rohit-talentelgia , this scenario is not valid, it will not show only archived camps

**Comment by rohit-talentelgia** [comment]
@vikasranatalentelgia we need to grey out the colors of the archived topic in the list with text on hover as Archived Topic

**Comment by SandeepTalentelgia** [comment]
Closed

**Comment by SandeepTalentelgia** [comment]
Closed, verified on live.
