### ISSUE TITLE
The event line button on the supported camps page is not working. 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#379]
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/2241bce4-6dc1-4c10-ba70-85c0b0c1ccef)

**Comment by rohit-talentelgia** [comment]
@vikasranatalentelgia and @rupalichavan9860 I do not think that the Eventline button should be displayed on Add Support page.

**Comment by rupalichavan9860** [comment]
@rohit-talentelgia Yes.

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by SandeepTalentelgia** [comment]
Closed
