### ISSUE TITLE
In the following case, a direct supporter is unable to object to the change.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#383]
Steps to reproduce : 
1. User A is the only direct supporter of the camp 
2. User B submitted a change to camp 
3. Direct supporter (User A) archived the camp 
4. Direct supporter (User A) - try to object the change submitted by User B

Actual Result : 
Direct supporter is able to agree but not able to object the change submitted by User B
Getting below error. Please find attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/54ae14e0-accd-467a-8e89-8373e47e4b9c)

**Comment by nalwa** [comment]
@rupalichavan9860  @mark-shamy  @BrentAllsop  As per my understanding of this feature. If any camp is archived then all the action on below section should be restricted until or unless it is restored:

1. All activities on Tree page (Already implemented).
2. restrict Activity on history page for previous cards (in-review card, old cards.).
3. And on live card which is already in **archived state** only change should be accepted if **_Un-archived_** is selected.

Please share you understanding and confirm which way we should proceed on this.

**Comment by rupalichavan9860** [comment]
Working fine

**Comment by rupalichavan9860** [comment]
Verified on live
