### ISSUE TITLE
Event Line : Old Topic name is displayed in bread crumbs.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#384]
For topic : https://canonizer3.canonizer.com/eventline/132-Help/1-Agreement 
Please refer attached screenshot : 

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/8ae8cbaf-5014-411d-9f06-0d95ef101291)

**Comment by rupalichavan9860** [comment]
Working properly for this particular topic, but there is a problem with other topics.

**Comment by rupalichavan9860** [comment]
Not able to test because getting page crash for old topics

**Comment by rupalichavan9860** [comment]
@sunilspr7 Still displaying old name

**Comment by sandeeptlgt** [comment]
Closed

**Comment by rupalichavan9860** [comment]
Working fine on live
