### ISSUE TITLE
Event Line : Incorrect unarchived camp event is listing 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#385]
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/392b862b-20fc-41da-bebe-b8dd2d76ab92)

Camp History page (" test camp 1" ) : 

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/54461104-30ab-473a-bc67-375aee088d7a)

Camp is never archived/unarchived and displaying unarchived camp event

**Comment by sunilspr7** [comment]
@rupalichavan9860  i will check this, lately there has been lots of chnages on archive feature it might have appeared due to this.

**Comment by sunilspr7** [comment]
@rupalichavan9860  we  need discussion on this task.

**Comment by rupalichavan9860** [comment]
This is coming when user submits a normal change to the camp (without selecting camp archive)

**Comment by sunilspr7** [comment]
@rupalichavan9860 I  am not able to reproduce this issue on my local and also not reproduce on staging server

**Comment by sunilspr7** [comment]
@rupalichavan9860 I have found this issue and solved it.

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by sandeeptlgt** [comment]
Closed, verified on live.
