### ISSUE TITLE
Delete Sandbox topic functionality in admin

### ISSUE THREAD

**Issue by karun0607gautam** [the-canonizer/Canonizer-Beta--Issue-Tracking#391]
Provide an option in admin to delete the sandbox namespace topics. It is needed to clean the test data from live and other environments
1. there should be an listing page which will list the topics under sandbox namespace
2. Dropdown on top to select the namespace and it should reflect the topics based on the namespace( this is if we have created any test data in any other namespace)
3. there should be an option to multiselect option in the list , user can multiselect the topics and delete them
4. User can also delete the topics one by one

**Comment by rupalichavan9860** [comment]
@ashish76 The functionality has been implemented, but there are some issues that I am tracking separately, therefore I am closing this.

**Comment by rupalichavan9860** [comment]
The functionality has been implemented so closing this
