### ISSUE TITLE
Camp/Topic/Statement History : View This Version is not working

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#392]
Please refer attached screenshot : 

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/41af1ae2-2cb6-445f-8650-dd0e03534e87)

Note :  Issue is exists for all 3 history pages

**Comment by array-junkie** [comment]
@rupalichavan9860 Please check this ticket again. It is fixed.

**Comment by rupalichavan9860** [comment]
Yes @M-Darab Working fine now

**Comment by rupalichavan9860** [comment]
Verified on live
