### ISSUE TITLE
Camp Archive : Score's are incorrect in below case

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#394]
Steps to reproduce  : 
1. Create topic
2. Create camps "Camp 1", "Camp 2" and "Camp 3"
3. Support all camps
4. Archive "Agreement" camp 
5. Unarchive "Agreement" camp
6. Archive "Camp 1" camp 
7. Unarchive "Camp 1" camp 
8. Observe tree ,score and preference numbers

Actual Result : Please refer screenshots below
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/0683d69f-3786-4832-83da-17e277f2cb91)

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/7d03c5c3-8c60-452f-9748-658972e569d0)

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by SandeepTalentelgia** [comment]
Closed, verified on live.
