### ISSUE TITLE
On staging, captcha is not working.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#397]
Please refer attached screenshot : 

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/244943eb-df40-48b7-8ee2-6c8fc9b0591f)

**Comment by ks-rahul** [comment]
@rupalichavan9860 please check now.

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by rupalichavan9860** [comment]
@ks-rahul Captcha is not available on live . Please check

**Comment by rupalichavan9860** [comment]
Verified on live
