### ISSUE TITLE
Event Line : when user click on events camp data displayed is blank

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#399]
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/3f0f645f-3872-48f7-9c6a-7930fcb3cf59)

**Comment by sunilspr7** [comment]
@shahab-ramzan Please check this issue.

**Comment by rupalichavan9860** [comment]
Working fine now so closing this

**Comment by rupalichavan9860** [comment]
As discussed with Wahaj, some code has to be added to avoid future issues.

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Working fine on live
