### ISSUE TITLE
Getting error "Given thread id does not exist in the database." when user click on thread and post created web notifications

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#4]
Please refer attached screenshots : 
Click on below links : 
![image](https://user-images.githubusercontent.com/40416610/203239890-84e16695-7ea5-4cf0-a9b3-0904fe618597.png)

Getting below error : 
![image](https://user-images.githubusercontent.com/40416610/203239804-a2582c94-392b-4827-97b6-631c6f26dec5.png)

**Comment by subhancd** [comment]
verified on both staging and beta. working fine. @rupalichavan9860
