### ISSUE TITLE
Breadcrumb improvements

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#400]
Make the keywords "Topic" and "Camp" normal text (not bold), and double the font size of the actual topic and camp names.

**Comment by rupalichavan9860** [comment]
Also need tooltip on subscribed icon

**Comment by ks-rahul** [comment]
@rupalichavan9860 I'm using this message, please notify me if any changes are required

For the topic: "You have subscribed to the entire topic"

For the camp: "You have subscribed to this camp."

**Comment by rupalichavan9860** [comment]
@ks-rahulAll changes are working, except the topic tooltip missing a "."
For consistency, we should either include "." at the end or delete it for the camp tooltip.

**Comment by rupalichavan9860** [comment]
Verified and working fine on staging

**Comment by hassaanCD** [comment]
Working fine on live
