### ISSUE TITLE
Statement Editor issues

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#401]
CKEditor - multiple tools(Link,image,table,Emojis ,special characters etc) aren't working.

**Comment by vikasranatalentelgia** [comment]
@rupalichavan9860 the tools are working fine.

**Comment by rupalichavan9860** [comment]
Tools are working fine now

**Comment by hassaanCD** [comment]
Working fine on live
