### ISSUE TITLE
Camp Archive : Support remains added to both parent and child in below case

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#402]
Steps to reproduce : 
1. Create topic
2. Create 2 camps "Camp 1" and "Camp 2"
3. Support both camps
4. Update "Camp 2" - check "Camp Archive" and commit changes 
5. Again Update "Camp 2" - change parent camp to "Camp 1" from "Agreement " and commit changes 
6. Update "Camp 2" - uncheck "Camp Archive" and commit changes 
7. Observe tree and score

Actual Result : "Camp 2" is child of "Camp 1" but score are Camp 1: 0.75 and Camp 2: 0.25 which is incorrect
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/73788863-cc79-4109-adc5-acb0f422b679)

**Comment by rupalichavan9860** [comment]
Please refer one more case : 
1. Create topic
2. Create "Camp 1" , "Camp 2" and child of "Camp 1" - "Sub Camp 1"
3. Login with User A and support "Sub Camp 1" and "Camp 2"
4. Login with User B and delegate support to User A
5. Login with User C and support "Camp 1"
6. Login with User C - Update "Camp 1" - check "camp archive"
7. It will be in review - Login with User A and agree the change
8. Login with any user and make "Camp 1" unarchive 
9. Observe score and support tree of "Camp 1" and "Sub Camp 1"

Expected  Result : User A must be direct supporter of "Sub Camp 1" and User B must be delegated support of User A
User C must be direct supporter of "Camp 1"

Actual Result : User A and User C is direct supporter of both camps and User B is delegated supporter

**Comment by nalwa** [comment]
@rupalichavan9860  in first scenario above, should we allow user to update parent change on camp which is in archive state?

As per my suggestion we should not allow any change on archive camp, until it is not revoked. As per discussion in one of the meeting we decided to allow updated on history  cards of that camp, but not the live camp which is in archived state. 

I need discussion over this.

**Comment by nalwa** [comment]
@mark-shamy can you please also share your views on this scenario, as it will conflict the support data.

We have to  decide which activity one can perform on camps in archived state..

**Comment by nalwa** [comment]
@rupalichavan9860  @mark-shamy  @BrentAllsop  to confirm the functionality of this issue: -
 Should we add "**Un-archive"** button in live archived camp and disable **"submit update on this camp"** till the time its in archive state.

Please confirm.

**Comment by nalwa** [comment]
As per the discussion in today's meeting:-  

for live archive camp  button says **"submit update on this camp"** should be replaced with **"un-archive this camp".**

@rupalichavan9860  please have look at this comment and let me know if i am missing anything here.

**Comment by rupalichavan9860** [comment]
@nalwa Please refer below steps : 
Steps to reproduce :

1. Create topic
2. Create 2 camps "Camp 1" and "Camp 2"
3. Support both camps
4. Update "Camp 2" - check "Camp Archive" and commit changes
5. Click on "Unarchive This Camp"(Do not commit changes)
6. Click on Edit change and change parent from "Agreement" to "Camp 1"
7. Observe tree and score 

Actual Result : "Camp 2" is child of "Camp 1" but score are Camp 1: 0.75 and Camp 2: 0.25 which is incorrect

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by hassaanCD** [comment]
Working fine on live
