### ISSUE TITLE
Direct supporter is unable to object their own change in below case

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#403]
Steps to reproduce : 
1. Login with User A and create topic - User A is supporter of "Agreement" camp
2. Login with User B and support Agreement camp
3. Login with User A and create "Camp 1"
4. Camp 1 - 0 supporters
5. Update "Camp 1" - select "Camp Archive"
6. Update "Camp 1" - unselect "Camp Archive"
7. Submit change to agreement camp and statement and commit change-User A login
8. Both User A and User B can see Object button but User A is getting message "You are not authorized to object to this statement because you do not support this camp." while objecting own change

Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/cec166d8-cc91-4d5b-8e1b-089b4ed2990d)

**Comment by array-junkie** [comment]
PR raised: [#730](https://github.com/the-canonizer/canonizer-3.0-api/pull/730)

**Comment by array-junkie** [comment]
There are some testcases that are failing, so I'm moving back to InProgress.

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Working fine on live
