### ISSUE TITLE
Delete Sandbox topic functionality in admin: It is listing topics a number of times (the number of times the topic has been modified).

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#404]
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/2bf6ab0d-2f20-407c-8e6b-d9b08cbff28b)

**Comment by rupalichavan9860** [comment]
Verified and working well on staging

**Comment by rupalichavan9860** [comment]
It is not listing updated names 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/73aebc2d-a994-4d80-b864-2c2e348125ed)

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/49002946-6686-4572-a874-eb38298f8c06)

**Comment by rupalichavan9860** [comment]
still not listing updated names
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/c94623c0-6558-494c-8b75-51cb868194e2)

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/e54bc326-fa48-4d5e-b8e9-a803fe223bd1)

**Comment by ashish76** [comment]
@rupalichavan9860 

The "PR" (Pull Request) hasn't been merged yet, that's why the code is not working as expected. I have requested Ashutosh to review and merge.

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Working fine on live
