### ISSUE TITLE
Delete Sandbox topic functionality in admin: Topic is not getting deleted from database

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#405]
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/a61c5918-988c-45d7-a627-a5761f406082)

I have deleted highlighted topic but still showing in list : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/4de69738-2954-4922-a816-174178dfb1d0)

**Comment by rupalichavan9860** [comment]
Topics are deleting from the database but it present in the mongo cache so currently I am moving this to "In progress"

**Comment by ashish76** [comment]
This ticket is related to a dependency problem. The specific issue can be tracked here: https://github.com/the-canonizer/canonizer-service/issues/240.

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Working fine on live
