### ISSUE TITLE
Emails : Issues

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#408]
Issue 1 : Camp names and topic names need to be bold. The topic and camp names are not bold in some emails.
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/d069a4e4-9fb9-4d5f-ab4e-f82049d7487d)

Issue 2 : Bread crumb camps not all being included in emails subject
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/a318c5c5-d973-4d41-81c5-e063f0f4a629)

Issue 3 : Topic name link is missing in below email 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/8bc883e2-36be-4e4c-82aa-6214df692e62)

**Comment by rupalichavan9860** [comment]
Topic/camp name links are missing for email objected to your proposed change for topic and camp statement 

Refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/bc1d4f0e-dc03-4683-886a-2d4c21f0b922)

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/42911dc9-88e3-46f9-9f7e-67037587b320)

**Comment by sajid315** [comment]
@rupalichavan9860 
All of the above issues are done except the Issue 2 (As we discussed with Brent in meeting to not include the breadcrumb in subject, so we can skip this). 

Also one thing i noticed for proposed change email that the "proposed a change" text not having the change link to redirect. As you can see in below screenshot. 

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/111273633/654988b9-701b-4344-bf0c-3d093b5ed127)

But the same case when user will object the change it will include the link in text of "proposed change".  As you can see in below screenshot. 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/111273633/dd3b1203-4de2-44a4-96ae-43d1643cafa7)

**Question Statement**
So do we have to include links on this text for all cases or we can exclude it from all emails ?

**Comment by rupalichavan9860** [comment]
@sajid315 This will take us to the history page, so provide links.

**Comment by sajid315** [comment]
> @sajid315 This will take us to the history page, so provide links.

@rupalichavan9860 that requirement is also done and PR been raised. You can check it after deployment of this ticket.
