### ISSUE TITLE
Camp Statement is not displaying in below case 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#409]
On the topic details page (On default filter), if a user adds just an image to a camp statement, it is hidden. The statement displays if the user selects "Include review," and subsequently it appears if the user selects "Default."

**Comment by rupalichavan9860** [comment]
I am getting this issue for every topic for normal statements also

**Comment by rupalichavan9860** [comment]
This is working now but "View This Version" is not displaying respective record

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by hassaanCD** [comment]
Working fine on live
