### ISSUE TITLE
Google Ads & Analytics Integration

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#41]
From JIRA : 
https://canonizer.atlassian.net/browse/CAN-14

**Comment by ks-rahul** [comment]
@rupalichavan9860 Could you provide some details about this requirement? Also, where can I get the necessary assets (keys, etc) for this?

**Comment by ks-rahul** [comment]
Hi, @gautamv16 could please confirm whether this ticket is the same as this "https://github.com/the-canonizer/canonizer-3.0-frontend/issues/610" ticket or different one?
