### ISSUE TITLE
On camp history page disable submit update on this camp button for archived camp

### ISSUE THREAD

**Issue by nalwa** [the-canonizer/Canonizer-Beta--Issue-Tracking#410]
So as per today's meeting, we have mutually decided that if camp is in archived state, then on its camp history page. all the old camps (camp history cards) should have disabled  button "submit camp update on this camp". and its should do nothing on its click.

**Comment by rupalichavan9860** [comment]
Implemented and working fine on staging

**Comment by sandeeptlgt** [comment]
Closed , verified on live.
