### ISSUE TITLE
Staging : The UI is breaking

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#413]
Steps to reproduce : 
1. Go to https://canonizer3.canonizer.com/
2. Select any topic
3. Go to event line 
4. Click on canonizer logo 
5. Observe UI

Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/1f85712a-5af1-4620-9a58-df597117b711)

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/69e1fc48-ca3f-4c4a-a2fa-00be817eecac)

**Comment by SandeepTalentelgia** [comment]
In mobile view, the UI is also disturbed. 
Refer screenshot

![70B1BD93-F693-4E01-8525-07C029AAEB73](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/129028750/2577a8e6-e5de-4a75-a552-6668d14ece66)

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Working fine on live
