### ISSUE TITLE
Event Line issues 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#415]
Issue 1 : It should show event line from topic created date , as of now it is showing any date and on reload dates are changing

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/49552ddf-7934-49c8-b90b-799c0967cc53)

Issue 2 : Topic name is blank when selecting other algorithms 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/96caa762-280d-473b-854e-7c8828b7addc)

Issue 3 : Select any other algorithm other than first 3 and reload the page . It is taking time to load data
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/846cbcbc-629e-4d14-856b-3cdab7633daa)

**Comment by sunilspr7** [comment]
#457 related to this.

**Comment by sandeeptlgt** [comment]
Closed

**Comment by rupalichavan9860** [comment]
Working fine on live
