### ISSUE TITLE
All in-review should become history (blue cards) after any topic, camp, or statement has changed and gone live.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#416]
All records that are now under review should become history (blue cards) if a user submits a modification to any topic, camp, or statement and the change becomes live.

**Comment by rupalichavan9860** [comment]
@M-Darab @sajid315 As discussed please refer below steps to reproduce : 
1. User A login - Create topic (user A is supporter)
2. User B login - Submit change to topic/camp/statement and commit (It will be in "in review")
3. Login with User A and submit another change (It will be live)

Actual Result : Change submitted by User B is still in "in review"
Expected Result :  It should become history (blue cards)

**Comment by array-junkie** [comment]
PR Raised: [#742](https://github.com/the-canonizer/canonizer-3.0-api/pull/742)

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by hassaanCD** [comment]
Working fine on live
