### ISSUE TITLE
Need to fix the position of  "Consensus Tree" toggle

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#417]
Steps to reproduce :
1.Go to https://canonizer3.canonizer.com/
2.Login with valid email and password
3.Go to browse 
4.Select any topic
5.Observe "Consensus Tree" toggle

Expected Result : It should not hide any text and icon. It should have fixed position while user scroll the screen.
Actual Result: Now it hide the text, icon and move with the page scroll.

Refer screenshot: https://prnt.sc/7rjmcUrAK9pZ

**Comment by SandeepTalentelgia** [comment]
Closed

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by SandeepTalentelgia** [comment]
Closed, verified on live.
