### ISSUE TITLE
Event Line : Incorrect event listing

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#418]
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/1f973751-77c8-4be8-b550-a10d7ea6de66)

History page for that camp : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/27540478-81ed-45f5-95fb-bfc7e1e763d4)

**Comment by sunilspr7** [comment]
@rupalichavan9860 let me know when we will discussion on this.

**Comment by rupalichavan9860** [comment]
Hello @sunilspr7  I am available starting at 6 PM IST. Could we connect on Friday at 6: 30 PM IST?

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by sandeeptlgt** [comment]
Closed, verified on live.
