### ISSUE TITLE
Need to make the consistency between all the "i" icons on Consensus Tree.

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#419]
Steps to reproduce :
1.Go to https://canonizer3.canonizer.com/
2.Login with valid email and password
3.Go to Consensus Tree
4. Check the i icon of Canonizer Algorithm.

Expected Result : Need to change the colour of  i icons and remove the underline, their should be consistency between all the icons.
Actual Result: Now its in blue colour and shows underline.

Refer screenshot: https://prnt.sc/AJ0mTJay_RyK

**Comment by rupalichavan9860** [comment]
It was link to "Algorithm Information" which is missing in new layout

**Comment by ks-rahul** [comment]
@SandeepTalentelgia @rupalichavan9860 As per the design, the "i" icon serves as the link to the algorithm information. I will add an underline to the "i" icon. Please let me know if you need anything else.


![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/95217406/84a32513-e48e-4cf9-8cce-72d216f08493)

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by hassaanCD** [comment]
@ks-rahul as per the above expected results written by @SandeepTalentelgia , the underline should be removed below all info icons, but here I can see the underline as in screenshot.


![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/120023458/82607b23-5832-40a9-a99b-50c97bcdd1d1)

Also @rupalichavan9860 as you mentioned above that there was a link "**Algorithm Information**", but in the new layout of topic detail page its still missing, Refer both screenshots.


![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/120023458/d1d5743c-bc28-4ec2-b56b-e11813d33ce0)


![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/120023458/5766ee88-9e2c-42e8-9cf8-4796833fcd08)

**Comment by rupalichavan9860** [comment]
In new design of Consensus Tree - This is icon with link which is redirecting to Algorithm information topic page . So this is not an issue and we can close this
