### ISSUE TITLE
User is not receiving post submitted email in below case 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#42]
Steps to reproduce : 
1. Go to https://beta.canonizer.com/
2. Login with valid email and password 
3. Login with User A and creates topic- create sub camps and support them
4. Login with User B and delegate support to User A in any camp
5. Login with User B and add thread to Agreement camp- User A is receiving email
6. Login with User B and submit a post to Agreement camp- User A is not receiving email

Actual Result : As User A is implicit supporter of Agreement of Agreement camp , User A should receive email

**Comment by subhancd** [comment]
working fine on both staging and beta. @rupalichavan9860

**Comment by rupalichavan9860** [comment]
Verified
