### ISSUE TITLE
Recent Activities : Incorrect camp update activity listing 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#421]
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/6647bbc3-3956-4723-b894-b1299e88860c)

**Comment by sajid315** [comment]
@rupalichavan9860 this issue has been resolved for all new activities that will b logged. You can check it on staging site.
After confirmation we can close this ticket. Or you can mention the scenario if Any.

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by rupalichavan9860** [comment]
Verified on live
