### ISSUE TITLE
Nickname > Advance filter and search > Need to implement the points mentioned below.

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#422]
1. Nickname - It should show the list of all the "public" nicknames from the DB.
2. Nickname > Advance filter :
# It should provide the search field to the user to search the Topic and camps.
# If the user tries to search, then it will show the results related to the topics and camps, under the search field.
# If the user selects the topic or camp from the search result then it will filter the nicknames which are the supporter of that particular topic or camp.

**Comment by saniatg** [comment]
Closing for now, when advance filter will be implemented then will check the functionality.
