### ISSUE TITLE
Advance filter and search design implementation

### ISSUE THREAD

**Issue by vikasranatalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#423]
Create static design for Advance filter and search as per the below design:

https://xd.adobe.com/view/fd089c71-f4a0-4c79-a3ae-8a748bd02b94-a85b/?fullscreen

**Comment by SandeepTalentelgia** [comment]
Acceptance criteria for the search functionality

   1. Verify the search field present and aligned.
    2. Verify place holder text added on search or not.
    3. Verify spelling and grammar should be correct for place holder text.
    4. Verify search icon is present on the field.
    5. Verify cursor should present on click on the search icon.
    6. Verify search is functional and generating the correct result for correct keywords or not by adding valid search.
    7. Verify search working by adding keyword and pressing the Enter key from the keyboard.
    8. Verify search working by adding keyword and on click on the search button.
    9. Verify if the user can paste the keyword with the mouse.
    10. Verify search should working in the mobile view.
    11. Verify that it should check the input data for Topics, Camps, Camp statements and Nicknames in the database.
    12. Verify all the labels (Topic, Camp, Camp statement and Nickname) should be shown for every results.
    13. Verify the sequence of labels should be same if data is founded under all the labels.
    14. Verify if "No Data" is founded under any label, then it should be shown at the bottom of the search result.
    15. Verify if date is founded only under any one label, then it should be shown at the top of the search result.
    16. Verify search should work by first added letter by the user in the search field and show the data accordingly.
    17. Verify search result under all the labels should be a link and redirect the user to the selected screen.
    18. Verify that the "View all" link should be added on the result screen.
    19. Verify the "View all" link should redirect the user to the screen where all the data should be present.
    20. Verify on View all screen there should be an option to visit (Topic, Camp, Camp statement and Nickname) separately.
    21. Verify on search result screen, it should allow the user to move up and down by using keyboard.
    22. Verify an error message display by entering invalid keywords in the search field and clicking the search button.
    23. Verify an error message should display for blank input.
    24. Verify and observe how much time required for getting the search result.
    25. Verify a loader added if take time to get the result.
    26. Verify pagination added in case if the search result goes on the number of pages.
    27. Verify pagination is accessible or not by clicking on the Next, Previous and number.
    29. Verify the max and min range for the search keyword.
    30. Verify auto suggestion shown on adding a keyword or not.
