### ISSUE TITLE
Getting "Something went wrong"  error

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#424]
Steps to reproduce : 
1. Login with User A and Create topic 
2. Create 2 camps "Camp 1" and "Camp 2"
3. Support both camps 
4. Login with User B and change parent of "Camp 2" to "Camp 1" from "Agreement"
5. Commit changes
6. Observe 
Actual Result : Getting "Something went wrong" error on committing changes 
![image](https://github.com/the-canonizer/canonizer-3.0-api/assets/40416610/76e64612-a36e-4211-9215-0fed51ac87d7)

**Comment by array-junkie** [comment]
PR Raised: [#738](https://github.com/the-canonizer/canonizer-3.0-api/pull/738)

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Working fine on live
