### ISSUE TITLE
Other than "One Person One Vote" algorithms, scores are wrong.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#426]
Steps to reproduce : 
1. Select any topic
Score for "One Person One Vote " is correct 
2. Select "Canonizer Shares"
3. Observe score on "Consensus Tree "-- Score is correct 

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/2386c4a1-f682-4032-a9d0-82b0d83ec093)
4. Click on cross icon 
5. Again open "Consensus Tree "
6.  Observe score 

Actual Result : scores are incorrect.
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/3b7e56a2-74e1-454f-b9fb-c4fd379d77af)

**Comment by rupalichavan9860** [comment]
@ks-rahul Please check the same for other filters 
I have applied "include review" filter but it is not showing changes: 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/ce64513a-45e4-405e-8ab7-c0d1a23bc89d)

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/d2e871b1-36aa-454f-a200-2738ddf1f6eb)

**Comment by ks-rahul** [comment]
@rupalichavan9860 I have investigated this issue and found that it occurs due to server-side rendering. When the API is called from the server, it uses the "blind_popularity" algorithm default if there is no algo in cookies. I have already reached out to the Code District team regarding this matter, and they have made some changes to that function. Once their code is merged, I will review this ticket again.

**Comment by shahab-ramzan** [comment]
@ks-rahul we've tested this issue locally and its working fine now.

**Comment by rupalichavan9860** [comment]
@shahab-ramzan @ks-rahul This is not working in below case : 
1. Go to home page
2. Select any topic
3. Change algorithm and observe score 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/9bba5b72-9ad2-4a1f-8dcc-edbda519b06d)

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by hassaanCD** [comment]
Working fine on live
