### ISSUE TITLE
Unarchive functionality is not working appropriately 

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#428]
1. login with any user.
2. Click on Browse and select ant topic.
3. Archive the camp having more than 1 supporter and commit the changes.
4. Try to unarchive the camp from its another supporter account.
Expected result: It should allow the user to unarchive the camp.
Actual result: Now unarchives functionality is not working.

**Comment by rupalichavan9860** [comment]
Both submitter and direct supporters getting error "The given data was invalid"

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by SandeepTalentelgia** [comment]
Closed, verified on live.
