### ISSUE TITLE
It does not allow the user to object the camp 2nd time on camp history screen.

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#433]
1.login with any user.
2. Click on Browse and select sandbox testing.
3. Search any topic in the search field.
4. Open the topic and try to update the camp record.
5. After updating the camp, object the record with reason. 
6. After submission observe the object button.

Expected result: It should not allow the user to again object the camp on history screen.
Actual result: Now it shows the object button after the objection.

Refer the screenshot": https://prnt.sc/uxv27Q0tbYEn

**Comment by saniatg** [comment]
working fine
