### ISSUE TITLE
Event Line : For old topics, the page is crashing 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#434]
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/cd62f608-b7ca-405f-8d6e-af3312b9f559)

**Comment by shahab-ramzan** [comment]
@rupalichavan9860 I'm unable to produce this issue locally even I've have created build multiple times. This issue is occurring in few specific topics on staging, I'm still investigating this issue and removing the show-stopper tag as event-line button is disabled on staging.

**Comment by rupalichavan9860** [comment]
This is working fine now

**Comment by sandeeptlgt** [comment]
Closed , verified on live.
