### ISSUE TITLE
It shows invalid validation if user click on object button for the topic which is already objected on topic history screen.

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#436]
1. login with any user.
2. Click on Browse and select sandbox testing.
3. Search topic "Global testing" in the search field.
4. Open manage/edit topic and object the topic.
5. Try to again object the already objected topic.

Expected result: It should allow the user to update the object reason.
Actual result: Now it show the "Topic Num is required".

Refer the screenshot": https://prnt.sc/WTTNZ9OT9f8d

**Comment by saniatg** [comment]
working fine on both servers
