### ISSUE TITLE
Page is crashing on supported camps page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#437]
Steps to reproduce : 
1.Create topic (User A is direct supporter )
2.Login with User B and try to delegate support to User A in topic (Getting error)
3. Try to support camp directly
Actual Result  : getting page crash 

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/d8bf4def-d613-4526-b7de-6a3b77bc8ccb)

**Comment by vikasranatalentelgia** [comment]
@rupalichavan9860 this is same as of ticket #430

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Working fine on live
