### ISSUE TITLE
Canonizer Algorithm is blank by default in below case 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#438]
Steps to reproduce : 
1.Create topic (User A is direct supporter )
2.Login with User B and try to delegate support to User A in topic (Getting error)
3.Try to support camp directly (getting page crash) and observe URL
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/abf6b495-83bf-453b-9d5c-0476c48164d2)
4. Remove URL from topic and observe home page 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/189c9bd4-f6e5-457d-8b10-1b05d6110689)

**Comment by shahab-ramzan** [comment]
@rupalichavan9860 this one is working fine. can you please test it once at your end.

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Working fine on live
