### ISSUE TITLE
Un-archive This Camp: Before unarchiving the camp, the user can submit a change. 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#441]
Please refer attached screenshot : 

![image](https://github.com/the-canonizer/canonizer-3.0-api/assets/40416610/3a53f612-fe39-4d25-b71c-0342b259111c)

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by hassaanCD** [comment]
Working fine on live
