### ISSUE TITLE
Archive camp : Before archiving the camp, the "Submit Camp Update Based On This" buttons are disabled.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#442]
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/f7d6ccf5-4d79-4a86-8343-60fce3e4fe87)

**Comment by rupalichavan9860** [comment]
Not fixed

**Comment by vikasranatalentelgia** [comment]
@rupalichavan9860 Its not replicating at my end, can you please check with new camp
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/98095849/9a261474-9416-4d34-92a8-3bfe57f2c3a7)

**Comment by rupalichavan9860** [comment]
Working fine now so closing this

**Comment by hassaanCD** [comment]
Working fine on live
