### ISSUE TITLE
Its shows the loader on 2nd topic, if user try to select the agree checkbox on topic history screen.

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#443]
1. login with any user.
2. Click on Browse and select sandbox testing.
3. Search any topic in the search field having supporters.
4. Open the topic and update the topic 2 times after commit.
5. Try to select the agree check box on history screen when there is 2 topics needs to be agreed.
6. click on first agree checkbox.
7.  observe the loader on 2nd one.

Expected result: It should not show the loader on 2nd topic.
Actual result: Now it shows the show the loader on 2nd topic.

**Comment by saniatg** [comment]
working on both servers
