### ISSUE TITLE
On camp history screen, if user try to commit the changes, then its shows "Something went wrong" on staging.

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#444]
1. login with any user.
2. Click on Browse and select ant topic.
3. Try to update and archive the camp having more than 1 supporter and commit the changes.
4.  After committing it shows "Something went wrong".

Expected result: It should allow the user to commit the changes.
Actual result: Now the functionality is not working.

Refer screenshot - https://prnt.sc/MKt6jzZlw7WZ

**Comment by array-junkie** [comment]
@SandeepTalentelgia I have checked it on staging and I'm unable to reproduce it. Kindly take a look and if it occurs again, do let me know

**Comment by SandeepTalentelgia** [comment]
Now its working fine

**Comment by rupalichavan9860** [comment]
Working fine on live
