### ISSUE TITLE
Page crash on Supported Camps page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#448]
Steps to reproduce : 
1. Create topic
2. Create camp "Camp 1"
3. Support "Camp 1"
4. Try to support "Agreement"
5. Click on Cancel button 
6. Observe page 
Actual Result : Getting below page crash 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/1013e50b-56ac-41b4-b71a-4e5eba98c8cc)

**Comment by rupalichavan9860** [comment]
This is working now but getting page crash while changing support order ,Please check URL for more details
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/c451439a-5471-4e21-9909-dbe1359b6acb)

**Comment by vikasranatalentelgia** [comment]
This ticket is fixed after Shahab has fixed the create camp issue.

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Working fine on live
