### ISSUE TITLE
Suggestion - For consistency "Recent Activities" column should be extended to cover the right side free space.

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#449]
1. login with any user.
2. Click on Browse and select ant topic.
3. Select any camp from Consensus Tree
4. Check the Recent Activities
 
Refer screenshot - https://prnt.sc/UPH2SAXfGDiF

**Comment by ks-rahul** [comment]
@SandeepTalentelgia This area is intended for the news feed. When an admin is logged in and there are available news articles, those cards will be displayed. The cards are consistently visible in this area, displaying the list of available news data.

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/95217406/d953262d-396f-4e8b-8411-4862459abbbb)

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
