### ISSUE TITLE
On Camp history page, it disable the "Submit camp update based on this" button.

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#450]
1. login with user A and create a new topic.
2. Login with user B and archive the camp for the same topic.
3. Commit the changes.
4. It disable the button "submit camp update based on this" for both users.

Expected result: It should not disable the button.
Actual result: Now It disabled the button "Submit camp update based on this" for both users.

Refer screenshot - https://prnt.sc/-RwQvTUIq_ax

**Comment by rupalichavan9860** [comment]
Duplicate of https://github.com/the-canonizer/canonizer-3.0-frontend/issues/1215
