### ISSUE TITLE
After Creating a new Topic, it shows "The Topic was created on invalid date" and didn't show the created topic details on consensus tree.

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#451]
1. login with any user.
2. Create a new topic.
3. After creating the new topic check the Consensus Tree.
4. On Consensus Tree, it shows "The Topic was created on invalid date" and didn't show the created topic details.

Expected result: It should show the created topic details on the Consensus Tree
Actual result: it shows "The Topic was created on invalid date" and didn't show the created topic details.

Refer screenshot - https://prnt.sc/G9V51SKeIM6m

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Working fine on live
