### ISSUE TITLE
Change is not going live on change approval 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#454]
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/b7ddeee6-b2db-41fa-9f6e-ec43b2c142ca)

**Comment by array-junkie** [comment]
@rupalichavan9860 Could you please reproduce this issue? Kindly do let me know if it is reproducible.

**Comment by rupalichavan9860** [comment]
@M-Darab I am able to reproduce the issue but not sure about the steps . Can we have a call?
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/76612c40-2bef-41e7-a490-0ae79f88180d)

https://canonizer3.canonizer.com/camp/history/2917-Regression-Testing-7-AUG-2023/2-Camp-1

**Comment by array-junkie** [comment]
@rupalichavan9860 Sure at 5 PM PST

**Comment by array-junkie** [comment]
@rupalichavan9860 Kindly make sure steps are correct:

- Login with "User A" and make a Topic
- Create a "Camp1" and add support from "User A"
- Login with "User B".
- Submit a change for "Camp Archieve" & commit from User B. The change will be in_review.
- From "User B", click on "Submit Camp Update Based On This", "Camp Archieve Checkbox" will be checked, Uncheck it and submit a change again.
- Now login with "User A" and accept the 1st change in review first, it will go live.
- Now accept the 2nd change. That change will not go live.

**Comment by array-junkie** [comment]
@nalwa We need to look into this by collective approach because I observed that the issue occurs in the scenario related to camp archive.

**Comment by nalwa** [comment]
@M-Darab  okay, we can connect for this...

**Comment by nalwa** [comment]
@rupalichavan9860  issue is fixed. please confirm

**Comment by array-junkie** [comment]
Another Usecase 

- Login with "User A" and make a Topic
- Create a "Camp1" and add support from "User A"
- Login with "User B" and support "Camp 1".
- Submit a change for "Camp Archive" & commit from User C(non Supporter). The change will be in_review.
- From "User A & B", agree to the change and it will go live.
- Now from "User C(non Supporter)" submit a change for "Camp Unarchive" & commit.

**Expected Result**: The change should go live after both direct supporters' approval.
**Actual Result**: The change is going live if either of the 2 direct supporters agrees.

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Working fine on live
