### ISSUE TITLE
When reloading the website, the dropdown "Show camps with score" displays unnecessary data. 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#456]
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/4c0dbdac-ed22-4bde-a572-a6f70d18ac1b)

**Comment by shahab-ramzan** [comment]
@rupalichavan9860 It's working fine for me. can you test it once again

**Comment by rupalichavan9860** [comment]
@shahab-ramzan Still facing same issue 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/d2e6909f-b3cf-4021-9b1d-4d1853613d93)

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Working fine on live
