### ISSUE TITLE
Issues on history pages

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#459]
Issue 1 : Number of supporters list is incorrect
Steps to reproduce : 
1. Create topic -Create "Camp 1" and support "Camp 1"(User A is supporter)
2. Login with User B and update camp - Select "Camp Archive"
3. Login with User A and agree changes
4. Login with User B and click on "Un-Archive This Camp " and commit changes 
5. Observe page (User B )
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/24b93a02-8cad-4022-bf40-436b862337b5)

**Comment by rupalichavan9860** [comment]
Not fixed

**Comment by rupalichavan9860** [comment]
Issue 1 : Number of supporters list is incorrect
Steps to reproduce : 
1. Create topic - User A is supporter of Agreement Camp 
2. Login with User B and update camp - Select "Camp Archive"
3. Login with User A and agree changes
4. Login with User B and click on "Un-Archive This Camp " and commit changes 
5. Login with User A and agree changes 

Expected Result : The camp should be unarchived immediately, and support should be restored at the end of support order.
Actual Result : The camp is not getting unarchived. It is showing "2 out of 3 required supporters have agreed"

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/f276e4f1-9248-4d4b-9a5f-b097dda4de06)

**Comment by array-junkie** [comment]
PR is raised: https://github.com/the-canonizer/canonizer-3.0-api/pull/752

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
