### ISSUE TITLE
Un-Archive This Camp: The first click results in nothing, while the second click results in the creation of two entries.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#460]
Steps to reproduce : 
1. Create topic and create camp "Camp 1"
2. Support "Camp 1"
3. Login with User B and make "Camp 1" archive 
4. Login with User A and agree changes
5. Try to unarchive the camp
Actual Result  : The first click results in nothing, while the second click results in the creation of two entries and when user commit changes , it is showing below two entries
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/82621c60-cd22-4a42-afec-0d296cd5b325)

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by hassaanCD** [comment]
Working fine on live
