### ISSUE TITLE
When a user changes the order of support (from manage support support-supported camps), the URL is wrong.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#461]
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/d9174f1b-462a-4fde-a75c-ca23a2294079)

**Comment by vikasranatalentelgia** [comment]
@rupalichavan9860 it's not replicating. Can you please elaborate more?

**Comment by rupalichavan9860** [comment]
@vikasranatalentelgia Please refer below steps : 
Case 1 : Drag and drop 2 camps multiple times and check
Case 2 : 
1. Create topic and create 2 camps 
2. Support both camps 
3. Try to support "Agreement" and observe page 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/4a443f84-648d-4bb5-b40a-218e95aea633)

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/4010f136-7a79-42ff-9d55-e842b379f975)

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Working fine on live
