### ISSUE TITLE
Parent change: The hierarchy is not reflected in the Consensus Tree. 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#462]
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/612bc205-9c76-423c-8b75-14ed04bfcb0f)

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/de49beb4-914c-491c-8f9a-3fc1840433b6)

**Comment by rupalichavan9860** [comment]
This exists for this topic https://canonizer3.canonizer.com/topic/2929-Testing-8-aug/3-Camp-2?score=0&algo=blind_popularity&asof=default&canon=1&is_tree_open=0

Also Please find supported camps page : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/0f74dc80-df45-4fea-bfdf-9d0ff46cc23f)

**Comment by sajid315** [comment]
@rupalichavan9860 I have reviewed the above topic and i tried to do the same like the steps in above topic. 
Here below is the reference URL that i made for testing and hierarchy is working for me. 

I think we need a call regarding this issue.

https://canonizer3.canonizer.com/topic/2938-TE2/1-Agreement?score=0&algo=blind_popularity&asof=default&canon=1&is_tree_open=1

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/111273633/335b16b0-33bd-419b-aa36-d1b618b6f0ab)

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/111273633/fa531e0f-b0b6-452d-9777-92148ad1abc5)

**Comment by sajid315** [comment]
@rupalichavan9860 do you found the same issue, I tried the hierarchy change again by including multiple supporters and by changing the preferences. But not found the exact.
Let me know if you ll find it in any scenario.

**Comment by rupalichavan9860** [comment]
@sajid315 I am trying to reproduce the same . I will let you know the scenario

**Comment by sajid315** [comment]
@rupalichavan9860 do you able to found the issue related to above scenario you mentioned ? Or we can close the ticket.

**Comment by rupalichavan9860** [comment]
@sajid315 I am not able to reproduce the same case but for topic below , I am getting error 

https://canonizer3.canonizer.com/topic/2929-Testing-8-aug/1-Agreement?score=0&algo=blind_popularity&asof=default&canon=1 

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/62fa6635-8b2e-4c41-8b72-2aa32bae209b)

**Comment by sajid315** [comment]
> @sajid315 I am not able to reproduce the same case but for topic below , I am getting error
> 
> https://canonizer3.canonizer.com/topic/2929-Testing-8-aug/1-Agreement?score=0&algo=blind_popularity&asof=default&canon=1
> 
> ![image](https://user-images.githubusercontent.com/40416610/274724151-62fa6635-8b2e-4c41-8b72-2aa32bae209b.png)

Yes this is recent issue and @shahab-ramzan  will fix it in ticket #538.

**Comment by rupalichavan9860** [comment]
Unable to reproduce

**Comment by rupalichavan9860** [comment]
As of now this is working fine on live so closing this
