### ISSUE TITLE
Its shows "Invalid date" for "Go live time" on Camp statement..

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#463]
1.Create topic.
2.Create 2 camps "Camp 1" and "Camp 2"
3.Support both camps
4.Update "Camp 2" - check "Camp Archive" and commit changes
5.Click on "Unarchive This Camp"(Do not commit changes)
6.Click on Edit change and change parent from "Agreement" to "Camp 1"
7. Check "Go live time".

Actual result : Its shows "Invalid date" for "Go live time" on Camp statement..

Refer screenshot :https://prnt.sc/1-tWSEQLwRwg

**Comment by rupalichavan9860** [comment]
Duplicate #https://github.com/the-canonizer/canonizer-3.0-api/issues/748
