### ISSUE TITLE
When a user clicks on a topic or camp link from a place below, the scores that are displayed are wrong.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#465]
Steps to reproduce : 
1. Go to https://canonizer3.canonizer.com/
2. Select Algorithm other than "One Person One Vote"
3. Go to Account settings ->Supported Camps 
4. Click on any topic /camp 
5. Observe score 

Actual Result : The selected algorithm is different, but the score is displayed according to "One Person, One Vote."
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/b6cee4e9-1fba-49d7-bb05-d332f4d0ba98)

**Comment by rupalichavan9860** [comment]
Same from User Profile /user supports page

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by hassaanCD** [comment]
Working fine on live
