### ISSUE TITLE
Register Now link is not working on login screen.

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#467]
1. Click on Canonizer logo for staging application.
2.  Click on login. 
3.  Try to open the Register now link

Refer screenshot : https://vimeo.com/853349543/c1f0c89061

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Working fine on live
