### ISSUE TITLE
Show camps with scores: 10% as the default value

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#469]
As discussed in the meeting, the default value should be changed to "10%" rather than "50%," and if the user changes the percentage, it should be recorded in session and maintained.

It is not currently maintaining the session value.

**Comment by ashish76** [comment]
@rupalichavan9860 Based on the description, we have implemented this ticket. The functionality works like as mentioned below.

- The default camp score percentage will be 10% and will be taken as the selected value to maintain the session. The session will be maintained within the same browser on different tabs for all camps.

- If a user changes the value of the camp score,  then the previous set value will be replaced by the new value.

- The text "Show camps with score > <score in percent>" is changed by "Collapse camps with less than <score in percent> of all support"

We haven't raised the PR of this ticket. If you can define the acceptance criteria of this functionality then we can validate the test cases.

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by rupalichavan9860** [comment]
Verified on live
