### ISSUE TITLE
For staging - Need to set the design for Select Canon drop down.

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#472]
1. login with any user.
2. Click on Canonizer logo.
3. Check the design for Select Canon drop down.

Refer screenshot -https://prnt.sc/fhF0MtoorJc6

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
