### ISSUE TITLE
Change went live without all implicit supporter's approval

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#476]
Steps to reproduce :  
1. Create topic
2. Create camp "Camp 1"
3. Support "Camp 1" with User A and User B
4. Login with User A and update  "Agreement" camp - make it archive
5. Camp is archived after User B's approval (Working fine)
6. Login with User A or User B and update "Agreement" camp -unarchive the camp 

Expected Result : If User A submits a change to unarchive ,change must be in "In review" and it should go live on User B's approval 
 If User B submits a change to unarchive ,change must be in "In review" and it should go live on User A's approval 

Actual Result : Change is going live immediately and camp is unarchived

**Comment by nalwa** [comment]
@rupalichavan9860  this is not implemented, do we need approval of implicit users for un-archiving, can you please confirm it?

**Comment by rupalichavan9860** [comment]
Yes @nalwa

**Comment by rupalichavan9860** [comment]
@nalwa Mentioned scenario is working fine but it is not listing implicit supporter name in pop up 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/7a5e3841-757e-4bbf-a3b7-a0780c355b78)


![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/d39f6b2f-1b10-463d-89c4-7aff99faace6)

**Comment by sajid315** [comment]
Verified the below cases on staging and local system as informed by @nalwa

Steps:
1. create a topic 
2. create a camp and support it from 2 users
3. now make any changes in agreement camp like statement change
4. commit the changes and submit it 
Result: it  goes live 
Expected: it should go in-review for approval of other implicit supporter 

So after verification it observed that the above scenario is working now. Only part was the ENV keys missing.
