### ISSUE TITLE
Live topic name is not displayed in the consensus tree and on the browse page.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#481]
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/25ff7b64-55e9-4b25-8cb6-a8add1a46993)
Consensus tree : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/e418d61b-f439-4c88-a6d5-51997e6e6be4)

Browse Page : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/5cfcf05f-432e-4842-9e7d-e1272bb26e88)

Steps to reproduce : 
1. Change topic name (It will go live after 24 hrs.)
2. Observe topic name in the consensus tree and on the browse page.

**Comment by sandeeptlgt** [comment]
Closed, verified on staging.

**Comment by rupalichavan9860** [comment]
Verified on live
