### ISSUE TITLE
 It does not allow the user to access the live topic by search, Once the topic name is updated or created by using round brackets ( ), then it shows "No Data".

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#482]
Steps to reproduce.
1. login with any user on staging server.
2. Search any topic and update the topic name.
3. Commit the changes.
4. Once the topic is live, try to search the same topic again in the search field.
5. Observe the result.

Expected result - it should allow the user to search the topic and show results.
Actual result - it shows "No data" 

Refer screenshot - https://prnt.sc/SjUCLQndd7Rc
https://prnt.sc/3pKMMBHDZZ9S

**Comment by array-junkie** [comment]
@SandeepTalentelgia Kindly provide acceptance criteria.

**Comment by SandeepTalentelgia** [comment]
@M-Darab Please check the acceptance criteria.

1. It should allow the user to search the topics by name in the search field.
2. It should redirect the user to the detailed screen when user click on any search result.
3. It should allow the user to add all type of brackets in the topic's name.
4. In the Search result, it should show the topics in which brackets have been used for topic name.
5. It should redirect the user to the detailed screen when user click on the topic having brackets, in the search result.

**Comment by array-junkie** [comment]
@SandeepTalentelgia OK! I'll start development.

**Comment by array-junkie** [comment]
PR Raised: [#255](https://github.com/the-canonizer/canonizer-service/pull/255)

**Comment by array-junkie** [comment]
@akashgit77 Please write test cases for this.

**Comment by akashgit77** [comment]
@M-Darab sure

**Comment by sajid315** [comment]
Written the unit test case and some fixing regarding this 
PR raised,
https://github.com/the-canonizer/canonizer-service/pull/257

**Comment by saniatg** [comment]
working fine on staging

**Comment by saniatg** [comment]
working fine on production
