### ISSUE TITLE
When a user clicks Unarchive this camp, it redirects to the camp update page rather than creating a new record on the history page.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#485]
Steps to reproduce : 
1.User A is the camp supporter
2.User B archived the camp, and User A approved the change. 
3.Unarchived the camp by User B 
4.User A objected to the change. 
5. The most recent entry is objected , and the user can archive from the second record.
6. Select Unarchive this camp. 

Actual Result : It redirects to the camp update page rather than creating a new record on the history page.

**Comment by sandeeptlgt** [comment]
@nalwa it's not fixed, i have verified it on staging.

**Comment by rupalichavan9860** [comment]
Working fine on live
