### ISSUE TITLE
User Profile : Selected canon Id isn't included in the URL

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#489]
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/394d042c-b100-4f91-8fb4-7bfa2ca11a32)

**Comment by ks-rahul** [comment]
The acceptance criteria for this ticket are as follows:

1. Selected canon ID in URL will be selected in the dropdown.

@rupalichavan9860  Please review the following acceptance criteria and add any that may be missing.

**Comment by rupalichavan9860** [comment]
Working fine on development and staging server

**Comment by rupalichavan9860** [comment]
Verified and working fine on live
