### ISSUE TITLE
Issues in Notifications - When user delegates support to other user

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#49]
Steps to reproduce : 
1. User A supports "camp 1", " "camp 2",  "camp 3",  "camp 4",  "camp 5",  "camp 6"
2. User B delegate support to User A in  "camp 6"

User A receives below notification : 
![image](https://user-images.githubusercontent.com/40416610/204238922-3e979f1c-2d25-4a33-aa41-d9625bd94bd2.png)

As delegate is not camp specific and it is user specific - It should say "`<nick name>`has just added delegate support to `<nick name>` in this topic : <topic name>"

**Comment by subhancd** [comment]
not fixed
![Image](https://user-images.githubusercontent.com/104552751/204718496-30a376a5-9859-4ab9-a7ed-ba456c430d02.png)

**Comment by subhancd** [comment]
working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on beta
