### ISSUE TITLE
Live Recent Activities (Threads) : Thread names are displaying as undefined 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#490]
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/0dba550a-9bde-4935-bc1d-34a2522c5636)

**Comment by rupalichavan9860** [comment]
@sajid315 Camp name is also "undefined"
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/a8d7b0c0-5bab-4a1f-b568-f0694a228950)

**Comment by sajid315** [comment]
This issue fixed on production, below are the PR's raised as Hotfix from front end side. 
https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1272
https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1271
https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1270
https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1269

Rest of the work will be fixed on staging first in ticket #191 as discussed with @rupalichavan9860 in call.

@rupalichavan9860 you can move this ticket ahead.

**Comment by rupalichavan9860** [comment]
Working fine on live
