### ISSUE TITLE
Recent Activities : One activity appears several times. 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#493]
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/6811c9ad-17b2-44ba-9bf9-4d8d3558e8a6)

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/d1fe9800-d2b1-4274-9318-9a3dbbac1d40)

**Comment by array-junkie** [comment]
PR Raised for Development: https://github.com/the-canonizer/canonizer-3.0-api/pull/772
PR Raised for Production: https://github.com/the-canonizer/canonizer-3.0-api/pull/773

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by rupalichavan9860** [comment]
Verified on live
