### ISSUE TITLE
Object button is enabled on the archived camp's subcamp's history pages 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#494]
1. Submit change for subcamps 
2. Archive parent camp 
3. Observe history pages 
4. Click on Object 

Getting error "Something went wrong" .
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/5c407ec0-850a-400d-822b-df9b2c875e91)

and below error when submitting objection : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/bf39f8f7-4c5f-44f3-86fc-a539a6fd46cb)

**Comment by sandeeptlgt** [comment]
Closed, verified on staging.

**Comment by rupalichavan9860** [comment]
This is not working . But created new ticket for the same so closing this
