### ISSUE TITLE
If user select the "As of date", and try to add the new camp then it shows the name of added camp as blank on live server.

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#496]
Steps to reproduce:
1. Login with any user on live.
2. Select any topic and open the "Consensus Tree".
3. Select "As of date".
4. Try to add a new camp or a sub-camp.
5. After creating the camp, check the name of the camp.

Actual result: It can't show the camp name, it shows as blank.
Expected result: It should show the name.

Refer screenshot:
![Screenshot (32)](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/129028750/a5d58c3e-c12b-4368-ab47-0c1d370b42e6)

**Comment by sajid315** [comment]
@SandeepTalentelgia , @rupalichavan9860 
I did debugging to find out this issue when user selects the "AsOfDate" filter first then create the new camp. 
As currently on redirection it redirect the user to new camp breadcrumb node at topic detail page. 

So in above scenario as we discussed in call we should hide the breadcrumb Or we can display the breadcrumb till the parent of camp. 

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/111273633/cf139f54-8a91-4e0d-aab3-f0798e91bd65)

**Comment by sajid315** [comment]
@akashgit77 Can you please write selenium for this specific issue, This issue was related to missing breadcrumb. 

Steps to create: 
1- Create any topic.
2- Create camp in it (Add support is optional).
3- Select as of date filter, now click on create camp on topic detail page. 
4- After creating new camp you will see the breadcrumbs are missing.

**Comment by akashgit77** [comment]
@sajid315 After deployment on "Development Server" i will test it.
