### ISSUE TITLE
For non-supporter user, unarchive button works by clicking twice.  

### ISSUE THREAD

**Issue by sandeeptlgt** [the-canonizer/Canonizer-Beta--Issue-Tracking#498]
Steps to reproduce:

1. Login with user A having 1 supporter (user B) on live.
2. Archive the camp from the account of user A and commit the changes.
2. Agree the changes from the account of user B.
3. Try to unarchive the same camp from the Creator / non-supporter user.
4. On first click on "Unarchive" button it does not work, we need to click twice on the "unarchive" button.

Actual result: To unarchive the camp user need to click twice on the "unarchive" button.
Expected result: Unarchive button should work on first click.

Refer screenshot:

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/108800065/e2dd731c-5765-43fc-a388-ec099a37db81)

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine production
