### ISSUE TITLE
Incorrect score and choice number is displaying in below case 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#5]
Steps to reproduce : 
1. Go to https://canonizer3.canonizer.com/ 
2. Login with User A and create topic
3. Create camp "Camp 1" and support "Camp 1"
4. Login with User B and submit topic change and commit changes
5. Delegate support to User A in "Camp 1"
6. Login with User A and create another camp "Camp 2" and support "Camp 2"
7. Observe score and choice numbers for "Camp 2"

Expected Result  : 
Camp 1: Score must be "0.75" for both User A and User B and choice numbers must be "1" and Total: 1.50
Camp 2: Score must be "0.25" for both User A and User B and choice numbers must be "2" and Total : 0.50
Topic total score must be : 2

Actual Result : 
Please refer attached screenshot : 
Camp 1: 
![image](https://user-images.githubusercontent.com/40416610/203247691-3d029a51-2e81-4e67-8f12-becf5308a554.png)

Camp 2 : 
![image](https://user-images.githubusercontent.com/40416610/203247589-ed3d31d0-dfb0-4bbb-b7e3-e0d15ac78223.png)

Total topic score : 
![image](https://user-images.githubusercontent.com/40416610/203248170-742a4ef9-5a17-4bea-ba02-36f928c7ea8c.png)

**Comment by rupalichavan9860** [comment]
Not able to verify as support tree is having score issues https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/issues/66

**Comment by subhancd** [comment]
working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on beta
