### ISSUE TITLE
Incorrect camp names listing in below case

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#50]
Case : 
User A is supporting "Agreement" camp 
User B is supporting "Camp 1" and "Camp 2"

Now login with User C - support "Agreement" camp and observe email

User A and User C receives below email : Incorrect camps listing
![image](https://user-images.githubusercontent.com/40416610/204268167-8b0059b1-b404-4e19-972f-c327b5834c14.png)

![image](https://user-images.githubusercontent.com/40416610/204268246-3db7ec3f-69c9-4e15-b0a0-6e6510cf72c2.png)

"Camp 1" and "Camp 2" listing instead of "Agreement"

User B receives below email : Correct
![image](https://user-images.githubusercontent.com/40416610/204268000-f029f6dc-a29f-4b2e-b599-c7351843d9b1.png)

**Comment by nalwa** [comment]
@rupalichavan9860  issue fixed. please verify

**Comment by subhancd** [comment]
fixed. working fine on staging

**Comment by subhancd** [comment]
working fine in beta. @rupalichavan9860 kindly, close the ticket
