### ISSUE TITLE
The same nick name appears multiple times on the Direct Supporters pop up. 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#500]
Steps to reproduce : 
1. User A : Create topic
2. User A : Create 2 camps "Camp 1" and "Camp 2"
3. User A : Support both camps 
4. User A : Archive "Camp 1"
5. User A : Archive "Camp 2"
6. User A : Support "Agreement" camp
7. User B : Archive "Agreement" camp (It will be in "In review")
8. Observe History page and pop up 

Please refer attached screenshot : 

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/3661abcd-ac9f-4d9f-891e-9a7beb9e9d65)

**Comment by nalwa** [comment]
@rupalichavan9860  and @vikasranatalentelgia  this issue got fixed with ticket #495.

**Comment by rupalichavan9860** [comment]
Working fine on live
