### ISSUE TITLE
Camp History Page : For the first three versions of the following camp, the camp name is missing.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#501]
Please refer topic/camp :  https://canonizer3.canonizer.com/camp/history/88-Camp2DSFVAL/14-SCVR

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/bbe30c86-4b4b-4107-ba2d-66b6ddbd2453)

**Comment by rupalichavan9860** [comment]
@shahab-ramzan This is not fixed on development server 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/cf8674c4-de2f-44fa-a164-bbad4d5079f3)

**Comment by subhancd** [comment]
verified on development server

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by hassaanCD** [comment]
Verified on production
