### ISSUE TITLE
For staging and live - Non supporter receives the approval check box. 

### ISSUE THREAD

**Issue by sandeeptlgt** [the-canonizer/Canonizer-Beta--Issue-Tracking#504]
Steps to reproduce:
1. Create a topic with "User A" and then create a sub-camp "C1" and support it.
2. Login with "User B" and create a sub-camp C11 under C1 and support it. (User A supports camp C1 and User B supports C11 which is the child of C1)
3. Login with User C and submit a "Camp Archive" change in the "Agreement" camp & agree with both User A & B. The change will go live.
4. Now again submit a "Camp Unarchive" change from user A. 
5. In users B's account, it sends the approval with message "2 out of 2 required supporters have agree" and accept the changes.
6. Now check both user's account A and B, it shows same screen with message "2 out of 2 required supporters have agreed", and changes didn't go live.
7. Check the user C (Non supporter) account, it shows the approval message with check box. 

Expected results: Non supporter should not receive the approval, changes should go live once approved by user B. 
![screenbud-15efaeac-3f59-4a6d-b057-3b376da20063](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/108800065/f859e2ee-52a9-4106-8cb8-56d208fec791)
![Screenshot (36)](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/108800065/eddbe484-ad0b-484c-b5ad-9fbe221cf106)

**Comment by rupalichavan9860** [comment]
On step 3 when User C archives the camps , observe supporters pop up 

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/626631dc-e56b-46f3-a09a-cb7a7753cc3c)
User A's name is listing twice


When User A agrees the change : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/53586920-8646-43de-89af-8b5a6cb954cd)

**Comment by nalwa** [comment]
@sandeeptlgt  i have checked this issue it is working fine for me on my local and Staging its also working fine

can you please re-verify this ticket.

**Comment by sandeeptlgt** [comment]
Closed, verified on staging.

**Comment by rupalichavan9860** [comment]
This is still not working in some cases 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/8cd366c5-e3f1-45e7-95c0-7947ea703fca)

**Comment by saniatg** [comment]
working fine for me on live and staging @rupalichavan9860 please confirm
