### ISSUE TITLE
Theories of Consciousness - timeline event

### ISSUE THREAD

**Issue by sunilspr7** [the-canonizer/Canonizer-Beta--Issue-Tracking#505]
Theories of Consciousness 
SCVR did not showing create event. 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/6298462/9497a40c-6461-4078-899a-9ba50a0f05b8)
![Screenshot 2023-09-18 162743](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/6298462/bfbec9bf-4b02-4a2c-acef-f6c3856103db)

**Comment by rupalichavan9860** [comment]
@sunilspr7 It is still not working . Please check

**Comment by rupalichavan9860** [comment]
Verified on development server

**Comment by rupalichavan9860** [comment]
Verified on live
