### ISSUE TITLE
Event line - It shows topic name instead of agreement camp on the events hyper link.

### ISSUE THREAD

**Issue by sandeeptlgt** [the-canonizer/Canonizer-Beta--Issue-Tracking#506]
Steps to reproduce:

1. Login with any user on staging.
2. Create a new topic.
3. Open event line and check the support event link.
Expected result: it should show the Agreement camp name instead of Topic name.

Refer screenshot:
![Screenshot (38)](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/108800065/9ab2fbd7-c1a8-4abe-a99d-80cf198661b3)

**Comment by saniatg** [comment]
working fine on staging

**Comment by hassaanCD** [comment]
Verified on production
