### ISSUE TITLE
Event line - For "one person one vote" it shows, created event and added support in one event link.

### ISSUE THREAD

**Issue by sandeeptlgt** [the-canonizer/Canonizer-Beta--Issue-Tracking#507]
Steps to reproduce:

1. Login with any user on staging.
2. Create a new topic.
3. Open event line and play the events.
4. Check the event link
Actual Result: it shows, created event and added support in one event link.
Expected result: it should show both the actions in 2 different steps as shown for other algorithms.

Refer screenshot:
![Screenshot (39)](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/108800065/18a2d17f-3fba-4b74-869f-4b4b5500ea4e)
![Screenshot (38)](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/108800065/4f72b518-398e-4027-b69a-073840c08dbe)

**Comment by saniatg** [comment]
working fine on staging

**Comment by hassaanCD** [comment]
Verified on production
