### ISSUE TITLE
While edit it can't update the status of camp as archived.

### ISSUE THREAD

**Issue by sandeeptlgt** [the-canonizer/Canonizer-Beta--Issue-Tracking#508]
Steps to reproduce:

1. Login with any user on staging.
2. Create a new topic and camp.
3. Try to update the camp and click on submit without updating any change (do not commit).
4. Edit the camp, select the archive checkbox and submit.
5. Observe the camp archive status.

Actual Result: it shows, the status of camp as Not archived.

Expected result: it should show the status as Archive.

https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/108800065/ab1bd1ab-5584-4678-a910-5ba943173ff7

**Comment by rupalichavan9860** [comment]
Working fine on live
