### ISSUE TITLE
Event line- Some time it can't load the data and show api status as 422.

### ISSUE THREAD

**Issue by sandeeptlgt** [the-canonizer/Canonizer-Beta--Issue-Tracking#509]
Refer screenshot
![Untitled](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/108800065/01f83b02-0ea6-487c-91a7-a630995488f6)
![SharedScreenshot12](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/108800065/2ec3974b-ae19-4f5f-badb-90d33ff27ccd)

**Comment by sunilspr7** [comment]
@sandeeptlgt eventline url is not correct. 
correct url in this format - https://canonizer3.canonizer.com/eventline/3234-EventLine-20

**Comment by sandeeptlgt** [comment]
Closed, verified on dev.
