### ISSUE TITLE
in Tree new camp is showing while in breadcrumbs and camp record old name is showing for the following case

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#51]
**Steps to reproduce**

1. create a topic
2. create a camp, camp1
3. change camp name, c1
4. view this version of old camp name
5. click on camp forum 
6. click on camp name from the breadcrumbs. 

**Actual Result**
in tree new camp name is showing while in breadcrumbs and camp record old camp name is showing. 
![image](https://user-images.githubusercontent.com/104552751/204450807-2ae78602-18e0-46b4-9382-2949eab2d608.png)

**Comment by sajid315** [comment]
@shahab-ramzan we need to pass correct payload parameters and also the ( fetch_topic_history = 1 ) in get API. I verified the API endpoints.

**Comment by subhancd** [comment]
working fine on staging

**Comment by subhancd** [comment]
working fine on beta
