### ISSUE TITLE
change auto commit is not working for history pages

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#510]
**Steps to reproduce**

1. login with valid credentials
2. create a topic
3. add one camp statement 
4. submit a change to the camp statement -- do not commit the change
5. wait for 1 hour
6. navigate to history page after 1 hour

**Actual Result**

change is not live. it is in review

**Expected Result**

change should go live as there's only one supporter of that camp

![Image](https://user-images.githubusercontent.com/104552751/269288660-092aad62-3acf-478d-aa8e-943c474fec91.png)

**Comment by subhancd** [comment]
verified on development server

**Comment by subhancd** [comment]
verified on staging

**Comment by hassaanCD** [comment]
Verified on production
