### ISSUE TITLE
on camp history page Delegate supporters name was appearing in "supporter agreed" popup in case of archive event.

### ISSUE THREAD

**Issue by nalwa** [the-canonizer/Canonizer-Beta--Issue-Tracking#511]
https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/issues/495 while solving this issue

 I encountered  one  more issue that delegate supporters were listed in popup (agreed supporters).

where as actual result: only direct supporters are eligible to approve any change and  only that should be displayed in popup as well.

**Comment by sandeeptlgt** [comment]
Closed, verified on staging.
