### ISSUE TITLE
Event line - after creating new topic/camp, eventline links redirect the user to the agreement camp and select default in the Consensus Tree.

### ISSUE THREAD

**Issue by sandeeptlgt** [the-canonizer/Canonizer-Beta--Issue-Tracking#512]
Steps to reproduce:
1. login with any user.
2.  Create a new topic/camp.
3.  Go to event line and click on the event link.
4. Observe the result after redirect.

Expected result: it should select the as of date on the consensus tree.

Refer screenshot:

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/108800065/794d9e33-d142-4204-90d5-76bc2710dbe6)

**Comment by sunilspr7** [comment]
I have checked and this issue related to frontend developer side. @vikasranatalentelgia please check this. 
Update/add these two paramerters in Url 
example : -  &asofdate=1695286321&asof=bydate 
asofdate = timestamp 
asof = bydate (fixed this word)

**Comment by vikasranatalentelgia** [comment]
@sunilspr7 The parameters are already there in the URL. 
![image_2023_09_26T04_14_13_101Z](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/98095849/af67ca8b-cd9f-4906-b847-34b16b7ebeef)

**Comment by sunilspr7** [comment]
@sandeeptlgt  this ticket related to https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/issues/531 
#531 
So closed this ticket.

**Comment by sandeeptlgt** [comment]
Closed, verified on dev.

**Comment by saniatg** [comment]
working fine on staging

**Comment by hassaanCD** [comment]
Verified on production
