### ISSUE TITLE
Event line - After removing the delegate support, it redirect the user to the supported camp screen from the event line link.

### ISSUE THREAD

**Issue by sandeeptlgt** [the-canonizer/Canonizer-Beta--Issue-Tracking#513]
Steps to reproduce:

1. login with user A on staging.
2. Create a new topic and camp.
3. Login with user B and provide the delegate support to the camp.
4. Remove the delegate support.
5. Go to event line and click on the event link.
6. Observe the result after redirect.
Expected result: it should redirect the user to the user support screen.

refer screenshot- https://prnt.sc/EvUnDpyWieOR

**Comment by sunilspr7** [comment]
@sandeeptlgt 
add Direct support , add Delegate support, removed Direct support and Removed Delegated support link here 
Supported Camps ( /support/topic_num-topic_name/camp_num-camp_name

**Comment by sunilspr7** [comment]
@sandeeptlgt closed this ticket. We have already ticket for this #531

**Comment by saniatg** [comment]
working fine, user will see the topic page.

**Comment by rupalichavan9860** [comment]
Working fine on live
