### ISSUE TITLE
Event line - if supporter change the parent, then it redirects the user to the camp detail screen, from the event line link.

### ISSUE THREAD

**Issue by sandeeptlgt** [the-canonizer/Canonizer-Beta--Issue-Tracking#514]
Steps to reproduce:

1. login with user A on staging.
2. Create a new topic and camp.
3. Login with user B and provide the direct support to the camp.
4. Change the parent of the camp by user B.
5. Go to event line and click on the event link.
6. Observe the result after redirect.
Expected result: it should redirect the user to the history screen.

**Comment by rupalichavan9860** [comment]
Not fixed

**Comment by sunilspr7** [comment]
@rupalichavan9860 related to #531

**Comment by saniatg** [comment]
working fine on staging

**Comment by rupalichavan9860** [comment]
Working fine on live
