### ISSUE TITLE
 Live topic name is not displayed on the event line and it can't generate the event link.

### ISSUE THREAD

**Issue by sandeeptlgt** [the-canonizer/Canonizer-Beta--Issue-Tracking#516]
Steps to reproduce:

1. Login with any user on staging.
2. Change topic name (It will go live after 24 hrs.)
3. Observe topic name and link on the event line screen.

Expected result: it should update the topic / camp name on the event line screen and create the link.

Refer screenshot:
![Screenshot (42)](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/108800065/41799e62-43f2-445e-bb68-7db07f2fb26a)
![Screenshot (41)](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/108800065/f98be067-63ff-43cc-921f-74cb6a69b983)
![Screenshot (40)](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/108800065/69efd9a2-4ab4-484e-8672-0b0e4e7b96e4)

**Comment by saniatg** [comment]
working fine on staging

**Comment by hassaanCD** [comment]
Verified on production
