### ISSUE TITLE
Edit Camp/ Topic - "Submit Update" button should be disabled until there no change in the data. Initially button should be disabled and should be enabled if there is change in any field.

### ISSUE THREAD

**Issue by sandeeptlgt** [the-canonizer/Canonizer-Beta--Issue-Tracking#517]
Steps to reproduce:
1. Login with any user.
2. Create a topic and camp.
3. Try to update the topic and camp.
4. Observe the "submit update" button.

Expected result: "Submit Update" button should be disabled.

**Comment by subhancd** [comment]
verified on development server

**Comment by subhancd** [comment]
verified on producation
