### ISSUE TITLE
Register : register is not working on the development server

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#518]
**Steps to reproduce**

1. navigate to https://development.canonizer.com/
2. click on register
3. enter valid data in all the fields
4. click on register

**Actual Result**
it throws an error

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/05f41298-7061-4b56-bd5e-835bf5385e9c)

**Expected Result**
It should let the user register

**Comment by ks-rahul** [comment]
@subhancd Google captcha keys are not updated in the env.

@akuks could you please check and update?

**Comment by akuks** [comment]
@gautamv16 can you please create the keys

**Comment by ashish76** [comment]
@subhancd Register functionality is working now. The issue was related to a missing captcha key in the development environment. Please verify this once again.

**Comment by subhancd** [comment]
verified on development server. working fine

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Working fine on live
