### ISSUE TITLE
Login : Login with "Google" on development server redirects user to the live server

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#519]
**Steps to reproduce**

1. navigate to https://development.canonizer.com/
2. click on login
3. login with "Google"
4. observe the result

**Actual Result**
user is redirected to the live server after login

**Expected Result**
user should be redirected to the development server after login

**Comment by ks-rahul** [comment]
@subhancd we can do this in 2 ways:
1. we create new credentials with the development redirection URL and update them in the respective env.
2. update the current URL in the env and all social login provider consoles. 

My recommendation is to create new credentials for the new development server and update them in the respective environment.

@akuks @gautamv16 please do the needful.
