### ISSUE TITLE
"camp created on this date" should be displayed inside the canonizer tree when as of date filter is applied

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#520]
**Steps to reproduce**

1. navigate to any topic
2. navigate to camp
3. apply as of date filter
4. observe the camp created message

**Expected Result**
camp created message should be displayed on the canonizer tree page

**Actual Result**
camp created message is displayed on topic detail page

**Comment by subhancd** [comment]
verified on development server

**Comment by subhancd** [comment]
verified on staging

**Comment by hassaanCD** [comment]
Verified on production
