### ISSUE TITLE
Event line - need to set the design on event line screen. 

### ISSUE THREAD

**Issue by sandeeptlgt** [the-canonizer/Canonizer-Beta--Issue-Tracking#523]
Steps to reproduce:
1. login with any user on development server.
2. Open event line screen.
3. Click on play button and observe the design.

Refer screenshot -

![screenbud-5699685d-645d-4eaa-8468-8a237ab40490](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/108800065/3ce59456-921a-42be-97e0-b469712d5e09)

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by hassaanCD** [comment]
Verified on production
