### ISSUE TITLE
Event line - it can't load the data if user change the Algo on the development server.

### ISSUE THREAD

**Issue by sandeeptlgt** [the-canonizer/Canonizer-Beta--Issue-Tracking#524]
Steps to reproduce:

1. login with any user on development server.
2. Open event line screen.
3. Change the algo and observe the results.
![screenbud-1569a3cf-c2b1-49ed-aa7e-c6f0a4f36145](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/108800065/7e06755d-742c-41cc-9d55-224a29867f26)

Refer screenshot -

**Comment by sandeeptlgt** [comment]
Closed, verified on dev server.

**Comment by hassaanCD** [comment]
Verified on development

**Comment by hassaanCD** [comment]
Working fine on production
