### ISSUE TITLE
Event line - it shows the same event link multiple times on the event line screen.

### ISSUE THREAD

**Issue by sandeeptlgt** [the-canonizer/Canonizer-Beta--Issue-Tracking#525]
Steps to reproduce:

1. login with any user on development server.
2. Select the topic "Theories of Consciousness".
3. Open event line for the same and click on play button. 
4. Observe the event link.

Refer screenshot:
![screenbud-2fc17e4c-cf0b-49cb-9cd0-228e9fe04548](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/108800065/71de42b6-69fc-4ce3-8b9a-275954fe44a2)

**Comment by saniatg** [comment]
working fine on staging

**Comment by hassaanCD** [comment]
Verified on production
