### ISSUE TITLE
camp statement is submitting twice on development server

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#526]
**Steps to reproduce**

1. navigate to https://development.canonizer.com/
2. login with valid credentials
3. create a topic
4. add a camp statement
5. click on submit twice
6. statement is submitted twice

**Actual Result**
camp statement is submitted twice

**Expected Result**
2 camp statements are being added

**Comment by sajid315** [comment]
@shahab-ramzan from the front end side, we need to handle form refresh after the form has been submitted. Wahaj is working on it.

**Comment by subhancd** [comment]
verified on development server

**Comment by akashgit77** [comment]
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/aa2f6b07-484a-4fb1-8df5-e5d351bfdea8)

@shahab-ramzan Still not working.

**Comment by DevAlchemyCD** [comment]
pr for this ticket : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1358

**Comment by subhancd** [comment]
verified on dev

**Comment by subhancd** [comment]
verified on staging

**Comment by saniatg** [comment]
verified on production
