### ISSUE TITLE
Development server : Videos are not working

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#529]
https://development.canonizer.com/videos/consciousness/introduction?format=360 

Please refer attached screenshot :
![image](https://github.com/the-canonizer/canonizer-3.0-api/assets/40416610/70444ff3-c8b9-4fca-b413-54c0a2cf5cec)

**Comment by ks-rahul** [comment]
@akuks could you please upload the video files on the dev server

**Comment by rupalichavan9860** [comment]
Videos are working fine on dev and staging server
