### ISSUE TITLE
Event line - event link, redirecting URL's with different cases.

### ISSUE THREAD

**Issue by sandeeptlgt** [the-canonizer/Canonizer-Beta--Issue-Tracking#531]
**Basic 4 cases as below:**

Case 1: create_topic ,create_camp 
  Url= /topic/topic_num-topic_name/camp_num-camp_name 

Case 2: update_topic
 Url=  /topic/history/topic_num-topic_name

Case 3: update_camp, parent_change
  Url=  /camp/history/topic_num-topic_name/camp_num-camp_name

Case 4: direct_support_added,direct_support_removed, delegate_support_start, delegate_support_removed, archive_camp , unarchived_camp,
Url : /topic/topic_num-topic_name/camp_num-camp_name

**Cases with URL's as below:**

Case 1
Create Topic: Sandeep created a new topic and also added their support on Camp Event line test.
URL = https://canonizer3.canonizer.com/topic/3277-/1-?score=0&algo=blind_popularity&asof=default&canon=19&is_tree_open=1

Case 2
Create Camp: Sandeep created a new Camp Camp 1.
URL = https://canonizer3.canonizer.com/topic/3277-Event-line-test/2-Camp-1?filter=50&score=0&algo=blind_popularity&asofdate=1695908702&asof=bydate&canon=19&viewversion=1

Case 3
Update Topic: Sandeep changed topic name from Event line test to Event line test update.
URL = https://canonizer3.canonizer.com/topic/history/3277-?score=0&algo=blind_popularity&asof=default&canon=19

Case 4
Update Camp: Sandeep changed camp name from Camp 1 to Camp 11.
URL: https://canonizer3.canonizer.com/camp/history/3277-Event-line-test-update/2-Camp-11

Case 5
Parent Change: Sandeep changed the parent of camp Camp 11.
URL: https://canonizer3.canonizer.com/camp/history/3277-Event-line-test-update/2-Camp-11

Case 6
Direct support added: Sandeep added direct support in camp - Camp 2.
Direct support removed: Sandeep has removed direct support in camp - Camp 2.
URL: https://canonizer3.canonizer.com/topic/3277-Event-line-test-update/3-Camp-2?score=0&algo=blind_popularity&asof=default&canon=19&is_tree_open=1

Case 7
Delegate support start: Talentelgia5566 has just delegated their support to camp - Camp 2.
URL: https://canonizer3.canonizer.com/topic/3277-Event-line-test-update/3-Camp-2?score=0&algo=blind_popularity&asof=default&canon=19&is_tree_open=1

Case 8
Delegate support removed: Talentelgia5566 has removed delegate support in camp - Camp 2.
URL: https://canonizer3.canonizer.com/topic/3277-Event-line-test-update/3-Camp-2?score=0&algo=blind_popularity&asof=default&canon=19&is_tree_open=1

Case 9
Archive camp :Sandeep archived a camp Camp 2.
URL: https://canonizer3.canonizer.com/topic/3277-Event-line-test-update/3-Camp-2?score=0&algo=blind_popularity&asof=default&canon=19&is_tree_open=1

Case 10
Unarchive camp: Sandeep unarchived a camp Camp 2.
URL: https://canonizer3.canonizer.com/topic/3277-Event-line-test-update/3-Camp-2?score=0&algo=blind_popularity&asof=default&canon=19&is_tree_open=1

**Comment by sunilspr7** [comment]
Events : 
case 7: 
Delegate support added:  "delegated_user_nickname" has just delegated their support to "nickname"
case 8:
Delegate support removed: "delegated user nickname" has removed their delegated support from "nickname"

**Comment by saniatg** [comment]
Working fine on production
