### ISSUE TITLE
Devlopment server - it shows only "cross" as an alert, if user try to unarchive the camp without login.

### ISSUE THREAD

**Issue by sandeeptlgt** [the-canonizer/Canonizer-Beta--Issue-Tracking#532]
Steps to reproduce:

1. Login with any user on dev server.
2. Open any camp and archive the same.
3. Copy the URL and paste it in the other browser, where user is not login.
4. Click on the Unarchive button.
5. Check the result.

Expected result: It should show alert with proper message.

Actual result: First time it shows extra "cross" with alert message, and 2nd time it shows only cross, without any alert message.

![Screenshot (50)](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/108800065/c08436f2-a110-4025-a9f5-6d34babe7f8b)

![Screenshot (51)](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/108800065/39b1bf62-6eca-4af4-b5d1-87e6e09b7277)

**Comment by subhancd** [comment]
verified on development server

**Comment by saniatg** [comment]
Working fine on staging

**Comment by saniatg** [comment]
working fine on production
