### ISSUE TITLE
Event Line - It shows the disturbed view of support count and topics, on the Consensus Tree Race screen.

### ISSUE THREAD

**Issue by sandeeptlgt** [the-canonizer/Canonizer-Beta--Issue-Tracking#533]
Steps to reproduce:

1. Login with any user on dev server.
2. Open any topic.
3. Go to event line.
4.  Click on play button and check the results.

![Screenshot (54)](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/108800065/bcf4f679-e29a-450b-8c62-b8fa301a295e)

**Comment by saniatg** [comment]
working fine on staging

**Comment by hassaanCD** [comment]
Verified on production
