### ISSUE TITLE
topic detail page: on incorrect topic number or camp number it should show data not found page

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#534]
**Steps to reproduce**

1. navigate to any topic detail page
2. change the topic number to incorrect topic number in the URL

**Actual result**
an empty page is displayed

**Expected Result**
show data not found

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/1d89d5d2-565c-4026-bcff-d8aba86414f4)

**Comment by array-junkie** [comment]
PR Raised

Canonizer Api PR [#804](https://github.com/the-canonizer/canonizer-3.0-api/pull/804)
Canonizer Service PR [#266](https://github.com/the-canonizer/canonizer-service/pull/266)

**Comment by DevAlchemyCD** [comment]
PR raised from frontend

https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1314

**Comment by subhancd** [comment]
verified on development server

**Comment by subhancd** [comment]
verified on staging

**Comment by saniatg** [comment]
working fine on production. Showing No topic found
