### ISSUE TITLE
Manage Support: show 404 data not found on incorrect topic number in the URL

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#535]
**Steps to reproduce**

1. navigate to topic detail page of any topic
2. click on manage support
3. change topic number to a non existing topic number in the URL. e.g. 88888888

**Actual Result**

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/dd87afa1-d7fa-4b58-b6ec-f2bf9e2b463d)

**Expected Result**
it should show 404 data not found as topic number is invalid

**Comment by subhancd** [comment]
this ticket is linked with ticket# 534 and 536

**Comment by array-junkie** [comment]
@vikasranatalentelgia Is this done from the frontend and backend? Could you specify the branch?

**Comment by vikasranatalentelgia** [comment]
@M-Darab Yes, its done and fixed from frontend. Branch Name: talentelgia-fixes
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/535

**Comment by subhancd** [comment]
verified on development server

**Comment by akashgit77** [comment]
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/29dce026-e552-43ba-b69c-44d56961d2fe)

@shahab-ramzan I am getting server error while passing random string or number in "Topic url ".

**Comment by sajid315** [comment]
> ![Image](https://user-images.githubusercontent.com/105647543/280961935-29dce026-e552-43ba-b69c-44d56961d2fe.png)
> 
> @shahab-ramzan I am getting server error while passing random string or number in "Topic url ".

Issue occurred due to value exceeded from php Integer range, so validation from backend fails. I am looking into it, and in case of validation failure we must show the validation error at frontend rathar than 500, Internal Server Error.

**Comment by sajid315** [comment]
@shahab-ramzan , @wahaj-hafeez  As discussed in scrum call (10 Nov) for case of validation failure for get tree API. We need to handle front-end failure as generic response like we did for 404 page handling. Because for end user we can't show that our payloads are missing.

**Comment by subhancd** [comment]
@wahaj-hafeez 

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/7ec09077-c71a-4ab0-bc7b-f7fa76d3cac5)

**Comment by DevAlchemyCD** [comment]
pr for this ticket : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1421

**Comment by saniatg** [comment]
on second step new page is not coming. There is a modal pop up now.
![Screenshot 2024-01-25 at 2 29 03 AM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/b647bb71-daac-49a3-a25b-1e179bfce51c)

**Comment by akashgit77** [comment]
working fine on the production
