### ISSUE TITLE
Camp Forum : show 404 data not found on incorrect topic number in the URL

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#536]
**Steps to reproduce**

1. navigate to topic detail page of any topic
2. click on camp forum
3. change topic number to a non existing topic number in the URL. e.g. 88888888

**Actual Result**
1. create thread button is clickable
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/e4e3c66d-d296-4a11-9095-2342fc19a705)

**Expected Result**
show 404 data not found page

**Comment by DevAlchemyCD** [comment]
Pr from frontend :  https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1328
