### ISSUE TITLE
Statement History: show 404 data not found for incorrect topic number in the URL

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#538]
**Steps to reproduce**

1. navigate to topic detail page of any topic
2. navigate to camp statement history page
3. change topic number to a non existing topic number in the URL. e.g. 88888888

**Actual Result**
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/de5b1acc-edff-471c-a72f-0ce52cf90d6d)

**Expected Result**
show 404 data not found page

**Comment by array-junkie** [comment]
Backend PR Raised: [#812](https://github.com/the-canonizer/canonizer-3.0-api/pull/812)

**Comment by DevAlchemyCD** [comment]
Frontend PR Raised : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1317

**Comment by subhancd** [comment]
verified on development server

**Comment by akashgit77** [comment]
@shahab-ramzan not working yet

**Comment by subhancd** [comment]
@akashgit77 this is working fine. user is redirected to "Topic not found page". There are separate tickets for 500 internal server error. 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/d5946bf9-54fc-4151-ab7c-1b1ec5ef2b0a)

**Comment by subhancd** [comment]
verified on dev

**Comment by subhancd** [comment]
verified on staging

**Comment by rupalichavan9860** [comment]
Verified on live
