### ISSUE TITLE
Topic History Page: show 404 data not found for incorrect topic number in the URL

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#539]
**Steps to reproduce**

1. navigate to topic detail page of any topic
2. navigate to topic history page
3. change topic number to a non existing topic number in the URL. e.g. 88888888

**Actual Result**

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/9ed6437e-6909-4a89-a6b8-03217a7311bb)

**Expected Result**
show 404 data not found page

**Comment by DevAlchemyCD** [comment]
pr raised for 539 : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1319
