### ISSUE TITLE
"As Of" filters (Include review, As of date) should get applied on topic detail page only

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#54]
As of now when user selects "include review " or As of date/view this version - topic/camp name of that selected filter is displaying on all pages instead of live topic/camp name in bread crumbs

As per functionality "as of" filters (Include review, As of date) should get applied on topic detail page only

Please refer attached screenshot : 
Live topic name : 
![image](https://user-images.githubusercontent.com/40416610/204466185-070ade95-7ef2-465f-a562-5339243c84de.png)

Now apply "include review "  and observe other pages like "Create New Camp", all history pages, supported camps page 
As of now it is displaying in review names 
![image](https://user-images.githubusercontent.com/40416610/204466449-9a1692cd-44cb-4edd-8300-d4bcb408cfac.png)

**Comment by shahab-ramzan** [comment]
PR raised https://github.com/the-canonizer/canonizer-3.0-frontend/pull/597

**Comment by rupalichavan9860** [comment]
@shahab-ramzan Verified on all pages except supported camps page . Please refer attached screenshot : 

![image](https://user-images.githubusercontent.com/40416610/205949918-7b687716-6e89-4563-a4d4-0584bbf90897.png)

**Comment by rupalichavan9860** [comment]
@shahab-ramzan The problem persists when a new user applies the review filter and attempts to support the camp.

![image](https://user-images.githubusercontent.com/40416610/206645475-e8cecf8e-ffae-407c-a86a-01d09f714538.png)

**Comment by rupalichavan9860** [comment]
Not fixed

**Comment by subhancd** [comment]
showing in review name in the message on manage support. 
![Image](https://user-images.githubusercontent.com/104552751/208912638-9a2401ad-7d24-4505-8802-bd0a14c34e8b.png)

**Comment by shahab-ramzan** [comment]
@vikasranatalentelgia  Live topic name should be shown in the Supported camps page as mentioned in the above screenshot.

**Comment by hassaanCD** [comment]
not fixed

**Comment by sos1003** [comment]
@rupalichavan9860  i am not able to reproduce this. its working for me. please verify once and lets connect if required.

**Comment by nalwa** [comment]
@rupalichavan9860  i have tested this issue both on local and staging. I am not able to reproduce this.
can you please verify once and we can connect for the same.

**Comment by rupalichavan9860** [comment]
@nalwa Please refer below topic : 
https://canonizer3.canonizer.com/support/1754-Regression-27-FEB-2023-re/2-Camp-1-in-review

Please refer attached screenshot : 
![image](https://user-images.githubusercontent.com/40416610/221650325-d1fef926-89f8-47a5-958a-a0748004fe6a.png)

**Comment by nalwa** [comment]
![Screenshot from 2023-03-17 13-26-14](https://user-images.githubusercontent.com/4891200/225845909-c4621349-dbb6-4de7-a13f-70914a2a8398.png)


@rupalichavan9860  This is what i am getting on staging. and this seems correct to me. please check once.

**Comment by DevAlchemyCD** [comment]
@rupalichavan9860 This is not produced on my local and staging please have look at this issue

**Comment by rupalichavan9860** [comment]
@wahaj-hafeez Please refer steps to reproduce : 
1. Create topic 
2. Create camp "Camp 1"
3. Create sub camp of "Camp 1" - "Sub camp 1" and Support "Sub camp 1"
4. Login with User B and change camp name from "Camp 1" to "Camp 1 updated"
5. Commit changes
6. Login with User A again
7. Apply filter "Include Review"
8. Try to support "Camp 1"

Observe camp name on page : 
![image](https://user-images.githubusercontent.com/40416610/230203005-83156d6f-c8ac-4153-b61b-4ab938e74900.png)

**Comment by hassaanCD** [comment]
@rupalichavan9860 functionality is working fine but "Camp1" only showing after page refresh.



![Image](https://user-images.githubusercontent.com/120023458/231071849-35e97901-af4b-435b-b2a4-be330da9abc0.png)




![Image](https://user-images.githubusercontent.com/120023458/231071887-34a095be-8afa-4194-bbd0-d0fdab925499.png)

**Comment by rupalichavan9860** [comment]
Not Working 

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/c689e195-2b9d-4a60-b2c6-976ef273e220)

**Comment by nalwa** [comment]
@rupalichavan9860   not able to reproduce this case, might be scenarios has changed or may be no longer persist as its been created long back.
![Screenshot from 2023-06-06 13-10-22](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/4891200/f21ac4dd-bce5-4edf-8632-613ca8aca9b3)


Please verify if the scenario is same when you created the ticket. If its changed i would suggest create seprate ticket so we can stick to that only. please verify one more time.

**Comment by rupalichavan9860** [comment]
@nalwa Please refer steps : 
1. User A login - Create topic
2. User A login - Create camp "Camp 1"
3. User A login - Create sub camp of "Camp 1" -- "Sub camp 1"
4. User A login - Support  "Camp 1"
5. Login with User B and support "Sub camp 1"
6. Login with User B and submit a change(Update camp name) for "Camp 1" -It will be in "In review"
7. Login with User B- Apply "Include Review" filter and try to support "Camp 1" directly  
8. Observe camp name 

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/b9b02ab8-be81-4746-b1b3-77031f717878)

**Comment by nalwa** [comment]
@rupalichavan9860   by following above steps i am able to reproduce it. Thank you for re-verifying it. we are looking into this.

**Comment by rupalichavan9860** [comment]
Working fine now

**Comment by rupalichavan9860** [comment]
Verified on live
