### ISSUE TITLE
Camp History Page : show 404 data not found for incorrect topic number in the URL

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#540]
**Steps to reproduce**

1. navigate to topic detail page of any topic
2. navigate to camp history page
3. change topic number to a non existing topic number in the URL. e.g. 88888888

**Actual Result**

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/e321daf1-9faf-41bd-86d1-7519557e0865)

**Expected Result**
show 404 data not found page

**Comment by subhancd** [comment]
verified on development server

**Comment by akashgit77** [comment]
@shahab-ramzan not working yet

**Comment by subhancd** [comment]
@akashgit77 user is navigated to "Topic not found" for non-existing topic numbers. for long integer topic number, there's 500 internal server error and we have separate ticket for that
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/3660aa82-3510-4cdf-af3a-f0c23110a654)

**Comment by akashgit77** [comment]
@subhancd Okay

**Comment by subhancd** [comment]
verified on dev

**Comment by subhancd** [comment]
verified on staging

**Comment by saniatg** [comment]
@M-Darab @shahab-ramzan on production it shows camp history page as seen in screenshot  for a sec and then shows 'no topic found' 
![Screenshot 2024-01-17 at 5 54 09 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/238f8ab4-5793-4dce-842b-27401d0cbf82)

**Comment by DevAlchemyCD** [comment]
PR : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1499

**Comment by saniatg** [comment]
@M-Darab it still shows camp history page loading before 404 on development

**Comment by array-junkie** [comment]
@saniatg yes. It has to show the loading page before the 404 page because it calls APIs on the backend and as it gets a 404 HTTP response from the backend, it shows the 404 page.

**Comment by saniatg** [comment]
@M-Darab working fine, skeleton is showing before 404

**Comment by saniatg** [comment]
working fine on production
