### ISSUE TITLE
Account Settings - Subscription : Disable "Remove" button after first click

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#541]
**Steps to reproduce**

1. navigate to any topic
2. subscribe to topic
3. navigate to account settings
4. navigate to subscription
5. click on **remove subscription** button multiple times

**Actual Result**

multiple success messages are displayed

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/dd86de96-9bad-4018-930e-80ff21da35ad)

**Expected Result**

disable **Remove** button after first click

**Comment by subhancd** [comment]
verified on development server

**Comment by subhancd** [comment]
not fixed

**Comment by saniatg** [comment]
@ks-rahul verified on development server , it is not fixed
![Screenshot 2023-12-10 at 1 36 29 AM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/6f74d6a4-3f74-4f21-82a1-d033336983a8)

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
