### ISSUE TITLE
Camp Update: Search is not working for Parent Camp Field

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#542]
**Steps to reproduce**

1. navigate to any topic 
2. click on manage/edit this camp
3. click on submit based on this
4. search in the parent camp field

**Actual Result**

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/6386d407-bca5-4bb1-b5de-935b48aa87e8)

**Expected Result**
search should work in the parent camp field

**Comment by DevAlchemyCD** [comment]
pr : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1363

**Comment by subhancd** [comment]
@wahaj-hafeez search is case-sensitive. remove case-senstiviness from search


![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/370bc610-13d8-4efe-a6f4-b6f8f7d9ec61)

**Comment by DevAlchemyCD** [comment]
Pr : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1436

**Comment by hassaanCD** [comment]
Verified on development

**Comment by hassaanCD** [comment]
Working fine on production
