### ISSUE TITLE
Update camp - It shows "Something went wrong" on dev server.

### ISSUE THREAD

**Issue by sandeeptlgt** [the-canonizer/Canonizer-Beta--Issue-Tracking#543]
Steps to reproduce:

1. Login with any user on dev server.
2. Open any topic and try to update the camp.
3.  Observe the result after click on submit button.

Actual result: it shows "Something went wrong".

![Screenshot (60)](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/108800065/6fac7fd8-e80a-4412-bcdc-7dd618a61bae)

**Comment by rupalichavan9860** [comment]
Working fine on dev server

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Working fine on live
