### ISSUE TITLE
While creating new topic and camps, it shows "Driver [elastic] not supported" on dev server.

### ISSUE THREAD

**Issue by sandeeptlgt** [the-canonizer/Canonizer-Beta--Issue-Tracking#544]
Steps to reproduce:

1. Login with any user on dev server.
2. Try to create new topic and camp.
3. Observe the result after click on submit button.

Actual result: it shows "Driver [elastic] not supported".

![Screenshot (61)](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/108800065/bd9c2fd4-201b-4f14-bae7-37f75c626b49)

**Comment by rupalichavan9860** [comment]
Working fine on dev server

**Comment by rupalichavan9860** [comment]
Working fine on live
