### ISSUE TITLE
Statement History: Objected Statement collapse color and collapse icon is in green color

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#545]
**Steps to reproduce**

1. create a topic with user A
2. add camp statement by user B
3. object the statement by user A
4. observe the collapse icon

**Actual Result**

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/f0774c8f-5066-44e2-bc36-032ad8762457)

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/1ef18765-8d79-40ec-9708-005427dc2872)

**Comment by subhancd** [comment]
not fixed


![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/114f4bc4-6655-4ca6-a2d1-b0f5f063be3b)

**Comment by DevAlchemyCD** [comment]
pr for this ticket : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1386

**Comment by subhancd** [comment]
verified on dev server

**Comment by subhancd** [comment]
verified on staging

**Comment by saniatg** [comment]
working fine on production
