### ISSUE TITLE
Topic History: multiple topic updates are added on clicking "Submit" button multiple times

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#546]
**Steps to reproduce**

1. create a topic
2. navigate to topic history page
3. submit a change
4. click on submit button multiple times

**Actual Result**

same topic change is added multiple times

**Expected Result**

disable the submit button after first click

**Comment by subhancd** [comment]
verified on development server

**Comment by subhancd** [comment]
verified on staging

**Comment by hassaanCD** [comment]
Verified on production
