### ISSUE TITLE
Account Settings : Address Line 1 (Google maps) is not working

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#547]
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/ce3eab5b-f32a-4348-909f-5e6c9dd56587)

**Comment by ks-rahul** [comment]
I checked this issue and found that the current URL needs to be added to map allowed referrers list

@akuks @gautamv16 could you please check and update the development site URL in the referrers list

**Comment by ashish76** [comment]
The referrer has been added in the Places API and the issue has been resolved

**Comment by subhancd** [comment]
verified on development server

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by rupalichavan9860** [comment]
Working fine on live
