### ISSUE TITLE
register: user can register with 9 digits phone number but on updating profile it throws an error

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#548]
**Steps to reproduce**

1. register with 9 digits
2. user is redirected to profile page
3. click on update

**Actual Result**

an error is displayed that "Phone number must have 10 character"

**Comment by ks-rahul** [comment]
@rupalichavan9860 please specify the acceptance criteria for this.

**Comment by rupalichavan9860** [comment]
@subhancd Please provide acceptance criteria

**Comment by subhancd** [comment]
@ks-rahul here's the acceptance criteria
Acceptance Criteria:

1. When a user attempts to register, the registration process should not allow the user to proceed if they enter a 9-digit phone number.

2. If the user provides a 9-digit phone number during registration, they should receive an error message indicating that the phone number is invalid and must have exactly 10 characters.

3. The error message should be clear and user-friendly, stating, "Phone number must have 10 characters."

4. The error message should prevent the user from successfully completing the registration process until they provide a valid 10-digit phone number.

5. Once the user corrects their phone number to have 10 digits, they should be allowed to continue with the registration process.

6. The system should ensure that only 10-digit phone numbers are accepted during registration, and any other variations (such as less than 10 digits) should trigger the error message and prevent registration.

**Comment by subhancd** [comment]
verified on development server

**Comment by akashgit77** [comment]
@subhancd @ks-rahul I think,this ticket is not deployed yet or there is an issue

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/0a36e6d5-2b87-46a7-b0dc-3bd30b5500fa)

.

**Comment by subhancd** [comment]
@akashgit77 user should be able to register only after entering 10 digits (excluding the code). you have entered only 9 digits, that's why you are getting this error

**Comment by subhancd** [comment]
verified on staging

**Comment by hassaanCD** [comment]
Verified on production
