### ISSUE TITLE
It shows the disturb view on frontend if user select the Canon having large text.

### ISSUE THREAD

**Issue by sandeeptlgt** [the-canonizer/Canonizer-Beta--Issue-Tracking#549]
Steps to reproduce:

1. Login with any user on dev server.
2. Click on Canonizer logo.
3. Select the Canon having large text.
4. Observe the results.

Actual result: it shows the disturb view.

Refer screenshot:
![Screenshot (63)](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/108800065/c1b39d12-99f7-464d-b766-fbf410c16842)

**Comment by saniatg** [comment]
Working fine on development server

**Comment by saniatg** [comment]
@ks-rahul This issue is coming on development and staging , for a particular screen size. Refer screenshot
![Screenshot 2023-12-22 at 1 08 05 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/917d4806-f95d-47cd-a2d8-050aaf37ab20)

**Comment by ks-rahul** [comment]
@saniatg can you please specify which screen size you have faced this issue?

**Comment by saniatg** [comment]
working fine on development.

**Comment by saniatg** [comment]
working fine on production
