### ISSUE TITLE
On dev server- it shows "No Camp Statement History Found" after adding a new camp statement.

### ISSUE THREAD

**Issue by sandeeptlgt** [the-canonizer/Canonizer-Beta--Issue-Tracking#551]
Steps to reproduce:

1. Login with any user on dev server.
2. Create new camp ( C1 ) under any topic.
3. Try to add camp statement for ( C1 ) .
4. Observe the result.
 
Actual result: it shows  "No Camp Statement History Found" after adding the camp statement.

Refer screenshot:
![Screenshot (66)](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/108800065/5c4704ca-33cd-4f5c-b801-85a3b0161d90)

**Comment by sajid315** [comment]
@sandeeptlgt its working fine on dev server because we did fixing for this scenario with 404 page handling ticket. Let me know please if you found this error again.

**Comment by subhancd** [comment]
verified on development server

**Comment by saniatg** [comment]
working fine on staging server

**Comment by saniatg** [comment]
working fine on production
