### ISSUE TITLE
Topic Detail Page: Camp name is not displayed in the support tree

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#552]
**Steps to reproduce**

1. navigate to topic detail page
2. scroll to camp support tree
3. observe the camp name

**Actual Result**

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/93c2d9a3-5e75-4757-929b-fdec38027000)

**Comment by array-junkie** [comment]
@subhancd This issue is fixed with https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/issues/534. Moving this issue to "In Review - Dev".

**Comment by subhancd** [comment]
verified on development server

**Comment by saniatg** [comment]
Working on staging  server

**Comment by hassaanCD** [comment]
Verified on production
