### ISSUE TITLE
Topic Detail Page : "get-camp-activity-log" and "get-camp-newsfed" apis are failing

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#553]
**Steps to reproduce**

1. navigate to development server
2. click on any topic

**Actual Result**

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/ba715d01-3af6-496c-b6d6-90b320fe19d6)

**Comment by rupalichavan9860** [comment]
Getting below error on creation new topic 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/2f4b560c-70e3-4cbf-b3e8-2ecd932cccdb)

**Comment by sandeeptlgt** [comment]
Two more Api's are failing, when user open any camp first time from the tree.

![Untitled](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/108800065/79f54230-6a74-41d7-b1a3-c6903ac1cbca)

**Comment by array-junkie** [comment]
@subhancd @rupalichavan9860 @sandeeptlgt  This issue is fixed with #534. Moving this issue to "In Review - Dev". Only status_code 500 & 400 will be considered as API Fail from the backend.

**Comment by subhancd** [comment]
verified on development server

**Comment by subhancd** [comment]
verified on staging server

**Comment by hassaanCD** [comment]
Verified on production
