### ISSUE TITLE
Topic Detail Page - Current Camp Record - Go live time, submitted time and camp name are incorrect

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#554]
**Steps to reproduce**

1. create a topic
2. navigate to current camp record

**Actual Result**

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/28f8d265-6773-4153-aa03-8a821fea698c)

**Comment by subhancd** [comment]
verified on development server

**Comment by subhancd** [comment]
verified on staging

**Comment by hassaanCD** [comment]
Verified on production
