### ISSUE TITLE
Topic Detail Page : "Create New Camp" button is not visible

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#555]
**Steps to reproduce**

1. navigate to topic detail page
2. observe the top bar below breadcrumbs

**Actual Result**

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/0d05285a-974e-416c-ba73-e949a2e31638)

**Comment by subhancd** [comment]
verified on development server

**Comment by akashgit77** [comment]
@shahab-ramzan not working yet.

**Comment by subhancd** [comment]
@akashgit77 the button is visible and working
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/c7454b74-09b4-4177-89af-017fd1b24ce9)

**Comment by akashgit77** [comment]
@shahab-ramzan Yeah its working

**Comment by subhancd** [comment]
verified on staging

**Comment by saniatg** [comment]
working fine on production
