### ISSUE TITLE
Dev server : terms-and-services page is blank 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#556]
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/e7e7ca5c-3d30-426e-beaa-66d2ca21629f)

**Comment by sajid315** [comment]
@akuks @gautamv16 

For working of this page you need to run the following command on development server,

**php artisan db:seed --class=UpdateTermAndServicesSeeder**

**Comment by sajid315** [comment]
@rupalichavan9860 now this page is working on development server.

**Comment by rupalichavan9860** [comment]
Verified on development server

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
