### ISSUE TITLE
Dev server : Old topic name is displaying in bread crumbs 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#557]
Please refer attached screenshot : 
Bread crumb : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/d831082d-2209-44d1-9729-9aa59c58fe04)

Consensus Tree : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/8fecf2eb-63c7-4d44-8782-40c22f633344)

**Comment by rupalichavan9860** [comment]
Verified on dev server

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by hassaanCD** [comment]
Verified on production
