### ISSUE TITLE
On dev server, it hides the search dropdown if user try to search any topic on the browse screen.

### ISSUE THREAD

**Issue by sandeeptlgt** [the-canonizer/Canonizer-Beta--Issue-Tracking#559]
Steps to reproduce:
1. Login with any user on dev serve.
2. Click on browse.
3. Try to search any topic in the search field.
4. Observe the search result.

Actual result: it hides the search dropdown.
![Screenshot (67)](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/108800065/92f8b7bc-6a43-47de-aa71-1949e9473bf7)

**Comment by sandeeptlgt** [comment]
Closed, verified on dev server.

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by saniatg** [comment]
working fine on production
