### ISSUE TITLE
On dev serve - it cannot load the event line data first time, it required to refresh the screen.

### ISSUE THREAD

**Issue by sandeeptlgt** [the-canonizer/Canonizer-Beta--Issue-Tracking#561]
Steps to reproduce:

1. login with any user on dev server.
2. Open any topic.
3. Try to open Event line by URL.
4. Observe the result

Actual result: First time it cannot load the event line data, it required to refresh the screen.
![Screenshot (68)](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/108800065/1ff42533-64f4-4b3e-b2cb-be651940c3bb)

**Comment by sunilspr7** [comment]
API_AGREE_CHANGE_FOR_LIVE=api/v3/canonizer/api/agree-to-change

also add this line in .env file
Already mentioned in PR and also run the script 
@karun0607gautam @akuks

**Comment by saniatg** [comment]
Working fine on staging

**Comment by hassaanCD** [comment]
Verified on production
