### ISSUE TITLE
On supported tree, instead of (one person one vote), It shows camp "Universal Unitarian".

### ISSUE THREAD

**Issue by sandeeptlgt** [the-canonizer/Canonizer-Beta--Issue-Tracking#562]
Steps to reproduce:

1. login with any user on dev server.
2. Create new topic and create new camp.
3.  Check the algo on supported tree.

Actual result:  Instead of (one person one vote), It shows camp "Universal Unitarian" on supported tree.

![Screenshot (69)](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/108800065/814deaa6-6966-4158-9c4e-04f5475a36ac)

**Comment by sajid315** [comment]
@sandeeptlgt I have repeated the same above steps mentioned, so its not changing the algorithm to "Universal". Rather than it is "One Person One Vote" that should be.

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/111273633/b40fddc8-0e8a-4691-b138-1e9c9ac1a903)

**Comment by sandeeptlgt** [comment]
Closed, verified on dev server.

**Comment by subhancd** [comment]
verified on development server

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by hassaanCD** [comment]
Verified on production
