### ISSUE TITLE
Event line- it automatically selects the universal algorithm for all the topics on dev.

### ISSUE THREAD

**Issue by sandeeptlgt** [the-canonizer/Canonizer-Beta--Issue-Tracking#563]
Steps to reproduce:

1. Login with any user on dev server.
2. Create a topic and camp.
3. Move to event line screen.
4. Check the algorithm.

Actual Result : It automatically selects the universal algorithm for all the  topics.

![Screenshot (70)](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/108800065/31af5804-e6c3-4408-aff6-d26678ff59d0)

**Comment by sunilspr7** [comment]
@sandeeptlgt based on selected algorithm.

**Comment by saniatg** [comment]
Working fine on staging

**Comment by hassaanCD** [comment]
Verified on production
