### ISSUE TITLE
Layout issues on dev server 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#564]
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/ee6272f4-4741-4a40-848c-ac51fd177011)

**Comment by subhancd** [comment]
verified on development server

**Comment by subhancd** [comment]
not fixed
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/22f6fffd-d2a5-4760-8829-8f989558d791)

**Comment by rupalichavan9860** [comment]
Working fine on dev server

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by hassaanCD** [comment]
Verified on production
