### ISSUE TITLE
Need to fix the design issues if user try to login from the event line scree.

### ISSUE THREAD

**Issue by sandeeptlgt** [the-canonizer/Canonizer-Beta--Issue-Tracking#565]
steps to reproduce:
1. Select any topic without login.
2. Go to event line screen.
3. Click on login button.
4. Observe the results.

Actual results: it shows the event line date on the login screen.
![Screenshot (71)](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/108800065/160ac7e2-8060-41a1-a83d-1eb5f34cdf1f)

**Comment by subhancd** [comment]
Not fixed

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/05d22092-6623-4351-9753-6ac72d5dba82)

**Comment by subhancd** [comment]
verified on development

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by rupalichavan9860** [comment]
Verified on live
