### ISSUE TITLE
On dev server Event line is not working

### ISSUE THREAD

**Issue by sandeeptlgt** [the-canonizer/Canonizer-Beta--Issue-Tracking#566]
steps to reproduce:

1. Login with any user on dev server.
2. Create new topic and camp.
3. Try to open event line by URL.
4.Observe the results.
Actual results: it shows something went wrong.
![Screenshot (72)](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/108800065/be305dcf-688b-4e9e-b994-ee43f0ee6f81)

**Comment by sunilspr7** [comment]
It's already fixed

**Comment by saniatg** [comment]
working fine on staging

**Comment by saniatg** [comment]
working fine on production
