### ISSUE TITLE
On dev server - topic name update events are not updated on event line. 

### ISSUE THREAD

**Issue by sandeeptlgt** [the-canonizer/Canonizer-Beta--Issue-Tracking#567]
Steps to reproduce:

1. Login with any user on dev server.
2. open any topic
3. update the topic name and submit.
4. go to event line and check the results

Actual result: it should show the update events on the event line.

**Comment by sunilspr7** [comment]
@sandeeptlgt please test again

**Comment by sandeeptlgt** [comment]
Closed, verified on dev server.

**Comment by saniatg** [comment]
working fine on staging

**Comment by hassaanCD** [comment]
Verified on production
