### ISSUE TITLE
On dev server - camp archive and unarchive events are not updated on event line

### ISSUE THREAD

**Issue by sandeeptlgt** [the-canonizer/Canonizer-Beta--Issue-Tracking#568]
Steps to reproduce:

1. Login with any user on dev server.
2. open any topic/camp.
3. try to archive or unarchive the camp and submit.
4. go to event line and check the results

Actual result: it should show the update events on the event line.

**Comment by sunilspr7** [comment]
@sandeeptlgt please test again

**Comment by sandeeptlgt** [comment]
Closed, verified on dev server.

**Comment by saniatg** [comment]
working fine on staging server

**Comment by hassaanCD** [comment]
Verified on production
