### ISSUE TITLE
User Profile - Getting "Something went wrong Error"

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#569]
**Steps to reproduce**

1. navigate to any topic detail page
2. navigate to manage support 
3. click on any nick name

**Actual Result**
getting errors "Something went wrong"

![Image](https://user-images.githubusercontent.com/104552751/277564687-885e4e89-5ae7-4fc0-9412-82020cfab2db.png)

API:

![Image](https://user-images.githubusercontent.com/104552751/277564767-da79f19f-6a4a-4e83-939f-e8a3c04b2129.png)

**Comment by subhancd** [comment]
@sajid315  unable to reproduce this issue. closing this ticket

**Comment by rupalichavan9860** [comment]
I am also getting this issue :  
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/04ace632-f525-45ab-a7fb-1109e48e5e09)

**Comment by sajid315** [comment]
@vikasranatalentelgia I have checked about this issue and following are the steps to reproduce it, 
1- Open the canonizer site.
2- Go to the any topic detail page.
3- Copy the URL and paste it in private window.
4- In Support tree click on any nickname, the following issue will be appeared.

Note: One thing to be noted that API calls are duplicate like namespaces and user profile api.

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/111273633/50aa4c85-506c-476b-908c-a065555af80c)

**Comment by subhancd** [comment]
verified on development server

**Comment by rupalichavan9860** [comment]
Verified on live
