### ISSUE TITLE
"Objected to your proposed change" notifications are missing

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#57]
Steps to reproduce : 
1. Login with User A and create topic(User A is supporter)
2. Login with User B and submit change for topic, camp and statement
3. Login with User A and object to proposed change by User B.

Expected Result : User B should receive "objected to your proposed change" notifications

Actual Result : User B is not receiving "objected to your proposed change" notifications

**Comment by sajid315** [comment]
@rupalichavan9860 as expected the objection mail is sending to user B as well regarding objection. Have a look please.


![Image](https://user-images.githubusercontent.com/111273633/205841389-67cf8d48-ffb7-4197-9b63-a6efec4a7145.png)

**Comment by rupalichavan9860** [comment]
Verified.
