### ISSUE TITLE
Remove API calls from Authentication Pages accessed by not logged in users

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#571]
**Steps to reproduce**

1. access any page that required authentication (e.g. create topic page) without login

**Actual Result**

![Image](https://user-images.githubusercontent.com/104552751/277576156-d9d0fba6-0fa5-489c-adad-f447b9c8da2b.png)

**Expected Result**
remove all the extra api calls

**Comment by subhancd** [comment]
verified on dev

**Comment by subhancd** [comment]
verified on staging

**Comment by hassaanCD** [comment]
Not fixed on production. Showing double "client token" API on both "logout" and "create topic". Also show double "Search term" API on when click on "Create Topic" without sign in.

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/120023458/c3854901-9488-4a31-bc08-f810140f38e6)



![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/120023458/2adccfbb-a128-49ba-bcb5-fa2470d98306)

**Comment by ks-rahul** [comment]
@vikasranatalentelgia have you checked the search API call

**Comment by hassaanCD** [comment]
Not fixed on development and live

**Comment by hassaanCD** [comment]
Not fixed on development


![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/120023458/f64a60a1-96d7-4d1c-9095-f4bae49f5862)

**Comment by vikasranatalentelgia** [comment]
@saniatg This ticket is working fine in development kindly test it and close the ticket

**Comment by hassaanCD** [comment]
Working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
