### ISSUE TITLE
Posts - Add 404 not found for posts incase of invalid thread id

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#572]
1. navigate to any thread
2. change the thread number in the URL

**Actual Result**

![Image](https://user-images.githubusercontent.com/104552751/277593042-3baf7ab7-a5b9-45f1-9200-1e2dee0a64ef.png)

**Comment by subhancd** [comment]
verified on development server

**Comment by akashgit77** [comment]
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/8c7b6b6e-7493-477d-b2ff-c30aa6d9a63d)

@wahaj-hafeez Still not working
