### ISSUE TITLE
Dev server : Camp Forum is not working

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#573]
Please refer attached screenshot : 

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/12f60579-4ea0-48b9-aecd-ce9e2b12fc9d)

**Comment by ks-rahul** [comment]
@rupalichavan9860 I have checked the camp forum on the development server and it is working

**Comment by subhancd** [comment]
@ks-rahul for this topic, camp forum page is not accessible. kindly, check without login
https://development.canonizer.com/topic/45-Advocate-All-Sentience/1-Agreement?score=0&algo=blind_popularity&asof=default&canon=1&filter=10

**Comment by array-junkie** [comment]
PR has been raised: [#825](https://github.com/the-canonizer/canonizer-3.0-api/pull/825)

**Comment by subhancd** [comment]
verified on development server

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by rupalichavan9860** [comment]
Verified on live
