### ISSUE TITLE
Eventline- add skeleton instead of "no data found" for events when data is loading

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#574]
![Image](https://user-images.githubusercontent.com/104552751/277912433-2758398f-45a6-4b21-a90b-6ee05921882a.png)

**Comment by subhancd** [comment]
verified on development server

**Comment by akashgit77** [comment]
@subhancd still facing the issue

**Comment by DevAlchemyCD** [comment]
pr for this : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1376

**Comment by saniatg** [comment]
Working fine on development server

**Comment by saniatg** [comment]
working fine on staging

**Comment by hassaanCD** [comment]
Verified on production
