### ISSUE TITLE
New Search : Getting error "Server Error" when typing any word in search box

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#576]
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/b4806a9d-8706-4edc-b7e1-38bfa271adc7)

**Comment by rupalichavan9860** [comment]
Working fine on development server

**Comment by akashgit77** [comment]
working fine on the production
