### ISSUE TITLE
User Profile - Bearer token is null when opening user profile page in incognito

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#577]
Bearer token is null when user profile page is opened in incognito for the first time

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/1eba0aad-772d-4d73-a60a-284403eb1514)

**Comment by hassaanCD** [comment]
Verified on development

**Comment by hassaanCD** [comment]
Working fine on production
