### ISSUE TITLE
Camp Forum - Bearer token is null in incognito

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#578]
- open camp forum in incognito

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/95ab38dc-e35e-47ee-bf2c-9c08fb6e8ad7)

**Comment by hassaanCD** [comment]
Verified on development

**Comment by rupalichavan9860** [comment]
Verified on live
