### ISSUE TITLE
Create Thread - Bearer token is null in incognito

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#579]
- open create thread page from URL in incognito

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/3eeb47c5-4b02-4d61-87d1-0d8b77fe7142)

**Comment by hassaanCD** [comment]
Verified on development

**Comment by rupalichavan9860** [comment]
Verified on live
