### ISSUE TITLE
Posts - Bearer token is null in incognito mode

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#580]
- access posts page by URL in incognito

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/b2313a5f-d82e-4a6d-b9bb-bcd210e1b4d7)

**Comment by hassaanCD** [comment]
Verified on development

**Comment by DevAlchemyCD** [comment]
@hassaanCD ! I have tested it on the development server. It is working fine there.





![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/99801525/f16fa4ef-0260-47d2-aeba-b7c9e48d581a)

**Comment by rupalichavan9860** [comment]
Verified on dev server

**Comment by hassaanCD** [comment]
Working fine on production
