### ISSUE TITLE
Event line - it shows "No event found" with "Consensus Tree Race" bar with enabled play button on dev.

### ISSUE THREAD

**Issue by sandeeptlgt** [the-canonizer/Canonizer-Beta--Issue-Tracking#582]
Steps to reproduce:

1. Go to event line screen
2. Put any value (greater than support count) in the filter field.
3. Observe the result.

Actual result: it shows![Screenshot (73)](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/108800065/fffe423b-28a3-4980-9c42-685641868c5f) and shows "No event found".

**Comment by sunilspr7** [comment]
@wahaj-hafeez hide filter button

**Comment by subhancd** [comment]
- since the score filter is hidden now so this issue is not retestable.

**Comment by saniatg** [comment]
No filter button staging. Therefore issue does not exist

**Comment by saniatg** [comment]
No filter button on live. Therefore issue does not exist
