### ISSUE TITLE
Event line - It shows the slider for "Consensus Tree Race" even if the bar size is according to the screen size.

### ISSUE THREAD

**Issue by sandeeptlgt** [the-canonizer/Canonizer-Beta--Issue-Tracking#584]
Steps to reproduce:

1. login with any user on dev.
2. Go to event line.
3.  Check the slider by changing the algo.

Refer screenshot
![Screenshot (74)](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/108800065/b4a1c40b-1b1c-4ae3-9fbf-aa468c123d63)

**Comment by saniatg** [comment]
@rupalichavan9860 Working fine on development server

**Comment by hassaanCD** [comment]
Working fine on production

**Comment by hassaanCD** [comment]
Working fine on production
