### ISSUE TITLE
Event line - it shows the start date over the filter 's "i icon" popup. 

### ISSUE THREAD

**Issue by sandeeptlgt** [the-canonizer/Canonizer-Beta--Issue-Tracking#585]
Steps to reproduce:

1. login with any user on dev.
2. Go to event line.
3.  Hover on the filter's i icon.
4.  Check the result.

**Comment by sandeeptlgt** [comment]
Not fixed

**Comment by shahab-ramzan** [comment]
@sandeeptlgt Since filter is removed from eventline page. Can you please close this ticket?

**Comment by cd-ali-ehsan** [comment]
The filter button is hidden.
