### ISSUE TITLE
Email: Even if there is no edit summary for a change, the Edit Summary field (with a blank) should be present. 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#586]

**Comment by array-junkie** [comment]
Action emails that have summary input

- Email on Topic Create
    - There is summary input on the topic creation page. But it is not showing in the email
 - Email on Camp Create
    - There is summary input on the camp creation page. But it is not showing in the email
- Email on "Proposed a change in a statement record"
- Email on "Proposed a change in a camp record"
- Email on "Proposed a change in a topic record"

@rupalichavan9860 Should we have to show a summary on Topic & Camp Create Email?

**Comment by rupalichavan9860** [comment]
@BrentAllsop Could you please check and update this one?

**Comment by BrentAllsop** [comment]
Yes, we want this same feature for statements, camp records, and topic records.

**Comment by array-junkie** [comment]
PR Raised for summary changes: [#831](https://github.com/the-canonizer/canonizer-3.0-api/pull/831)

**Comment by sajid315** [comment]
@rupalichavan9860 
As per last discussion we observed that on any change it does not include the older record in email. So we have made dummy template to include the older change in email.
Please refer to below screenshot OR we can connect about this discussion, 

![image_2023_11_15T05_40_29_697Z](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/111273633/8a57e69b-9d4d-492f-b412-ad3cbff8448c)
![image_2023_11_15T05_39_30_130Z](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/111273633/1984b175-d67a-4339-86ea-fe743b445308)

**Comment by sajid315** [comment]
@M-Darab Summary changes for this ticket are done, so for more email templates we have to work on it in below ticket.
https://github.com/the-canonizer/canonizer-3.0-api/issues/844

**Comment by rupalichavan9860** [comment]
@sajid315 @M-Darab Working fine for create topic and create camp but unable to check for proposed a change emails because proposed a change(topic/camp/statement) emails are not working on development server 

Please refer ticket https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/issues/530

**Comment by rupalichavan9860** [comment]
Working fine

**Comment by rupalichavan9860** [comment]
Verified on live
