### ISSUE TITLE
Dev Sever - Frontend UX improvements

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#587]
**Create Topic**
when click on create topic, the page redirects back to the create topic form before going to topic detail page
**Video**

https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/75fe3b29-84b3-42a7-96d0-5266964cb850

**Add Camp Statement**
when adding camp statement on clicking submit update it redirects to the same form before going to the history page

https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/44dc9af7-2365-4a16-9d5c-4466af33a946

**Create Camp**
when creating camp, on clicking create camp it redirects back to the same form before navigating to the topic detail page

https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/c0920fef-e26d-454b-9133-8715b81a760f

when creating thread, it shows the form then loader. after clicking on create thread button it redirects back to the form before going to the camp forum page

https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/2ed34545-9b99-4aea-8618-d7d9d3eb5bf5

**Comment by DevAlchemyCD** [comment]
pr for ticket : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1400

**Comment by hassaanCD** [comment]
Not fixed.

**Comment by DevAlchemyCD** [comment]
pr : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1532

**Comment by rupalichavan9860** [comment]
Working fine on development server

**Comment by hassaanCD** [comment]
Working fine on production
