### ISSUE TITLE
Posts - Error message is displayed when the field is filled

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#588]
**Steps to reproduce**

1. navigate to camp forum
2. navigate to thread
3. create a post
4. click on submit
5. post is submitted --> click on submit again. 

**Actual Result**
an error message is displayed when there's still data in the field

https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/568a4473-96e2-42fd-8a03-c94cce5ba2ac

**Expected Result**
clear the field once post is submitted

**Comment by subhancd** [comment]
this flow is changed. I will retest this ticket once new flow is implemented

**Comment by ks-rahul** [comment]
@subhancd could you please elaborate more about the changed flow?

**Comment by rupalichavan9860** [comment]
This is working fine on development server

**Comment by saniatg** [comment]
working fine on production
