### ISSUE TITLE
Topic History : 422 status code in get API on submitting change

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#589]
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/dfb1c598-2399-4f1e-bd99-89ac3090f09f)

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/8a9f71b4-8706-4f6b-aafb-ec26287251d5)

**Comment by subhancd** [comment]
not fixed


![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/7e75a295-cee9-4c8f-b893-023c7a0404bb)

**Comment by shahab-ramzan** [comment]
@subhancd It's working fine on dev server. Can you please check once again.

**Comment by subhancd** [comment]
verified on dev

**Comment by subhancd** [comment]
verified on staging

**Comment by hassaanCD** [comment]
Verified on production
