### ISSUE TITLE
get topic record and get camp record api are failing for the below case

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#59]
**Steps to reproduce**

1. navigate to canonizer3.canonizer.com
2. navigate to any topic
3. select as of date filter
4. select a previous date
5. click on camp forum
**Actual Result**
![image](https://user-images.githubusercontent.com/104552751/205267215-6e46bde0-047e-407a-b26c-430189f70459.png)

**Comment by sajid315** [comment]
@subhancd its working fine now. From last updates of updating payload param's.

**Comment by subhancd** [comment]
working fine on staging

**Comment by subhancd** [comment]
working fine on beta
