### ISSUE TITLE
Camp statement change : Flag is missing in below case 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#590]
Steps to reproduce : 
1. Login with User A 
2. Create topic
3. Login with User B and add first version of camp statement - It will be in "In Review"
4. Observe Topic detail page 

Actual Result : Flag is missing

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/ef6ad28a-b037-4ec6-b19d-223f1c540010)

**Comment by DevAlchemyCD** [comment]
pr from frontend : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1369

**Comment by rupalichavan9860** [comment]
Working fine now

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by rupalichavan9860** [comment]
Working fine on live
