### ISSUE TITLE
500|Internal Server Error on dev server 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#591]
Steps to reproduce : 
1. Go to https://development.canonizer.com/
2. Choose any algorithm other than the first three.
3. Click on "Algorithm Information"
4. Observe result 

Actual Result :  Getting below error 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/f2cf1b96-f2e0-4fbb-8299-0d105e2e7310)

**Comment by shahab-ramzan** [comment]
@rupalichavan9860  This one ticket is working fine. Ashutosh had fixed the server related issue. Can you please verify and close this ticket

**Comment by rupalichavan9860** [comment]
This is working fine on dev server

**Comment by saniatg** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Working fine on live
