### ISSUE TITLE
Homepage - Topics list is empty

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#592]
**Steps to reproduce**

1. navigate to any topic
2. open event line
3. change algorithm to **Phd**
4. click on canonizer logo
5. observe the topics list

**Actual Result**

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/5b795c0f-2c8d-4a37-8ecd-0f86815e664d)

**Expected Result**
topics should be displayed

**Comment by subhancd** [comment]
not fixed 


![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/2c0335cf-328a-47dd-a7af-570d50e5aa6a)

**Comment by sajid315** [comment]
Following PR needed to be merged from frontend 
https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1343

**Comment by rupalichavan9860** [comment]
Working fin on development server

**Comment by saniatg** [comment]
working fine on production
