### ISSUE TITLE
Homepage - Disable canon selection when as of date filter is applied and the "get all" api reponse is pending

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#593]
**Steps to reproduce**

1. navigate to canonizer homepage
2. select as of date filter and change the date to any previous date
3. while the topics are loading --> change canon
4. 2 api calls will be sent for "get all" api

**Video**

https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/67cff10e-ccce-4738-9678-768c98d2af73

**Expected result**
canon selection should be disabled when **get all** api response is pending

**Comment by subhancd** [comment]
not fixed

**Comment by subhancd** [comment]
not fixed

**Comment by DevAlchemyCD** [comment]
pr : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1427

**Comment by subhancd** [comment]
verified on dev

**Comment by hassaanCD** [comment]
Working fine on production
