### ISSUE TITLE
Homepage - 500 Internal server for "get all" api for the mentioned algorithms

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#594]
**Algorithm List**

1. Democract
2. Forward Party
3. republicans
4. united utah
5. Transhumanist
6. Athiest
7. Universal unitarian
8. mormon
9. secular / non religious
10. christian
11. Ph.D.

**Actual Result**

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/013e4bab-e964-47b9-a614-681952dec093)

**Comment by array-junkie** [comment]
All the algorithms are working on development.

**Comment by subhancd** [comment]
verified on development server

**Comment by hassaanCD** [comment]
Verified on production
