### ISSUE TITLE
Posts - Remove the extra get threads list api when user is on posts page

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#596]
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/a995e457-e519-4c13-9af7-6e7cb8fcff8d)

**Comment by subhancd** [comment]
verified on dev

**Comment by subhancd** [comment]
verified on staging

**Comment by hassaanCD** [comment]
This issue is fixed as post is now showing in popup. But when user navigate to "Camp Forum" page it show double "List" API on production.


![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/120023458/e774edae-a05c-4cd6-a480-7656882ac935)

**Comment by hassaanCD** [comment]
Verified on development

**Comment by hassaanCD** [comment]
Working fine on production
