### ISSUE TITLE
Camp statement of child camp is displayed in the parent camp

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#597]
**Steps to reproduce**

1. create a topic by user A
2. add camp statement by user B. agree with statement by user A
3. create child camp, camp1 by user B. user B adds support in camp1
4. refresh the page by user A --> navigate to camp1

**User B**

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/3fb97e0c-6107-47be-a753-5ad4fb232f97)

**User A**

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/f9ff360f-5069-4e96-be46-b68f654bc91e)

**Comment by subhancd** [comment]
- verified on dev

**Comment by saniatg** [comment]
working fine on production
