### ISSUE TITLE
client-token api should be called once post-verify-otp api is successful

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#599]
**Steps to reproduce**

1. navigate to login
2. enter email and request OTP
3. enter invalid 6 digit OTP

**Actual Result**
client-token api is called

**Expected Result**
client-token api should only be called only if valid OTP is entered

**Comment by DevAlchemyCD** [comment]
pr : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1472

**Comment by hassaanCD** [comment]
Verified on development

**Comment by hassaanCD** [comment]
Working fine on production
