### ISSUE TITLE
Filters should be disabled if there's already an API call

### ISSUE THREAD

**Issue by shahab-ramzan** [the-canonizer/Canonizer-Beta--Issue-Tracking#6]
Side Bar Algorithms, score and as of date filters should be disabled if there's already an API call to avoid duplication of API calls

**Comment by shahab-ramzan** [comment]
PR Raised https://github.com/the-canonizer/canonizer-3.0-frontend/pull/551

**Comment by subhancd** [comment]
working fine on both staging and beta
