### ISSUE TITLE
registeration not working with 10 digit phone number

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#600]
refer to screenshot:

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/a7ca0bb3-7449-43ff-b63e-d1bf477957a9)

**Comment by array-junkie** [comment]
PR Raised from backend [#838](https://github.com/the-canonizer/canonizer-3.0-api/pull/838)
PR Raised from frontend [#1356](https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1356)

**Comment by hassaanCD** [comment]
Verified on development

**Comment by hassaanCD** [comment]
Working fine on production
