### ISSUE TITLE
500 internal server error for alphanumeric camp number

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#601]
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/3ec4576c-b997-4a13-839a-a41e5c12a48a)

**Comment by DevAlchemyCD** [comment]
pr : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1359

**Comment by subhancd** [comment]
@wahaj-hafeez 
- for camp forum


![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/e0099c33-ca02-4626-b47b-a6b7db81a8ad)

- for manage support

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/04a7bac5-9745-44ff-91af-d967b6e836b6)

- for camp history


![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/6fc82285-076b-43e0-8e64-c2e9f68c2a0f)

**Comment by DevAlchemyCD** [comment]
pr for ticket : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1426

**Comment by array-junkie** [comment]
Backend PR: https://github.com/the-canonizer/canonizer-3.0-api/pull/879

**Comment by subhancd** [comment]
verified on dev

**Comment by saniatg** [comment]
Working fine on production
