### ISSUE TITLE
History Pages - handle error messages sent from backend for alphanumeric camp number

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#602]
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/aaff2ef1-19af-44b2-8aea-2829403f3c37)

**Comment by DevAlchemyCD** [comment]
pr : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1359

**Comment by subhancd** [comment]
not fixed @wahaj-hafeez 

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/10f17328-4f84-479e-bd1c-2439ce6c3ee5)

**Comment by DevAlchemyCD** [comment]
pr for this  : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1426

**Comment by hassaanCD** [comment]
Verified on development

**Comment by hassaanCD** [comment]
Working fine on production
