### ISSUE TITLE
add statement - payload is empty for get-topic-nickname-used api

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#603]
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/45b6b12b-9ebb-4a11-b4ae-d043b853dde6)

**Comment by DevAlchemyCD** [comment]
pr for this ticket : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1372

**Comment by subhancd** [comment]
verified

**Comment by subhancd** [comment]
verified on staging
