### ISSUE TITLE
Event line - it show the over all score count if user moves by the event URL from the event line.

### ISSUE THREAD

**Issue by sandeeptlgt** [the-canonizer/Canonizer-Beta--Issue-Tracking#604]
Steps to reproduce: 

1. login with any user on dev server
2. Open any topic having score, (for example 6 score).
3. Move to event line screen and click on forward button until it reaches to score 3.
4. Click on generated event link and it redirects to the desired screen.
5. Observe the score.

Expected result: It should show the score according to the timeline.
Actual result: it shows the aver all score.

![Screenshot (77)](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/108800065/e4b5f637-6e5a-4a36-9abc-826e6eae56dc)
![Screenshot (76)](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/108800065/d1c4e3b8-5758-4e59-94dc-f1d7a5ef1777)

**Comment by DevAlchemyCD** [comment]
pr for this ticket : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1358

**Comment by hassaanCD** [comment]
Verified on development

**Comment by hassaanCD** [comment]
Working fine on production
