### ISSUE TITLE
Event Line - Need to remove the filter from event line screen.

### ISSUE THREAD

**Issue by sandeeptlgt** [the-canonizer/Canonizer-Beta--Issue-Tracking#605]
As discussed with @rohit-talentelgia and @sunilspr7 we need to remove the filter from event line.

**Comment by DevAlchemyCD** [comment]
pr for this ticket : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1358

**Comment by hassaanCD** [comment]
Verified on development

**Comment by saniatg** [comment]
working fine on production
