### ISSUE TITLE
Event line - it can't update the topic name and generate the link on event line.

### ISSUE THREAD

**Issue by sandeeptlgt** [the-canonizer/Canonizer-Beta--Issue-Tracking#607]
Steps to reproduce:
1. Login with user A on dev server.
2. Create new topic and support the same.
3. Login with user B and delegate their support (don't submit).
4. Move to user A and open event line.
5. Observe the result.

Expected result: it does not update the topic name and generate the link on eventline.

**Comment by hassaanCD** [comment]
Verified on development

**Comment by hassaanCD** [comment]
Working fine on production
