### ISSUE TITLE
Need to fix the input search text issues.

### ISSUE THREAD

**Issue by sandeeptlgt** [the-canonizer/Canonizer-Beta--Issue-Tracking#609]
Refer screenshot: 

![image_2023_11_10T05_55_27_315Z](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/108800065/1cc440d3-4a11-44a5-846f-6eaba902df6c)

**Comment by hassaanCD** [comment]
Verified on development

**Comment by hassaanCD** [comment]
Search is not working on development and live

**Comment by saniatg** [comment]
working fine on development
