### ISSUE TITLE
Browse : Search by topic name list is not showing properly

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#611]
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/5a513ec3-4364-4991-b6ef-e9bd85adb77c)

**Comment by subhancd** [comment]
This is a dublicate ticket of this issue: https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/issues/570

**Comment by rupalichavan9860** [comment]
This is working fine on dev, staging and production server so closing this
