### ISSUE TITLE
400 status code for "agree-to-change" api

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#612]
**Steps to reproduce**

1. create a topic by user A
2. create camp1 and create subcamp1
3. add support in subcamp1 from user A
4. add support in subcamp1 by user B
5. archive camp1
6. submit change in subcamp1 with user A
7. agree to change with user B

**Actual Result**

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/12acd90a-0232-4941-8e83-78b9da646aab)

**Comment by array-junkie** [comment]
@subhancd This ticket is fixed with recent commits so it is not reproducable as of now. So I'm moving this ticket to in review

**Comment by subhancd** [comment]
@M-Darab this is occurring on staging. please have a look
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/b01c664e-bb26-4aeb-a722-5d0217055a66)

**Comment by subhancd** [comment]
verified on dev
