### ISSUE TITLE
"as of date" filter is in green color

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#613]
**Steps to reproduce**

1. navigate to any topic
2. apply as of date filter
3. click on browse
4. observe the as of date filter color

**Actual Result**
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/f763af3b-5c55-4f91-8812-38df841fddf2)

**Comment by DevAlchemyCD** [comment]
pr: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1362

**Comment by subhancd** [comment]
verified

**Comment by subhancd** [comment]
verified on staging

**Comment by saniatg** [comment]
working fine on production
