### ISSUE TITLE
"save topic" api is responding with 400

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#614]
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/51463bbd-0e77-4279-b6b3-4ae6156c3d6c)

**Comment by nalwa** [comment]
@subhancd  issue is non-producible, but this appears when elastic server is not running.

But i will implement the check to handle this server  connectivity issue.

**Comment by saniatg** [comment]
working fine on staging

**Comment by saniatg** [comment]
working fine on production
