### ISSUE TITLE
Admin (Hot Topic) : View Topic link is redirecting to incorrect URL 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#618]
Steps to reproduce : 
1. Configure a hot topic 
2. Go to Menu 
3. Select Preview 
4. Click on "View Topic" link on Preview pop up 

Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/e1f33d51-914a-4457-b2a6-bd382832a721)

is redirecting to : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/47e77047-e0d1-45df-b7a2-dd8e42f49ffa)

Note : Working fine on home page

**Comment by array-junkie** [comment]
@akuks We have to connect about this. I think there might be an env configuration that we have to check.

**Comment by array-junkie** [comment]
@rupalichavan9860 I'm moving this ticket because as per the discussion, the Admin is now connected with Production. If you have access to admin, then let me know if it is working.

**Comment by rupalichavan9860** [comment]
Yes @M-Darab As admin is pointing to live database this is working fine as per requirement

**Comment by rupalichavan9860** [comment]
Working fine

**Comment by rupalichavan9860** [comment]
Working fine on live
