### ISSUE TITLE
user profile page not working

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#619]
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/6f3871cc-7c6c-446e-ab50-98a57750234d)

**Comment by DevAlchemyCD** [comment]
pr : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1363

**Comment by rupalichavan9860** [comment]
Working fine on dev server

**Comment by subhancd** [comment]
verified on staging

**Comment by saniatg** [comment]
working fine on production
