### ISSUE TITLE
Admin : Shares - Error 404 NOT FOUND on nickname link 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#623]
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/87c7cf86-bc98-4f3c-8796-0dea08481bc8)

**Comment by sajid315** [comment]
@rupalichavan9860, @ashish76  this issue is already resolved for nickname link. Following is the PR raised for admin panel.
https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/issues/581

**Comment by rupalichavan9860** [comment]
@sajid315 Thank you for the updates

**Comment by ashish76** [comment]
This issue has been addressed by the code district team, so closing this issue
