### ISSUE TITLE
Camp not found error when click on event link and then try to create topic

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#624]
Precondition: Clear cache
Issue 1
Steps:

1. Create topic
2. replace topic with eventline in the url
3. Now click on the event link on left panel under events
Actual result:on click shows camp not found
expected result: should redirect to the topic created
![Screenshot 2023-11-20 at 11 18 34 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/6d888382-b329-4b84-a816-675424f1cd6e)

Issue 2:
Now click on create topic from the bread crumb

same camp not found error
![Screenshot 2023-11-20 at 11 23 59 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/c04cbd33-5f26-46cc-bc5d-05e175f95aef)

**Comment by rupalichavan9860** [comment]
Working fine
