### ISSUE TITLE
Elastic search not working properly for nicknames

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#625]
**Steps to reproduce**

1. search with the second word of user-name. i.e username is "James_barrie" > search with "Barrie"

**Nick Name**

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/2eda82a8-1cf7-45ef-b0d2-ff3212b00465)

**Search**

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/94b03464-4a06-4a94-b55b-0f18a01ed166)

**Comment by rohit-talentelgia** [comment]
@subhancd and @vikasranatalentelgia the nickname seems like private nickname and should not come in search.

**Comment by subhancd** [comment]
@rohit-talentelgia I changed my nickname to public and it is still not searchable for last name

**Nick Name**
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/d3aa508f-b8ef-492e-80c3-de2f220da9d8)

**Search with last name**

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/b28c4f2d-c443-490d-ba94-3328eca34755)

**Search with first name**

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/52c89f0f-af99-49ed-a207-12268faccdaa)

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
