### ISSUE TITLE
elastic search - site breaks

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#626]
please refer to the attached video

https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/dff206ec-0c87-43b4-bf64-b106e7766b93

**Comment by subhancd** [comment]
verified on dev

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by rupalichavan9860** [comment]
Working fine on live
