### ISSUE TITLE
For all algorithms except the first three, an archived topic is listed on the home and browse pages(Without selecting "Show archived camps").

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#627]
Please refer attached screenshot : 
One Person One Vote : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/ac8a596b-ff5f-4b5e-a6db-5ec31c3f0080)

Other : 

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/f5542959-286e-4733-9a8a-fc6c829f0be1)

Selected topic is archived : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/24ebcaa0-3974-4dc8-a0d2-c6a2bb005d2f)

**Comment by hassaanCD** [comment]
Verified on development

**Comment by hassaanCD** [comment]
Working fine on production
