### ISSUE TITLE
Dev Server : Layout issue on topic detail page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#628]
Please refer attached screenshot : 

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/86f895e9-d174-4cb0-abd5-c30fe17640f2)

**Comment by DevAlchemyCD** [comment]
pr for this : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1386

**Comment by rupalichavan9860** [comment]
Working fine on development server

**Comment by saniatg** [comment]
working fine on production
