### ISSUE TITLE
Global search- Show message" No data found" when searching for random keyword

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#629]
Steps:

Type any random keyword in search and click enter

Actual result: White screen shows 
Expected result: Show message" No data found"
![Screenshot 2023-11-21 at 5 20 52 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/d7e08fd8-c852-4e21-9ee7-e6a3ba8f4925)

**Comment by saniatg** [comment]
working fine on development

**Comment by akashgit77** [comment]
Working fine on the production.
