### ISSUE TITLE
Request One Time Verification Code : Getting error "Failed to Send OTP." On beta

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#63]
When user click on Request One Time Verification Code , getting below error 

![image](https://user-images.githubusercontent.com/40416610/205829469-f37f3519-ef55-4859-b83a-247e361579ca.png)

**Comment by ks-rahul** [comment]
Hi @rupalichavan9860 I checked that and its working fine for me.

**Comment by rupalichavan9860** [comment]
Working fine
