### ISSUE TITLE
Global Search - Search is not working when searching any topic/statement which has special character

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#630]
Steps:

1. Create a topic/topic statement with a special character.
2. Now search that topic

The topic is not searched
Refer screenshot

![Screenshot 2023-11-22 at 11 20 38 AM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/4a8fb222-a585-45c5-bab4-717550f7295f)

**Comment by saniatg** [comment]
@nalwa @vikasranatalentelgia not fixed
![Screenshot 2024-01-25 at 1 24 04 AM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/99e08819-d76a-4caa-8553-6154c95d624d)

**Comment by saniatg** [comment]
@vikasranatalentelgia @nalwa now it searches all special chars and list them, but on click the topic nothing is happening. There is error in the console
![Screenshot 2024-04-03 at 12 28 26 AM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/7f88ceb1-112c-4b7f-968d-0fd626386c98)

**Comment by rupalichavan9860** [comment]
Working fine on development server

**Comment by hassaanCD** [comment]
Working fine on production
