### ISSUE TITLE
Elastic Search - "All" doesn't show all the camp statements

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#631]
**Steps to reproduce**

1. Search "**God"** in new search
2. navigate to search page
3. observe the results in **all** for camp statements
4. navigate to camp statement and observe the results

**URL**
https://development.canonizer.com/search?q=god

**Actual Result**
**For All**

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/46067bb1-b066-43a3-b71b-d01feaaaea93)

**For Camp Statement**
we have navigation

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/0263a8c3-f6e3-473a-b44e-b6a02f4d1570)

**Comment by nalwa** [comment]
@subhancd  ALL displays all the sections with 'camp', 'topic','statement' and 'nickname' first  5 searched  under all four categories.
that's how it is developed. and if one want all results in particular section then one can navigate to that category through left side bar.

you can connect if you need to discuss more over this. for me its not an issue.
