### ISSUE TITLE
Global search- show hand pointer on the searched keyword that are displayed 

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#632]
Steps:

1. Type any topic name in search eg'test'
2. 5-6 topic names will be displayed
3. now if I want to click on any one topic, the hand cursor is not showing instead normal pointer is seen.

hand pointer must be seen as the results are clickable

![Screenshot 2023-11-22 at 12 21 55 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/fbc95cc1-11d5-45ae-b5d2-a284b9092ba8)

**Comment by saniatg** [comment]
working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
