### ISSUE TITLE
Global search- new statement added is not showing when searched

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#633]
Steps:

1. Added new statement for already created topic" e.g topic was eventtest2 and statement added" new statement 123"
2. Committed the statement
3. Now in searched I typed "new"

The camp statement is not seen in the result. Checked in network tab also , the topic with this statement is not seen in response tab

**Comment by saniatg** [comment]
@nalwa not fixed.

**Comment by saniatg** [comment]
working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
