### ISSUE TITLE
Global search- UI issue- > Font style must be uniform in search results in the droop down for topi/statement /camp

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#634]
Keep font style some, currently for topic results are seen in black bold , camp results are different in font 

![Screenshot 2023-11-22 at 1 08 01 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/0b77287c-a7e4-4172-80e8-ed7eacac5d26)

**Comment by hassaanCD** [comment]
Not fixed for "camp statement".

**Comment by saniatg** [comment]
not fixed @vikasranatalentelgia

**Comment by hassaanCD** [comment]
It is not highlighting camp statement heading. Just highlighting the text. 
As shown in attached screenshot: camp heading is highlighted but not the statement.

![Screenshot_5](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/120023458/f7545f6f-05bf-4534-9e18-e5078ab93e03)

**Comment by hassaanCD** [comment]
Not fixed for "Camp Statement"
![Screenshot_4](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/120023458/074f859a-e4f3-4db3-9e0e-85bc1813f333)

**Comment by saniatg** [comment]
Fixed on development

**Comment by saniatg** [comment]
working on on production
