### ISSUE TITLE
Global search- When try to search any result quickly, I see random result for a sec then I see the correct result

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#635]
Refer video 

https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/96b8c1af-4821-4b9e-9bfe-ab3c029665d4

**Comment by hassaanCD** [comment]
Verified on development

**Comment by hassaanCD** [comment]
Working fine on production
