### ISSUE TITLE
Global Search - Same topic is displayed multiple times

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#636]
please refer to the screenshots:

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/e2155ae2-cb02-44d2-9af7-1f34b9c26120)

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/dfc5d1ed-1936-416d-89b9-c4cfc01d99b5)

**Comment by nalwa** [comment]
@subhancd  i am not able to reproduce this scenario for new topic topics. there were some changes made in later commits. so can you please check the same for other topics.

**Comment by subhancd** [comment]
closing this ticket
