### ISSUE TITLE
Global Search - Old Canon is displayed

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#637]
**Steps to reproduce**

- create a topic in sandbox testing
- change canon
- search topic from global search

**Global Search result**

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/8a696305-3fba-4bb6-a752-df4a09e5fa35)

**Actual Topic canon**

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/d4923198-9e44-488a-a602-b25b12c58aaa)

**Comment by saniatg** [comment]
working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
