### ISSUE TITLE
Global Search - search not working for changed topic name

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#638]
**Steps to reproduce**

1. create a topic
2. change it's name
3. search with new name

**Topic**

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/5e3bdaca-9bdb-4aff-be39-5712e566cd5c)

**Search**

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/e9a47fc1-c718-4785-bfad-fff19be7337a)

**Comment by saniatg** [comment]
working fine on development

**Comment by akashgit77** [comment]
Working fine on the production

**Comment by rupalichavan9860** [comment]
Verified on live
