### ISSUE TITLE
Elastic Search - Newly created camps redirect to 404 on searching

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#639]
**Steps to reproduce**

1. create a topic
2. creat a camp
3. search by camp name

**Search**

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/2c3d15e8-dfdc-40ba-817a-cb63775fee38)

**Camp**

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/7ce9f735-b02b-48f3-95ec-1db90d5fefed)

**Comment by saniatg** [comment]
@nalwa Not fixed on development
![Screenshot 2023-12-10 at 1 15 42 AM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/0a6cd15e-20e1-46a1-aa4f-1e61229d56ec)

**Comment by saniatg** [comment]
working fine on development now

**Comment by hassaanCD** [comment]
Search is not working on development and live

**Comment by nalwa** [comment]
@saniatg  @subhancd  i am not able to reproduce this not on development and not production. its working fine for me . please verify.

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
