### ISSUE TITLE
Admin (Hot Topic) : Issues on Config Hot Topic page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#640]
Issue 1 : It should show error messages when user click on "Configure" button without entering data in mandatory fields 

Actual Result : As of not it is showing message for only "Select Hot Topic"

Issue 2 : The user's selected topic will be deselected when they click "Configure" after choosing it from the "Select Hot Topic" dropdown.

**Comment by ashish76** [comment]
This is a duplicate topic. we have already resolved in https://github.com/the-canonizer/canonizer3-admin/issues/35
