### ISSUE TITLE
Collapse camps in consensus tree is not working correctly

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#643]
Refer topic
https://development.canonizer.com/topic/797-scenario11case01/2-camp1?filter=70&algo=secular&canon=19&is_tree_open=1

The camps should collapse when 70% or more.

![Screenshot 2023-11-23 at 12 46 11 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/863a2665-a169-48fe-a71a-5ab0c3e299db)

**Comment by DevAlchemyCD** [comment]
@saniatg i just revived this bug on local and development server so its working fine at my end.
if there is any  specific scenario to reproduce it kindly mention or we can close this ticket.

**Comment by saniatg** [comment]
@wahaj-hafeez It is working fine. Therefore, closing the issue.
