### ISSUE TITLE
UI issues on topic screen 

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#646]
Issue 1: Topic and Camp are not straightly aligned
![Screenshot 2023-11-23 at 10 46 58 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/29e292af-8073-44f9-b609-912f112e2f5c)

Issue 2: Extra space after colon
![Screenshot 2023-11-23 at 10 49 15 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/b035e513-18c1-40a4-8ee9-9ceacb9e442c)

**Comment by DevAlchemyCD** [comment]
pr for this ticket : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1386

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
