### ISSUE TITLE
Global search- Type 40 in search field, giving error "oops something went wrong" and then the site becomes blank

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#647]
refer screenshot
![Screenshot 2023-11-24 at 12 05 56 AM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/ef4dbda3-fa6c-4ac4-afef-06a25858962c)

**Comment by saniatg** [comment]
working fine on development

**Comment by akashgit77** [comment]
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/65f19979-a566-46fb-9db4-7233e141c3f8)

@saniatg I am getting this "No Data" before data appears.

**Comment by hassaanCD** [comment]
Working fine on production
