### ISSUE TITLE
Global search - Something went wrong error when searching for camp1

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#650]
Steps:

1. Create a topic
2. Now create camp 'camp1'
3. In search type' camp1'
4. click enter
5. Click on camp from left navigation

Error Something went wrong on click camp

![Screenshot 2023-11-24 at 10 51 08 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/64fa0b72-b381-42f4-9b00-4ca7879c3fac)

**Comment by nalwa** [comment]
@saniatg  not able to re-produce this, please verify once again if you facing same issue again.

**Comment by saniatg** [comment]
@nalwa The page is not breaking, but If I create a topic and create subcamp 'camp1' and then try to search 'camp1'
The camp1 w.r.t the topic is not searched

**Comment by saniatg** [comment]
Related issue 
https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/issues/639

Therefore, closing the issue
