### ISSUE TITLE
Global search- Nickname is not showing when searched

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#653]
Scenario:

There is a nickname " sania_talentelgia"
When I type talentelgia in search, this username is not seen under nicknames

**Comment by vikasranatalentelgia** [comment]
@saniatg its not replicating.

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/98095849/01b024e3-aaed-4de5-9107-45d9347c5804)

**Comment by saniatg** [comment]
@vikasranatalentelgia As discussed the issue with steps please check

**Comment by saniatg** [comment]
@vikasranatalentelgia Not working.
![Screenshot 2023-12-11 at 11 16 36 AM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/8f212463-94b2-496a-83f9-b507c85f0014)

**Comment by nalwa** [comment]
@saniatg its working now please test, earlier PR was not  merged

**Comment by rupalichavan9860** [comment]
Working fine now

**Comment by saniatg** [comment]
@vikasranatalentelgia not working on staging
![Screenshot 2023-12-25 at 1 20 03 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/bb967911-8030-4120-873a-14a571247b72)

**Comment by vikasranatalentelgia** [comment]
@saniatg its not replicating

**Comment by saniatg** [comment]
working fine on staging

**Comment by saniatg** [comment]
working fine on production
