### ISSUE TITLE
Camps name and topic name must be unique

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#654]
As a user Im able to create camp name same as topic name.

![Screenshot 2023-11-25 at 12 12 46 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/f198a021-dded-4f3b-9f8f-9e7eedf5bee9)

**Comment by ashish76** [comment]
@saniatg As I mentioned over the call we can create a camp with the same name as a topic but within a topic, the camp name cannot be duplicated. I agree with your point as it creates confusion for the user, so let's discuss this on Monday (11-Dec-2023) morning's call with Brent.

**Comment by rupalichavan9860** [comment]
Verified on development server

**Comment by saniatg** [comment]
working fine on production
