### ISSUE TITLE
Global Search - Misleading Hand Icon: Indicates Clickability, but Closes Search on Click

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#655]
kindly, refer to the attached video for more information

https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/b23a98f3-40b3-463e-9858-a53477efd875

**Comment by saniatg** [comment]
Not fixed @vikasranatalentelgia 
showing hand cursor in right end at some points but is not clickable

**Comment by saniatg** [comment]
working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
