### ISSUE TITLE
Global Search - Inconsistent Search Results: Topic Appears, but Camp Statement Doesn't

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#656]
**Steps to reproduce**

1. Ensure you are logged into the system.
2. Create a topic with the name "Maneskin"
3. Go to the camp statement sectio and add the word "Maneskin" to the camp statement.
4. Save the changes made to the camp statement
5. Navigate to the global search functionality.
6. Enter "Maneskin" in the search bar.

**video**

https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/85ab9ee0-3e54-42b2-90e3-a80a8c369361

**Comment by hassaanCD** [comment]
Verified on development

**Comment by hassaanCD** [comment]
Working fine on production
