### ISSUE TITLE
Inconsistent Color Display: Camp Statement Text Appears Red in Editor, but Displays Yellow on Topic Detail Page

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#657]
kindly, refer to the attached video

https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/146ebff3-eb5d-4601-a4ef-bb7a12d2582c

**Comment by DevAlchemyCD** [comment]
pr  : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1438

**Comment by hassaanCD** [comment]
Verified on development

**Comment by hassaanCD** [comment]
Working fine on production
