### ISSUE TITLE
Global Search - when a nick name is not supporting any camps, it should display 0 instead of blank

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#658]
refer to the screenshot attached

**Screenshot**

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/7898c954-1dd1-4abc-ab4b-2fdba907d65d)

**Comment by hassaanCD** [comment]
Verified on development

**Comment by saniatg** [comment]
Not fixed on production @vikasranatalentelgia 
![Screenshot 2024-03-18 at 10 03 40 AM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/bccebd6f-48ef-4275-b037-e4669967ac27)

**Comment by saniatg** [comment]
working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
