### ISSUE TITLE
Incorrect score  displaying under support tree 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#66]
Please refer below screenshot : 

![image](https://user-images.githubusercontent.com/40416610/205920760-53a56085-5fd7-47bb-955b-518e8eca2878.png)

**Comment by subhancd** [comment]
this is fixed with ticket#5 on staging

**Comment by rupalichavan9860** [comment]
Verified on beta
