### ISSUE TITLE
Event line : Links to event messages (as of date) don't show data for the selected date.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#660]
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/f89b498f-384f-4e5b-b3ea-1b040a27bcad)

Select previous date and again same date and observe : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/da4f2e2c-3be9-4ad9-83a2-33a4271452cf)

**Comment by sajid315** [comment]
@rupalichavan9860 this issue has been fixed and working fine now on development server. For other servers we have to wait for code merge.

**Comment by rupalichavan9860** [comment]
@sajid315 Yes working fine on development server

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by hassaanCD** [comment]
Verified on production
