### ISSUE TITLE
Un-archive is not working on click for a specific scenario

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#662]
Steps:

1. Create a topic
2. Create a camp 'camp1'
3. Login with user2
4. Create a subcamp 'subcamp' under 'camp1'
5. Support 'subcamp'
6.  Login with user B and support 'subcamp' . Now , Subcamp has 2 supporters
7. User A will submit camp camp for 'subcamp' by clicking on  archive camp and commit the change
8. User B agrees to the change
9. User B then clicks on Unarchive. 

Issue 1: The unarchive  button on single click is not working
Issue 2: click again on the button duplicate history created
Issue 3: Supporter count from 2 is seen to 3 , in the history
issue 4: In eventline unarchive for this case is not showing under events

**Comment by array-junkie** [comment]
The issue occurs due to simultaneous calls of two APIs from the frontend on the camp history page.

**Comment by DevAlchemyCD** [comment]
Pr from frontend : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1485

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
