### ISSUE TITLE
Eventline->when click on  archive or unarchive in the events link , shows camp not found

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#664]
Steps:

1. Create a topic 
2. Create a camps
3. Archive any camp
4. Then unarchive
5. Go to events
6. Play events
7.Under  events click on links Archive and unarchive

Error:  shows camp not found
![Screenshot 2023-11-28 at 5 29 43 AM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/86574f5d-89a6-4298-84f5-d172c4f1ede1)

**Comment by saniatg** [comment]
Working fine now. Closing the issue

**Comment by saniatg** [comment]
camp archive / unarchive events are not listing on production

**Comment by DevAlchemyCD** [comment]
@saniatg I have verified the mentioned case of archive / unarchive the eventline on production. It is working fine and correctly showing the data of camps on production.
<img width="1485" alt="Screenshot 2024-04-17 at 2 02 17 PM" src="https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/99801525/224f808d-6984-4301-b702-fc5a0e914f3e">

**Comment by saniatg** [comment]
working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
