### ISSUE TITLE
UI - cursor for username initials logo in the header , should be hand pointer as it is clickable 

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#665]
Refer screenshot
![Screenshot 2023-11-28 at 5 26 05 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/b688bc06-86f4-403f-8f98-d3f99404354f)

**Comment by hassaanCD** [comment]
Not fixed

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
Not fixed on production . Hand pointer missing for logo

**Comment by vikasranatalentelgia** [comment]
@saniatg This ticket is working fine in development kindly test it and close the ticket

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on live
