### ISSUE TITLE
Change is not going live on last approval in below case 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#666]
Steps to reproduce : 
1. Login with User A and create topic
2. Create sub camp and support camp 
3. Login with User B and delegate support to User A
4. Login with User B and remove delegated support
5. Login with User B and add support to sub camp directly
6. Login with User B and archive the camp
7. Login with User A and agree the change (Camp is archived ) 
8. Login with User A and unarchive the camp
9. Login with User B and try to agree the change

User B can agree the change but change is not going live
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/b9475c43-04b0-428c-a7c2-2bf38cd3b0be)

**Comment by kshitij1326** [comment]
@rupalichavan9860 I have checked this issue with mentioned steps on local, development and staging server and I am unable to reproduce this issue.

**Comment by rupalichavan9860** [comment]
Working fine on dev server

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by rupalichavan9860** [comment]
Verified on live
