### ISSUE TITLE
Camp name is missing

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#667]
Steps : 
1. Go to https://development.canonizer.com/
2. Create topic
3. Login with User B and delegate support to User A in Agreement camp
4. Login with User A and create sub camp
5. Support sub camp and observe 
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/44ef563a-136b-494a-9d60-48cce3711fc7)

**Comment by rupalichavan9860** [comment]
Working fine on development server

**Comment by hassaanCD** [comment]
Working fine on production
