### ISSUE TITLE
UI is distorted and camps /topic name empty when select as of filter and click on topic from recent activities

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#669]
Steps:

1. On home page select as of date filter and choose any past date 
2. Now under recent activities there must be a topic created, if not then create one and click on that topic

![Screenshot 2023-11-29 at 11 04 30 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/832fec55-baa1-4ce6-841d-61ad749ea40b)

**Comment by DevAlchemyCD** [comment]
pr raised : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1398

**Comment by saniatg** [comment]
@rupalichavan9860 working fine on development server

**Comment by saniatg** [comment]
working fine on staging server

**Comment by saniatg** [comment]
working fine on production
