### ISSUE TITLE
Account Settings : changing order of support from account settings is not reflecting in the tree

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#67]
**Steps to reproduce**

1. navigate to https://canonizer3.canonizer.com/
2. login with valid credentials
3. create a topic
4. create multiple camps --> camp1 , camp2
5. support both camps
6. navigate to account settings
7. navigate to supported camps
8. change the support order and save the changes
9. navigate to topic detail page

**Actual Result**
the order on account settings page
![image](https://user-images.githubusercontent.com/104552751/206101708-3cce377a-dd5b-44e1-8c57-747e0a11dea0.png)
the order in the tree
![image](https://user-images.githubusercontent.com/104552751/206102191-709898de-6b12-434b-874b-0ebc265bce44.png)

**Expected Result**
the changes of made in the account settings should be reflected in the tree in topic detail page

**Comment by subhancd** [comment]
working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on beta
