### ISSUE TITLE
Event line - Camp not found error on click topic create link under events

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#670]
1. Create a new topic
2. Copy the url and replace 'topic' with eventline
3. Now under events click on the link [username]create an new topic

Camp no found error will be seen for the first time, second time will work fine.

![Screenshot 2023-11-29 at 10 16 54 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/886a8795-4bc8-489d-b1d7-5df5948f54ca)

**Comment by DevAlchemyCD** [comment]
pr for ticket : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1397

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
