### ISSUE TITLE
Dev server : The thread title (field value) must be visible on the edit page.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#671]
As of now when user tries to edit their own thread , thread title is blank 

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/160df81c-feb1-478c-a713-a001f8332219)

**Comment by sajid315** [comment]
@rupalichavan9860 I have checked this issue and actually the Edit API is not calling in this page, Also I think we need endpoint that will return only the text that needs to be edited. 
So I am working to create the endpoint for edit of this text.

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/111273633/c109a3fe-7f60-4457-a617-761c682f922f)

**Comment by sajid315** [comment]
@wahaj-hafeez as we discussed in scrum call of 07 December, we need some updates for thread title edit scenario. 
1- We need to remove redirect to separate form for edit of thread title.
2- Also on click of edit icon , display a popup having form for edit of thread.
3- We don't need the API to get previous text of title, just pick the text written with edit icon.

**Comment by saniatg** [comment]
@wahaj-hafeez verified on development server, this seems not fixed.

**Comment by DevAlchemyCD** [comment]
pr for tiicket : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1409

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
