### ISSUE TITLE
Global search- too many API's are getting hit when searching for keyword'picture' 

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#676]
![Screenshot 2023-12-01 at 1 17 01 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/4a9ff210-7bb9-4ed4-8ab9-2a4f13b3d0a2)

In network tab too many api's are seen when enter keyword' picture'
![Screenshot 2023-12-01 at 1 17 01 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/06421134-90cb-43f9-a71e-806c6643d0a2)

**Comment by SidhantUppalSyantaq** [comment]
@saniatg 
 there are youtube videos uploaded with the name of picture, the API hits are related to youtube and googleads. its not a bug.

**Comment by vikasranatalentelgia** [comment]
@saniatg there are youtube videos uploaded with the name of picture, the API hits are related to youtube and googleads. its not a bug.
