### ISSUE TITLE
Browse : Mentioned topic is showing on the browse page on a date it was not created in as of date filter

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#68]
this topic https://canonizer3.canonizer.com/topic/1231-could-you-find-a-way/1-Agreement was created today, 07 December. Now go to browse page and search the topic name with default filter. it will show the topic. then change the as of date to yesterday's date, 06 December. the topic still shows on the browse page.

**Comment by sajid315** [comment]
@subhancd I m unable to reproduce the steps for this issue. Please check and let me know for new topics.
Thanks.

**Comment by subhancd** [comment]
couldn't reproduce this issue. closing this ticket
