### ISSUE TITLE
Support count is showing incorrect for a specific scenario

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#680]
steps:

1. User A creates a topic, by default support is in agreement camp
2. User A creates a camp 'camp1'
3. Login with User B in a different browser and delegate support to User A
4. Login with User C in different browser and delegate support to User B
5. Login with user A in different browser and give direct support in camp 'camp1'
6. Now User B  which was logged in a different browser , the page will be seen like this with support. Do not refresh the browser
![Screenshot 2023-12-05 at 10 52 56 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/7502b9ff-cea7-4549-95ae-d6e211eb1f90)

7. Click on button 'Directly join and support'

Message 'Your supporting camp list for topic "topiv788"
Issue 1: Camp1 mentioned  is incorrect as now User B is supporting agreement 
![Screenshot 2023-12-05 at 11 00 49 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/5637895e-5379-42bf-9624-3e62bf0d6c40)

8. Click submit
Issue 2: Support is seen 6 which is incorrect
![Screenshot 2023-12-05 at 11 05 33 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/8747a3d1-56f9-4ef3-aa15-d59d74935c74)

**Comment by sajid315** [comment]
@rupalichavan9860 Can we discuss above mentioned issues , because according to your second screenshot its showing the same score as on support at Agreement camp.

We can connect via call to discuss further case in this.

**Comment by saniatg** [comment]
@nalwa not fixed
![Screenshot 2024-05-01 at 12 25 46 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/61efd44b-3938-4f2f-8e16-d2a1e4fb54a4)

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
