### ISSUE TITLE
Eventline- Remove support is not showing under events  in a specific case

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#681]
Steps:

1. From user profile navigate to supported camps
2. Under direct supported camps if click on cross icon and save changes for supported camp or topic, the event for removed is not showing 

![Screenshot 2023-12-06 at 9 56 28 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/6aca4066-3f64-4c43-a59e-196d960b636e)

**Comment by hassaanCD** [comment]
Verified on development

**Comment by saniatg** [comment]
working fine on production
