### ISSUE TITLE
Disable `Submit Camp Update Based On This` button when camp is archived

### ISSUE THREAD

**Issue by kshitij1326** [the-canonizer/Canonizer-Beta--Issue-Tracking#682]
Steps to reproduce :-
1. Login with user A 
2. Create a topic, create a camp and support that camp
3. Login with user B
4. support the above created camp directly.
5. Archive that camp
6. Login with user B and agree to the change
7. un-archive the camp (now the change will be under review for un-archive)
8. Now we are able to submit another change in camp since `Submit Camp Update Based On This` is enabled.
![screencapture-localhost-4000-camp-history-749-new-test-topic-2-Camp-1-2023-12-07-14_56_13](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91306850/f7d26a7b-8fb3-4c8e-bbfd-b2fea01d72bc)

**Comment by rupalichavan9860** [comment]
Verified on development server
