### ISSUE TITLE
Issue in direct supporter count while submitting a change to camp

### ISSUE THREAD

**Issue by kshitij1326** [the-canonizer/Canonizer-Beta--Issue-Tracking#683]
Steps to reproduce :-
1. Login with user A 
2. Create a topic, create a camp and support that camp
3. Login with user B
4. support the above created camp directly.
5. Archive that camp
6. Login with user B and agree to the change
7. un-archive the camp (now the change will be under review for un-archive)
8. click on `Submit Camp Update Based On This` and submit a new change (now this change will also be in review and You will see `1 out of 2 required 
9. Login with user A and agree to change of un-archive camp.
10. You will see `1 out of 1 required supporters have agreed` in the in_review change

![Screenshot from 2023-12-07 15-13-46](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91306850/f033e74f-265c-43e0-9a7e-4c5156eb1115)

**Comment by DevAlchemyCD** [comment]
pr for ticket  : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1415

**Comment by hassaanCD** [comment]
Not fixed.

**Comment by rupalichavan9860** [comment]
Working fine on development server

**Comment by rupalichavan9860** [comment]
Verified on live
