### ISSUE TITLE
Event line  : Objected event is listed under event list 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#684]
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/1f69e701-1831-4e01-909c-2bdf63d253d8)

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/1e98e06c-8e12-4c5f-9911-81aae1ac6b89)

**Comment by rupalichavan9860** [comment]
Working fine on development server

**Comment by saniatg** [comment]
working fine on production
