### ISSUE TITLE
Logging out should not take you back to the homepage

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#685]
As discussed in the meeting, 
1. If the user logs out of any page, the page should reroute to the login page if necessary, and if the user logs back in, the page they were previously on should reroute to.
2. If the user logs out of any page, the page should reroute to that page instead of the homepage (if login is not necessary).

**Comment by saniatg** [comment]
@ks-rahul this issue is not fixed on development

**Comment by rupalichavan9860** [comment]
@ks-rahul Can you please check this for create thread case ,topic update , camp update ,add camp statement 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/faaf4f59-98ad-4750-a27c-f741af0a54c0)

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/ffd3484d-56bc-455b-a8c8-7a8adcba4fb4)

**Comment by rupalichavan9860** [comment]
Verified on dev server

**Comment by rupalichavan9860** [comment]
Not working for few pages . We will list the pages and update here

**Comment by saniatg** [comment]
@ks-rahul 
1- Camp forum
2- Camp/topic/statement history pages
3- browse page
4- Recent activity

**Comment by ks-rahul** [comment]
@wahaj-hafeez can we connect for this

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
