### ISSUE TITLE
Dev server : Upload File is not working

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#686]
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/67410c30-b4d9-461a-b6b3-8ec5c6e1a178)

**Comment by rupalichavan9860** [comment]
Working fine on development server

**Comment by akashgit77** [comment]
https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/01bd96ae-923c-49d3-b533-aeb23e63fcc6

**Comment by akashgit77** [comment]
@vikasranatalentelgia Still having trouble while uploading file.

**Comment by rupalichavan9860** [comment]
Verified on development server

**Comment by saniatg** [comment]
working fine on production
