### ISSUE TITLE
Dev server : Upload File link is visible only after refreshing the page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#687]
Steps to reproduce : 
1. Go to https://development.canonizer.com/
2. Login with admin credentials 
3. Observe footer 

Upload File link is missing

4. Refresh the page and observe

User can see Upload File

**Comment by DevAlchemyCD** [comment]
pr for this ticket : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1417

**Comment by rupalichavan9860** [comment]
Working fine on development server

**Comment by akashgit77** [comment]
working fine the production

**Comment by rupalichavan9860** [comment]
Verified on live
