### ISSUE TITLE
Edit Post : Pop up name must be Edit Post Form instead of Create Post Form

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#688]
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/b9f57dd5-c903-477a-86ed-d381e38f1891)

**Comment by rupalichavan9860** [comment]
Verified on development server

**Comment by saniatg** [comment]
working fine on production
