### ISSUE TITLE
Homepage : current date is disabled for the following case

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#69]
**Steps to reproduce**

1. navigate to homepage
2. navigate as of date filter 
3. select yesterday's date, 06 december
4.  click on cross button in the date search bar 
5.  click on as of date.
**Actual Result**
current date will also be disabled

**Comment by subhancd** [comment]
working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on beta
