### ISSUE TITLE
Global search-  the specific keyword that is searched is not highlighted 

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#690]
I was checking the design in adobe , if we search for any keyword , the specific keyword is highlighted but this is not implemented in our application. 
![Screenshot 2023-12-11 at 11 40 24 AM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/ff385610-b1cc-4ee5-ac3c-fcb1ad9f1c73)

**Comment by saniatg** [comment]
working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
