### ISSUE TITLE
Global search- No maximum limit given to search any keyword

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#691]
When I keep adding statement " We believe that the mind or consciousness is identical with brain states. As it states at in the Stanford Encyclopedia of Philosophy: "States and processes of the mind are identical to states and processes of the brain." 
like 5 time or more the search dropdown get distorted . 
Refer screenshot
![Screenshot 2023-12-11 at 4 24 47 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/874f8c70-981c-4f6c-a43e-c670f42b5ea5)

**Comment by saniatg** [comment]
@vikasranatalentelgia not fixed.
Typed " We believe that the mind or consciousness is identical with brain states. As it states at in the Stanford Encyclopedia of Philosophy: "States and processes of the mind are identical to states and processes of the brain."
like 5 time or more the search dropdown get distorted ."

shows this as seen in screenshot.

![Screenshot 2024-01-24 at 4 45 53 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/3bee528d-2175-4742-8106-8bc17880f859)

**Comment by saniatg** [comment]
@vikasranatalentelgia  UI is not distorted now but search keeps loading as per my above comment

**Comment by saniatg** [comment]
@nalwa please check
![Screenshot 2024-02-29 at 2 37 28 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/2d9576bd-ef44-4a88-bd06-f207fee8b33c)

**Comment by saniatg** [comment]
working fine on development

**Comment by rupalichavan9860** [comment]
Verified on live
