### ISSUE TITLE
Delegate Supporter should not be able to agree or object for the mentioned scenario

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#695]
- Log in with User A. Create a Topic and Camp (C1) and support it.
- Log in with User B and delegate support to User A.
- Log in with User C, submit a change in Camp Statement, and commit. You’ll see a message “1 out of 2 supporters have agreed…”. 
- Log in with User A and remove the support from C1. Now User B (who is a delegated supporter) will become a direct supporter. 

**Actual Result**
1 out of 3 supporters have agreed
**Expected Result**
delegate supporter should not be able to agree or object once he becomes direct supporter

**Comment by hassaanCD** [comment]
Verified on development

**Comment by hassaanCD** [comment]
Working fine on production
