### ISSUE TITLE
Recent Activities : Displaying two different activities on camp change,  one when user updating camp (before commit) and second after committing changes

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#7]
It should show only one after committing changes

**Comment by sajid315** [comment]
https://github.com/the-canonizer/canonizer-3.0-api/pull/419

**Comment by sajid315** [comment]
@rupalichavan9860  This ticket is working fine now on beta. Changes done in above PR and also with other tickets code.

**Comment by rupalichavan9860** [comment]
Verified
