### ISSUE TITLE
Beta : Topic list is blank on browse page for some algorithms

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#70]
Please refer below screenshot : 
![image](https://user-images.githubusercontent.com/40416610/206145001-ae47c984-1279-464a-9662-ae38984b0c19.png)

![image](https://user-images.githubusercontent.com/40416610/206145219-c7598576-d3dd-4259-84fe-778b5cfc63d6.png)

**Comment by sajid315** [comment]
@rupalichavan9860  Working fine now.

**Comment by rupalichavan9860** [comment]
Working fine
