### ISSUE TITLE
Global search- Showing titles in search dropdown when no data is found

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#702]
![Screenshot 2023-12-15 at 4 53 32 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/bb00ed3c-354a-46a2-9a5e-7875bd7a7658)

**Comment by saniatg** [comment]
@vikasranatalentelgia not fixed
![Screenshot 2024-01-25 at 2 20 23 AM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/c2d8514e-63e7-4149-b3ea-ab5a0e44978e)

**Comment by saniatg** [comment]
working fine on development

**Comment by hassaanCD** [comment]
Working fine on production

**Comment by hassaanCD** [comment]
Working fine on production
