### ISSUE TITLE
remove "get-activity" api call on changing algorithm on homepage

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#703]
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/22cb543f-2194-488a-94c3-2c556ac2cb12)

**Comment by DevAlchemyCD** [comment]
PR for ticket : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1433

**Comment by hassaanCD** [comment]
Verified on development

**Comment by hassaanCD** [comment]
Working fine on production
