### ISSUE TITLE
disable all filters on homepage once a "get-all" api call is in process

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#704]
1. click on "show archive camps" multiple times

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/9f2d3ba6-0160-4857-96f0-09077c26e317)

**Comment by DevAlchemyCD** [comment]
PR : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1433

**Comment by hassaanCD** [comment]
Verified on development

**Comment by hassaanCD** [comment]
Working fine on production
