### ISSUE TITLE
Incorrect warning displaying while supporting camp 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#705]
Steps to reproduce : 
1. Create Topic
2. Create sub camp "Camp 1" and support "Camp 1"
3. Archive "Camp 1"
4. Unarchive "Camp 1"
5. Remove support from "Camp 1"
Note : Now there are no supporter on topic
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/f42346de-f275-416b-ba7b-29cac63667f8)

7. Try to support "Agreement" camp 
Actual Result : Getting warning message "Warning! "Agreement" is a parent camp to the archived child camp. So if you commit your support to "Agreement", the support of archived child camp will be removed permanently." even if user is not supporting any camp 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/4b401186-b12b-41c3-a08c-48d392b732e8)

**Comment by rupalichavan9860** [comment]
Working fine on development server

**Comment by akashgit77** [comment]
working fine on the development

**Comment by rupalichavan9860** [comment]
Verified on live
