### ISSUE TITLE
Global search- only titles are showing when enter space after number in search field

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#706]
![Screenshot 2023-12-19 at 12 13 35 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/4906e1a3-ffa2-4a6e-b71b-c0df784b2553)
 Type camp1 then enter space

**Comment by saniatg** [comment]
@vikasranatalentelgia not fixed . Searched 'camp 1' shows nickname header only
![Screenshot 2024-01-24 at 3 15 42 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/48da4898-1c61-46ba-969f-f446c23fa9ec)

**Comment by saniatg** [comment]
working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
