### ISSUE TITLE
Beta: Topic detail page is blank for some algorithms 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#71]
Please refer attached screenshot : 
![image](https://user-images.githubusercontent.com/40416610/206146425-72fe6a9f-5eeb-4bea-8f38-879905736468.png)

**Comment by sajid315** [comment]
@rupalichavan9860  working fine now.

**Comment by rupalichavan9860** [comment]
Verified
