### ISSUE TITLE
Page crash on Camp forum in below case 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#712]
Steps to reproduce : 
1. Go to https://canonizer3.canonizer.com/ or https://development.canonizer.com/
2. Open any topic 
3. Change topic  URL e.g. from https://canonizer3.canonizer.com/topic/54-Religious-Preference/1-Agreement Change URL to https://canonizer3.canonizer.com/topic/54  
4. Click on Camp Forum
5. Observe page 

Getting below page crash 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/06eae884-e786-4d57-81ce-4c6f24d49a97)

**Comment by DevAlchemyCD** [comment]
pr : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1437

**Comment by rupalichavan9860** [comment]
@wahaj-hafeez Page crash issue is resolved but getting error message while creating thread : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/54db6fb5-a520-4764-9e1d-8d05d8d67636)

**Comment by rupalichavan9860** [comment]
Working fine now on development server

**Comment by rupalichavan9860** [comment]
> @wahaj-hafeez Page crash issue is resolved but getting error message while creating thread : ![image](https://private-user-images.githubusercontent.com/40416610/299063567-54db6fb5-a520-4764-9e1d-8d05d8d67636.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MzA5NTcsIm5iZiI6MTcxMDQzMDY1NywicGF0aCI6Ii80MDQxNjYxMC8yOTkwNjM1NjctNTRkYjZmYjUtYTUyMC00NzY0LTllMWQtOGQwNWQ4ZDY3NjM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDE1MzczN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNWU5NDYzZTliNWVhNDY0ZjU4OTQxMmY3MTBhYWRmMzBkOTQyMWE1MDQyMDkwZDU5ODI4NWQ4NTc0YjQxMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5i5fsR4f_02JVOQTBFYVxKIie5eR6uWytPdyT9m5Gm0)

This is not fixed on live

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/0b0b87ea-b0e8-4553-822e-3880168a16ac)

**Comment by DevAlchemyCD** [comment]
@sajid315 Have a look

> > [@wahaj-hafeez](https://github.com/wahaj-hafeez) Page crash issue is resolved but getting error message while creating thread : ![image](https://private-user-images.githubusercontent.com/40416610/299063567-54db6fb5-a520-4764-9e1d-8d05d8d67636.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MzA5NTcsIm5iZiI6MTcxMDQzMDY1NywicGF0aCI6Ii80MDQxNjYxMC8yOTkwNjM1NjctNTRkYjZmYjUtYTUyMC00NzY0LTllMWQtOGQwNWQ4ZDY3NjM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDE1MzczN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNWU5NDYzZTliNWVhNDY0ZjU4OTQxMmY3MTBhYWRmMzBkOTQyMWE1MDQyMDkwZDU5ODI4NWQ4NTc0YjQxMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5i5fsR4f_02JVOQTBFYVxKIie5eR6uWytPdyT9m5Gm0)
> 
> This is not fixed on live
> 
> ![image](https://private-user-images.githubusercontent.com/40416610/312903047-0b0b87ea-b0e8-4553-822e-3880168a16ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MzMyODMsIm5iZiI6MTcxMDgzMjk4MywicGF0aCI6Ii80MDQxNjYxMC8zMTI5MDMwNDctMGIwYjg3ZWEtYjBlOC00NTUzLTgyMmUtMzg4MDE2OGExNmFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA3MjMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyMjAzMDA0ZTI5MjNlOGM5YmFjMGEwOTY3M2YyYTc1OTQ0OTdlYTY4MGQ2Y2RlZTI0MDRlNTdkNzg2NzUzYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A6Faq2tPkPejNHix2sf4aQW4epzO6Y3V0rU5qclm9Cc)

**Comment by sajid315** [comment]
@ks-rahul According to my findings into this , we are missing topic_name from frontend side in above mentioned specific scenario. You can see this in below image. 
**Note:** Also on create thread page we need to check the reason of calling API for get-topic-record and get-camp-record. 

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/111273633/619e6358-020b-4027-8915-e84ab979eb1f)

**Comment by ks-rahul** [comment]
@sajid315 pr raised. https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1651

**Comment by rupalichavan9860** [comment]
@ks-rahul Again getting error on dev server 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/9f243ec7-aa51-495b-bcd8-caded6f6d57d)

**Comment by sajid315** [comment]
> @sajid315 pr raised. [the-canonizer/canonizer-3.0-frontend#1651](https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1651)

@ks-rahul mentioned PR has conflicts on merge, can you please look into this ?

**Comment by ks-rahul** [comment]
@sajid315 conflict resolved.

**Comment by rupalichavan9860** [comment]
@ks-rahul @sajid315 Now getting error while submitting post . Please refer attached screenshot 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/efd351f4-df3f-439b-a1a3-39fec4564e3f)

**Comment by rupalichavan9860** [comment]
Verified on development server

**Comment by rupalichavan9860** [comment]
Verified on live
