### ISSUE TITLE
Play button is not changing even "eventline" has reached at final date.

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/Canonizer-Beta--Issue-Tracking#715]
Step:Go to event line,click on play button and change the algorithm.

**Comment by akashgit77** [comment]
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/f9cef1e4-fd6d-41a1-88f2-0f1df7d60b7a)

**Comment by akashgit77** [comment]
https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/d75f72bc-d801-4214-a550-ee367b9c0146

**Comment by DevAlchemyCD** [comment]
pr : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1442

**Comment by saniatg** [comment]
working fine on development

**Comment by akashgit77** [comment]
Working fine on the production.
