### ISSUE TITLE
Search : Getting error "404 Page Not Found" in below case

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#717]
Steps to reproduce : 
1. Search keyword "test"
2. Click on Search for "test"
3. Click on Camp Statement 
4. Click on below result 

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/7bd9ab14-1f8d-4e02-a6c2-a495c8d22003)

5. Observe result 
Getting below error : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/8a4ed147-8ca7-4e14-b681-303c332450af)

**Comment by nalwa** [comment]
@rupalichavan9860  its working fine for me, can you please confirm

**Comment by rupalichavan9860** [comment]
Yes @nalwa Working fine now

**Comment by rupalichavan9860** [comment]
Working fine on live
