### ISSUE TITLE
Search(Staging) : Getting error "Oops! Something went wrong" when user search keyword "canonizer"

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#718]
Search keyword "canonizer" and click on "Camp". Getting below error

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/2db211d9-89cf-408e-82ad-78f5f9de95d2)

**Comment by vikasranatalentelgia** [comment]
@rupalichavan9860 its not replicating

**Comment by rupalichavan9860** [comment]
This is working fine now on staging

**Comment by rupalichavan9860** [comment]
Working fine on live
