### ISSUE TITLE
Mongo DB : Score is not getting updated under Canonizer Sorted Camp Tree

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#72]
Steps to reproduce :

1. Create topic
2. Create two camps "camp 1" and "camp 2"
3. Support both camps by User A
4. Login with User B and change parent of "camp 2" to "camp 1" from agreement and commit changes
5. Wait for 24 hours and observe Canonizer Sorted Camp Tree

Expected Result :
1. It should go live after 24 hours
2. "camp 2" must be child of "camp 1"
3. And Support should get removed from parent camp("camp 1")

Actual Result : 
As of now score is not getting updated under Canonizer Sorted Camp Tree

**Comment by sunilspr7** [comment]
https://github.com/the-canonizer/canonizer-3.0-api/pull/448
PR raised

**Comment by rupalichavan9860** [comment]
@sunilspr7 @sajid315 Support is being removed from the parent camp, and the score is correct under the support tree, but the incorrect score is still displayed under the canonizer sorted camp tree. Please see the attached image:
![image](https://user-images.githubusercontent.com/40416610/207261857-b1810d32-54c4-4117-bf7d-17ae99a6fc5d.png)

**Comment by sajid315** [comment]
@rupalichavan9860 i verified it  again on my local by executing jobs, as tested on call. We need to check it on server that same process is working or not by the help of Ashu.

**Comment by rupalichavan9860** [comment]
Working fine
