### ISSUE TITLE
Multiple posts are created after clicking multiple times on "Post Submit Button"

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/Canonizer-Beta--Issue-Tracking#720]

**Comment by akashgit77** [comment]
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/7373b3d3-d9c3-4a58-8f10-448ba37b7e7d)

**Comment by hassaanCD** [comment]
Not fixed. "Session Expired" error occurred when user click multiple times on "Submit" button.

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/120023458/8beba38e-7469-4411-8448-867370910227)

**Comment by ks-rahul** [comment]
@hassaanCD this is fixed and PR has been raised.

**Comment by hassaanCD** [comment]
Verified on development server

**Comment by rupalichavan9860** [comment]
Working fine on development server

**Comment by saniatg** [comment]
working fine on production
