### ISSUE TITLE
Global search - On click searched Nickname is showing error' user not found'

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#723]
Steps:

1. Search for nickname
2. Then navigate to nickname column
3. Click on any
shows error
![Screenshot 2023-12-28 at 6 23 57 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/b5325c0d-f75a-4fba-9468-547038e4ba84)

**Comment by saniatg** [comment]
working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
