### ISSUE TITLE
Global search-  statements  showing blank which has images in search

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#725]
refers screenshot
![Screenshot 2023-12-29 at 4 53 37 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/20324f8e-efbe-4347-965c-c00c9a91800d)

**Comment by rupalichavan9860** [comment]
Working fine on development server

**Comment by akashgit77** [comment]
working fine on the production
