### ISSUE TITLE
User is unable to Un-archive the camp

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#728]
Steps to reproduce : 
1. Create Topic
2. Create sub camp and support sub camp 
3. Archive Sub camp 
4. Go to any other page 
5. Again go to camp history page and Try to un-archive the sub camp 

Result : "Un-Archive The Camp" button is disabled 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/07ee24e1-35c6-4f4e-b2c4-e25ad6cac8ee)

**Comment by DevAlchemyCD** [comment]
pr : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1457

**Comment by rupalichavan9860** [comment]
Working fine on development server

**Comment by saniatg** [comment]
working fine on production
