### ISSUE TITLE
Support is getting added to archived camp in below case 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#729]
Steps to reproduce : 
1. Create Topic
2. Create sub camp "Camp 1" 
3. Support "Camp 1"
4. Archive "Camp 1"
Note : Now score is 0
4. Create sub camps "Camp 2" and "Camp 3"
5. Support both camps
Note : Scores are- Camp 2- 0.75 and Camp 3- 0.25 and Camp 1 is archived .Refer below screenshot
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/6aa393f9-f6fb-4ed5-be76-7e5739315560)
6. Now Change parent of "Camp 2" to "Camp 3" from "Agreement "
7. Observe tree 

Expected Result : 
Camp 2 : 1

Actual Result : 
scores are 
Camp 2 : 0.75
Camp 1 : 0.25   --This camp is archived

Please refer screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/cd7515ff-2aba-4b23-b2a1-15c9f741fc8d)

**Comment by rupalichavan9860** [comment]
Working fine on development server

**Comment by hassaanCD** [comment]
Verified on development

**Comment by hassaanCD** [comment]
Working fine on production
