### ISSUE TITLE
Staging and Beta : Irrelevant data is showing on video pages

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#73]
Please refer attached screenshot : 

![image](https://user-images.githubusercontent.com/40416610/206172836-50934a55-ba1f-4712-bea7-ff0d6f8b39b6.png)

"1" , "2" and "3" must be removed

**Comment by shahab-ramzan** [comment]
PR Raised https://github.com/the-canonizer/canonizer-3.0-frontend/pull/625

**Comment by rupalichavan9860** [comment]
Verified
