### ISSUE TITLE
site breaks on logout for the profile having gravatar image

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#730]
https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/faf8a8aa-7228-4467-b7f7-3cc58c37cc98

**Comment by DevAlchemyCD** [comment]
pr : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1452

**Comment by hassaanCD** [comment]
Verified on development

**Comment by saniatg** [comment]
working fine on production
