### ISSUE TITLE
500 internal server error on "check-camp-status" api on opening history pages in incognito

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#731]
1. go to any history page
2. open history page in incognito
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/d98a7423-6cc2-4726-9701-cdf866302937)

**Comment by array-junkie** [comment]
This ticket is resolved in the following mentioned ticket.
https://github.com/the-canonizer/canonizer-3.0-api/issues/863

We have removed the check_camp_status API and the Get API from the topic/camp/statement history pages.

**Comment by hassaanCD** [comment]
Verified on development

**Comment by hassaanCD** [comment]
Working fine on production
