### ISSUE TITLE
While passing "0" in camp number url ("https://development.canonizer.com/topic/1766-New2/0-new-camp-again?canon=19&is_tree_open=0"),It is showing "something went wrong".

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/Canonizer-Beta--Issue-Tracking#733]
Steps:
1.Go to Any Camp Detail and set the camp number "0" in url.

**Comment by akashgit77** [comment]
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/45b020e1-8b32-4ddc-825d-6a9270155e57)

**Comment by sajid315** [comment]
@akashgit77 above mentioned issue is resolved. However one new issue is coming in case of wrong camp number its actually showing the topic and camp record. Even that camp is not existing in our system.

I'm looking into this issue.

**Comment by sajid315** [comment]
> @akashgit77 above mentioned issue is resolved. However one new issue is coming in case of wrong camp number its actually showing the topic and camp record. Even that camp is not existing in our system.
> 
> I'm looking into this issue.

@wahaj-hafeez I have looked into the API responses in this case, so as we discussed there's is one condition that is wrong on frontend side. So Please update that condition and update accordingly.

**Comment by DevAlchemyCD** [comment]
PR:https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1711

**Comment by saniatg** [comment]
working fine on development
