### ISSUE TITLE
When we are going to user detail page from "Support Page", then we found that while changing the numbers of users in this url "https://development.canonizer.com/user/supports/1?canon=1" it showing us the "Email" and "Home addresses" of that user even without login.

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/Canonizer-Beta--Issue-Tracking#735]
Steps:
1.Go to any "Camp Detail" page and click on the "Nick name" from the "Support" Section.
2.After getting the url "https://development.canonizer.com/user/supports/1?canon=1" change the value 
 "supports/1" to any number "supports/"N" where N = 1,2,3 ............etc.

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/70528c4f-6fd7-4a56-a721-188bcc63be18)

**Comment by akashgit77** [comment]
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/5a0413b9-79d2-43fa-8816-fcdaf52feb95)

**Comment by akashgit77** [comment]
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/29a0cbe5-9024-40fa-afdc-f63d5ac15570)

**Comment by sajid315** [comment]
@akashgit77 @rupalichavan9860 
This page information displayed as required according to public and private profile of user at canonizer, and anyone can see this info with or without login. 
Only thing i found after testing is that some fields like (DOB, State, Address Line 2) are not taking effect even we select these as public or private. Following is the reference screenshot.

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/111273633/a4074d4e-472d-44ea-b682-2628670965f4)

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/111273633/214a1ba5-7fa0-446c-a938-a7bc1dbac560)



So Do we need to display these as well ?

**Comment by akashgit77** [comment]
@sajid315 I will discuss with @rupalichavan9860 and will let you know.

**Comment by BrentAllsop** [comment]
Anything marked private should **NEVER BE SHOWN TO ANYONE**  but the logged in owner.
We need to provide a bounty for anyone who can get any "private" info, to be sure our system is very secure.
Even administrators or developers should not be able to find out this if possible, like an encrypted password.

**Comment by sajid315** [comment]
Sure @BrentAllsop , We will reverify the privacy of data. 

One point i found while we are getting users supports, so for fetching profile we should also respond only public data in it. 
I will made a fix on it as well



![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/111273633/a421f758-90ed-4da4-a3a6-556cf8c488e3)

**Comment by sajid315** [comment]
@akashgit77 All of the private flags data is verified for API responses. We can move this ticket ahead.
