### ISSUE TITLE
Camp archive issue 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#736]
If the parent camp ( Agreement ) is archived, the child camps are also archived, and the overall score of the topic becomes 0. However, for 24 hour case - Change is going live after 24 hour and the camp is archived, the child camps are unarchived, and the score does not change to 0. 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/e861c0a2-c5e7-445b-ab92-34ff71bea167)

**Comment by rupalichavan9860** [comment]
@nalwa Parent camp is unarchived but sub camps are still unarchived
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/6077012c-45e9-4eeb-aa14-02e686e26eed)

**Comment by nalwa** [comment]
@rupalichavan9860  i am clear from above statement -  **Parent camp is unarchived but sub camps are still unarchived**.

**Comment by rupalichavan9860** [comment]
This is working fine now on development server

**Comment by rupalichavan9860** [comment]
Verified on live
