### ISSUE TITLE
User Supports page : Supported camps are not listing in below case 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#737]
Steps to reproduce : 
1. Click on any nick name 
Refer below page : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/4e8b2464-0f7b-4eb5-8e60-2b1422949476)

2. Click on nickname (Support delegated to nickname) link 
3. Observe page 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/f15e3f7f-ac22-4b14-8f9c-2754ecbffcf1)

Actual Result : It is not listing supported camps 

4. Reload page and observe (It lists supported camps)
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/a426fab2-0dd6-4704-8b71-cf50e172f29a)

**Comment by rupalichavan9860** [comment]
Working fine on development server

**Comment by saniatg** [comment]
working fine on production
