### ISSUE TITLE
"Account Page" is crashing on staging and development server.

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/Canonizer-Beta--Issue-Tracking#738]
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/8ddfb392-5fd9-4962-a195-aeaafafa57c8)

**Comment by rupalichavan9860** [comment]
Working fine on dev and staging server

**Comment by rupalichavan9860** [comment]
Verified on live
