### ISSUE TITLE
The camp statement section displays "undefined".

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#739]
Steps to reproduce : 
1. Login with User A and create topic
2. Login with B and add camp statement (It will be in "in review")
3. Observe Topic detail page 
Actual Result : The camp statement section displays "undefined".
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/c93dee3d-ced8-4216-b84e-87b9d34ac9a2)

**Comment by DevAlchemyCD** [comment]
pr from frontend https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1465

**Comment by DevAlchemyCD** [comment]
pr for staging : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1466

**Comment by sajid315** [comment]
@rupalichavan9860 This issue has been fixed and PR raised for both staging and development server.

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by rupalichavan9860** [comment]
Verified on live
