### ISSUE TITLE
Blog page issues 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#74]
1. Old logo displaying 

![image](https://user-images.githubusercontent.com/40416610/206174896-540380cf-c351-4db1-8a9b-5710bc7c4c40.png)

2. When user click on canonizer logo on blog page , page should redirect to canonizer home page
As of now , it is reloading same page

3. Remove Follow Us from footer 

![image](https://user-images.githubusercontent.com/40416610/206175179-bd4af183-2217-485d-80cc-d179f3e3dd77.png)

4. Do we need canonizer.com on blog page ?
![image](https://user-images.githubusercontent.com/40416610/206175481-04ea3b94-ab8c-4427-862b-40f29a5a342a.png)

5. Header and footer links are redirecting to canonizer.com pages

**Comment by ks-rahul** [comment]
@rupalichavan9860 as per discussion with @sunnyjindal, this "5. Header and footer links are redirecting to canonizer.com pages" point is okay because we will use this blog for canonizer.com. and for this "4. Do we need canonizer.com on blog page ?" point, I add canonizer.com link on logo so now i going to remove it from menu.

**Comment by subhancd** [comment]
logo is old. Upload File page is only for admin, it should be hidden on blog page. Follow US links are removed from the footer on canonizer main page
![Image](https://user-images.githubusercontent.com/104552751/208031230-a83f6e54-8c21-4c18-ac88-715262d81d4b.png)

**Comment by ks-rahul** [comment]
PR is still open.

**Comment by subhancd** [comment]
still not working on staging and beta.

**Comment by ks-rahul** [comment]
@subhancd PR that is related to this ticket is still not merged.

check this PR.
https://github.com/the-canonizer/canonizer3-blog/pull/4

**Comment by rupalichavan9860** [comment]
@gautamv16 Can you please merge the PR

**Comment by ks-rahul** [comment]
this is fixed.

**Comment by rupalichavan9860** [comment]
Working fine
