### ISSUE TITLE
When click on any nickname , shows error on staging and on development

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#740]
![Screenshot 2024-01-08 at 10 19 23 AM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/230bcfa4-7806-4b5b-9eb8-4a2fb3e0d6f2)

**Comment by rupalichavan9860** [comment]
Working fine on live
