### ISSUE TITLE
Topic History Page - Change submit button is disabled

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#741]
**Steps to reproduce**
1. create a topic
2. navigate to topic detail page
3. navigate to topic history
4. observe the button

**Actual Result**

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/45349c08-97c9-4151-bb4e-a467915601ee)

**Comment by DevAlchemyCD** [comment]
pr form frontend: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1464

**Comment by array-junkie** [comment]
PR Raised from backend https://github.com/the-canonizer/canonizer-3.0-api/pull/897

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
