### ISSUE TITLE
Global Search - Inconsistent Data Rendering Sequence: Data Appears, Loader Intervenes, Data Reappears

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#742]
refer to the video

https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/580286cb-6da3-4670-ac12-b53b51d5e988

**Comment by vikasranatalentelgia** [comment]
same as ticket #713 and it is fixed

**Comment by subhancd** [comment]
closing this ticket as this is duplicate of https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/issues/713

**Comment by akashgit77** [comment]
working fine on the production
