### ISSUE TITLE
Topic Detail Page -  'Remove Your Support' Action Doesn't Reflect Until Page Refresh

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#743]
kindlt refer to the video

https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/22911e3c-fea3-4bad-bc66-8ae3a5a3216e

**Comment by ks-rahul** [comment]
@subhancd it is working fine on the staging and development server.

**Comment by subhancd** [comment]
@ks-rahul I'm still facing this issue on development server
[screencast-development.canonizer.com-2024.01.09-15_00_21.webm](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/7efae08b-f3b5-4fb2-97fd-a64fc7caedf0)

**Comment by saniatg** [comment]
working fine on development

**Comment by akashgit77** [comment]
working fine on the production
