### ISSUE TITLE
Camp History Page - "Submit based on this" button is displayed in "old" tab

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#744]
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/89c48a7e-b32a-489f-96e6-cf9b59f4f380)

**Comment by subhancd** [comment]
@wahaj-hafeez same for 
**Not Live**
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/50ab0883-049d-4b07-942c-4098394ac468)
**Objected**
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/8a8bb69a-7be6-4e34-a991-547fdc31e1bf)

**Comment by DevAlchemyCD** [comment]
pr from frontend :https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1464

**Comment by array-junkie** [comment]
PR Raised from backend https://github.com/the-canonizer/canonizer-3.0-api/pull/897

**Comment by saniatg** [comment]
working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
