### ISSUE TITLE
Global Search: Api 's are called two times when we clicking on "Listed Result Tab" in the Global Search Result.

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/Canonizer-Beta--Issue-Tracking#746]
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/69733979-f65a-4b8f-a780-fcaf897c4918)

**Comment by saniatg** [comment]
working fine on development

**Comment by akashgit77** [comment]
working fine on the production
