### ISSUE TITLE
Global Search: When we are switching from "camp statement" to "Camp" or "Topic", It is showing "No Data" even data is available.

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/Canonizer-Beta--Issue-Tracking#747]
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/a4125a3c-8068-40c8-8209-d6d4a26775ed)

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
@vikasranatalentelgia not fixed

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
