### ISSUE TITLE
Multiple messages are displayed on adding new image. Mulitple api calls for "update-profile-picture" are sent

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#748]
kindly, refer to the video

https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/7340e2bd-9361-40fe-9cc8-2636c32f66cf

**Comment by DevAlchemyCD** [comment]
pr : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1469

**Comment by hassaanCD** [comment]
Verified on development

**Comment by akashgit77** [comment]
@wahaj-hafeez Still not working.

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1659

**Comment by hassaanCD** [comment]
Working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
