### ISSUE TITLE
UI issues on forgot password and 

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#75]
kindly refer to the screenshots
![image](https://user-images.githubusercontent.com/104552751/206189989-e14b62ad-3042-44d7-888b-3c47b38dbe93.png)
![image](https://user-images.githubusercontent.com/104552751/206190100-f010de3b-cc23-4e0c-9baa-382f99e25bdf.png)

**Comment by rupalichavan9860** [comment]
Verified on staging and beta
