### ISSUE TITLE
Show Additional Information when topic already exists with the same name

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#750]
**Case 1**
- When user creates a new topic with the name of an existing topic, we are showing an error message
- we should display the redirection link to that topic under the topic name field

**Case 2**
- when user tries to update an existing topic with the name of already existing topic name, we are showing an error message
- we should display the redirection link to that topic under the topic name field
- validation message should display under topic name field

**Comment by DevAlchemyCD** [comment]
pr : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1510

**Comment by sajid315** [comment]
> Case 1

When user creates a new topic with the name of an existing topic, we are showing an error message
we should display the redirection link to that topic under the topic name field

> Case 2

when user tries to update an existing topic with the name of already existing topic name, we are showing an error message
we should display the redirection link to that topic under the topic name field
validation message should display under topic name field

@sunnyjindal Can you please provide content for above cases validations?

**Comment by sunnyjindal** [comment]
_The topic titled 'XXXX' already exists. Please enter a different name._

@sajid315 please underline the XXXX and open a new page when a user clicks on it.

The message will work for both the above scenarios.

**Comment by DevAlchemyCD** [comment]
Pr from frontend : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1558

**Comment by rupalichavan9860** [comment]
Verified on development server

**Comment by hassaanCD** [comment]
Working fine on production
