### ISSUE TITLE
Issues with log out 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#752]
Steps to reproduce : 
1. Login to https://canonizer3.canonizer.com/ or https://development.canonizer.com/
2. Go to Account Setting and log out 
3. Observe 

Actual Result : Screen is blank 

Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/49e78641-aaa6-4f8a-b6fd-edd94fc2a838)

**Comment by DevAlchemyCD** [comment]
pr  : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1471

**Comment by rupalichavan9860** [comment]
@wahaj-hafeez Screen is still blank for sometime and then it is working fine . can you please check this again?

**Comment by DevAlchemyCD** [comment]
@rupalichavan9860 I have verified it on development and staging.No blank page is displaying but its redirecting me to login page after successfull logout

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/99801525/e3d537b8-5f36-46d7-be6c-5ceb505ec3ad)

**Comment by rupalichavan9860** [comment]
Verified on development server

**Comment by saniatg** [comment]
working fine on production
