### ISSUE TITLE
New Search : Console error 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#754]
Getting below console errors : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/48514ef5-7be6-48ac-91c5-5311fe112c1f)

**Comment by rupalichavan9860** [comment]
Verified on development server

**Comment by akashgit77** [comment]
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/bff51f73-8e5f-4aa4-a75e-840fd0efacc5)

@rupalichavan9860 is  that fine?

**Comment by saniatg** [comment]
working fine on production
