### ISSUE TITLE
While updating Profile Info, the user is logged out.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#755]
Steps to reproduce : 
1. Go to https://canonizer3.canonizer.com/
2. Login with valid credentials 
3. Go to Account Settings-Profile Info
4. Change "Choose Default Algorithm Preferences"
5. Change "Choose Default Algorithm Preferences" one more time and observe 

Actual Result : User is getting logged out

**Comment by DevAlchemyCD** [comment]
pr  : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1484

**Comment by rupalichavan9860** [comment]
This is working fine but message "Profile updated successfully." is missing

**Comment by rupalichavan9860** [comment]
Working fine on development server

**Comment by akashgit77** [comment]
@wahaj-hafeez its not working , if we are clicking "Two times" or multiple click on the "Update" button.

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/8c585022-92a5-477f-b807-940d5f3db782)

**Comment by DevAlchemyCD** [comment]
Pr for staging : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1603

**Comment by rupalichavan9860** [comment]
Verified on development server

**Comment by rupalichavan9860** [comment]
Verified on live
