### ISSUE TITLE
Getting "Something went wrong" error when we are clicking on "Create New Camp" from "Topic Detail Page" Where "Agreement Camp" is archived.

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/Canonizer-Beta--Issue-Tracking#756]
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/d09b200b-3d80-4e08-aa33-07836e0c9343)

**Comment by akashgit77** [comment]
Steps:
1.Create  "A New topic" then archive the "Agreement Camp"
2.Now go "Edit Topic" and Click on "View This Version" then Click on "Create New Camp".

**Comment by rupalichavan9860** [comment]
Working fine on development server

**Comment by akashgit77** [comment]
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/b31f2b32-c799-4385-8b5e-31f8e7495072)

@ks-rahul Also disable  in "Drawer"

**Comment by rupalichavan9860** [comment]
@ks-rahul Still getting error, need to disable in drawer
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/2ed19d3d-7077-40f0-abb3-b012c5551621)

**Comment by ks-rahul** [comment]
@rupalichavan9860 pr is still not merged

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
