### ISSUE TITLE
When we are clicking on "Update" Button from Profile Edit Page then we are getting logged out.

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/Canonizer-Beta--Issue-Tracking#757]
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/25d456ac-b5ca-485d-a85a-c0a52d699aa1)

**Comment by rupalichavan9860** [comment]
Reported already .Please refer #755

**Comment by ashish76** [comment]
This is a duplicate issue #755

**Comment by hassaanCD** [comment]
Verified on development

**Comment by saniatg** [comment]
working fine on production
