### ISSUE TITLE
"only my topics" check box is not working on production 

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#758]
![Screenshot 2024-01-17 at 12 21 54 AM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/89b02f8a-af68-4bb8-ae4e-721ef419f124)

1. Navigate to browse page
2. click on check box "only my topics"

Nothing is happening

**Comment by rupalichavan9860** [comment]
Working fine on development server

**Comment by saniatg** [comment]
working fine on production
