### ISSUE TITLE
Global search -  Results are not loading 

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#759]
search for any keyword and then click on 'all'
![Screenshot 2024-01-17 at 4 33 04 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/717ced61-3383-4f01-870f-d07a639bff4f)

**Comment by hassaanCD** [comment]
Verified on development

**Comment by hassaanCD** [comment]
Working fine on production
