### ISSUE TITLE
Load more link for topics should appear only when there are topics to load

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#760]
Steps:

1. As a user I checked 'my topics' checkbox and selected canon as 'sandbox' on staging.
2. I clicked on link 'load more' , nothing happened no topics loaded.

Only show this link when there are topics to load otherwise not required
![Screenshot 2024-01-19 at 2 36 42 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/69d9d047-98fa-45de-89dd-d71a38bd73de)

**Comment by sajid315** [comment]
As discussed in the evening scrum call, we have to fix & test this same issue in the new UI/UX Overhaul. 
Also I just verified that the pagination coming from back-end is correct as it is required.

**Comment by rupalichavan9860** [comment]
Verified on development server

**Comment by saniatg** [comment]
working fine on production
