### ISSUE TITLE
Search : Getting error "404 Page Not Found" 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#761]
Steps to reproduce : 
1. Go to https://canonizer.com/
2. Search keyword "agree" or "canonizer"
3. Click on records which contains only "/"
Click on below highlighted records 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/2e78f550-fec3-427e-80f6-b1fa67aaca34)
4. Observe result 

Getting below error : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/2dafcaf1-f39e-4bbe-b545-2f30f3634e9a)

**Comment by rupalichavan9860** [comment]
Working fine on development server

**Comment by saniatg** [comment]
@nalwa getting empty breadcrumbs issue again on live
![Screenshot 2024-03-04 at 12 57 53 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/e22d97dd-d500-4c19-907e-0b41f8ef7fd7)
![Screenshot 2024-03-04 at 12 53 03 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/20afd029-1109-40a6-9bce-10a2c14b0339)

**Comment by rupalichavan9860** [comment]
We are unable to test the new search because it has been hidden on development.

**Comment by rupalichavan9860** [comment]
Working fine on dev server

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
Not working on live
![Screenshot 2024-04-10 at 12 12 22 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/a9b2a489-b2bf-41ad-8bdb-7a05bfccece6)

**Comment by rupalichavan9860** [comment]
Verified on development server

**Comment by rupalichavan9860** [comment]
Verified on live
