### ISSUE TITLE
While submitting post , the user is logged out. 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#765]
Steps to reproduce :

1. Go to https://canonizer3.canonizer.com/
2. Login with valid credentials
3. Select any topic
4. Go to "Camp Forum"
5. Create thread and try to create post 

Actual Result : The user is getting logged out. 
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/11ccb8f8-8658-4bb2-a657-58530c274f77)

**Comment by rupalichavan9860** [comment]
Working fine on development server

**Comment by saniatg** [comment]
working fine on production
