### ISSUE TITLE
Global search- on click browser back results are not showing

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#768]
Steps:

1. Type any keyword in search
2. Click enter
3. Now click on the searched result, user will be redirected to the page
4. Now click on browser back
5. Search 'all' screen is seen but it is empty 

![Screenshot 2024-01-24 at 4 44 58 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/a0bddd25-b258-4d3a-a462-d1ed79b2a19e)

In the url still shows the searched query

**Comment by saniatg** [comment]
@vikasranatalentelgia working fine but there is a minor issue, that the searched keyword is empty . 
![Screenshot 2024-02-09 at 12 36 49 AM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/92aa66cb-1d0f-40f3-ae2b-1d75a900b1bb)

**Comment by vikasranatalentelgia** [comment]
@saniatg This is as per requirement, this is not an issue

**Comment by hassaanCD** [comment]
Working fine on production

**Comment by hassaanCD** [comment]
Working fine on production
