### ISSUE TITLE
Change is not going live on direct supporter approval and getting error "Something went wrong"

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#769]
Steps to reproduce : 
1. Create topic (User A is supporter)
2. Login with User B and archive camp "Agreement"
3. Login with User A and agree the change

Expected Result : Change should go live 
Actual; Result : 
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/e8e06d11-89c4-4c7d-9b9d-25453f641fed)

**Comment by saniatg** [comment]
Not fixed on development

**Comment by saniatg** [comment]
working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
