### ISSUE TITLE
Camp archive : Change is going for approval even if there are no supporters 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#770]
Steps to reproduce : 
1. Create topic (User A is direct supporter)
2. Login with User A and archive the camp "Agreement"
(Note : there are 0 supporter)
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/0794990d-c5e1-4e3b-880a-9d521ca9a27b)

4. Login with User B and unarchive the camp "Agreement"
5. Observe result after 24 hours .(Note after 2 mins on dev server)

Actual Result : Change is going for approval and User A can see Agree and Object 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/add67bc2-769c-4a29-9950-675019cbb08f)
On Object User is getting error below : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/e796800d-32f1-4763-a9a3-078f4e9444ed)

Expected Result : Change should go live immediately as there are no supporters

**Comment by rupalichavan9860** [comment]
Not working

**Comment by nalwa** [comment]
@rupalichavan9860  i tested this as per the mentioned steps pn DEV env and its working fine. l

Please re-verify and we can connect if you will still face same issue.

**Comment by saniatg** [comment]
working fine on development

**Comment by rupalichavan9860** [comment]
@nalwa I am still facing this 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/f98aaa16-a27a-4382-ad00-ad0350c12fbc)

**Comment by sajid315** [comment]
> [@nalwa](https://github.com/nalwa) I am still facing this ![image](https://private-user-images.githubusercontent.com/40416610/308297969-f98aaa16-a27a-4382-ad00-ad0350c12fbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MzgxNjEsIm5iZiI6MTcwOTUzNzg2MSwicGF0aCI6Ii80MDQxNjYxMC8zMDgyOTc5NjktZjk4YWFhMTYtYTI3YS00MzgyLWFkMDAtYWQwMzUwYzEyZmJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA3Mzc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4MjE4MGQwZWYxZTIxNTQ4Yzc2YjI1ZmEzYzRlMDMyMmE2MGU0NDY2YzZlNDIwODRmNWJhNDYzZGUxNWZjOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2MmBu6gQYWi20eZI2tzFSLlbMg0MHIk61hBWyrCdKvY)

This issue has been fixed and PR raised for development server.

**Comment by nalwa** [comment]
> > [@nalwa](https://github.com/nalwa) I am still facing this ![image](https://private-user-images.githubusercontent.com/40416610/308297969-f98aaa16-a27a-4382-ad00-ad0350c12fbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MzgxNjEsIm5iZiI6MTcwOTUzNzg2MSwicGF0aCI6Ii80MDQxNjYxMC8zMDgyOTc5NjktZjk4YWFhMTYtYTI3YS00MzgyLWFkMDAtYWQwMzUwYzEyZmJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA3Mzc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4MjE4MGQwZWYxZTIxNTQ4Yzc2YjI1ZmEzYzRlMDMyMmE2MGU0NDY2YzZlNDIwODRmNWJhNDYzZGUxNWZjOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2MmBu6gQYWi20eZI2tzFSLlbMg0MHIk61hBWyrCdKvY)
> 
> This issue has been fixed and PR raised for development server.

ho @sajid315  not able to open the image. can we connect for the same?

**Comment by rupalichavan9860** [comment]
Verified on dev server

**Comment by rupalichavan9860** [comment]
Verified on live
