### ISSUE TITLE
UI- Searched camp statement is out of the border

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#771]
![Screenshot 2024-01-24 at 11 27 32 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/c532c304-7225-4cba-86fb-d3b2cf26d227)

**Comment by saniatg** [comment]
working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
