### ISSUE TITLE
Global search- searched data when refresh gets cleared

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#773]
Steps;

1. Search any keyword
2. click enter
3. searched results are seen
4. Now refresh

data is cleared

**Comment by hassaanCD** [comment]
Working fine on development

**Comment by saniatg** [comment]
@vikasranatalentelgia click on page 2 or any other, and click refresh, page 1 results are seen. Page 2 data should be refreshed.

**Comment by hassaanCD** [comment]
Working fine on production
