### ISSUE TITLE
Social Signup with "Github" is not Working.

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/Canonizer-Beta--Issue-Tracking#774]

**Comment by rupalichavan9860** [comment]
Working fine on development server

**Comment by rupalichavan9860** [comment]
Still not working
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/46aab950-f0b5-4c1e-9b79-90f3609604df)

**Comment by ks-rahul** [comment]
@akashgit77 this is working fine on the live server.

**Comment by rupalichavan9860** [comment]
Verified on live
