### ISSUE TITLE
Upload File : The uploaded files have failed to load.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#776]
Please refer attached screenshots : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/c76307c6-890d-484d-a6ae-b7e809d15dcf)

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/7010978c-23c9-4a7d-ac59-11005d6d7559)

**Comment by sajid315** [comment]
@rupalichavan9860 @akuks 
Now uploaded files are showing on development server, only issue remaining is about the perma link of file. Because we are getting this from canonizer domain URL. 
So for this I am looking into this with @akuks and we need to check uploads file table from staging to review the exact URL.

**Comment by sajid315** [comment]
@wahaj-hafeez All of the issue related to upload file updates are completed. 
Regarding this I have collaboarated with @akuks and we fixed the perma links issues as well. Only issue left is related to file render in the image box. 
I have copied the URL of image and tried to include it in camp statement (reference attached in screenshot) so at those places files are rendering but its not rendering in the image boxes inside the folder. 
Have a look please.
![image_2024_02_23T11_01_47_310Z](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/111273633/e2245230-9df8-4d36-ab4c-7c457f19d892)

**Comment by DevAlchemyCD** [comment]
Ok @sajid315 , I'm looking into this.

**Comment by DevAlchemyCD** [comment]
Pr from frontend : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1591

**Comment by rupalichavan9860** [comment]
Verified on development server

**Comment by rupalichavan9860** [comment]
Verified on live
