### ISSUE TITLE
Incorrect approver count is showing in below case 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#777]
Steps to reproduce : 
1. Create topic
2. Create 3 camps 
3. Support all 3 camps (User A is supporter)
4. Login with User B and archive "Agreement" camp 
Note : Camp will archive after 24 hrs
5. Login with User B and unarchive the Agreement camp 

Actual Result : It is showing "1 out of 4 required supporters have agreed"

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/c3d86fc4-2cc8-4e68-87dc-78b64d795d57)

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/7b30dd41-ed10-4fd6-b41d-965dee6e999b)

**Comment by saniatg** [comment]
working fine on development

**Comment by rupalichavan9860** [comment]
Verified on live
