### ISSUE TITLE
Fields are included in proposed changed emails even though they have not changed.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#778]
Submit change only for "camp archive" and check email 
It is listing Camp About Url and Camp About Nick Name values even if they have not changed.

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/3680308f-da61-49cf-8265-015e21ac1c0e)

**Comment by saniatg** [comment]
working fine on development

**Comment by rupalichavan9860** [comment]
Not working on development 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/8809d2c9-327b-4021-a59e-3d3437f8fc32)

**Comment by rupalichavan9860** [comment]
Working fine now on development server

**Comment by rupalichavan9860** [comment]
Verified on live
