### ISSUE TITLE
Email: Blog link should redirect to "https://blog.canonizer.com/"

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#78]
As of now it is redirecting to https://beta.canonizer.com/blog

**Comment by subhancd** [comment]
in staging, blog link is not redirecting to the blog
![Image](https://user-images.githubusercontent.com/104552751/208030783-d2cd298b-4b13-45b2-b4de-0972e0ff21c1.png)

**Comment by ks-rahul** [comment]
@akuks @gautamv16 could you please update this key **BLOG_URL=https://blog.canonizer.com** in api env file.

**Comment by subhancd** [comment]
working fine now.

**Comment by rupalichavan9860** [comment]
Verified on beta
