### ISSUE TITLE
Emails> showing admin@canonizer.com as recipient in emails instead of user's email Id in development for proposed change emails

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#780]
![Screenshot 2024-01-30 at 11 40 34 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/c9059230-be66-49ec-85d8-0a683ef323fd)

**Comment by saniatg** [comment]
working fine now

**Comment by rupalichavan9860** [comment]
Verified on live
