### ISSUE TITLE
Camp Archive : Getting error "Something went wrong"

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#783]
Steps to reproduce : 
1. Create topic - Login with User A
2. Create camp "Camp 1" - Login with User A
3. Support camp "Camp 1" - Login with User A
4. Login with User B and submit change for "Camp 1" - It will be in "in review"
5. Login with User A and archive "Agreement" camp 
6. Login with User A and try to object change submitted by User B in Step 4

Getting below error : 
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/90d63e99-69ba-4a10-a703-8b30a4810cce)

**Comment by DevAlchemyCD** [comment]
pr : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1537

**Comment by rupalichavan9860** [comment]
Working fine on development server

**Comment by rupalichavan9860** [comment]
Verified on live
