### ISSUE TITLE
In review -User must not be able to make changes in topic/camp if it is archived 

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#784]
Steps:

1. Archive a camp which has statement/topic/camp in review state
2. Now click on the review icon as seen below

![Screenshot 2024-02-02 at 2 05 11 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/52d6a310-83f9-40f2-a27a-90d17e6adbb3)

On click user is able to make changes in statement/topic/camp.

**Comment by saniatg** [comment]
@ks-rahul not fixed
refer screenshot
![Screenshot 2024-02-08 at 10 59 13 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/2d468e4b-d155-404f-85e9-ad26f07f9a3a)

**Comment by ks-rahul** [comment]
@saniatg pr is still not merged

**Comment by saniatg** [comment]
@ks-rahul not fixed
![Screenshot 2024-03-29 at 4 48 11 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/6a6ea5bd-5d69-4030-b732-a1ceb433299c)

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
