### ISSUE TITLE
When we go to "edit camp" for archived camp then "Create New Camp" button is visible for a moment.

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/Canonizer-Beta--Issue-Tracking#787]
https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/d1638c44-420a-4961-bed7-67bfa0e19e60

**Comment by saniatg** [comment]
working fine on development

**Comment by akashgit77** [comment]
@saniatg
https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/34aa71f0-56bc-4f45-b4b0-ea1ab3bd8d90

**Comment by akashgit77** [comment]
@saniatg @ks-rahul 

https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/6606fd8b-1802-4c7a-a4f4-b57a24705679

I just archived this camp, but its not written on "Camp Detail Page"

**Comment by ks-rahul** [comment]
@akashgit77 it is not replicating on my end

**Comment by akashgit77** [comment]
Working fine on the production.
