### ISSUE TITLE
UI issue- Space between words 'up and 'with' on forgot password page

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#789]
Login with phone and click on link " forgot password"
Need Space between words 'up and 'with'
 
![28F8F02E-6ED3-4933-814B-8052CCFFA618](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/c0e1c94c-502a-4028-bbb2-05e34f2edb70)

**Comment by saniatg** [comment]
working fine development

**Comment by rupalichavan9860** [comment]
Working fine on live
