### ISSUE TITLE
Recent Activities : Incorrect Recent Activities displaying when post submitted 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#79]
Please refer attached screenshot : 
![image](https://user-images.githubusercontent.com/40416610/206379460-90bd1737-14a6-4af6-8a3b-774bf534dab4.png)

**Comment by sajid315** [comment]
@rupalichavan9860 ,
On staging after queue restart its working,


![Image](https://user-images.githubusercontent.com/111273633/206684633-a58025c7-5d1b-4122-a9a6-91d71f07a111.png)

**Comment by subhancd** [comment]
working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on beta
