### ISSUE TITLE
Header bar  missing 

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#791]
Steps:

1. Login and go to home page
2. Now minimize screen like this as seen in screenshot

![Screenshot 2024-02-08 at 12 12 24 AM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/ddbe9a5e-2a4d-4d06-9c16-9ad484172f70)

3. Now maximize the screen
Issue 1-> Header bar is missing

![Screenshot 2024-02-06 at 4 31 53 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/9e354afd-af80-45c9-a0fb-5abb3e2cbb26)

Issue 2-> when screen is minimized , create topic button is seen, but how do I navigate to blog or browse page and upload file page. Options are not seen

**Comment by ks-rahul** [comment]
@saniatg header bar is working fine for me when minimizing and maximizing the screen, and all the other menus on the minimized screen are moved to the side drawer that will open when you click on the hamburger menu icon



![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/95217406/73d3b9a7-4e44-4243-81a8-2ce0740173cf)

**Comment by saniatg** [comment]
working fine on development

**Comment by rupalichavan9860** [comment]
Verified on live
