### ISSUE TITLE
Camp Statements and History Not Loading

### ISSUE THREAD

**Issue by mark-shamy** [the-canonizer/Canonizer-Beta--Issue-Tracking#793]
Intermittent issue on production, camp statements will not load, can't access history as the "Add Statement" button is visible. Going to the URL /statement/history/topic_number does not show history.

**Comment by DevAlchemyCD** [comment]
pr : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1560

**Comment by saniatg** [comment]
working fine on production

**Comment by rupalichavan9860** [comment]
Working fine on live
