### ISSUE TITLE
Archived camp/topic must not be editable

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#796]
Case:

1. Go to notifications
2. click on any  support notification of any camp/topic  which is archived

Support modal pop up opens and user is able to make changes like delete, change order. This is incorrect as the camp is archived

![Screenshot 2024-02-08 at 10 22 06 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/bf0e6f07-8b2a-4a5c-88a6-27eab3ebc325)

**Comment by saniatg** [comment]
@vikasranatalentelgia Not fixed

**Comment by saniatg** [comment]
working fine

**Comment by hassaanCD** [comment]
Working fine on production
