### ISSUE TITLE
In review icon missing for camp statement

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#797]
Create topic by User A
Manage edit camp statement by User B(non supporter) and click commit. The statement will be in review

Actual result: in review icon missing
Expected result:
User A must see the review icon in yellow
![Screenshot 2024-02-08 at 10 56 39 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/7bab29f6-1ff3-40a9-a8fd-04101037254e)

**Comment by saniatg** [comment]
working fine on development

**Comment by rupalichavan9860** [comment]
Verified on live
