### ISSUE TITLE
Archive- getting something went wrong error when direct supporters tries to accept the proposed change

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#798]
Steps:

1. User A creates topic and camp 
2. Support camp
3. User B tries to propose change by archiving
4. Change is in review
5. Login with User A and click on check box"I agree with this camp change"

getting error
![Screenshot 2024-02-09 at 1 16 17 AM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/32385eb3-546f-46ea-a08f-9e9eed9bac3d)

**Comment by nalwa** [comment]
@saniatg  issue tested on dev env and working fine for me, please re-verify and let me know.

**Comment by saniatg** [comment]
working fine on development

**Comment by rupalichavan9860** [comment]
Working fine on live
