### ISSUE TITLE
Topics and URL are not getting reset  when user is Logged out 

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#802]
Steps:

1. Go to browse and select only my topics
2. Now choose filter " include review"
3. And logout

Actual result :user will still see only my topics and filter will be set to default but in the URL as of =review is seen 
Expected result: URL must show default and topics should also reset

![Screenshot 2024-02-13 at 3 46 15 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/3614c4ed-f475-4321-ad83-7149c893d0e3)

**Comment by DevAlchemyCD** [comment]
pr : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1574

**Comment by saniatg** [comment]
@wahaj-hafeez failing in case of as of date filter
As seen in screenshot URL is also not reset and the date field is enabled , but selected is default
![Screenshot 2024-03-28 at 11 06 23 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/10b83501-d57b-46e2-bbcf-5b44adebb2b7)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1671

**Comment by saniatg** [comment]
working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
