### ISSUE TITLE
User is able to click on "Support" button and "pop up" is also  open even he is not logged in yet.

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/Canonizer-Beta--Issue-Tracking#803]
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/96e5a093-bb49-4d95-a33d-32805d1d7931)

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
