### ISSUE TITLE
Blank page when trying to support camp

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#804]
Steps:

1. Go to  topic details page
2. logout 
3. Now click on the logo next to camp forum button, and click on "directly join and support camp " as highlighted in the screenshot
![Screenshot 2024-02-13 at 4 30 46 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/1484034f-e6df-43fc-8a8c-c4cc4175cae9)
4. on click blank screen is seen

The option should be disabled as user is not logged in

**Comment by hassaanCD** [comment]
Working fine on development

**Comment by saniatg** [comment]
on logout , user is redirected to home page. Now this case is not coming
