### ISSUE TITLE
Disable  directly join button  for users who are not logged in or redirect to login page

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#805]
Go to topic details page and click on button directly join
Modal pop up opens and now click submit .
Pop up is blank

![Screenshot 2024-02-13 at 4 42 54 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/faa5b5ea-dc1e-43f9-90cb-1e4f978436e6)
![Screenshot 2024-02-13 at 4 42 59 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/5e24fb00-9e23-49d6-8b0c-0840380dc3cc)

**Comment by saniatg** [comment]
duplicate of ticket
https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/issues/803
closing

**Comment by saniatg** [comment]
working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
