### ISSUE TITLE
Disable 'remove support' button for users not logged in 

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#806]
Steps:

1. Go to topic details page and support topic
2. Now log out

Actual result: user will see 'remove support" button enabled
Expected result: 'remove support" button should be disabled
![Screenshot 2024-02-13 at 4 45 19 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/678399d4-b06d-4b28-aae0-7d41570a6068)

**Comment by saniatg** [comment]
working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
