### ISSUE TITLE
Canonizer logo is not Showing on top left corner and missing in other areas as well

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#809]
![Screenshot 2024-02-14 at 4 15 50 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/f385ada1-05cf-4fe5-bdc4-004d07f7d1f5)

**Comment by hassaanCD** [comment]
Canonizer logo is also not showing in footer



![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/120023458/26604c7c-5717-40ad-a77d-23edbe2dff33)

**Comment by rupalichavan9860** [comment]
This is working fine
