### ISSUE TITLE
When a user clicks on the camp name, the support pop-up should close. 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#810]
Steps to reproduce : 
1. Go to any supported camp
2. Click on "Manage Support" /"Directly Join and Support"/"Delegate Your Support"
3. Click on camp name 

Expected Result : It should show topic detail page 

Actual Result : It is showing blank support pop up
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/5e580b90-ec56-4827-a8fa-75391ccf6f85)

**Comment by saniatg** [comment]
@vikasranatalentelgia WHen click on camp name nothing is happening on supported module and in the uRl it is showing # at the end .

**Comment by rupalichavan9860** [comment]
Verified on dev server

**Comment by rupalichavan9860** [comment]
Verified on live
