### ISSUE TITLE
Create new camp button from history page is not redirecting to create camp page

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#811]
![Screenshot 2024-02-16 at 4 14 51 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/eafc6a90-ddfa-4d16-989f-ab1245810217)

**Comment by DevAlchemyCD** [comment]
@saniatg I tried to reproduce this issue but I'm not able to reproduce it. Can you please check it again and reverify ?

**Comment by saniatg** [comment]
@wahaj-hafeez working fine on development

**Comment by saniatg** [comment]
@wahaj-hafeez This issue is coming, refer the steps below

1. Archive agreement camp
2. Then from history page unarchive the camp and click on "create camp button"

The page is not loading

**Comment by saniatg** [comment]
WORKING FINE

**Comment by akashgit77** [comment]
https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/5a4517f8-8a71-44e3-80eb-5db9381a58cb
Not working on the development server.

**Comment by DevAlchemyCD** [comment]
@akashgit77 ! I have tested this case on development. The button is displaying and also redirects me to create the new camp page.

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/99801525/46d2d97a-f41c-465c-99e3-6e89a3b3e5a9)

**Comment by rupalichavan9860** [comment]
Verified on development server

**Comment by saniatg** [comment]
working fine on production
