### ISSUE TITLE
Showing the "View All Topics" option/link for canons with less than 15 topics.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#813]
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/4e244666-66c0-4657-a7d1-648e9d06e0b4)

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/ff1019a3-65af-4f0f-b09f-9eb3202a9958)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1578

**Comment by rupalichavan9860** [comment]
Not fixed 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/15eee9b8-5664-4d1c-8824-e695a8780c9c)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1668

**Comment by rupalichavan9860** [comment]
Verified on development server

**Comment by rupalichavan9860** [comment]
Verified on live
