### ISSUE TITLE
UI: "Sort By" text  is overlapping on "Select Canon Division".Url("https://development.canonizer.com/")

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/Canonizer-Beta--Issue-Tracking#814]
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/74e8b4d7-489d-4bbb-b933-b285bd13aec7)

**Comment by ks-rahul** [comment]
@akashgit77 this is working fine for me. could you please provide me more information about this when you are getting this issue.

**Comment by akashgit77** [comment]
@ks-rahul Sure

**Comment by rupalichavan9860** [comment]
Verified on dev server

**Comment by saniatg** [comment]
working fine on production
