### ISSUE TITLE
Recent activities- 'i' info icon , it is showing empty on hover

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#816]
refer screenshot

![Screenshot 2024-02-20 at 4 23 49 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/27b3aee9-0343-4abc-8bdf-5cf219adbbde)

Also On "Current Camp Recent Activities" 

![Screenshot 2024-02-20 at 4 28 40 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/91b4d654-6dfe-44cd-9a13-dbbaa60bb9e8)

**Comment by DevAlchemyCD** [comment]
@saniatg this ticket works fine

**Comment by saniatg** [comment]
working fine on development

**Comment by akashgit77** [comment]
@saniatg @wahaj-hafeez Info button is removed now.

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/622b2805-437d-40a6-af76-d3e3f902f4ab)

**Comment by saniatg** [comment]
tootlip is working fine on development

**Comment by saniatg** [comment]
working fine on production
