### ISSUE TITLE
Incorrect date and time when creating thread

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#819]
![Screenshot 2024-02-20 at 11 48 58 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/5ae653fb-32f7-4e0e-aadc-fea6166a70ca)

**Comment by rupalichavan9860** [comment]
Working fine on development server

**Comment by rupalichavan9860** [comment]
Verified on live
