### ISSUE TITLE
Issues in sort by functionality

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#824]
Issue 1: It should be score value not sort view
![Screenshot 2024-02-21 at 5 15 39 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/5351e882-3e44-4e22-98da-773ad5a6c2d2)

Issue 2: when click on sort by and choose any option it redirects to browse page
Issue 3: Sort view when replaced by score value should come in single line
![Screenshot 2024-02-21 at 5 17 08 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/3029c6c8-454c-44e1-8fe8-3004317334bb)

**Comment by saniatg** [comment]
working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
