### ISSUE TITLE
Something went wrong error  when create camp in case of archive

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#826]
Scenario:

1. Create a topic and a camp
2. Submit any camp change
3. And ow archive the camp
4. Now in recent activities click on  '[username] proposed change on [camp_name]
5. Create camp button is seen , click on it error is seen

Create camp button should be disabled here as it is archived
![Screenshot 2024-02-21 at 6 06 44 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/3735e61c-e42e-40a3-8385-99def106b481)

**Comment by saniatg** [comment]
working fine for now.

**Comment by hassaanCD** [comment]
Working fine on production
