### ISSUE TITLE
Eventline is not working for new topics

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#827]
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/2846742d-7058-4932-ab6e-ca0227a22f7d)

**Comment by rupalichavan9860** [comment]
This is working fine now on development server

**Comment by akashgit77** [comment]
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/5f01d608-26bb-4141-bc3d-7d14dcadafc4)

@rupalichavan9860 Still Not Working ,After creating new topic and going into eventline through "Url"

**Comment by rupalichavan9860** [comment]
Still not working . Working fine on reloading the page  
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/b1182166-d5bb-47d3-a4f5-140dccc81fb5)

**Comment by sunilspr7** [comment]
#eventline queue service name
EVENTLINE_QUEUE_SERVICE_NAME=canonizer3-service-eventline

queue services not working but now it is done.

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on live
