### ISSUE TITLE
Bread crumbs should display the live topic and live camp names.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#83]
Steps :
1. Select any topic/camp.
2. Go to the history pages.
3. Select an old /in review /objected record.
4. Click the View this version button.
5. Navigate to any page and look for bread crumb names.

Expected Result : It should always display live names.

Actual Result: It is currently displaying selected record names.
Please refer attached screenshot : 
![image](https://user-images.githubusercontent.com/40416610/206682933-bef106bc-3a16-4af4-8751-685503bd5166.png)

![image](https://user-images.githubusercontent.com/40416610/206683058-ae2ca21e-c6e3-4a56-ba15-a80997663e99.png)

**Comment by sajid315** [comment]
From backend PR created: 
https://github.com/the-canonizer/canonizer-3.0-api/pull/459

**Comment by subhancd** [comment]
@sajid315 for this topic: 
https://canonizer3.canonizer.com/topic/88-Theories-of-Consciousness/1-Agreement
go to topic history -> view this version of old topic -> navigate to camp forum or any history page -> old topic name is showing on those pages. 
it should display live topic name.

**Comment by subhancd** [comment]
working fine on staging.

**Comment by subhancd** [comment]
working fine on beta. kindly verify and close @rupalichavan9860
