### ISSUE TITLE
UI issues in sort by

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#830]
selecting canon 'crypto currency' 'by' is out of the div
![Screenshot 2024-02-23 at 2 01 43 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/edb1ae5a-ca97-4015-b625-b94e2f9fde36)

and when selecting canon : organization>united_utah_party the whole sort by is out of div
![Screenshot 2024-02-23 at 2 03 25 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/20029781-71a8-4f6d-8de6-913a4b4b373b)

**Comment by saniatg** [comment]
working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
