### ISSUE TITLE
Add "Camp Leader" field on Camp History Comparison 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#831]

**Comment by rupalichavan9860** [comment]
Functionality is implemented but this field is not added on Camp History Comparison page so reopening this ticket

**Comment by array-junkie** [comment]
@wahaj-hafeez We need to show camp leader details in camp comparison page.

**Comment by wahaj-hafeez** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1924

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1924
