### ISSUE TITLE
Camp is archived but the message "This camp is archived" is not visible when we open Url without login.

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/Canonizer-Beta--Issue-Tracking#832]
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/50f7b3a0-42c9-40a1-9587-bc7681c9f72a)

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
