### ISSUE TITLE
Remove support on first click is not working on live and development

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#834]
1. Go to any topic or create new
2. remove support or click on manage support , add support then click on remove support button

On first click nothing happens
On refresh support is removed

This is happening because of delayed response.

**Comment by hassaanCD** [comment]
I encountered 2 confirmation messages on production. (For new topic)

![Screenshot_4](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/120023458/5273f1ec-80a4-45ed-811e-1173a1e43ce1)

**Comment by DevAlchemyCD** [comment]
@saniatg this ticket works fine

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
Not working . Still facing issue also delegate support is not removing

**Comment by DevAlchemyCD** [comment]
@saniatg ! I have tested and verified this scenario on both development & live environments. It is working fine.

**Comment by rupalichavan9860** [comment]
Verified on dev server

**Comment by saniatg** [comment]
working fine on development
