### ISSUE TITLE
Topic name and Camp name in URL and Consensus Tree is not getting updated 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#836]
Change topic name and camp name
Observe URL and Consensus Tree

Please refer attached screenshot : 
URL : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/bad042d7-e497-41d1-b2ff-f0d43e64a318)
Consensus Tree : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/d9c0a28e-3f65-47de-8106-e5357e4bb644)

When user refresh/reload the page and again click on topic name link then it is working fine

**Comment by wahaj-hafeez** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1589

**Comment by DevAlchemyCD** [comment]
@sajid315 We need a check in the "/commit" API. So, we can call breadcrumb API, if all supports agree and the change is going live in the current commit

**Comment by sajid315** [comment]
> @sajid315 We need a check in the "/commit" API. So, we can call breadcrumb API, if all supports agree and the change is going live in the current commit

Sure @wahaj-hafeez , I am working on it and will let you know after passing checks.

**Comment by sajid315** [comment]
@wahaj-hafeez here is the commit for changes that are done from backend side, 
https://github.com/the-canonizer/canonizer-3.0-api/commit/a5fcad7b7c545ff90875449c72ffede078ee5abc

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1596

**Comment by rupalichavan9860** [comment]
Verified on dev server

**Comment by hassaanCD** [comment]
Working fine on production
