### ISSUE TITLE
Validation message is not refreshed

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#837]
Steps:

1. Click on create new topic button
2. Enter duplicate topic name
3. error message'The topic titled [topic] already exists. Please enter a different name.' is seen which is correct
4. Now enter unique name
5. Click button 'create topic

Error message - 'The topic titled [topic] already exists. Please enter a different name.' is seen while loading .

![Uploading Screenshot 2024-02-27 at 6.47.49 PM.png…]()

**Comment by DevAlchemyCD** [comment]
@saniatg This issue was reported by @hassaanCD and PR has been raised by me today.

Ticket URL: https://github.com/orgs/the-canonizer/projects/4/views/1?filterQuery=1583&pane=issue&itemId=54298887

**Comment by saniatg** [comment]
Duplicate of issue 
Ticket URL: https://github.com/orgs/the-canonizer/projects/4/views/1?filterQuery=1583&pane=issue&itemId=54298887

Therefore, closing it
