### ISSUE TITLE
UI- Validation error messages should be of same font size, color and  family throughout the application

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#838]
In below screenshot for duplicate topic error  the font size, color is different than rest messages

 
![Screenshot 2024-02-27 at 7 18 40 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/dd9023e0-8436-43e8-b148-10279ce88090)

This one is for camp
![Screenshot 2024-02-27 at 7 18 16 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/ff0d5729-60f1-4c39-a956-7068c75f4f1a)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1593

**Comment by saniatg** [comment]
@wahaj-hafeez not fixed

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1683

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
