### ISSUE TITLE
"Topic Name" section is overlapping the "Footer Section".

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/Canonizer-Beta--Issue-Tracking#841]
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/0ef2cc8d-26de-4ec3-98aa-4b5b4c91e75b)
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/0445a327-3731-42f6-9c70-7e8800a4f383)

**Comment by saniatg** [comment]
@ks-rahul not fixed
![Screenshot 2024-04-02 at 7 09 45 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/32c08316-4d7e-470a-b5fa-e031d372c6ae)

**Comment by ks-rahul** [comment]
@saniatg I checked this issue and it seems to be working fine.

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
