### ISSUE TITLE
Delete news UI - space between  words 'from' and 'agreement'

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#842]
Also add  space before delete icon

![Screenshot 2024-03-01 at 12 10 24 AM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/3c133cad-b534-4ba7-95ad-bcb35cc45468)

**Comment by rupalichavan9860** [comment]
Verified on development server

**Comment by saniatg** [comment]
working fine on production
