### ISSUE TITLE
Site Map is Not Working on "Live" & "Staging".

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/Canonizer-Beta--Issue-Tracking#844]
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/3b773acb-9f1d-436c-953b-0c76ccbc6c71)

**Comment by ks-rahul** [comment]
@akashgit77 this is working now please check.

**Comment by akashgit77** [comment]
@ks-rahul Okay

**Comment by rupalichavan9860** [comment]
Working fine on live
