### ISSUE TITLE
Topic not found error on live under canon "sandbox"

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#845]
When in home page and selected canon is "sandbox" 
There are few topic when click shows 404 

E.g. Can AI replace humans
https://canonizer.com/topic/1659-Can-AI-replace-humans/1-Agreement
https://canonizer.com/topic/220-Test-making-changes-go-live/1-Agreement

**Comment by saniatg** [comment]
working fine

**Comment by sajid315** [comment]
@saniatg Thanks for confirmation. 
One thing we have as issue is, whenever user is going to a non-existing URL then "Go Back" button not working as expected. 
For example, Open this URL in newTab and in same tab and then click on "Go Back" button. 
https://canonizer.com/topic/1659-Can-AI-replace-humans/1-Agreement

@wahaj-hafeez can look into this issue. "Go Back" not working as expected.

**Comment by DevAlchemyCD** [comment]
pr  : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1648

**Comment by saniatg** [comment]
@wahaj-hafeez "Go Back" not working as expected- this issue still exists

**Comment by saniatg** [comment]
@wahaj-hafeez I checked on live , on development is working fine.

**Comment by saniatg** [comment]
working fine on live
