### ISSUE TITLE
Github login not working on live

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#846]
![Screenshot 2024-03-04 at 2 00 59 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/3021c6d8-de7c-40d8-884f-9268cb2eb778)

**Comment by ks-rahul** [comment]
@saniatg I have tested this issue on the live server and it is working fine. could you please verify this again?

**Comment by rupalichavan9860** [comment]
Working fine on live
