### ISSUE TITLE
Profile info- Profile pic when uploading is giving error

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#848]
![Screenshot 2024-03-04 at 5 38 04 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/c8b367e6-d9e9-4c1e-a33e-1aa4232e071d)

**Comment by sajid315** [comment]
@saniatg , @wahaj-hafeez Fixing from back-end side is done and PR raised from my end. 
But on front-end side we need some more fixings to do, 
1- We should display exact error message to end user that is coming from back-end, currently its showing "Upload Failed" only.

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/111273633/3f749328-a7f0-42ff-95f8-850d40f8474f)

2- Also need to remove the static file condition of 1000x1000 pixel at client side.

**Comment by DevAlchemyCD** [comment]
@sajid315 Changes have been done from frontend side and PR is also raised.
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1624
