### ISSUE TITLE
404 error for some topics on live

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#849]
Under canon 'Corporations ' , click on any topic except the  first one rest all  are redirecting to 404 'Page not found' on live

Note: This issues exist for other topic also in different canon

**Comment by sajid315** [comment]
@saniatg this issue is already resolved in last show stopper issue of https://github.com/the-canonizer/canonizer-service/issues/296. 
Now its working fine , Have a look Please.

**Comment by rupalichavan9860** [comment]
Working fine on live
