### ISSUE TITLE
UI- loader design is not proper on recent activities load more

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#851]
Steps:

1. Go to recent activities
2. Click on 'View all topics"
3. Now click on button 'Load more'

Notice the loader

![Screenshot 2024-03-05 at 6 35 35 PM](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/91254708/ce2c85c5-9652-40b6-b9d0-21675687b9ac)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1601

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
