### ISSUE TITLE
Create Topic Form is not loading properly when we refresh specially "Nickname Field".After submitting without nickname ,it shows an error.

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/Canonizer-Beta--Issue-Tracking#853]
https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/e63c18a9-8ac4-412e-98a8-90324f6f05f6

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
