### ISSUE TITLE
Multiple clicks are working while clicking on "delete", In uploaded files list.

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/Canonizer-Beta--Issue-Tracking#858]
https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/d3dfca21-ea6d-4bed-9de0-25cf35d5e326

**Comment by DevAlchemyCD** [comment]
pr : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1605

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
