### ISSUE TITLE
Search is not loading on development 

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#860]
![Screenshot 2024-03-08 at 10 00 31 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/632f8a44-cdd0-4603-88da-c6b7e8513a10)

**Comment by nalwa** [comment]
@saniatg  search is now working on development server. please check and close this issue.

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
Working on production
