### ISSUE TITLE
As of date is different on consensus tree and on topic detail page

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#861]
When I choose any as of date of past date, on consensus tree . The same is not updated on topic detail page

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1607

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
