### ISSUE TITLE
After creating new camp "something went  wrong" error is coming.

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/Canonizer-Beta--Issue-Tracking#863]
Steps: Create a topic then create a camp.

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/de165678-c057-411c-9f06-59a7e1fb4f6c)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1612

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
Working fine on production
