### ISSUE TITLE
Live: showing Invalid date and nickname is missing next to 'Started by' when creating thread

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#866]
![Screenshot 2024-03-11 at 6 50 54 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/d751bd90-e863-4ede-81bd-8796ce33b642)

**Comment by ks-rahul** [comment]
@saniatg this issue is already fixed and deployed on the development server once the dev code is pushed to the live server it will be resolved.

**Comment by saniatg** [comment]
working fine on live

**Comment by saniatg** [comment]
working fine on production
