### ISSUE TITLE
Some times "Loading page" appears for a moment when we are navigating the web pages.

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/Canonizer-Beta--Issue-Tracking#867]
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/35ac11f6-38a0-4990-b422-05caa264c8be)

**Comment by saniatg** [comment]
Duplicate of https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/issues/859

**Comment by DevAlchemyCD** [comment]
@akashgit77  not works on production

**Comment by DevAlchemyCD** [comment]
Pr for production : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1694

**Comment by saniatg** [comment]
working fine on production
