### ISSUE TITLE
Some times "Something went wrong" error appears for a moment when we are navigating the web pages.

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/Canonizer-Beta--Issue-Tracking#868]
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/4ba67ab2-36bc-459a-898f-bd9134321097)

**Comment by sajid315** [comment]
@akashgit77 its not producing at my end even on local or on development. Can you please check?

**Comment by akashgit77** [comment]
@sajid315 Its working fine , Now.

**Comment by akashgit77** [comment]
Working fine on the production.
