### ISSUE TITLE
Thread page is not reponsive

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#869]
Refer screenshot
![Skype_Picture_2024_03_14T05_10_25_301Z](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/690a732f-5d68-415d-877d-d1ba715dff06)

**Comment by vikasranatalentelgia** [comment]
@saniatg It is deployed on development server. Please test

**Comment by vikasranatalentelgia** [comment]
@saniatg This ticket is working fine in development kindly test it and close the ticket

**Comment by saniatg** [comment]
@vikasranatalentelgia for a sec it  flickers  as shown in the screenshot
![ImportedPhoto 733912939 450778 (1)](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/23471408-2cd9-4d49-a22d-b80d6a99e32c)

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
Not fixed on production @vikasranatalentelgia

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
