### ISSUE TITLE
Commit Change: User is able to click more than once, and direct supporters receive multiple emails and notifications.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#87]
This problem exists on all history pages.

**Comment by subhancd** [comment]
@shahab-ramzan commit can still be clicked twice on all history pages


![Image](https://user-images.githubusercontent.com/104552751/208038040-9ec92757-9016-4e64-9130-64cdcbe3e25a.png)

**Comment by subhancd** [comment]
working fine on staging and beta @rupalichavan9860
