### ISSUE TITLE
Selected filter on topic page- Clear all not working when selecting algo

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#870]
Steps:

1. Choose Mind expert or any algo from consensus tree
2. On Topic page click on clear All

Clear All is not working
![Uploading Screenshot 2024-03-14 at 12.59.16 PM.png…]()

**Comment by saniatg** [comment]
@vikasranatalentelgia not working, the score is not changing

**Comment by hassaanCD** [comment]
Sometimes score change sometimes remain same after clicking on "Clear" button.
Algorithm also not changed sometimes in consensus tree after clicking on "Clear" button.

**Comment by hassaanCD** [comment]
Working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
