### ISSUE TITLE
UI issue - Showing arrow on censuses tree 

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#872]
![Screenshot 2024-03-14 at 12 58 27 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/5bd94379-6c41-47fc-914e-578321778310)

**Comment by DevAlchemyCD** [comment]
@saniatg This arrow is displaying here because Collapse Component of antd is used here.

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
