### ISSUE TITLE
Unarchive button not working for a specific case

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#875]
1. Go to any camp
2. Archive camp by user A
3. Copy the url of history page and paste it in other browser
4. Login with user b 
5. Click on unarchive button

![Screenshot 2024-03-15 at 12 52 59 AM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/e7e7171d-54fa-4d60-9083-3ece3a89cdc2)

**Comment by vikasranatalentelgia** [comment]
@saniatg This ticket is working fine in development kindly test it and close the ticket

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
