### ISSUE TITLE
Session expired issue on create camp page

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#876]
Steps.

1. Go to create camp page
2. Click on logout 

Your session has expired message is seen
![Screenshot 2024-03-15 at 10 10 43 AM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/c2792270-c24a-44d3-aa41-f6c8fa658770)

**Comment by ks-rahul** [comment]
@saniatg I verified this issue on all three servers, and it works fine. Have you faced this issue in the specific scenario

**Comment by rupalichavan9860** [comment]
Working fine
