### ISSUE TITLE
UI- Upload files , show pagination  only when there are next pages

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#877]
Currently showing pagination where there are no pages.

![Screenshot 2024-03-15 at 9 52 46 AM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/183048b4-5a69-4433-beda-eca3668507e4)

**Comment by vikasranatalentelgia** [comment]
@saniatg This ticket is working fine in development kindly test it and close the ticket

**Comment by saniatg** [comment]
working fine on developement

**Comment by saniatg** [comment]
working fine on production
