### ISSUE TITLE
Create date is not showing in correct format on thread detail page 

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#878]
Steps:

1. Go to camp forum
2. Create a thread
3. Click on the thread created 
4. Now logout
5. Login

On login notice the created date 
![Screenshot 2024-03-15 at 10 20 29 AM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/5978a7c7-bd0c-4a5b-b401-e41357837a1a)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1622

**Comment by saniatg** [comment]
working fine on development and production

**Comment by saniatg** [comment]
working fine on production
