### ISSUE TITLE
issue in email of direct supporter and subscriber

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#88]
**Steps to reproduce**

1. user A creates a topic 
2. user B subscribe to agreement camp
3. user B adds support in agreement camp
4. check mail
**Actual Result**
the mail user A receives.
![image](https://user-images.githubusercontent.com/104552751/207048846-4d420447-2f6d-4610-af17-77fe59d9c1cf.png)
**Expected Result**
user A is not subscribed to the camp, so "You're subscribed to <camp name>" shouldn't be in the mail

**Comment by subhancd** [comment]
working fine on staging. not working on beta @rupalichavan9860

**Comment by rupalichavan9860** [comment]
Working fine on beta
