### ISSUE TITLE
Upload files : Perma links are not working in camp statements on live

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#880]
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/eb54882b-6532-49ea-999e-3d4acafc3421)

**Comment by sajid315** [comment]
Raised PR's are following:
https://github.com/the-canonizer/canonizer-3.0-api/pull/962
https://github.com/the-canonizer/canonizer-3.0-api/pull/961

**Comment by sajid315** [comment]
@rupalichavan9860 I have fixed the above mentioned issue, and now all of the Perma-links are working. Have a look please.

https://canonizer.com/statement/history/804-827-Testing/1-Agreement

**Comment by rupalichavan9860** [comment]
Yes @sajid315 Working fine now on live so closing this 
@akashgit77 Could you kindly check it and create an automation script for it?
