### ISSUE TITLE
Selected Filter : "Include Review" selected filter is not showing in below case 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#881]
Steps to reproduce : 
1. Go to any topic detail
2. Apply "Include Review" filter 
3. Go to any other page (e. Camp Forum, Camp statement)
4. Click on Agreement 
5. Observe 

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/c557706f-df22-465a-aaac-44a357c1c267)

**Comment by hassaanCD** [comment]
Working fine on development

**Comment by saniatg** [comment]
working fine on production
