### ISSUE TITLE
Live : Event line is not working properly

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#884]
Issue 1 : Incorrect topic name displaying in breadcrumb 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/bd279b90-0e69-485c-9a01-dce92ffdbf84)

**Comment by saniatg** [comment]
Archive and unarchive events are also not listing

**Comment by saniatg** [comment]
Also, for the first time when you try to check eventline for any topic, eventline does not load

**Comment by rupalichavan9860** [comment]
Archive and unarchive events are not listing on dev server

**Comment by sunilspr7** [comment]
#eventline queue service name
EVENTLINE_QUEUE_SERVICE_NAME=canonizer3-service-eventline

queue services not working but now it is done.

**Comment by rupalichavan9860** [comment]
Verified on live
