### ISSUE TITLE
Layout issues on mobile devices

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#887]
Please refer attached screenshot : 
1. Extra line on right top corner
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/871f374d-c959-4689-8d24-e2b9bd3fed39)

2. Camp Forum is not displaying properly
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/09272d63-93f4-40ff-af65-0ad3dfc06ff7)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1652

**Comment by hassaanCD** [comment]
2nd issue is not fixed

**Comment by wahaj-hafeez** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1669

**Comment by rupalichavan9860** [comment]
Verified on development server

**Comment by rupalichavan9860** [comment]
Verified on live
