### ISSUE TITLE
Multiple clicks on "Perma link" are working in the "Uploaded Image View" page.

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/Canonizer-Beta--Issue-Tracking#889]
Steps:

1.Go to Upload FIle Page.
2.Then Click on "View File " from three Dots.
3.Then Click Multiple Times On "Copy Perma link".

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/4b1ee5a6-e7b4-402a-af32-0a09f06ea263)

**Comment by DevAlchemyCD** [comment]
@akashgit77 
1-Go to npmjs.com
2-Search out any npm package using the search bar
3-Click on npm i package-name to copy the installation command multiple times.
4-Note the behavior.

**Comment by DevAlchemyCD** [comment]
@akashgit77 ! Its not an issue

**Comment by akashgit77** [comment]
@wahaj-hafeez okay
