### ISSUE TITLE
Live : Getting error "No alive nodes. All the 1 nodes seem to be down." while creating new topic and camp 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#891]
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/92b44419-ed3e-45d0-a644-9f76b3a9bd42)

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/b04a39d7-a911-44c1-beea-f6587b32b6f3)

**Comment by nalwa** [comment]
@rupalichavan9860  its working,  whenever elastic search server stopped working its shows this error. So if in future this appears again you can ask @akuks  to restart the server.

**Comment by rupalichavan9860** [comment]
Sure @nalwa . Closing this for now
