### ISSUE TITLE
When we have selected "As of Date" (Selected date before topic was created) filter then "Create New Camp" button comes and goes after refreshing the page.

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/Canonizer-Beta--Issue-Tracking#894]
@rupalichavan9860 Should we show "Create New Camp" button when we selected "As of Date" filter when topic was not created?

https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/95d12432-05f3-410e-b29c-e3bbffe7bc7a

**Comment by akashgit77** [comment]
@rupalichavan9860  Should we show "Create New Camp" button when we selected "As of Date" filter when topic was created?

**Comment by DevAlchemyCD** [comment]
Pr : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1663

**Comment by saniatg** [comment]
working fine, button disabled with a note
