### ISSUE TITLE
UI - showing double arrows on history pages

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#898]
![Screenshot 2024-03-29 at 4 44 27 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/a6ec7e9a-de62-47d9-a60f-1aa4e86551a0)

**Comment by rupalichavan9860** [comment]
Verified on development server

**Comment by saniatg** [comment]
working fine on production
