### ISSUE TITLE
Showing NA when select as of date 

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#899]
Steps:

1. Go to any topic
2. now from consensus tree choose any past date
3. Close the consensus tree
4. Click on the date when topic was created

![Screenshot 2024-04-01 at 12 41 37 AM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/cc59d991-cd9b-453c-9580-84fc9e1c8fe1)

**Comment by rupalichavan9860** [comment]
@saniatg This is already reported and in "In review-dev" status 
Please check below ticket
https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/issues/790

**Comment by saniatg** [comment]
OKAY @rupalichavan9860 closing this issue
