### ISSUE TITLE
Thread : Time is invalid and nick name is missing for the following case

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#90]
**Steps to reproduce**

1. user A creates a topic
2. user A navigates to camp forum
3. user A creates a thread
4. user A navigates to thread
5. copy the url
6. paste it in a new browser
7. click on sign in
8. sign in with user B
**Actual Result**
after sign in, user B is redirected to thread page but time is invalid and nick name is missing
![image](https://user-images.githubusercontent.com/104552751/207239577-33440b4f-0e4d-4567-988c-d639528b5830.png)

**Comment by subhancd** [comment]
working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on beta
