### ISSUE TITLE
Edit Camp is not working, Its not redirecting to "Camp History" when we click on "Edit Camp" button.

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/Canonizer-Beta--Issue-Tracking#902]
https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/83016e19-e704-4db6-a4a9-23a93d50a2c4

**Comment by rupalichavan9860** [comment]
Working fine on dev server

**Comment by saniatg** [comment]
working fine on live
