### ISSUE TITLE
Supporter nickname is not showing in below case

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#903]
Steps to reproduce : 
1. Create topic (User A is direct supporter)
2. Login with User A and archive the camp "Agreement"
3. Login with User B and unarchive the camp "Agreement"

Observe result after grace period

Expected Result : 
Support must be revoked 

Actual Result : 
Can see "Manage Support" but nickname is not listing

**Comment by rupalichavan9860** [comment]
Verified on development server

**Comment by saniatg** [comment]
@nalwa not working on live. The support is not revoked

**Comment by rupalichavan9860** [comment]
Working fine on live
