### ISSUE TITLE
Incorrect button name is showing 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#904]
Steps to reproduce : 
1. Create Topic
2. Create camp "Camp 1"
3. Support "Camp 1" --- User is supporter of "Camp 1"
4. Go to Agreement Camp and observe support button name 

Actual Result :  Button name displaying is "Manage Support"
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/671c07d0-0db6-4226-b42b-aefdf9c7466e)

Expected Result : Button name should display  "Directly Join and Support"

Note : On reload , it is working fine

5. Now reload -- It will show button name as "Directly Join and Support" for agreement camp which is correct 
6. Now click on "Camp 1" and  observe support button name
Actual Result :  Button name displaying is "Directly Join and Support"
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/f19dee31-71e5-4912-b849-024a37b0c997)

Expected Result : Button name should display  "Manage Support"

**Comment by rupalichavan9860** [comment]
Users can see support list for both child and parent camps 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/7f777df4-18d8-46a3-8e3c-4d40c22b4b05)

**Comment by sajid315** [comment]
> Users can see support list for both child and parent camps ![image](https://private-user-images.githubusercontent.com/40416610/322327557-7f777df4-18d8-46a3-8e3c-4d40c22b4b05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNjI2NzAsIm5iZiI6MTcxMzE2MjM3MCwicGF0aCI6Ii80MDQxNjYxMC8zMjIzMjc1NTctN2Y3NzdkZjQtMThkOC00NmEzLThlM2MtNGQ0MGMyMmI0YjA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDA2MjYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2YjNmMTEwZGFiZTc4NGQ5YmM3Yzg4MmNmYTVhMzIxNjg0YmQxNzczNTAyMzBhYjNlYmM2ODRmNjcxYzczNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nZwTx3CUgvWXMuTleLArvdNngdIeUykmuw928OeWbT8)

@rupalichavan9860 This issue will be resolved automatically when the API call for support check will be called on navigation b/w the camps in tree and breadcrumb. 
@wahaj-hafeez currently looking into this.

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1701

**Comment by rupalichavan9860** [comment]
Verified on development server

**Comment by rupalichavan9860** [comment]
Working fine on live
