### ISSUE TITLE
"Camp Detail Page" is not working on the development server.

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/Canonizer-Beta--Issue-Tracking#906]
Steps:
  1. Try to open this camp "https://development.canonizer.com/topic/369-Regression-25-JAN-2022/1-Agreement"

https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/c6fec551-1a3a-4328-b18d-15b1600b7fb1

**Comment by sajid315** [comment]
@akashgit77 this issue is resolved , can you please check it on development site again ? On same topic?

**Comment by akashgit77** [comment]
Working fine on the development server
