### ISSUE TITLE
Issue in login with github

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#907]
Steps:

1. Login with github
2. Asks for first name and last name
3. on next page it asks for OTP
4. 
But the OTP is not sent to the email address 
As a user I'm stuck on that step
![Screenshot 2024-04-10 at 12 49 19 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/516542c1-37fb-4712-b97b-8391c632afd8)

**Comment by saniatg** [comment]
also if I click on cross icon, the page will keep loading
![Screenshot 2024-04-10 at 3 49 42 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/1fbddfb2-5c04-4fe0-91ca-22e747401d65)

**Comment by kshitij1326** [comment]
@saniatg Could you please check this again? We have tested it on the development server and we are able to receive the email with the OTP on Mailtrap.

**Comment by saniatg** [comment]
@kshitij1326  is receiving OTP . Can you check the other issue mentioned above if I click on cross icon, the page will keep loading .

**Comment by kshitij1326** [comment]
sure

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
