### ISSUE TITLE
Development server : Consensus Tree button is missing in mobile devices

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#908]
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/26565023-abc3-443c-90fb-bc349a438a65)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1704

**Comment by rupalichavan9860** [comment]
Verified on development server

**Comment by DevAlchemyCD** [comment]
Cards width issue is fixed in this PR
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1706

**Comment by rupalichavan9860** [comment]
Verified on live
