### ISSUE TITLE
Development Server : Canonizer Algorithm and As of filters are missing in mobile device

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#909]

**Comment by DevAlchemyCD** [comment]
This issue has been resolved in the following PR.
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1704

**Comment by rupalichavan9860** [comment]
@wahaj-hafeez Please fix alignment 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/3da6b699-ee84-4368-a13e-2c360f835a01)

**Comment by DevAlchemyCD** [comment]
This issue is resolved in this PR:
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1706

**Comment by rupalichavan9860** [comment]
Verified on development server

**Comment by rupalichavan9860** [comment]
Verified on live
