### ISSUE TITLE
History Pages : Not direct supporter can object the changes for the below case

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#91]
**Steps to reproduce**

1. user A creates a topic
2. user B adds a statement and commits it
3. user A navigates to statement history page
4. user A navigates to objection page
5. copy the url
6. paste it in a new browser
7. login with user B or user C
8. enter data in objection field and click on submit
**Actual Result**
the objection is submitted. 
The same is case with all history pages
**Expected Result**
as user B and user C are not direct supporter, so they shouldn't be allowed to object the change.

**Comment by sunilspr7** [comment]
https://github.com/the-canonizer/canonizer-3.0-api/pull/492 
@gautamv16 PR created

**Comment by sunilspr7** [comment]
https://github.com/the-canonizer/canonizer-3.0-api/pull/507

Topic and Camp history page also applied objection condition.

**Comment by rupalichavan9860** [comment]
Getting below error message : 
![image](https://user-images.githubusercontent.com/40416610/210354854-e1998703-4c7e-4cb9-ba54-489e0a26e58b.png)

**Comment by sunilspr7** [comment]
https://github.com/the-canonizer/canonizer-3.0-api/pull/516

**Comment by rupalichavan9860** [comment]
When a direct supporter copies the URL and logs in, the Object button is disabled; however, when the page is reloaded, the Object button is enabled.

**Comment by sunilspr7** [comment]
@rupalichavan9860 this is not related to API.  I have added this comment ticket no #125.

**Comment by rupalichavan9860** [comment]
Okay @sunilspr7 Closing this

**Comment by rupalichavan9860** [comment]
Verified on live
