### ISSUE TITLE
Create topic: In the following case, the user is not redirected to the create topic page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#910]
Pre-condition : User must be logged out
Steps to reproduce : 
1. Go to https://development.canonizer.com/
2. Click on "Create Topic"
3. Login with valid Email and Password 
4. Observe result 

Expected Result : It should redirect to Create Topic page 

Actual Result : It is redirecting to home page

**Comment by rupalichavan9860** [comment]
Header Link : not working 
Footer Link : Working fine

**Comment by saniatg** [comment]
working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
