### ISSUE TITLE
Score not changing when clearing filter

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#911]
Steps:

1. Choose any algo E.G Mind expert
2. Score will be 0
3. Now click on cross icon or clear all
4. Score will be 1 which is correct as filter is set to 'One person one vote'
5. Now choose again Mind expert
6. On topic detail the score is not changed

**Comment by hassaanCD** [comment]
Working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
