### ISSUE TITLE
Search : Nickname advance filter 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#913]
Label must be related to nickname 
As of now label is displaying as "Search for Topic or Camp"

Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/3cfcfcc8-b54e-438a-9497-25c806610f41)

**Comment by rohit-talentelgia** [comment]
Hello @rupalichavan9860 , the advanced filter in Nickname is to search for Topics and camps. If you search for a topic or camp in this advance filter it will show the nicknames from the searched list which support that topic or camp. 

Let me know if you have any confusion.

**Comment by rupalichavan9860** [comment]
@rohit-talentelgia Thanks for the clarification
