### ISSUE TITLE
The support camp pop-up keeps loading while adding support with "Reason for adding/removing support"

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#915]
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/6abbeb09-1b72-42c4-b1a3-e31f9b231b51)

**Comment by sajid315** [comment]
@rupalichavan9860 this issue has been fixed under this PR.
https://github.com/the-canonizer/canonizer-3.0-api/pull/976

**Comment by rupalichavan9860** [comment]
Verified on development server

**Comment by rupalichavan9860** [comment]
Verified on live
