### ISSUE TITLE
Search : Getting error "Oops! Something went wrong" when searching few keywords

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#919]
Search "tree" and click on "Search for tree"
Getting page crash below : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/948ef309-704e-4201-9432-e37e0654591a)

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/26718aee-134e-4820-ac42-b0cfb74e4a5f)

**Comment by rupalichavan9860** [comment]
Verified on development server

**Comment by hassaanCD** [comment]
Working fine on production
