### ISSUE TITLE
since the social media icons are hidden now. the API call should also be removed

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#92]
![image](https://user-images.githubusercontent.com/104552751/207268763-39597dc8-df14-49d6-b4cd-a0eaf27a4ef2.png)

**Comment by shahab-ramzan** [comment]
PR Raised https://github.com/the-canonizer/canonizer-3.0-frontend/pull/635

**Comment by subhancd** [comment]
working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on beta
