### ISSUE TITLE
Eventline- All events are listing together and play button is not working for topic "233 Testing cn fn"

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#924]
I checked eventline for this topic on 19th April , All events were listing together and play button was also not working .
![Screenshot 2024-04-21 at 12 48 03 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/aca5b91c-c47b-405f-b7a7-61ef48d42b7a)

I checked this again on 22nd April, all events listing at once issue still there but now play button is working.
As discussed with Sunil, the issue is related to server .
Please check

**Comment by sunilspr7** [comment]
command :  
php artisan timeline:all 2093 
Done

**Comment by rupalichavan9860** [comment]
Verified on development server

**Comment by saniatg** [comment]
this issue for only on development
