### ISSUE TITLE
Page crash on create new camp 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#926]
Steps to reproduce : 
1. Go to any Topic
2.  Apply as of date filter as previous date than camp created date 
3. Click on topic created link
4. Click on "Create New Camp" button on topic detail page 
5. Again Click on "Create New Camp" button on topic detail page 

Actual Result : Getting below page crash 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/b6860a7b-a162-41ab-b2a6-a3121ab81938)

**Comment by saniatg** [comment]
@wahaj-hafeez working fine for this case, but when click under recent activities" [username] created topic [topic_name] , then also need to disable the button
![Screenshot 2024-04-30 at 8 22 36 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/deb60ff3-2005-4bc1-9f00-b937e391b5ea)

**Comment by sajid315** [comment]
@saniatg , @wahaj-hafeez I think the above issue about camp not found is already fixed under following PR.
https://github.com/the-canonizer/canonizer-3.0-api/pull/984/

**Comment by sajid315** [comment]
Just noticed one thing , in case of older date than topic creation date selected as a filter. We are showing only text of "Topic: " with no topic name from breadcrumb API. 
I think it should be hidden in this scenario ? Can we go with it ? 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/111273633/a4f16d96-64e0-4901-8bed-b3b9ad2c0b53)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1753

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
