### ISSUE TITLE
Mobile Device : Recent activities showing twice on mobile device 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#928]
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/08500552-233f-4150-843e-f7b2ab90d1cd)

**Comment by rupalichavan9860** [comment]
Verified on development

**Comment by hassaanCD** [comment]
Working fine on production
