### ISSUE TITLE
"Three Dots" option is not working for all topics in certain scenario.

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/Canonizer-Beta--Issue-Tracking#929]
Steps:
1. Login with user and Go in any "topic detail page".
2. After logging out and clicking on "join support" button from "three dots" then "login" page pops up after that we click "close" button then again clicking on "three dots" then its not clickable.

https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/c0017b51-14d1-4aea-9d15-ffdde1bc32ce

**Comment by saniatg** [comment]
@ashish76 When click close button  on step 2, the drop down also opens which is incorrect

**Comment by saniatg** [comment]
@ks-rahul issue not fixed on development

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
