### ISSUE TITLE
"Create New Camp" is not working on the "Development Server".

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/Canonizer-Beta--Issue-Tracking#930]
https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/62748353-bfdb-4101-bfd9-39bbb82af3b7

**Comment by wahaj-hafeez** [comment]
PR : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1717

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1717

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
