### ISSUE TITLE
Website title "Build consensus by canonizing what you believe is right" is missing on development server 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#932]
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/432cc964-b844-476d-96ec-b6a64ac42fb0)

**Comment by saniatg** [comment]
working fine on development

**Comment by rupalichavan9860** [comment]
Verified on live
