### ISSUE TITLE
Proposed change to topic/camp/statement emails : Getting error "Topic Num is required." 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#935]
Getting error "Topic Num is required." when user click on "Proposed a change" link from Proposed change to topic/camp/statement emails

Refer attached screenshot : 
Topic History : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/a6ac0d58-da0f-4ded-bf33-90cbe7367ce6)

Camp History : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/8c81a5d1-afcb-4f32-a960-f0e961b555ec)

Camp Statement History : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/0ab01e1a-1d37-41bd-bf06-11a422da0c72)

**Comment by sajid315** [comment]
@wahaj-hafeez email links are fine but from front-end side the topic_num is not passing in two of the API's. Please have a look.

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1725

**Comment by rupalichavan9860** [comment]
Verified on development server

**Comment by rupalichavan9860** [comment]
Verified on live
