### ISSUE TITLE
The thread name displayed is incorrect.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#94]
Prerequisite: The user is not logged in.
Steps to reproduce : 
1. Go to https://beta.canonizer.com/
2. Select topic "Theories of Consciousness"
3. Click on "Camp Forum"
4. Select any thread name other than the first.
6. Observe thread title on page 

I have selected "Can we unify “Integrated Information” and “Global Workspace” with “Representational Qualia Theory”?" and it displays "Moving the Panexperientialism branch to Monism"  which is first thread in list

Refer attached screenshot : 

![image](https://user-images.githubusercontent.com/40416610/207398426-8b536cd7-ad13-44c3-b94d-d348f2ee22cc.png)

**Comment by subhancd** [comment]
working fine on beta. @rupalichavan9860 kindly, verify.

**Comment by rupalichavan9860** [comment]
Verified
