### ISSUE TITLE
User does not exist error when trying to open username on new tab

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#940]
Open username link in new tab

![Screenshot 2024-04-26 at 4 23 55 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/8d174654-2102-4efd-bcae-5502be8f00c1)
![Screenshot 2024-04-26 at 4 25 07 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/6965c97f-6835-4718-a646-5fc318e4f7e7)

**Comment by rupalichavan9860** [comment]
Also getting same issue when clicking on nickname link from emails

**Comment by sajid315** [comment]
@saniatg I tried the same process as mentioned in attached screenshot in this ticket. And the pages related to user public info via support tree and via email nicknames are working now on development. 
Can you please again have a look, please?

**Comment by rupalichavan9860** [comment]
Verified on development server

**Comment by rupalichavan9860** [comment]
Verified on live
