### ISSUE TITLE
Getting error "Topic Num is required." when user trying to open Add Camp Statement , Manage/Edit Camp Statement, Manage/Edit This Topic, Manage/Edit This Camp in new tab

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#941]
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/4724c44e-228a-4838-a4b5-70b8992459a3)

**Comment by sunilspr7** [comment]
i have tested this,  this require fix from front-end @vikasranatalentelgia  please look  into this, if any assitance required let me know

**Comment by saniatg** [comment]
@rupalichavan9860 working fine now, can you confirm

**Comment by rupalichavan9860** [comment]
Verified on live
