### ISSUE TITLE
Add news : Getting page crash when opening in new tab

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#942]
Please refer attached screenshot : 

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/903438ed-cc6e-4950-9305-3f8d63f3184e)

**Comment by sajid315** [comment]
@wahaj-hafeez from frontend side when you will open this link on same page, its opening with topic number and camp number.
But when you will **open same link in new tab** its missing the params in the URL.

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/111273633/e8bcdc0e-da97-4dce-bc51-139199ae5358)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1729

**Comment by rupalichavan9860** [comment]
@wahaj-hafeez Not fixed. Can you please check whether PR is merged or not?

**Comment by rupalichavan9860** [comment]
PR merged and it is working fine now on development

**Comment by saniatg** [comment]
working fine on production
