### ISSUE TITLE
Account Settings : Phone Number issues 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#943]
Issue 1: Move the phone number and mobile carrier fields to the "Personal Information" section. 

Issue 2: Set the Phone Number and Mobile Carrier fields as optional. Once the user enters the phone number, it should display an error message to select the mobile carrier.

Issue 3 : After entering the phone number and choosing the carrier to confirm it, the user should receive an OTP on the phone number. 
Actual Result : As of now user is receiving OTP on registered email address

**Comment by ks-rahul** [comment]
@rupalichavan9860 Currently, we do not have an SMS gateway, so OTPs are being sent to users via email. Once the SMS gateway is set up, SMS notifications will be enabled.

**Comment by rupalichavan9860** [comment]
@ks-rahul I can see new changes now but facing below issue , 
Without entering into fields "Phone Number (for mobile otp verification)" and "Mobile Carrier" click on "Verify" button 

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/1df1aa37-8cbf-4b27-bc30-7dff0bb6dd28)


![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/030c8dc6-55c5-478d-a312-49b9ee32a0dd)

Result : Button is disabled and need to refresh the page to enable the button

**Comment by rupalichavan9860** [comment]
Also change field name to "Phone Number (for mobile OTP verification)" instead of  "Phone Number (for mobile otp verification)"

**Comment by rupalichavan9860** [comment]
Verified on development server

**Comment by rupalichavan9860** [comment]
Except for Issue 3, everything works correctly. so closing this.
