### ISSUE TITLE
Recent Activities for threads/posts are not working 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#944]
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/35aa0a49-4a75-4875-96cb-7aba2e451d56)

Latest thread /post activities are not listing

**Comment by sajid315** [comment]
@rupalichavan9860 all of the thread and post activities are showing, you can have a look in below screenshot. 

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/111273633/4919c1f0-ea80-4511-a03f-baaff7c9e6ec)

**Comment by rupalichavan9860** [comment]
Working fine now on development server

**Comment by hassaanCD** [comment]
Working fine on production
