### ISSUE TITLE
Filter is not being reset when open topic in eventline

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#951]
Steps:

1. Go to eventline of a topic which has 2 or more added score  in past 
2. Click on the first event
3. Clear the as of date filter

The topic details page and consensus tree is not refreshed. It should should default topic details

**Comment by vikasranatalentelgia** [comment]
@saniatg This is not replicating.

**Comment by saniatg** [comment]
working fine for now.

**Comment by saniatg** [comment]
Working fine on production
