### ISSUE TITLE
Live: Camp names are displayed multiple times for nickname (Brent_Allsop) "https://canonizer.com/user/supports/1?canon=9" and support order is also incorrect

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#952]
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/787aece1-3056-49a7-b708-70fd705f53fc)

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/d2bfd74a-e562-4c50-b744-fb2688485182)

**Comment by rupalichavan9860** [comment]
Same for user https://canonizer.com/user/supports/453?canon=9

**Comment by nalwa** [comment]
@saniatg  issue has been fixed . i was able to find the root cause. it was appearing due to archive functionality.  there is also PR raised for the same

**Comment by nalwa** [comment]
https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/issues/949   this is issue which were causing duplicacy as per findings

**Comment by rupalichavan9860** [comment]
Verified on live and working fine

**Comment by rupalichavan9860** [comment]
Verified on live
