### ISSUE TITLE
Incorrect Heading is seen when score count is loading for a camp

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#954]
Steps:

1. Create a topic 
2. create a camp 'camp1'
3. click on directly join button for camp 1
4. click submit

Observer the heading shows" Support Tree for "agreement" Camp while loading which is incorrect .

![Screenshot 2024-05-03 at 1 19 54 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/c6af8bed-7463-4509-9896-0339be3743f2)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1738

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
