### ISSUE TITLE
In camp statements, short code does not work.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#96]
Please refer attached screenshot : 
![image](https://user-images.githubusercontent.com/40416610/207662620-5dc52757-6f51-4bc6-b618-d14c07083ed5.png)

**Comment by ks-rahul** [comment]
as discussed with @nalwa the shortcode functionality is not developed yet. she will work on it.

**Comment by rupalichavan9860** [comment]
Working fine on beta
