### ISSUE TITLE
Search is taking time to load on production

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#963]
![Screenshot 2024-05-08 at 3 40 17 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/308ba60d-b813-43e8-aed3-4c52a666d1bb)

**Comment by hassaanCD** [comment]
Production is also taking time when user change algorithm

**Comment by saniatg** [comment]
working fine now on production.
