### ISSUE TITLE
UI issue on consensus tree- Subscribe icon is not aligned correctly

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#965]
Refer screenshot
![Screenshot 2024-05-09 at 11 44 06 AM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/2eb76206-ac66-4d38-8b73-887730d64bdd)

**Comment by rupalichavan9860** [comment]
Verified on dev server

**Comment by saniatg** [comment]
working fine on production
