### ISSUE TITLE
When the filter "include review" is selected, the topic name displays instead of the camp name "Agreement".

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#966]
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/6df89ce5-901b-4c04-9a0c-4429f476d41c)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1819

**Comment by rupalichavan9860** [comment]
Verified on dev server

**Comment by hassaanCD** [comment]
Working fine on production
