### ISSUE TITLE
Eventline is not working when we are going from "Camp Forum"

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/Canonizer-Beta--Issue-Tracking#967]
Steps:
1. Go to "Camp Forum Page" then click on "Eventline" button from the tree(left panel).

https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/2bb03411-ba0e-4569-b653-9f0ff657d6d8

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1775

**Comment by rupalichavan9860** [comment]
Not fixed

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
