### ISSUE TITLE
Non-administrator users can access the URL for adding news.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#97]
Non-administrator users can access the URL for adding news.
and getting below error while submitting news
Please refer attached screenshot : 

![image](https://user-images.githubusercontent.com/40416610/207663815-5d77046d-3b90-4f23-aeb2-10c3c6585da9.png)

**Comment by subhancd** [comment]
working fine on both staging and beta @rupalichavan9860

**Comment by rupalichavan9860** [comment]
Verified
