### ISSUE TITLE
Development server : Videos are not working

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#978]
Videos are not working from both old and new links , Please refer attached screenshot :  
New Link : https://development.canonizer.com/videos
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/e2df0db7-ef6a-4831-93ec-8c40bce9aae9)

Old Link : https://development.canonizer.com/videos/consciousness/introduction
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/4a8d040c-008a-4df3-8bfd-1f5f43e61330)

**Comment by rupalichavan9860** [comment]
Working fine now

**Comment by akashgit77** [comment]
@sajid315 when we are opening this url "https://development.canonizer.com/videos/consciousness/introduction?format=360" directly in browser then it keeps loading.When video format is pre-defined.

**Comment by sajid315** [comment]
Yes, @akashgit77 I'm looking into it.

**Comment by sajid315** [comment]
@wahaj-hafeez I have looked into this from backend, so the video base src is coming from the API. Just the resolution selection at front-end is not being selected by default, in the case that mentioned by Akash.

**Comment by DevAlchemyCD** [comment]
PR:https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1767

**Comment by rupalichavan9860** [comment]
Working fine on development server

**Comment by rupalichavan9860** [comment]
Verified on live
