### ISSUE TITLE
Getting error "Topic Num is required" for Topic and camp in below case 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#979]
Steps to reproduce : 
1. User A is supporter of Agreement camp
2. Login with User B and submit change for Camp, Topic and statement 
3. Login with User A and object change
4. Again with User A try to object the objected record

Getting blow error : 
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/1970714b-16c5-45bb-9921-1b2550c24fb1)

**Comment by ks-rahul** [comment]
@rupalichavan9860 I followed the steps above and it seems to be working fine for me. Could you please explain it again?

**Comment by rupalichavan9860** [comment]
Sure @ks-rahul Can we have a quick call for this?

**Comment by sajid315** [comment]
@ks-rahul , @rupalichavan9860 Actual issues in this ticket are resolved , however as we discussed in call. We need following scenario's to discuss:

1- Currently once the statement is already objected then nobody is able to again make a object on it (Object button is not available). As we can see in below screenshot. 
But the same case is working for topic/camp changes.

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/111273633/8bec8e35-c978-4ebe-8d2d-25578408dac9)

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/111273633/81176501-e89a-4050-bc85-b0556fd97a5f)


2- When the go-live-time of objected change is lesser than current time, front-end restricting user to object and redirecting us back on history pages.

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/111273633/8af625ba-1138-4f6e-9ca5-dc40533e4fa0)

**Comment by rupalichavan9860** [comment]
@sajid315 As discussed in the meeting, remove the Object button from the objected record and ensure that the behavior of the statement, camp, and topic history pages are the same.

**Comment by DevAlchemyCD** [comment]
PR:https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1797

**Comment by rupalichavan9860** [comment]
Verified on development server

**Comment by rupalichavan9860** [comment]
Verified on live
