### ISSUE TITLE
Remove subscription is missing for this topic' "new_topic_88888'

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#982]
refer screenshot
![Screenshot 2024-05-17 at 3 32 01 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/9787a020-d4de-4c71-97c1-1d9219dd61dd)

**Comment by rupalichavan9860** [comment]
Not an issue
