### ISSUE TITLE
In mobile create topic button is seen on create topic page

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#983]
Click on create topic button on mobile . Create topic button is seen on create topic page which is incorrect
![Skype_Picture_2024_05_20T10_54_41_219Z](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/d4a7e488-5ba7-4a66-9eb5-4d07b7e01e30)

**Comment by saniatg** [comment]
@ks-rahul Not fixed

**Comment by ks-rahul** [comment]
> [@ks-rahul](https://github.com/ks-rahul) Not fixed

@saniatg this pr is not merged

https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1771

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
