### ISSUE TITLE
Drop down (three dots ) menu is not working next to camp forum page when click on any support notification

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#984]
When Click on support notification, the three dots menu is not working

![Screenshot 2024-05-21 at 8 02 43 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/5aa079bf-36c7-480f-be47-0fb1512f096c)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1818

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
