### ISSUE TITLE
Camp Leader : Minor change in label information 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#987]
It should be "Rupali C is currently the camp leader." instead of "
"Rupali C is a currently a camp leader"

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/9ee56938-6d58-4b7f-b4c5-84b6650aa082)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1776

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
working fine on production
