### ISSUE TITLE
Statement Mail : Topic link is not redirecting to the topic

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#99]
**Steps to reproduce**

1. create a topic
2. add statement
3. navigate to mail
4. click on topic link
**Actual Result**

![Image](https://user-images.githubusercontent.com/104552751/208359540-32cff8a0-5c5b-4ccb-854b-e5d27dd42582.png)

**Comment by subhancd** [comment]
still not working


![Image](https://user-images.githubusercontent.com/104552751/208903938-55882666-16a9-4d97-93b8-02573ff0d0c4.png)

**Comment by ks-rahul** [comment]
@subhancd i checked this on staging and its working. could you please check again?

![Image](https://user-images.githubusercontent.com/95217406/209063830-252a9000-e7a7-4f40-acf2-2563d7b38e90.png)

**Comment by subhancd** [comment]
@ks-rahul it is not working when we create a new topic and add very first statement.

**Comment by ks-rahul** [comment]
@subhancd previously code was not deployed on the server please check now.

**Comment by subhancd** [comment]
working fine on both beta and staging.
