### ISSUE TITLE
Camp leader- Need to disable the button 'Sign' in case of archive and as of date filter when selected any past date

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#990]
When archive and any past date is applied in as of date filter, the support buttons are disabled . Need to do the same for 'Sign' button

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1790

**Comment by saniatg** [comment]
Working fine on development

**Comment by saniatg** [comment]
working fine on production
