### ISSUE TITLE
Getting error "Something went wrong"

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#991]
Steps to reproduce : 
1. User A creates a topic, by default User A is the camp leader
2. User A creates a new camp "Camp 1" under "Agreement" and Directly join camp and then try to sign it (Working fine)
3. User A creates a new camp "Camp 2" under "Agreement" and Directly join camp and then try to sign it

Getting error on Submit button on Sign pop up
Please refer attached screenshot : 

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/57cddd51-feaf-4498-ba67-9d0e43195e5b)

**Comment by wahaj-hafeez** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1792

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1794
