### ISSUE TITLE
Issues with change approver

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#992]
Precondition -
User A - Camp Leader
User B - Direct supporter
User C - Direct Supporter

Steps to reproduce : 
1. User B submits change (User C as camp leader)  ---Record is in "in review" 

Actual Result : It is showing (1 out of 2 required supporters have agreed, Since you are the last hold out, the instant you agree, this will go live.) for both User A and User C
And record is going live on User A's approval 

Expected Result : Only User C should able to agree the change

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1789

**Comment by rupalichavan9860** [comment]
Now only User C can agree the change but on User A screen it is showing "1 out of 2 required supporters have agreed, Since you are the last hold out, the instant you agree, this will go live."

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/2eb51257-f56c-4502-a9c3-4a4bc62869fb)

**Comment by DevAlchemyCD** [comment]
PR : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1812

**Comment by rupalichavan9860** [comment]
Working fine on development server

**Comment by rupalichavan9860** [comment]
Verified on live
