### ISSUE TITLE
When auto-selected, the camp leader should be updated under the camp meta information.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#993]
Precondition : 
User A is direct supporter 
User B is Camp Leader 
Steps to reproduce : 
1. User B - Remove support 
2. Observe camp meta information.

Actual Result : The camp leader is not being updated; however, it is being updated when you refresh or reload. 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/d7097930-9e27-4c7a-9d7a-f9a17c3e4811)

**Comment by wahaj-hafeez** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1788

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1795

**Comment by rupalichavan9860** [comment]
Verified on dev server

**Comment by saniatg** [comment]
working fine on production
