### ISSUE TITLE
Camp Leader : Getting incorrect warning "Warning! You are the camp leader of this camp <camp name>. You cannot sign the camp." in below case 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#994]
Steps to reproduce : 
1. Create Topic -User A login 
User A is camp Leader of "Agreement" camp 
2. Login with User B and support Agreement camp directly
3. Login with User A -go to Account settings->supported camps - remove support from agreement camp 
4. On topic detail page click on "Sign" button 

Getting below error message : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/fe65dfb0-0b0a-4482-a0f7-69b93a5643d6)

**Comment by rupalichavan9860** [comment]
Working fine on development server

**Comment by saniatg** [comment]
working fine on production
